


CREATE VIEW [dbo].[Recado]
AS

SELECT TOP 1 * FROM GPIMAC_Altamira.dbo.ATDAUX
UNION 
SELECT     
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0Cod AS VwAtd0Cod, 
	'GPIMAC' AS VwAtd0Origem, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0Dat AS VwAtd0Dat, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0DtH AS VWAtd0DtH, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0Aut AS VwAtd0Aut, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0Pc0Cod AS VwAtd0Pc0Cod, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0LogTipCod AS VwAtd0Pc0LogTipCod, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0End AS VwAtd0Pc0End, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0EndNum AS VwAtd0Pc0EndNum, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0EndCpl AS VwAtd0Pc0EndCpl, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0Bai AS VwAtd0Pc0Bai, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0Cep AS VwAtd0Pc0Cep, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0Cid AS VwAtd0Pc0Cid, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0UfCod AS VwAtd0Pc0UfCod, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0Fan AS VwAtd0Pc0Fan, 
	GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0Nom AS VwAtd0Pc0Nom, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0Pc1Cod AS VwAtd0Pc1Cod, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1Nom AS VwAtd0Pc1Nom, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1TelDdd AS VwAtd0Pc1TelDdd, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1TelNum AS VwAtd0Pc1TelNum, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1TelRam AS VwAtd0Pc1TelRam, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1FaxDdd AS VwAtd0Pc1FaxDdd, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1FaxNum AS VwAtd0Pc1FaxNum, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1FaxRam AS VwAtd0Pc1FaxRam, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1CelDdd AS VwAtd0Pc1CelDdd, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1CelNum AS VwAtd0Pc1CelNum, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1Dep AS VwAtd0Pc1Dep, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1Cgo AS VwAtd0Pc1Cgo, 
	GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1Eml AS VwAtd0Pc1Eml, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0CvCod AS VwAtd0CvCod, 
	GPIMAC_ALTAMIRA.dbo.CAREP.CVNOM AS VwAtd0CvNom, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0TpA0Cod AS VwAtd0TpA0Cod, 
	GPIMAC_ALTAMIRA.dbo.CATPA.CTpA0Nom AS VwAtd0TpA0Nom, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0StA0Cod AS VwAtd0StA0Cod, 
	GPIMAC_ALTAMIRA.dbo.CASTA.CStA0Nom AS VwAtd0StA0Nom, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0MdA0Cod AS VwAtd0MdA0Cod, 
	GPIMAC_ALTAMIRA.dbo.CAMDA.CMdA0Nom AS VwAtd0MdA0Nom, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0Obs AS VwAtd0Obs, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0SmsTxt AS VwAtd0SmsTxt, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0SmsEnv AS VwAtd0SmsEnv, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0SmsOkUsu AS VwAtd0SmsOkUsu, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0SmsOkDtH AS VwAtd0SmsOkDtH, 
	GPIMAC_ALTAMIRA.dbo.ATD.Atd0SmsOk AS VwAtd0SmsOk
FROM         
	GPIMAC_ALTAMIRA.dbo.CAPCL WITH (NOLOCK) INNER JOIN
	GPIMAC_ALTAMIRA.dbo.ATD WITH (NOLOCK) ON GPIMAC_ALTAMIRA.dbo.CAPCL.Pc0Cod = GPIMAC_ALTAMIRA.dbo.ATD.Atd0Pc0Cod INNER JOIN
	GPIMAC_ALTAMIRA.dbo.CAPCL1 WITH (NOLOCK) ON GPIMAC_ALTAMIRA.dbo.ATD.Atd0Pc1Cod = GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc1Cod AND GPIMAC_ALTAMIRA.dbo.ATD.Atd0Pc0Cod = GPIMAC_ALTAMIRA.dbo.CAPCL1.Pc0Cod INNER JOIN
	GPIMAC_ALTAMIRA.dbo.CASTA WITH (NOLOCK) ON GPIMAC_ALTAMIRA.dbo.ATD.Atd0StA0Cod = GPIMAC_ALTAMIRA.dbo.CASTA.CSta0Cod INNER JOIN
	GPIMAC_ALTAMIRA.dbo.CATPA WITH (NOLOCK) ON GPIMAC_ALTAMIRA.dbo.ATD.Atd0TpA0Cod = GPIMAC_ALTAMIRA.dbo.CATPA.CTpA0Cod INNER JOIN
	GPIMAC_ALTAMIRA.dbo.CAMDA WITH (NOLOCK) ON GPIMAC_ALTAMIRA.dbo.ATD.Atd0MdA0Cod = GPIMAC_ALTAMIRA.dbo.CAMDA.CMdA0Cod INNER JOIN
	GPIMAC_ALTAMIRA.dbo.CAREP WITH (NOLOCK) ON GPIMAC_ALTAMIRA.dbo.ATD.Atd0CvCod = GPIMAC_ALTAMIRA.dbo.CAREP.CVCOD


