CREATE TABLE [dbo].[CAIBGEUF] (
    [GPUF0Cod] SMALLINT  NOT NULL,
    [GPUF0Nom] CHAR (20) NOT NULL,
    [GPUF0SIG] CHAR (2)  NOT NULL,
    PRIMARY KEY CLUSTERED ([GPUF0Cod] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UCAIBGEUFB]
    ON [dbo].[CAIBGEUF]([GPUF0SIG] ASC);

