CREATE TABLE [dbo].[CAIBGEMUN] (
    [GPMun0Cod] INT       NOT NULL,
    [GPMun0Nom] CHAR (50) NOT NULL,
    [GPUF0Cod]  SMALLINT  NOT NULL,
    PRIMARY KEY CLUSTERED ([GPMun0Cod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAIBGEMUNB]
    ON [dbo].[CAIBGEMUN]([GPUF0Cod] ASC);

