CREATE TABLE [dbo].[CFGPAR] (
    [CFGEMP] CHAR (2)     NOT NULL,
    [CFGPAR] CHAR (50)    NOT NULL,
    [CFGVAL] DECIMAL (10) NOT NULL,
    [CFGPRM] CHAR (250)   NOT NULL,
    CONSTRAINT [PK__CFGPAR__4316F928] PRIMARY KEY CLUSTERED ([CFGEMP] ASC, [CFGPAR] ASC)
);

