CREATE TABLE [dbo].[NFE] (
    [NFe0Emp]                  CHAR (2)       NOT NULL,
    [NFe0FatNum]               INT            NOT NULL,
    [NFe0FatTip]               CHAR (1)       NOT NULL,
    [NFe0FatCnpjCpfEmi]        CHAR (14)      NOT NULL,
    [NFe0_infNFe_LayOutVer]    SMALLINT       NULL,
    [NFe0_infNFe_Id]           CHAR (100)     NULL,
    [NFe0_ide_cUFCod]          CHAR (2)       NULL,
    [NFe0_ide_cUFNom]          CHAR (20)      NULL,
    [NFe0_ide_cUF]             SMALLINT       NULL,
    [NFe0_ide_cNF]             INT            NULL,
    [NFe0_ide_natOpCod]        CHAR (5)       NULL,
    [NFe0_ide_natOp]           CHAR (60)      NULL,
    [NFe0_ide_indPag]          SMALLINT       NULL,
    [NFe0_ide_mod]             CHAR (2)       NULL,
    [NFe0_ide_serie]           SMALLINT       NULL,
    [NFe0_ide_nNF]             INT            NULL,
    [NFe0_ide_dEmi]            DATETIME       NULL,
    [NFe0_ide_dSaiEnt]         DATETIME       NULL,
    [NFe0_ide_tpNF]            SMALLINT       NULL,
    [NFe0_ide_cMunFG]          INT            NULL,
    [NFe0_ide_cMunFGNom]       CHAR (50)      NULL,
    [NFe0_ide_tpImp]           SMALLINT       NULL,
    [NFe0_ide_tpEmis]          SMALLINT       NULL,
    [NFe0_ide_cDV]             SMALLINT       NULL,
    [NFe0_ide_tpAmb]           SMALLINT       NULL,
    [NFe0_ide_finNFe]          SMALLINT       NULL,
    [NFe0_ide_procEmi]         SMALLINT       NULL,
    [NFe0_ide_verProc]         CHAR (20)      NULL,
    [Nfe0_emit_CNPJ_CPF]       CHAR (14)      NULL,
    [NFe0_emit_xNome]          CHAR (60)      NULL,
    [NFe0_emit_xFant]          CHAR (60)      NULL,
    [NFe0_enderEmit_xLgr]      CHAR (60)      NULL,
    [NFe0_enderEmit_nro]       CHAR (60)      NULL,
    [NFe0_enderEmit_xCpl]      CHAR (60)      NULL,
    [NFe0_enderEmit_xBairro]   CHAR (60)      NULL,
    [NFe0_enderEmit_cMun]      INT            NULL,
    [NFe0_enderEmit_xMun]      CHAR (60)      NULL,
    [NFe0_enderEmit_UF]        CHAR (2)       NULL,
    [NFe0_enderEmit_CEP]       CHAR (8)       NULL,
    [NFe0_enderEmit_cPais]     SMALLINT       NULL,
    [NFe0_enderEmit_xPais]     CHAR (60)      NULL,
    [NFe0_enderEmit_fone]      CHAR (11)      NULL,
    [NFe0_emit_IE]             CHAR (14)      NULL,
    [NFe0_emit_IEST]           CHAR (14)      NULL,
    [NFe0_emit_IM]             CHAR (15)      NULL,
    [NFe0_emit_CNAE]           CHAR (7)       NULL,
    [Nfe0_dest_CNPJ_CPF]       CHAR (14)      NULL,
    [NFe0_dest_xNome]          CHAR (60)      NULL,
    [NFe0_enderDest_xLgr]      CHAR (60)      NULL,
    [NFe0_enderDest_nro]       CHAR (60)      NULL,
    [NFe0_enderDest_xCpl]      CHAR (60)      NULL,
    [NFe0_enderDest_xBairro]   CHAR (60)      NULL,
    [NFe0_enderDest_cMun]      INT            NULL,
    [NFe0_enderDest_xMun]      CHAR (60)      NULL,
    [NFe0_enderDest_UF]        CHAR (2)       NULL,
    [NFe0_enderDest_CEP]       CHAR (8)       NULL,
    [NFe0_enderDest_cPais]     SMALLINT       NULL,
    [NFe0_enderDest_xPais]     CHAR (60)      NULL,
    [NFe0_enderDest_fone]      CHAR (11)      NULL,
    [NFe0_dest_IE]             CHAR (14)      NULL,
    [NFe0_dest_ISUF]           CHAR (9)       NULL,
    [Nfe0_retirada_CNPJ]       CHAR (14)      NULL,
    [NFe0_retirada_xLgr]       CHAR (60)      NULL,
    [NFe0_retirada_nro]        CHAR (60)      NULL,
    [NFe0_retirada_xCpl]       CHAR (60)      NULL,
    [NFe0_retirada_xBairro]    CHAR (60)      NULL,
    [NFe0_retirada_cMun]       INT            NULL,
    [NFe0_retirada_xMun]       CHAR (60)      NULL,
    [NFe0_retirada_UF]         CHAR (2)       NULL,
    [Nfe0_entrega_CNPJ]        CHAR (14)      NULL,
    [NFe0_entrega_xLgr]        CHAR (60)      NULL,
    [NFe0_entrega_nro]         CHAR (60)      NULL,
    [NFe0_entrega_xCpl]        CHAR (60)      NULL,
    [NFe0_entrega_xBairro]     CHAR (60)      NULL,
    [NFe0_entrega_cMun]        INT            NULL,
    [NFe0_entrega_xMun]        CHAR (60)      NULL,
    [NFe0_entrega_UF]          CHAR (2)       NULL,
    [NFe0_ICMSTot_vBC]         MONEY          NULL,
    [NFe0_ICMSTot_vICMS]       MONEY          NULL,
    [NFe0_ICMSTot_vBCST]       MONEY          NULL,
    [NFe0_ICMSTot_vST]         MONEY          NULL,
    [NFe0_ICMSTot_vProd]       MONEY          NULL,
    [NFe0_ICMSTot_vFrete]      MONEY          NULL,
    [NFe0_ICMSTot_vSeg]        MONEY          NULL,
    [NFe0_ICMSTot_vDesc]       MONEY          NULL,
    [NFe0_ICMSTot_vII]         MONEY          NULL,
    [NFe0_ICMSTot_vIPI]        MONEY          NULL,
    [NFe0_ICMSTot_vPIS]        MONEY          NULL,
    [NFe0_ICMSTot_vCOFINS]     MONEY          NULL,
    [NFe0_ICMSTot_vOutro]      MONEY          NULL,
    [NFe0_ICMSTot_vNF]         MONEY          NULL,
    [NFe0_ISSQNtot_vServ]      MONEY          NULL,
    [NFe0_ISSQNtot_vBC]        MONEY          NULL,
    [NFe0_ISSQNtot_vISS]       MONEY          NULL,
    [NFe0_ISSQNtot_vPIS]       MONEY          NULL,
    [NFe0_ISSQNtot_vCOFINS]    MONEY          NULL,
    [NFe0_retTrib_vRetPIS]     MONEY          NULL,
    [NFe0_retTrib_vRetCOFINS]  MONEY          NULL,
    [NFe0_retTrib_vRetCSLL]    MONEY          NULL,
    [NFe0_retTrib_vBCIRRF]     MONEY          NULL,
    [NFe0_retTrib_vIRRF]       MONEY          NULL,
    [NFe0_retTrib_vBCRetPrev]  MONEY          NULL,
    [NFe0_retTrib_vRetPrev]    MONEY          NULL,
    [NFe0_transp_modFrete]     SMALLINT       NULL,
    [Nfe0_transporta_CNPJ_CPF] CHAR (14)      NULL,
    [Nfe0_transporta_xNome]    CHAR (60)      NULL,
    [Nfe0_transporta_IE]       CHAR (14)      NULL,
    [Nfe0_transporta_xEnder]   CHAR (60)      NULL,
    [Nfe0_transporta_xMun]     CHAR (60)      NULL,
    [Nfe0_transporta_UF]       CHAR (2)       NULL,
    [Nfe0_retTransp_vServ]     MONEY          NULL,
    [Nfe0_retTransp_vBCRet]    MONEY          NULL,
    [Nfe0_retTransp_pICMSRet]  SMALLMONEY     NULL,
    [Nfe0_retTransp_vICMSRet]  MONEY          NULL,
    [Nfe0_retTransp_CFOP]      CHAR (5)       NULL,
    [Nfe0_retTransp_cMunFG]    INT            NULL,
    [Nfe0_veicTransp_placa]    CHAR (8)       NULL,
    [Nfe0_veicTransp_UF]       CHAR (2)       NULL,
    [Nfe0_veicTransp_RNTC]     CHAR (20)      NULL,
    [Nfe0_reboque01_placa]     CHAR (8)       NULL,
    [Nfe0_reboque01_UF]        CHAR (2)       NULL,
    [Nfe0_reboque01_RNTC]      CHAR (20)      NULL,
    [Nfe0_reboque02_placa]     CHAR (8)       NULL,
    [Nfe0_reboque02_UF]        CHAR (2)       NULL,
    [Nfe0_reboque02_RNTC]      CHAR (20)      NULL,
    [NFe0_vol_Ite]             SMALLINT       NULL,
    [Nfe0_vol_qVol]            DECIMAL (15)   NULL,
    [Nfe0_vol_esp]             CHAR (60)      NULL,
    [Nfe0_vol_marca]           CHAR (60)      NULL,
    [Nfe0_vol_nVol]            CHAR (60)      NULL,
    [Nfe0_vol_pesoL]           MONEY          NULL,
    [Nfe0_vol_pesoB]           MONEY          NULL,
    [NFe0FatEmi]               CHAR (1)       NULL,
    [NFe0_cobr_fat_nFat]       CHAR (60)      NULL,
    [NFe0_cobr_fat_vOrig]      MONEY          NULL,
    [NFe0_cobr_fat_vDesc]      MONEY          NULL,
    [NFe0_cobr_fat_vLiq]       MONEY          NULL,
    [NFe0_infAdFisco]          VARCHAR (2000) NULL,
    [NFe0_infCpl]              VARCHAR (5000) NULL,
    [NFe0_exporta_UFEmbarq]    CHAR (2)       NULL,
    [NFe0_exporta_xLocEmbarq]  CHAR (60)      NULL,
    [Nfe0_Imp]                 CHAR (1)       NULL,
    [Nfe0_MotCanc]             CHAR (255)     NULL,
    [NFe0_NotComp]             INT            NULL,
    [NFe0_Email]               CHAR (100)     NULL,
    [NFe0_Ide_hSaiEnt]         CHAR (10)      NULL,
    [NFe0_emit_CRT]            SMALLINT       NULL,
    [Nfe0_transporta_Bairro]   CHAR (30)      NULL,
    [Nfe0_Enviado]             CHAR (3)       NULL,
    CONSTRAINT [PK__NFE__0BC6C43E] PRIMARY KEY CLUSTERED ([NFe0Emp] ASC, [NFe0FatNum] ASC, [NFe0FatTip] ASC, [NFe0FatCnpjCpfEmi] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNFEA]
    ON [dbo].[NFE]([NFe0FatNum] DESC);

