CREATE TABLE [dbo].[NFE1ITE] (
    [NFe0Emp]                       CHAR (2)        NOT NULL,
    [NFe0FatNum]                    INT             NOT NULL,
    [NFe0FatTip]                    CHAR (1)        NOT NULL,
    [NFe0FatCnpjCpfEmi]             CHAR (14)       NOT NULL,
    [NFe1_nItem]                    SMALLINT        NOT NULL,
    [NFe1_prod_cprod]               CHAR (60)       NOT NULL,
    [NFe1_prod_cEAN]                CHAR (14)       NOT NULL,
    [NFe1_prod_xProd]               CHAR (120)      NOT NULL,
    [NFe1_prod_NCM]                 CHAR (8)        NOT NULL,
    [NFe1_prod_EXTIPI]              CHAR (3)        NOT NULL,
    [NFe1_prod_genero]              CHAR (2)        NOT NULL,
    [NFe1_prod_CFOP]                CHAR (5)        NOT NULL,
    [NFe1_prod_uCom]                CHAR (6)        NOT NULL,
    [NFe1_prod_qCom]                DECIMAL (11, 4) NOT NULL,
    [NFe1_prod_vUnCom]              DECIMAL (18, 7) NOT NULL,
    [NFe1_prod_vProd]               MONEY           NOT NULL,
    [NFe1_prod_cEANTrib]            CHAR (14)       NOT NULL,
    [NFe1_prod_uTrib]               CHAR (6)        NOT NULL,
    [NFe1_prod_qTrib]               DECIMAL (11, 4) NOT NULL,
    [NFe1_prod_vUnTrib]             DECIMAL (18, 7) NOT NULL,
    [NFe1_prod_vFrete]              MONEY           NOT NULL,
    [NFe1_prod_vSeg]                MONEY           NOT NULL,
    [NFe1_prod_vDesc]               MONEY           NOT NULL,
    [NFe1_prod_DI_nDI]              CHAR (10)       NOT NULL,
    [NFe1_prod_DI_dDi]              DATETIME        NOT NULL,
    [NFe1_prod_DI_xLocDesemb]       CHAR (60)       NOT NULL,
    [NFe1_prod_DI_UFDesemb]         CHAR (2)        NOT NULL,
    [NFe1_prod_DI_dDesemb]          DATETIME        NOT NULL,
    [NFe1_prod_DI_cExportador]      CHAR (60)       NOT NULL,
    [NFe1_imposto_ICMS_orig]        SMALLINT        NOT NULL,
    [NFe1_imposto_ICMS_CST]         CHAR (3)        NOT NULL,
    [NFe1_imposto_ICMS_modBC]       SMALLINT        NOT NULL,
    [NFe1_imposto_ICMS_pRedBC]      SMALLMONEY      NOT NULL,
    [NFe1_imposto_ICMS_vBC]         MONEY           NOT NULL,
    [NFe1_imposto_ICMS_pICMS]       SMALLMONEY      NOT NULL,
    [NFe1_imposto_ICMS_vICMS]       MONEY           NOT NULL,
    [NFe1_imposto_ICMS_modBCST]     SMALLINT        NOT NULL,
    [NFe1_imposto_ICMS_pMVAST]      SMALLMONEY      NOT NULL,
    [NFe1_imposto_ICMS_pRedBCST]    SMALLMONEY      NOT NULL,
    [NFe1_imposto_ICMS_vBCST]       MONEY           NOT NULL,
    [NFe1_imposto_ICMS_pICMSST]     SMALLMONEY      NOT NULL,
    [NFe1_imposto_ICMS_vICMSST]     MONEY           NOT NULL,
    [NFe1_imposto_IPI_clEnq]        CHAR (5)        NOT NULL,
    [NFe1_imposto_IPI_CNPJProd]     CHAR (14)       NOT NULL,
    [NFe1_imposto_IPI_cSelo]        CHAR (7)        NOT NULL,
    [NFe1_imposto_IPI_qSelo]        DECIMAL (12)    NOT NULL,
    [NFe1_imposto_IPI_cEnq]         CHAR (3)        NOT NULL,
    [NFe1_imposto_IPI_CST]          CHAR (2)        NOT NULL,
    [NFe1_imposto_IPI_vBC]          MONEY           NOT NULL,
    [NFe1_imposto_IPI_qUnid]        DECIMAL (15, 4) NOT NULL,
    [NFe1_imposto_IPI_vUnid]        DECIMAL (15, 4) NOT NULL,
    [NFe1_imposto_IPI_pIPI]         SMALLMONEY      NOT NULL,
    [NFe1_imposto_IPI_vIPI]         MONEY           NOT NULL,
    [NFe1_imposto_IPI_vTip]         CHAR (1)        NOT NULL,
    [NFe1_imposto_PIS_CST]          CHAR (2)        NOT NULL,
    [NFe1_imposto_PIS_vBC]          MONEY           NOT NULL,
    [NFe1_imposto_PIS_pPIS]         SMALLMONEY      NOT NULL,
    [NFe1_imposto_PIS_vPIS]         MONEY           NOT NULL,
    [NFe1_imposto_PIS_qBCProd]      DECIMAL (15, 4) NOT NULL,
    [NFe1_imposto_PIS_vAliqProd]    DECIMAL (15, 4) NOT NULL,
    [NFe1_imposto_COFINS_CST]       CHAR (2)        NOT NULL,
    [NFe1_imposto_COFINS_vBC]       MONEY           NOT NULL,
    [NFe1_imposto_COFINS_pCOFINS]   SMALLMONEY      NOT NULL,
    [NFe1_imposto_COFINS_qBCProd]   DECIMAL (15, 4) NOT NULL,
    [NFe1_imposto_COFINS_vAliqProd] DECIMAL (15, 4) NOT NULL,
    [NFe1_imposto_COFINS_vCOFINS]   MONEY           NOT NULL,
    [NFe1_imposto_ISSQN_vBC]        MONEY           NOT NULL,
    [NFe1_imposto_ISSQN_vAliq]      SMALLMONEY      NOT NULL,
    [NFe1_imposto_ISSQN_vISSQN]     MONEY           NOT NULL,
    [NFe1_imposto_ISSQN_cMunFG]     INT             NOT NULL,
    [NFe1_imposto_ISSQN_cListServ]  SMALLINT        NOT NULL,
    [NFe1_infAdProd]                VARCHAR (500)   NOT NULL,
    [NFe1_imposto_II_vBC]           MONEY           NOT NULL,
    [NFe1_imposto_II_vDespAdu]      MONEY           NOT NULL,
    [NFe1_imposto_II_vII]           MONEY           NOT NULL,
    [NFe1_imposto_II_vIOF]          MONEY           NOT NULL,
    [Nfe1_prod_indTot]              SMALLINT        NULL,
    [NFe1_prod_vOutro]              MONEY           NULL,
    [Nfe1_Prod_xPed]                CHAR (15)       NULL,
    [Nfe1_Prod_nItemPed]            INT             NULL,
    [Nfe1_Imposto_ICMS_vBCSTRet]    MONEY           NULL,
    [Nfe1_Imposto_ICMS_vICMSSTRet]  MONEY           NULL,
    [Nfe1_Imposto_ICMS_pCredSN]     SMALLMONEY      NULL,
    [Nfe1_Imposto_ICMS_vCredICMSSN] MONEY           NULL,
    CONSTRAINT [PK__NFE1ITE__09DE7BCC] PRIMARY KEY CLUSTERED ([NFe0Emp] ASC, [NFe0FatNum] ASC, [NFe0FatTip] ASC, [NFe0FatCnpjCpfEmi] ASC, [NFe1_nItem] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UNFE1ITEA]
    ON [dbo].[NFE1ITE]([NFe0Emp] ASC, [NFe0FatNum] ASC, [NFe0FatTip] ASC, [NFe0FatCnpjCpfEmi] ASC, [NFe1_nItem] DESC);

