CREATE TABLE [dbo].[NFESCE] (
    [Scecod] SMALLINT  NOT NULL,
    [SceCes] CHAR (10) NOT NULL,
    [SceCno] CHAR (10) NOT NULL,
    [Scetip] CHAR (1)  NOT NULL,
    CONSTRAINT [PK_NFESCE] PRIMARY KEY CLUSTERED ([Scecod] ASC)
);

