CREATE TABLE [dbo].[SGPER] (
    [SgPer0Cod] CHAR (20)      NOT NULL,
    [SgPer0Nom] CHAR (50)      NOT NULL,
    [SgPer0Des] VARCHAR (1000) NOT NULL,
    CONSTRAINT [PK_SGPER] PRIMARY KEY CLUSTERED ([SgPer0Cod] ASC)
);

