CREATE TABLE [dbo].[Funcionario_Documento] (
    [cd_funcionario]              INT           NOT NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [cd_carteira_prof]            VARCHAR (15)  NULL,
    [sg_serie_carteira_prof]      VARCHAR (10)  NULL,
    [dt_carteira_prof]            DATETIME      NULL,
    [sg_carteira_prof]            CHAR (5)      NULL,
    [cd_rg]                       VARCHAR (18)  NULL,
    [dt_rg]                       DATETIME      NULL,
    [sg_serie_rg]                 VARCHAR (10)  NULL,
    [cd_cpf]                      VARCHAR (15)  NULL,
    [cd_titulo_eleitor]           VARCHAR (20)  NULL,
    [cd_zona_titulo]              VARCHAR (10)  NULL,
    [cd_secao_titulo]             VARCHAR (10)  NULL,
    [nm_cidade_titulo]            VARCHAR (25)  NULL,
    [cd_cnh]                      VARCHAR (20)  NULL,
    [dt_cnh]                      DATETIME      NULL,
    [sg_categoria_cnh]            VARCHAR (5)   NULL,
    [cd_reservista]               VARCHAR (20)  NULL,
    [cd_pis]                      VARCHAR (20)  NULL,
    [cd_sindicato]                INT           NULL,
    [cd_registro_sindicato]       VARCHAR (10)  NULL,
    [cd_banco]                    INT           NULL,
    [cd_agencia_banco]            INT           NULL,
    [cd_conta_fgts]               VARCHAR (25)  NULL,
    [ic_optante_fgts]             CHAR (1)      NULL,
    [dt_opcao_fgts]               DATETIME      NULL,
    [dt_retratacao_fgts]          DATETIME      NULL,
    [dt_vencimento_cnh]           DATETIME      NULL,
    [nm_obs_documento]            VARCHAR (100) NULL,
    [nm_orgao_emissor_rg]         VARCHAR (15)  NULL,
    [dt_emissao_titulo]           DATETIME      NULL,
    [ic_doc_pendente_funcionario] CHAR (1)      NULL,
    [dt_exp_rg]                   DATETIME      NULL,
    CONSTRAINT [PK_Funcionario_Documento] PRIMARY KEY CLUSTERED ([cd_funcionario] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Funcionario_Documento_Funcionario] FOREIGN KEY ([cd_funcionario]) REFERENCES [dbo].[Funcionario] ([cd_funcionario])
);

