CREATE TABLE [dbo].[Funcionario_Informacao] (
    [cd_funcionario]           INT          NOT NULL,
    [ic_adicional_noturno]     CHAR (1)     NULL,
    [ic_periculosidade]        CHAR (1)     NULL,
    [pc_periculosidade]        FLOAT (53)   NULL,
    [ic_insalubridade]         CHAR (1)     NULL,
    [pc_insalubridade]         FLOAT (53)   NULL,
    [ic_pensao]                CHAR (1)     NULL,
    [ic_vale_transporte]       CHAR (1)     NULL,
    [ic_dsr]                   CHAR (1)     NULL,
    [ic_adiantamento]          CHAR (1)     NULL,
    [qt_hora_mes]              FLOAT (53)   NULL,
    [qt_salario_familia]       INT          NULL,
    [qt_ir]                    INT          NULL,
    [ic_ferias]                CHAR (1)     NULL,
    [dt_demissao]              DATETIME     NULL,
    [cd_motivo_demissao]       INT          NULL,
    [dt_afastamento]           DATETIME     NULL,
    [cd_tipo_afastamento]      INT          NULL,
    [dt_desligamento]          DATETIME     NULL,
    [cd_tipo_desligamento]     INT          NULL,
    [cd_turno]                 INT          NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [ic_atualizacao_cart_prof] CHAR (1)     NULL,
    [dt_alteracao_cart_prof]   DATETIME     NULL,
    [nm_motivo_cart_prof]      VARCHAR (40) NULL,
    [nm_obs_informacao]        VARCHAR (60) NULL,
    [cd_sindicato]             INT          NULL,
    [ic_aprendiz_funcionario]  CHAR (1)     NULL,
    [ic_assistencial]          CHAR (1)     NULL,
    [ic_confederativa]         CHAR (1)     NULL,
    [pc_pensao]                FLOAT (53)   NULL,
    [vl_pensao]                FLOAT (53)   NULL,
    [dt_proxima_ferias]        DATETIME     NULL,
    [dt_solicitacao_ferias]    DATETIME     NULL,
    [ic_convenio]              CHAR (1)     NULL,
    [cd_convenio]              INT          NULL,
    [cd_plano_medico]          INT          NULL,
    [cd_registro_convenio]     VARCHAR (30) NULL,
    [ic_refeicao_funcionario]  CHAR (1)     NULL,
    [cd_vinculo_empregaticio]  INT          NULL,
    [cd_tipo_regime]           INT          NULL,
    CONSTRAINT [PK_Funcionario_Informacao] PRIMARY KEY CLUSTERED ([cd_funcionario] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Funcionario_Informacao_Sindicato] FOREIGN KEY ([cd_sindicato]) REFERENCES [dbo].[Sindicato] ([cd_sindicato]),
    CONSTRAINT [FK_Funcionario_Informacao_Turno] FOREIGN KEY ([cd_turno]) REFERENCES [dbo].[Turno] ([cd_turno])
);

