CREATE TABLE [dbo].[Historico_Compra_Servico] (
    [cd_historico_compra]       INT           NULL,
    [dt_historico_compra]       DATETIME      NULL,
    [cd_servico]                INT           NULL,
    [cd_fornecedor]             INT           NULL,
    [cd_cotacao]                INT           NULL,
    [dt_cotacao]                DATETIME      NULL,
    [vl_historico_compra]       FLOAT (53)    NULL,
    [pc_iss]                    FLOAT (53)    NULL,
    [pc_icms]                   FLOAT (53)    NULL,
    [pc_desconto]               FLOAT (53)    NULL,
    [vl_liq_historico_compra]   FLOAT (53)    NULL,
    [nm_historico_compra]       VARCHAR (100) NULL,
    [cd_condicao_pagamento]     INT           NULL,
    [qt_dia_entrega]            FLOAT (53)    NULL,
    [nm_entrega]                VARCHAR (40)  NULL,
    [cd_pedido_compra]          INT           NULL,
    [cd_requisicao_compra]      INT           NULL,
    [cd_item_requisicao_compra] INT           NULL,
    [cd_opcao_compra]           INT           NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [qt_historico_compra]       FLOAT (53)    NULL,
    [cd_item_pedido_compra]     INT           NULL,
    [cd_item_cotacao]           INT           NULL,
    [nm_marca_produto]          VARCHAR (30)  NULL,
    [dt_pedido_compra]          DATETIME      NULL,
    [dt_requisicao_compra]      DATETIME      NULL,
    [cd_nota_entrada]           INT           NULL,
    [cd_item_nota_entrada]      INT           NULL,
    [dt_nota_entrada]           DATETIME      NULL,
    [cd_local_entrega_empresa]  INT           NULL,
    [ic_manual_hist_compra]     CHAR (1)      NULL,
    [ds_historico_compra]       TEXT          NULL,
    [cd_moeda]                  INT           NULL,
    CONSTRAINT [FK_Historico_Compra_Servico_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda])
);

