CREATE TABLE [dbo].[INPRO] (
    [CODIGO]     VARCHAR (20)  NULL,
    [NOME]       VARCHAR (40)  NULL,
    [COMPLEM]    VARCHAR (40)  NULL,
    [DESCRIC]    VARCHAR (60)  NULL,
    [PROMAT]     VARCHAR (1)   NULL,
    [UNIDADE]    VARCHAR (3)   NULL,
    [SETOR]      FLOAT (53)    NULL,
    [CODNBM]     VARCHAR (10)  NULL,
    [LNBM]       VARCHAR (1)   NULL,
    [CODTRIB]    VARCHAR (3)   NULL,
    [QTDEST]     FLOAT (53)    NULL,
    [QTDVIR]     FLOAT (53)    NULL,
    [QTDMIN]     FLOAT (53)    NULL,
    [QTDMAX]     FLOAT (53)    NULL,
    [QTDMED]     FLOAT (53)    NULL,
    [QTDCOM]     FLOAT (53)    NULL,
    [QTDPRO]     FLOAT (53)    NULL,
    [CODALT]     VARCHAR (20)  NULL,
    [IMPCOD]     VARCHAR (20)  NULL,
    [IMPDESC]    VARCHAR (50)  NULL,
    [IMPVAL]     FLOAT (53)    NULL,
    [IMPIND]     FLOAT (53)    NULL,
    [DOLAR]      FLOAT (53)    NULL,
    [VRVENDA]    FLOAT (53)    NULL,
    [CONSUM]     FLOAT (53)    NULL,
    [MATACADO]   FLOAT (53)    NULL,
    [VRATACADO]  FLOAT (53)    NULL,
    [MVAREJO]    FLOAT (53)    NULL,
    [VRVAREJO]   FLOAT (53)    NULL,
    [VRVARPRO]   FLOAT (53)    NULL,
    [VRTRANSF]   FLOAT (53)    NULL,
    [DTPROMO]    DATETIME      NULL,
    [N_DOLAR]    FLOAT (53)    NULL,
    [N_VRVENDA]  FLOAT (53)    NULL,
    [N_MATACADO] FLOAT (53)    NULL,
    [N_VRATACAD] FLOAT (53)    NULL,
    [N_MVAREJO]  FLOAT (53)    NULL,
    [N_VRVAREJO] FLOAT (53)    NULL,
    [UPDAT_]     DATETIME      NULL,
    [LISTA]      VARCHAR (1)   NULL,
    [DTPRECO]    DATETIME      NULL,
    [PESO]       FLOAT (53)    NULL,
    [TIPO]       VARCHAR (1)   NULL,
    [MARKUP]     FLOAT (53)    NULL,
    [INDELAB]    FLOAT (53)    NULL,
    [LARGURA]    FLOAT (53)    NULL,
    [CAIXAS]     FLOAT (53)    NULL,
    [EMPRESA]    VARCHAR (15)  NULL,
    [DESENHO]    VARCHAR (15)  NULL,
    [FOLLOWUP]   VARCHAR (200) NULL,
    [QTDFOL]     FLOAT (53)    NULL,
    [COMPRIM]    FLOAT (53)    NULL,
    [GRAMATURA]  FLOAT (53)    NULL,
    [DTULTC]     DATETIME      NULL,
    [QTDULTC]    FLOAT (53)    NULL,
    [ULTNOTA]    FLOAT (53)    NULL,
    [DIASREP]    SMALLINT      NULL,
    [VRDL]       FLOAT (53)    NULL,
    [EMPULTC]    VARCHAR (15)  NULL,
    [EMP1]       VARCHAR (15)  NULL,
    [EMP2]       VARCHAR (15)  NULL,
    [EMP3]       VARCHAR (15)  NULL,
    [EMP4]       VARCHAR (15)  NULL,
    [EMP5]       VARCHAR (15)  NULL,
    [EMP6]       VARCHAR (15)  NULL,
    [EMP7]       VARCHAR (15)  NULL,
    [EMP8]       VARCHAR (15)  NULL,
    [EMP9]       VARCHAR (15)  NULL,
    [EMP0]       VARCHAR (15)  NULL,
    [VRCOT1]     FLOAT (53)    NULL,
    [VRCOT2]     FLOAT (53)    NULL,
    [VRCOT3]     FLOAT (53)    NULL,
    [VRCOT4]     FLOAT (53)    NULL,
    [VRCOT5]     FLOAT (53)    NULL,
    [VRCOT6]     FLOAT (53)    NULL,
    [VRCOT7]     FLOAT (53)    NULL,
    [VRCOT8]     FLOAT (53)    NULL,
    [VRCOT9]     FLOAT (53)    NULL,
    [VRCOT0]     FLOAT (53)    NULL,
    [DTCOT1]     DATETIME      NULL,
    [DTCOT2]     DATETIME      NULL,
    [DTCOT3]     DATETIME      NULL,
    [DTCOT4]     DATETIME      NULL,
    [DTCOT5]     DATETIME      NULL,
    [DTCOT6]     DATETIME      NULL,
    [DTCOT7]     DATETIME      NULL,
    [DTCOT8]     DATETIME      NULL,
    [DTCOT9]     DATETIME      NULL,
    [DTCOT0]     DATETIME      NULL,
    [NCOT1]      FLOAT (53)    NULL,
    [NCOT2]      FLOAT (53)    NULL,
    [NCOT3]      FLOAT (53)    NULL,
    [NCOT4]      FLOAT (53)    NULL,
    [NCOT5]      FLOAT (53)    NULL,
    [NCOT6]      FLOAT (53)    NULL,
    [NCOT7]      FLOAT (53)    NULL,
    [NCOT8]      FLOAT (53)    NULL,
    [NCOT9]      FLOAT (53)    NULL,
    [NCOT0]      FLOAT (53)    NULL,
    [MARCA]      VARCHAR (15)  NULL,
    [ALTURA1]    FLOAT (53)    NULL,
    [SITUACAO]   VARCHAR (1)   NULL,
    [MOEDA]      VARCHAR (10)  NULL,
    [COMISSAO]   FLOAT (53)    NULL
);

