CREATE TABLE [dbo].[Instrucao_Interna] (
    [cd_instrucao]              INT           NOT NULL,
    [dt_instrucao]              DATETIME      NOT NULL,
    [cd_interno_instrucao]      VARCHAR (20)  NOT NULL,
    [cd_planta]                 INT           NULL,
    [cd_area]                   INT           NULL,
    [cd_departamento]           INT           NULL,
    [cd_assunto_instrucao]      INT           NULL,
    [nm_titulo_instrucao]       VARCHAR (50)  NOT NULL,
    [dt_vigencia_instrucao]     DATETIME      NULL,
    [cd_tipo_instrucao]         INT           NULL,
    [cd_situacao_instrucao]     INT           NULL,
    [cd_acesso_instrucao]       INT           NULL,
    [ic_treinamento_instrucao]  CHAR (1)      NULL,
    [ds_instrucao]              TEXT          NULL,
    [nm_doc_instrucao]          VARCHAR (100) NULL,
    [nm_fluxo_instrucao]        VARCHAR (100) NULL,
    [nm_obs_instrucao]          VARCHAR (40)  NULL,
    [cd_usuario_formatador]     INT           NULL,
    [cd_usuario_emitente]       INT           NULL,
    [cd_usuario_aprovacao]      INT           NULL,
    [dt_aprovacao_instrucao]    DATETIME      NULL,
    [dt_cancelamento_instrucao] DATETIME      NULL,
    [dt_ativacao_instrucao]     DATETIME      NULL,
    [nm_motivo_cancelamento]    VARCHAR (40)  NULL,
    [nm_motivo_ativacao]        VARCHAR (40)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    CONSTRAINT [PK_Instrucao_Interna] PRIMARY KEY CLUSTERED ([cd_instrucao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Instrucao_Interna_Usuario] FOREIGN KEY ([cd_usuario_aprovacao]) REFERENCES [dbo].[Usuario] ([cd_usuario])
);

