CREATE TABLE [dbo].[Invoice] (
    [cd_fornecedor]           INT          NOT NULL,
    [cd_importador]           INT          NOT NULL,
    [cd_invoice]              INT          NOT NULL,
    [cd_tipo_frete]           INT          NULL,
    [nm_invoice]              VARCHAR (30) NULL,
    [dt_invoice]              DATETIME     NULL,
    [dt_embarque]             DATETIME     NULL,
    [cd_porto_origem]         INT          NULL,
    [cd_porto_destino]        INT          NULL,
    [cd_condicao_pagamento]   INT          NULL,
    [cd_moeda]                FLOAT (53)   NULL,
    [vL_total_invoice]        FLOAT (53)   NULL,
    [qt_total_volume]         FLOAT (53)   NULL,
    [qt_total_item]           FLOAT (53)   NULL,
    [qt_peso_bruto]           FLOAT (53)   NULL,
    [qt_peso_liquido]         FLOAT (53)   NULL,
    [ds_invoice_observacao]   TEXT         NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    [cd_termo_comercial]      INT          NULL,
    [cd_status_invoice]       INT          NULL,
    [vl_moeda]                FLOAT (53)   NULL,
    [dt_moeda]                DATETIME     NULL,
    [dt_chegada_empresa_prev] DATETIME     NULL,
    [dt_liberacao_prev]       DATETIME     NULL,
    [dt_chegada_pais_prev]    DATETIME     NULL,
    [dt_moeda_frete]          DATETIME     NULL,
    [vl_moeda_frete]          FLOAT (53)   NULL,
    [cd_moeda_frete]          INT          NULL,
    [vl_embalagem_invoice]    FLOAT (53)   NULL,
    [vl_total_frete]          FLOAT (53)   NULL,
    [cd_tipo_importacao]      INT          NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED ([cd_invoice] ASC) WITH (FILLFACTOR = 90)
);

