CREATE TABLE [dbo].[kgm_nota_saida_item] (
    [cd_nota_saida]                 INT           NOT NULL,
    [cd_item_nota_saida]            INT           NOT NULL,
    [cd_num_formulario_nota]        INT           NULL,
    [nm_fantasia_produto]           VARCHAR (30)  NULL,
    [ds_item_nota_saida]            TEXT          NULL,
    [cd_pd_compra_item_nota]        VARCHAR (40)  NULL,
    [cd_posicao_item_nota]          VARCHAR (15)  NULL,
    [cd_os_item_nota_saida]         VARCHAR (15)  NULL,
    [vl_unitario_item_nota]         FLOAT (53)    NULL,
    [dt_restricao_item_nota]        DATETIME      NULL,
    [ic_status_item_nota_saida]     CHAR (1)      NULL,
    [nm_motivo_restricao_item]      TEXT          NULL,
    [qt_devolucao_item_nota]        FLOAT (53)    NULL,
    [cd_requisicao_faturamento]     INT           NULL,
    [cd_item_requisicao]            INT           NULL,
    [cd_produto]                    INT           NULL,
    [cd_procedencia_produto]        INT           NULL,
    [cd_tributacao]                 INT           NULL,
    [vl_total_item]                 FLOAT (53)    NULL,
    [cd_unidade_medida]             INT           NULL,
    [pc_icms]                       FLOAT (53)    NULL,
    [pc_ipi]                        FLOAT (53)    NULL,
    [vl_ipi]                        FLOAT (53)    NULL,
    [cd_usuario]                    INT           NULL,
    [dt_usuario]                    DATETIME      NULL,
    [qt_item_nota_saida]            FLOAT (53)    NULL,
    [qt_liquido_item_nota]          FLOAT (53)    NULL,
    [qt_bruto_item_nota_saida]      FLOAT (53)    NULL,
    [cd_item_pedido_venda]          INT           NULL,
    [cd_pedido_venda]               INT           NULL,
    [cd_categoria_produto]          INT           NULL,
    [cd_classificacao_fiscal]       INT           NULL,
    [cd_situacao_tributaria]        CHAR (3)      NULL,
    [vl_frete_item]                 FLOAT (53)    NULL,
    [vl_seguro_item]                FLOAT (53)    NULL,
    [vl_desp_acess_item]            FLOAT (53)    NULL,
    [pc_icms_desc_item]             FLOAT (53)    NULL,
    [dt_cancel_item_nota_saida]     DATETIME      NULL,
    [pc_desconto_item]              FLOAT (53)    NULL,
    [cd_tipo_calculo]               CHAR (1)      NULL,
    [cd_lote_produto]               VARCHAR (40)  NULL,
    [cd_numero_serie_produto]       VARCHAR (40)  NULL,
    [cd_status_nota]                INT           NULL,
    [nm_produto_item_nota]          VARCHAR (100) NULL,
    [qt_saldo_atual_produto]        FLOAT (53)    NULL,
    [cd_servico]                    INT           NULL,
    [ds_servico]                    TEXT          NULL,
    [pc_iss_servico]                FLOAT (53)    NULL,
    [vl_servico]                    FLOAT (53)    NULL,
    [pc_irrf_serv_empresa]          FLOAT (53)    NULL,
    [vl_irrf_nota_saida]            FLOAT (53)    NULL,
    [vl_iss_servico]                FLOAT (53)    NULL,
    [pc_reducao_icms]               FLOAT (53)    NULL,
    [cd_pdcompra_item_nota]         INT           NULL,
    [cd_registro_exportacao]        VARCHAR (15)  NULL,
    [cd_operacao_fiscal]            INT           NULL,
    [ic_tipo_nota_saida_item]       CHAR (1)      NULL,
    [qt_saldo_estoque]              FLOAT (53)    NULL,
    [cd_di]                         INT           NULL,
    [nm_di]                         VARCHAR (20)  NULL,
    [nm_invoice]                    VARCHAR (50)  NULL,
    [ic_movimento_estoque]          CHAR (1)      NULL,
    [qt_ant_item_nota_saida]        FLOAT (53)    NULL,
    [nm_kardex_item_nota_saida]     VARCHAR (30)  NULL,
    [ic_dev_nota_saida]             CHAR (1)      NULL,
    [cd_nota_dev_nota_saida]        VARCHAR (15)  NULL,
    [cd_pedido_importacao]          INT           NULL,
    [cd_item_ped_imp]               INT           NULL,
    [dt_nota_saida]                 DATETIME      NULL,
    [cd_grupo_produto]              INT           NULL,
    [vl_icms_item]                  FLOAT (53)    NULL,
    [vl_base_icms_item]             FLOAT (53)    NULL,
    [vl_base_ipi_item]              FLOAT (53)    NULL,
    [pc_subs_trib_item]             FLOAT (53)    NULL,
    [cd_reg_exportacao_item]        VARCHAR (14)  NULL,
    [vl_icms_isento_item]           FLOAT (53)    NULL,
    [vl_icms_outros_item]           FLOAT (53)    NULL,
    [vl_icms_obs_item]              FLOAT (53)    NULL,
    [vl_ipi_isento_item]            FLOAT (53)    NULL,
    [vl_ipi_outros_item]            FLOAT (53)    NULL,
    [vl_ipi_obs_item]               FLOAT (53)    NULL,
    [cd_fase_produto]               INT           NULL,
    [ic_mp66_item_nota_saida]       CHAR (1)      NULL,
    [cd_mascara_produto]            VARCHAR (20)  NULL,
    [cd_conta]                      INT           NULL,
    [cd_produto_smo]                INT           NULL,
    [cd_grupo_produto_smo]          INT           NULL,
    [vl_ipi_corpo_nota_saida]       FLOAT (53)    NULL,
    [ic_icms_zerado_item]           CHAR (1)      NULL,
    [ic_ipi_zerado_item]            CHAR (1)      NULL,
    [vl_bc_subst_icms_item]         FLOAT (53)    NULL,
    [cd_tributacao_anterior]        INT           NULL,
    [cd_di_item]                    INT           NULL,
    [ic_iss_servico]                CHAR (1)      NULL,
    [vl_cofins]                     FLOAT (53)    NULL,
    [vl_pis]                        FLOAT (53)    NULL,
    [vl_csll]                       FLOAT (53)    NULL,
    [dt_ativacao_nota_saida]        DATETIME      NULL,
    [cd_moeda_cotacao]              INT           NULL,
    [vl_moeda_cotacao]              FLOAT (53)    NULL,
    [dt_moeda_cotacao]              DATETIME      NULL,
    [cd_lote_item_nota_saida]       VARCHAR (25)  NULL,
    [cd_num_serie_item_nota]        VARCHAR (30)  NULL,
    [vl_ii]                         FLOAT (53)    NULL,
    [pc_ii]                         FLOAT (53)    NULL,
    [vl_desp_aduaneira_item]        FLOAT (53)    NULL,
    [pc_cofins]                     FLOAT (53)    NULL,
    [pc_pis]                        FLOAT (53)    NULL,
    [ic_cambio_fixado_pedido_venda] CHAR (1)      NULL,
    [ic_perda_item_nota_saida]      CHAR (1)      NULL,
    [cd_lote_item_nota]             VARCHAR (25)  NULL,
    [vl_inss_nota_saida]            FLOAT (53)    NULL,
    [pc_inss_servico]               FLOAT (53)    NULL,
    [vl_icms_desc_item]             FLOAT (53)    NULL,
    [vl_icms_subst_icms_item]       FLOAT (53)    NULL,
    [qt_cubagem_item_nota]          FLOAT (53)    NULL,
    [cd_rnc]                        INT           NULL,
    [cd_nota_entrada]               INT           NULL,
    [cd_item_nota_entrada]          INT           NULL,
    [ic_subst_tributaria_item]      CHAR (1)      NULL,
    [cd_nota_saida_origem]          INT           NULL,
    [cd_item_nota_origem]           INT           NULL,
    [vl_unitario_ipi_produto]       FLOAT (53)    NULL,
    [qt_multiplo_embalagem]         FLOAT (53)    NULL
);

