CREATE TABLE [dbo].[Laudo] (
    [cd_laudo]                  INT          NOT NULL,
    [dt_laudo]                  DATETIME     NULL,
    [cd_origem_laudo]           INT          NULL,
    [cd_fornecedor]             INT          NULL,
    [cd_nota_entrada]           INT          NULL,
    [cd_item_nota_entrada]      INT          NULL,
    [cd_processo]               INT          NULL,
    [cd_amostra]                INT          NULL,
    [cd_produto]                INT          NULL,
    [cd_unidade_medida]         INT          NULL,
    [qt_laudo]                  FLOAT (53)   NULL,
    [cd_lote]                   VARCHAR (25) NULL,
    [dt_fabricacao]             DATETIME     NULL,
    [dt_validade]               DATETIME     NULL,
    [cd_tecnico]                INT          NULL,
    [ds_laudo]                  TEXT         NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [nm_produto_laudo]          VARCHAR (50) NULL,
    [cd_fase_produto]           INT          NULL,
    [ds_cabecalho]              TEXT         NULL,
    [ds_rodape]                 TEXT         NULL,
    [cd_serie_nota_fiscal]      INT          NULL,
    [cd_operacao_fiscal]        INT          NULL,
    [cd_origem_produto]         INT          NULL,
    [cd_metodo_inspecao]        INT          NULL,
    [cd_tipo_inspecao]          INT          NULL,
    [cd_inspetor]               INT          NULL,
    [cd_cliente]                INT          NULL,
    [cd_pedido_venda]           INT          NULL,
    [cd_item_pedido_venda]      INT          NULL,
    [cd_fabricante]             INT          NULL,
    [cd_interface]              INT          NULL,
    [qt_amostra_laudo]          FLOAT (53)   NULL,
    [qt_aprovado_laudo]         FLOAT (53)   NULL,
    [qt_rejeitado_laudo]        FLOAT (53)   NULL,
    [cd_servico]                INT          NULL,
    [nm_produto_especial_laudo] VARCHAR (50) NULL,
    [cd_lote_interno]           VARCHAR (25) NULL,
    [cd_lote_fabricante]        VARCHAR (25) NULL,
    CONSTRAINT [PK_Laudo] PRIMARY KEY CLUSTERED ([cd_laudo] ASC) WITH (FILLFACTOR = 90)
);

