CREATE TABLE [dbo].[Lote_Produto_Item] (
    [cd_lote_produto]          INT          NOT NULL,
    [cd_produto]               INT          NOT NULL,
    [qt_produto_lote_produto]  FLOAT (53)   NULL,
    [nm_obs_item_lote_produto] VARCHAR (40) NULL,
    [dt_inicio_item_lote]      DATETIME     NULL,
    [dt_final_item_lote]       DATETIME     NULL,
    [ic_status_item_lote]      CHAR (1)     NULL,
    [cd_peca_item_lote]        INT          NULL,
    [cd_box_item_lote]         VARCHAR (10) NULL,
    [cd_cor]                   INT          NULL,
    [cd_tipo_desenho]          INT          NULL,
    [cd_fase_produto]          INT          NULL,
    [cd_loja]                  INT          NULL,
    [qt_largura_item_lote]     FLOAT (53)   NULL,
    [qt_comp_item_lote]        FLOAT (53)   NULL,
    [qt_venda_item_lote]       FLOAT (53)   NULL,
    [qt_reserva_m2_item_lote]  FLOAT (53)   NULL,
    [qt_saldo_m2_item_lote]    FLOAT (53)   NULL,
    [qt_saldo_ml_item_lote]    FLOAT (53)   NULL,
    [cd_unidade_medida]        INT          NULL,
    [cd_movimento_lote]        INT          NULL,
    [cd_movimento_lote_origem] INT          NULL,
    [ic_tipo_movimento_lote]   CHAR (1)     NULL,
    [cd_movimento_estoque]     INT          NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [cd_item_nota_saida]       INT          NULL,
    [cd_nota_saida]            INT          NULL,
    [ic_saldo_item_lote]       CHAR (1)     NULL,
    [cd_nota_entrada]          INT          NULL,
    [cd_fornecedor]            INT          NULL,
    [cd_serie_nota_fiscal]     INT          NULL,
    [cd_operacao_fiscal]       INT          NULL,
    [cd_item_nota_entrada]     INT          NULL,
    [qt_saldo_atual_lote]      FLOAT (53)   NULL,
    CONSTRAINT [PK_Lote_Produto_Item] PRIMARY KEY CLUSTERED ([cd_lote_produto] ASC, [cd_produto] ASC) WITH (FILLFACTOR = 90)
);

