CREATE TABLE [dbo].[Materia_Prima] (
    [cd_mat_prima]              INT          NOT NULL,
    [nm_mat_prima]              VARCHAR (30) NULL,
    [nm_fantasia_mat_prima]     VARCHAR (15) NULL,
    [sg_mat_prima]              VARCHAR (10) NULL,
    [qt_peso_especifico_materi] FLOAT (53)   NULL,
    [ic_tipo_calculo_mat_prima] CHAR (1)     NULL,
    [qt_velocidade_preacab]     FLOAT (53)   NULL,
    [qt_velocidade_acab]        FLOAT (53)   NULL,
    [qt_fator_fur_fixacao]      FLOAT (53)   NULL,
    [ic_oxicorte_mat_prima]     CHAR (1)     NULL,
    [qt_forca_especifica]       FLOAT (53)   NULL,
    [ic_ferramenta_cnc]         CHAR (1)     NULL,
    [vl_mat_prima]              FLOAT (53)   NULL,
    [nm_obs_mat_prima]          VARCHAR (70) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [vl_materia_prima]          FLOAT (53)   NULL,
    [ic_tipo_mat_prima]         CHAR (1)     NULL,
    [cd_unidade_medida]         INT          NULL,
    [cd_grupo_estoque]          INT          NULL,
    [nm_venda_mat_prima]        VARCHAR (15) NULL,
    [cd_tipo_calculo]           INT          NULL,
    [cd_classificacao_fiscal]   INT          NULL,
    [dt_mat_prima]              DATETIME     NULL,
    [vl_custo_exportacao]       FLOAT (53)   NULL,
    [qt_coeficiente_corte]      FLOAT (53)   NULL,
    [vl_fator_queda_producao]   FLOAT (53)   NULL,
    CONSTRAINT [PK_Materia_Prima] PRIMARY KEY CLUSTERED ([cd_mat_prima] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Materia_Prima_Classificacao_Fiscal] FOREIGN KEY ([cd_classificacao_fiscal]) REFERENCES [dbo].[Classificacao_Fiscal] ([cd_classificacao_fiscal]),
    CONSTRAINT [FK_Materia_Prima_Unidade_Medida] FOREIGN KEY ([cd_unidade_medida]) REFERENCES [dbo].[Unidade_Medida] ([cd_unidade_medida])
);

