CREATE TABLE [dbo].[Medico] (
    [cd_medico]               INT           NOT NULL,
    [nm_medico]               VARCHAR (40)  NULL,
    [cd_cep]                  VARCHAR (8)   NULL,
    [nm_bairro_medico]        VARCHAR (20)  NULL,
    [cd_crm_medico]           VARCHAR (20)  NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [cd_tipo_pessoa]          INT           NULL,
    [dt_alteracao_medico]     DATETIME      NULL,
    [dt_cadastro_medico]      DATETIME      NULL,
    [ic_situacao_medico]      CHAR (1)      NULL,
    [cd_numero_endereco]      VARCHAR (10)  NULL,
    [nm_complemento_endereco] VARCHAR (40)  NULL,
    [nm_endereco_medico]      VARCHAR (50)  NULL,
    [ds_perfil_medico]        TEXT          NULL,
    [nm_obs_medico]           VARCHAR (40)  NULL,
    [cd_identifica_cep]       INT           NULL,
    [cd_pais]                 INT           NULL,
    [cd_estado]               INT           NULL,
    [cd_cidade]               INT           NULL,
    [nm_site_medico]          VARCHAR (100) NULL,
    [nm_email_medico]         VARCHAR (100) NULL,
    [cd_celular_medico]       VARCHAR (15)  NULL,
    [cd_ddd_celular_medico]   CHAR (4)      NULL,
    [cd_fone_medico]          VARCHAR (15)  NULL,
    [cd_ddd_medico]           VARCHAR (4)   NULL,
    [nm_fantasia_medico]      VARCHAR (15)  NULL,
    CONSTRAINT [PK_Medico] PRIMARY KEY CLUSTERED ([cd_medico] ASC) WITH (FILLFACTOR = 90)
);

