CREATE TABLE [dbo].[Membro] (
    [cd_membro]               INT           NOT NULL,
    [nm_membro]               VARCHAR (50)  NULL,
    [cd_tipo_membro]          INT           NULL,
    [dt_nascimento_membro]    DATETIME      NULL,
    [cd_estado_civil]         INT           NULL,
    [cd_rg_obreiro]           VARCHAR (18)  NULL,
    [cd_cpf_membro]           VARCHAR (18)  NULL,
    [dt_registro_membro]      DATETIME      NULL,
    [dt_cadastro_membro]      DATETIME      NULL,
    [cd_pais]                 INT           NULL,
    [cd_estado]               INT           NULL,
    [cd_cidade]               INT           NULL,
    [cd_identifica_cep]       INT           NULL,
    [nm_endereco_membro]      VARCHAR (60)  NULL,
    [cd_numero_endereco]      VARCHAR (10)  NULL,
    [nm_complemento_endereco] VARCHAR (30)  NULL,
    [nm_bairro]               VARCHAR (25)  NULL,
    [nm_foto_membro]          VARCHAR (100) NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [cd_igreja]               INT           NULL,
    [ds_membro]               TEXT          NULL,
    [dt_batismo_membro]       DATETIME      NULL,
    [cd_ddd_membro]           CHAR (4)      NULL,
    [cd_fone_membro]          VARCHAR (15)  NULL,
    [cd_celular_membro]       VARCHAR (15)  NULL,
    CONSTRAINT [PK_Membro] PRIMARY KEY CLUSTERED ([cd_membro] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Membro_Igreja] FOREIGN KEY ([cd_igreja]) REFERENCES [dbo].[Igreja] ([cd_igreja])
);

