CREATE TABLE [dbo].[Moeda] (
    [cd_moeda]                  INT          NOT NULL,
    [nm_moeda]                  VARCHAR (30) NULL,
    [nm_fantasia_moeda]         VARCHAR (15) NULL,
    [sg_moeda]                  CHAR (10)    NULL,
    [ic_controle_moeda]         CHAR (1)     NULL,
    [ic_convercao_moeda]        CHAR (1)     NULL,
    [nm_extensao_s_moeda]       VARCHAR (20) NULL,
    [nm_extensao_p_moeda]       CHAR (20)    NULL,
    [nm_centavo_s_moeda]        VARCHAR (20) NULL,
    [nm_centavo_p_moeda]        VARCHAR (20) NULL,
    [cd_siscomex_moeda]         INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_solicita_cad_moeda]     CHAR (1)     NULL,
    [ic_taxa_moeda]             CHAR (1)     NULL,
    [ic_padrao_comercial_moeda] CHAR (1)     NULL,
    [ic_mostra_comercial_moeda] CHAR (1)     NULL,
    [qt_num_digitos]            INT          NULL,
    [ic_pad_exportacao_moeda]   CHAR (1)     NULL,
    [ic_padrao_compra_moeda]    CHAR (1)     NULL,
    [qt_digito_documento_moeda] INT          NULL,
    [cd_tipo_caixa]             INT          NULL,
    [cd_tipo_adiantamento]      INT          NULL,
    [qt_digito_entrada_moeda]   INT          NULL,
    CONSTRAINT [PK_Moeda] PRIMARY KEY CLUSTERED ([cd_moeda] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Moeda_Tipo_Adiantamento] FOREIGN KEY ([cd_tipo_adiantamento]) REFERENCES [dbo].[Tipo_Adiantamento] ([cd_tipo_adiantamento]),
    CONSTRAINT [FK_Moeda_Tipo_Caixa] FOREIGN KEY ([cd_tipo_caixa]) REFERENCES [dbo].[Tipo_Caixa] ([cd_tipo_caixa])
);

