CREATE TABLE [dbo].[Movimento_Caixa] (
    [cd_movimento_caixa]        INT          NOT NULL,
    [dt_movimento_caixa]        DATETIME     NULL,
    [vl_movimento_caixa]        MONEY        NULL,
    [cd_tipo_movimento_caixa]   INT          NULL,
    [nm_obs_movimento_caixa]    VARCHAR (40) NULL,
    [pc_desc_movimento_caixa]   FLOAT (53)   NULL,
    [dt_cancel_movimento_caixa] DATETIME     NULL,
    [nm_motivo_cancel_mov]      VARCHAR (40) NULL,
    [cd_cliente]                INT          NULL,
    [cd_vendedor]               INT          NULL,
    [cd_nota_saida]             INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_movimento_finalizado]   CHAR (1)     NULL,
    [cd_contato]                INT          NULL,
    [vl_total_descontado]       MONEY        NULL,
    [vl_dinheiro]               MONEY        NULL,
    [vl_cheque]                 MONEY        NULL,
    [vl_cartao_credito]         MONEY        NULL,
    [vl_cartao_debito]          MONEY        NULL,
    [vl_troco]                  MONEY        NULL,
    [vl_total_venda]            MONEY        NULL,
    [cd_vendedor_fechamento]    INT          NULL,
    [cd_consulta]               INT          NULL,
    [vl_cheque_eletronico]      MONEY        NULL,
    [cd_condicao_pagamento]     INT          NULL,
    [vl_total_custo_financeiro] MONEY        NULL,
    [ic_custo_financeiro]       CHAR (1)     NULL,
    [dt_validade_orcamento]     DATETIME     NULL,
    [ic_desc_acima_vendedor1]   CHAR (1)     NULL,
    [ic_desc_acima_vendedor2]   CHAR (1)     NULL,
    [cd_motivo_retirada_caixa]  INT          NULL,
    [cd_vendedor_cancelamento]  INT          NULL,
    [cd_banco_calc_custo_fin]   INT          NULL,
    [vl_credito_devolucao]      MONEY        NULL,
    [cd_loja]                   INT          NULL,
    [cd_empresa]                INT          NULL,
    [cd_terminal_caixa]         INT          NULL,
    [cd_operador_caixa]         INT          NULL,
    [cd_tabela_preco]           INT          NULL,
    [cd_tipo_endereco]          INT          NULL,
    [cd_tipo_pagamento]         INT          NULL,
    [cd_cupom_fiscal]           INT          NULL,
    [cd_cpf_cliente]            VARCHAR (18) NULL,
    [cd_cartao_credito]         INT          NULL,
    [cd_origem_caixa]           INT          NULL,
    CONSTRAINT [PK_Movimento_Caixa] PRIMARY KEY CLUSTERED ([cd_movimento_caixa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Movimento_Caixa_Banco_Calculo_Custo_Financeiro] FOREIGN KEY ([cd_banco_calc_custo_fin]) REFERENCES [dbo].[Banco_Calculo_Custo_Financeiro] ([cd_banco_calc_custo_fin]),
    CONSTRAINT [FK_Movimento_Caixa_Cliente_Contato] FOREIGN KEY ([cd_cliente], [cd_contato]) REFERENCES [dbo].[Cliente_Contato] ([cd_cliente], [cd_contato]),
    CONSTRAINT [FK_Movimento_Caixa_Condicao_Pagamento] FOREIGN KEY ([cd_condicao_pagamento]) REFERENCES [dbo].[Condicao_Pagamento] ([cd_condicao_pagamento]),
    CONSTRAINT [FK_Movimento_Caixa_Operador_Caixa] FOREIGN KEY ([cd_operador_caixa]) REFERENCES [dbo].[Operador_Caixa] ([cd_operador_caixa]),
    CONSTRAINT [FK_Movimento_Caixa_Terminal_Caixa] FOREIGN KEY ([cd_terminal_caixa]) REFERENCES [dbo].[Terminal_Caixa] ([cd_terminal_caixa]),
    CONSTRAINT [FK_Movimento_Caixa_Tipo_Cartao_Credito] FOREIGN KEY ([cd_cartao_credito]) REFERENCES [dbo].[Tipo_cartao_credito] ([cd_cartao_credito]),
    CONSTRAINT [FK_Movimento_Caixa_Vendedor2] FOREIGN KEY ([cd_vendedor_fechamento]) REFERENCES [dbo].[Vendedor] ([cd_vendedor])
);

