CREATE TABLE [dbo].[Movimento_Caixa_Recebimento] (
    [cd_movimento_caixa]       INT          NOT NULL,
    [dt_movimento_caixa]       DATETIME     NULL,
    [cd_veiculo]               INT          NULL,
    [cd_motorista]             INT          NULL,
    [cd_funcionario]           INT          NULL,
    [cd_entregador]            INT          NULL,
    [cd_tipo_documento]        INT          NULL,
    [cd_documento]             VARCHAR (25) NULL,
    [cd_historico_recebimento] INT          NULL,
    [nm_historico_complemento] VARCHAR (60) NULL,
    [vl_movimento_recebimento] FLOAT (53)   NULL,
    [cd_pedido_venda]          INT          NULL,
    [cd_item_pedido_venda]     INT          NULL,
    [cd_nota_saida]            INT          NULL,
    [qt_parcela_nota_saida]    FLOAT (53)   NULL,
    [cd_documento_receber]     INT          NULL,
    [cd_prestacao]             INT          NULL,
    [nm_obs_movimento_caixa]   VARCHAR (40) NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [dt_vencimento_caixa]      DATETIME     NULL,
    [dt_pagamento_caixa]       DATETIME     NULL,
    [cd_tipo_lancamento]       INT          NOT NULL,
    [cd_terminal_caixa]        INT          NULL,
    [cd_operador_caixa]        INT          NULL,
    [cd_tipo_movimento_caixa]  INT          NULL,
    [cd_vendedor]              INT          NULL,
    [cd_condicao_pagamento]    INT          NULL,
    [cd_loja]                  INT          NULL,
    [cd_cliente]               INT          NULL,
    [dt_cancel_movimento]      DATETIME     NULL,
    [nm_cheque_movimento]      VARCHAR (15) NULL,
    CONSTRAINT [PK_Movimento_Caixa_Recebimento] PRIMARY KEY CLUSTERED ([cd_movimento_caixa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Movimento_Caixa_Recebimento_Tipo_Lancamento_Caixa] FOREIGN KEY ([cd_tipo_lancamento]) REFERENCES [dbo].[Tipo_Lancamento_Caixa] ([cd_tipo_lancamento])
);

