CREATE TABLE [dbo].[Nota_Saida_Entrada] (
    [cd_nota_entrada]           INT          NOT NULL,
    [dt_nota_entrada]           DATETIME     NULL,
    [cd_requisicao_compra]      INT          NULL,
    [cd_operacao_fiscal]        CHAR (6)     NULL,
    [nm_fantasia_nota_entrada]  CHAR (15)    NULL,
    [cd_transportadora]         INT          NULL,
    [cd_origem_produto]         INT          NULL,
    [cd_obs_padrao_nf]          INT          NULL,
    [cd_tipo_pagamento_frete]   INT          NULL,
    [ds_obs_compl_nota_entrada] TEXT         NULL,
    [qt_peso_liq_nota_entrada]  FLOAT (53)   NULL,
    [qt_peso_bruto_nota_entrad] FLOAT (53)   NULL,
    [qt_volume_nota_entrada]    FLOAT (53)   NULL,
    [cd_especie_embalagem]      INT          NULL,
    [nm_especie_nota_entrada]   VARCHAR (25) NULL,
    [nm_marca_nota_entrada]     VARCHAR (20) NULL,
    [cd_placa_nota_entrada]     CHAR (8)     NULL,
    [nm_numero_emb_nota_entrad] VARCHAR (10) NULL,
    [ic_emitida_nota_entrada]   CHAR (1)     NULL,
    [nm_mot_cancel_nota_entrad] VARCHAR (50) NULL,
    [dt_cancel_nota_entrada]    DATETIME     NULL,
    [dt_entrada_nota_entrada]   DATETIME     NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [vl_bc_icms]                FLOAT (53)   NULL,
    [vl_icms]                   FLOAT (53)   NULL,
    [vl_bc_subst_icms]          FLOAT (53)   NULL,
    [vl_produto]                FLOAT (53)   NULL,
    [vl_frete]                  FLOAT (53)   NULL,
    [vl_seguro]                 FLOAT (53)   NULL,
    [vl_desp_acess]             FLOAT (53)   NULL,
    [vl_total]                  FLOAT (53)   NULL,
    [vl_icms_subst]             FLOAT (53)   NULL,
    [vl_ipi]                    FLOAT (53)   NULL,
    [cd_vendedor]               INT          NULL,
    [cd_fornecedor]             INT          NULL,
    [cd_cliente]                INT          NULL,
    [cd_itinerario]             INT          NULL,
    [ic_minuta_nota_usuario]    CHAR (1)     NULL,
    [nm_obs_receb_nota_entrada] VARCHAR (40) NULL,
    [nm_receptor_nota_entrada]  VARCHAR (40) NULL,
    [cd_observacao_entrega]     INT          NULL,
    [cd_receptor]               INT          NULL,
    [ic_recebe_nota_entrada]    CHAR (1)     NULL,
    [sg_estado_plana]           CHAR (2)     NULL,
    [cd_pedido_cliente]         VARCHAR (30) NULL,
    [cd_status_nota]            INT          NULL,
    [cd_tipo_calculo]           CHAR (1)     NULL,
    [cd_num_formulario]         INT          NULL,
    [cd_cnpj_cliente]           VARCHAR (18) NULL,
    [cd_insestadual]            VARCHAR (20) NULL,
    [cd_inscmunicipal_cliente]  VARCHAR (18) NULL,
    [cd_cep_recebimento]        CHAR (9)     NULL,
    [nm_endereco_recebimento]   VARCHAR (60) NULL,
    [cd_numero_endereco_rec]    CHAR (10)    NULL,
    [nm_complemento_end_rec]    VARCHAR (30) NULL,
    [nm_bairro_recebimento]     VARCHAR (25) NULL,
    [cd_ddd_cliente]            CHAR (4)     NULL,
    [cd_telefone_cliente]       VARCHAR (15) NULL,
    [cd_fax_cliente]            VARCHAR (15) NULL,
    [nm_pais_cliente]           VARCHAR (30) NULL,
    [sg_estado_recebimento]     CHAR (2)     NULL,
    [nm_cidade_recebimento]     VARCHAR (50) NULL,
    [hr_entrada_nota_entrada]   CHAR (5)     NULL,
    [nm_endereco_cobranca]      VARCHAR (60) NULL,
    [nm_bairro_cobranca]        VARCHAR (25) NULL,
    [cd_cep_cobranca]           CHAR (9)     NULL,
    [nm_cidade_cobranca]        VARCHAR (30) NULL,
    [sg_estado_cobranca]        CHAR (2)     NULL,
    [cd_num_endereco_cob]       CHAR (10)    NULL,
    [nm_complemento_end_cob]    VARCHAR (30) NULL,
    [qt_item_nota_entrada]      INT          NULL,
    [ic_outras_operacoes]       CHAR (1)     NULL,
    [cd_pedido_compra]          INT          NULL,
    [ic_status_nota_entrada]    CHAR (1)     NULL,
    [ds_descricao_servico]      TEXT         NULL,
    [vl_iss]                    FLOAT (53)   NULL,
    [vl_servico]                FLOAT (53)   NULL,
    [ic_minuta_nota_entrada]    CHAR (1)     NULL,
    [dt_recebimento_nota_entra] DATETIME     NULL,
    [cd_entrada_recebimento]    INT          NULL,
    [cd_origem_importacao]      INT          NULL,
    [cd_di]                     VARCHAR (30) NULL
);

