CREATE TABLE [dbo].[Nota_Entrada_Contabil] (
    [cd_nota_entrada]             INT          NOT NULL,
    [cd_fornecedor]               INT          NOT NULL,
    [cd_operacao_fiscal]          INT          NOT NULL,
    [cd_serie_nota_fiscal]        INT          NOT NULL,
    [cd_it_contab_nota_entrada]   INT          NOT NULL,
    [dt_contab_nota_entrada]      DATETIME     NULL,
    [cd_lancamento_padrao]        INT          NULL,
    [cd_conta_debito]             INT          NULL,
    [cd_conta_credito]            INT          NULL,
    [cd_historico_contabil]       INT          NULL,
    [nm_historico_nota_entrada]   VARCHAR (40) NULL,
    [ic_sct_contab_nt_entrada]    CHAR (1)     NULL,
    [dt_sct_contab_nt_entrada]    DATETIME     NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [vl_contab_nota_saida]        FLOAT (53)   NULL,
    [vl_contab_nota_entrada]      FLOAT (53)   NULL,
    [vl_ipi_nota_entrada]         FLOAT (53)   NULL,
    [vl_icms_nota_entrada]        FLOAT (53)   NULL,
    [nm_fantasia_destinatario]    VARCHAR (15) NULL,
    [cd_plano_compra]             INT          NULL,
    [cd_tributacao]               INT          NULL,
    [cd_classificacao_fiscal]     INT          NULL,
    [cd_destinacao_produto]       INT          NULL,
    [ic_manutencao_contabil]      CHAR (1)     NULL,
    [cd_lote_contabil]            INT          NULL,
    [vl_csll_nota_entrada]        FLOAT (53)   NULL,
    [vl_cofins_nota_entrada]      FLOAT (53)   NULL,
    [vl_pis_nota_entrada]         FLOAT (53)   NULL,
    [vl_inss_nota_entrada]        FLOAT (53)   NULL,
    [vl_iss_nota_entrada]         FLOAT (53)   NULL,
    [vl_irrf_nota_entrada]        FLOAT (53)   NULL,
    [vl_ipi_reducao_nota_entrada] FLOAT (53)   NULL
);

