CREATE TABLE [dbo].[Nota_Saida] (
    [cd_nota_saida]               INT          NOT NULL,
    [cd_num_formulario_nota]      INT          NULL,
    [dt_nota_saida]               DATETIME     NULL,
    [cd_requisicao_faturamento]   INT          NULL,
    [cd_operacao_fiscal]          INT          NULL,
    [nm_fantasia_nota_saida]      CHAR (15)    NULL,
    [cd_transportadora]           INT          NULL,
    [cd_destinacao_produto]       INT          NULL,
    [cd_obs_padrao_nf]            INT          NULL,
    [cd_tipo_pagamento_frete]     INT          NULL,
    [ds_obs_compl_nota_saida]     TEXT         NULL,
    [qt_peso_liq_nota_saida]      FLOAT (53)   NULL,
    [qt_peso_bruto_nota_saida]    FLOAT (53)   NULL,
    [qt_volume_nota_saida]        FLOAT (53)   NULL,
    [cd_especie_embalagem]        INT          NULL,
    [nm_especie_nota_saida]       VARCHAR (25) NULL,
    [nm_marca_nota_saida]         VARCHAR (20) NULL,
    [cd_placa_nota_saida]         VARCHAR (8)  NULL,
    [nm_numero_emb_nota_saida]    VARCHAR (10) NULL,
    [ic_emitida_nota_saida]       CHAR (1)     NULL,
    [nm_mot_cancel_nota_saida]    VARCHAR (50) NULL,
    [dt_cancel_nota_saida]        DATETIME     NULL,
    [dt_saida_nota_saida]         DATETIME     NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [vl_bc_icms]                  FLOAT (53)   NULL,
    [vl_icms]                     FLOAT (53)   NULL,
    [vl_bc_subst_icms]            FLOAT (53)   NULL,
    [vl_produto]                  FLOAT (53)   NULL,
    [vl_frete]                    FLOAT (53)   NULL,
    [vl_seguro]                   FLOAT (53)   NULL,
    [vl_desp_acess]               FLOAT (53)   NULL,
    [vl_total]                    FLOAT (53)   NULL,
    [vl_icms_subst]               FLOAT (53)   NULL,
    [vl_ipi]                      FLOAT (53)   NULL,
    [cd_vendedor]                 INT          NULL,
    [cd_fornecedor]               INT          NULL,
    [cd_cliente]                  INT          NULL,
    [cd_itinerario]               INT          NULL,
    [nm_obs_entrega_nota_saida]   VARCHAR (40) NULL,
    [nm_entregador_nota_saida]    VARCHAR (40) NULL,
    [cd_observacao_entrega]       INT          NULL,
    [cd_entregador]               INT          NULL,
    [ic_entrega_nota_saida]       CHAR (1)     NULL,
    [sg_estado_placa]             CHAR (2)     NULL,
    [cd_pedido_cliente]           VARCHAR (30) NULL,
    [cd_status_nota]              INT          NULL,
    [cd_tipo_calculo]             CHAR (1)     NULL,
    [cd_num_formulario]           INT          NULL,
    [cd_cnpj_nota_saida]          VARCHAR (20) NULL,
    [cd_inscest_nota_saida]       VARCHAR (20) NULL,
    [cd_inscmunicipal_nota]       VARCHAR (18) NULL,
    [cd_cep_entrega]              CHAR (9)     NULL,
    [nm_endereco_entrega]         VARCHAR (60) NULL,
    [cd_numero_endereco_ent]      CHAR (10)    NULL,
    [nm_complemento_end_ent]      VARCHAR (30) NULL,
    [nm_bairro_entrega]           VARCHAR (25) NULL,
    [cd_ddd_nota_saida]           CHAR (4)     NULL,
    [cd_telefone_nota_saida]      VARCHAR (15) NULL,
    [cd_fax_nota_saida]           VARCHAR (15) NULL,
    [nm_pais_nota_saida]          VARCHAR (30) NULL,
    [sg_estado_entrega]           CHAR (2)     NULL,
    [nm_cidade_entrega]           VARCHAR (50) NULL,
    [hr_saida_nota_saida]         CHAR (5)     NULL,
    [nm_endereco_cobranca]        VARCHAR (60) NULL,
    [nm_bairro_cobranca]          VARCHAR (25) NULL,
    [cd_cep_cobranca]             CHAR (9)     NULL,
    [nm_cidade_cobranca]          VARCHAR (30) NULL,
    [sg_estado_cobranca]          CHAR (2)     NULL,
    [cd_numero_endereco_cob]      CHAR (10)    NULL,
    [nm_complemento_end_cob]      VARCHAR (30) NULL,
    [qt_item_nota_saida]          INT          NULL,
    [ic_outras_operacoes]         CHAR (1)     NULL,
    [cd_pedido_venda]             INT          NULL,
    [ic_status_nota_saida]        CHAR (1)     NULL,
    [ds_descricao_servico]        TEXT         NULL,
    [vl_iss]                      FLOAT (53)   NULL,
    [vl_servico]                  FLOAT (53)   NULL,
    [ic_minuta_nota_saida]        CHAR (1)     NULL,
    [dt_entrega_nota_saida]       DATETIME     NULL,
    [sg_estado_nota_saida]        CHAR (2)     NULL,
    [nm_cidade_nota_saida]        VARCHAR (50) NULL,
    [nm_bairro_nota_saida]        VARCHAR (25) NULL,
    [nm_endereco_nota_saida]      VARCHAR (60) NULL,
    [cd_numero_end_nota_saida]    CHAR (10)    NULL,
    [cd_cep_nota_saida]           CHAR (9)     NULL,
    [nm_razao_social_nota]        VARCHAR (60) NULL,
    [nm_razao_social_c]           VARCHAR (40) NULL,
    [cd_mascara_operacao]         CHAR (6)     NULL,
    [nm_operacao_fiscal]          VARCHAR (35) NULL,
    [cd_tipo_destinatario]        INT          NULL,
    [cd_contrato_servico]         INT          NULL,
    [cd_condicao_pagamento]       INT          NULL,
    [vl_irrf_nota_saida]          FLOAT (53)   NULL,
    [pc_irrf_serv_empresa]        FLOAT (53)   NULL,
    [nm_fantasia_destinatario]    VARCHAR (30) NULL,
    [nm_compl_endereco_nota]      VARCHAR (10) NULL,
    [ic_sedex_nota_saida]         CHAR (1)     NULL,
    [ic_coleta_nota_saida]        CHAR (1)     NULL,
    [dt_coleta_nota_saida]        DATETIME     NULL,
    [nm_coleta_nota_saida]        VARCHAR (30) NULL,
    [cd_tipo_local_entrega]       INT          NULL,
    [ic_dev_nota_saida]           CHAR (1)     NULL,
    [cd_nota_dev_nota_saida]      INT          NULL,
    [dt_nota_dev_nota_saida]      DATETIME     NULL,
    [nm_razao_social_cliente]     VARCHAR (60) NULL,
    [nm_razao_socila_cliente_c]   VARCHAR (40) NULL,
    [cd_tipo_operacao_fiscal]     INT          NULL,
    [vl_bc_ipi]                   FLOAT (53)   NULL,
    [cd_mascara_operacao3]        CHAR (6)     NULL,
    [cd_mascara_operacao2]        CHAR (6)     NULL,
    [cd_operacao_fiscal3]         INT          NULL,
    [cd_operacao_fiscal2]         INT          NULL,
    [nm_operacao_fiscal2]         VARCHAR (35) NULL,
    [nm_operacao_fiscal3]         VARCHAR (35) NULL,
    [cd_tipo_operacao_fiscal2]    INT          NULL,
    [cd_tipo_operacao_fiscal3]    INT          NULL,
    [cd_tipo_operacao3]           INT          NULL,
    [cd_tipo_operacao2]           INT          NULL,
    [ic_zona_franca]              VARCHAR (1)  NULL,
    [cd_nota_fiscal_origem]       INT          NULL,
    [ic_forma_nota_saida]         CHAR (1)     NULL,
    [cd_serie_nota]               INT          NULL,
    [cd_vendedor_externo]         INT          NULL,
    [nm_local_entrega_nota]       VARCHAR (40) NULL,
    [cd_cnpj_entrega_nota]        VARCHAR (40) NULL,
    [cd_inscest_entrega_nota]     VARCHAR (40) NULL,
    [vl_base_icms_reduzida]       FLOAT (53)   NULL,
    [vl_bc_icms_reduzida]         FLOAT (53)   NULL,
    [cd_dde_nota_saida]           VARCHAR (14) NULL,
    [dt_dde_nota_saida]           DATETIME     NULL,
    [nm_fat_com_nota_saida]       VARCHAR (14) NULL,
    [vl_icms_isento]              FLOAT (53)   NULL,
    [vl_icms_outros]              FLOAT (53)   NULL,
    [vl_icms_obs]                 FLOAT (53)   NULL,
    [vl_ipi_isento]               FLOAT (53)   NULL,
    [vl_ipi_outros]               FLOAT (53)   NULL,
    [vl_ipi_obs]                  FLOAT (53)   NULL,
    [ic_mp66_item_nota_saida]     CHAR (1)     NULL,
    [ic_fiscal_nota_saida]        CHAR (1)     NULL,
    [cd_pais]                     INT          NULL,
    [cd_moeda]                    INT          NULL,
    [dt_cambio_nota_saida]        DATETIME     NULL,
    [vl_cambio_nota_saida]        FLOAT (53)   NULL,
    [qt_desconto_nota_saida]      FLOAT (53)   NULL,
    [vl_desconto_nota_saida]      FLOAT (53)   NULL,
    [qt_peso_real_nota_saida]     FLOAT (53)   NULL,
    [ds_obs_usuario_nota_saida]   TEXT         NULL,
    [ic_obs_usuario_nota_saida]   CHAR (1)     NULL,
    [cd_requisicao_fat_ant]       INT          NULL,
    [qt_ord_entrega_nota_saida]   INT          NULL,
    [ic_credito_icms_nota]        CHAR (1)     NULL,
    [ic_locacao_cilindro_nota]    CHAR (1)     NULL,
    [ic_smo_nota_saida]           CHAR (1)     NULL,
    [cd_di]                       INT          NULL,
    [cd_guia_trafego_nota_said]   INT          NULL,
    [dt_lancamento_entrega]       DATETIME     NULL,
    [vl_iss_retido]               FLOAT (53)   NULL,
    [vl_cofins]                   FLOAT (53)   NULL,
    [vl_pis]                      FLOAT (53)   NULL,
    [vl_csll]                     FLOAT (53)   NULL,
    [nm_mot_ativacao_nota_saida]  VARCHAR (50) NULL,
    [vl_desp_aduaneira]           FLOAT (53)   NULL,
    [ic_di_carregada]             CHAR (1)     NULL,
    [vl_ii]                       FLOAT (53)   NULL,
    [pc_ii]                       FLOAT (53)   NULL,
    [ic_cupom_fiscal]             CHAR (1)     NULL,
    [cd_cupom_fiscal]             INT          NULL,
    [cd_loja]                     INT          NULL,
    [vl_simbolico]                FLOAT (53)   NULL,
    [cd_identificacao_nota_saida] INT          NULL,
    [cd_coleta_nota_saida]        VARCHAR (25) NULL,
    [qt_ord_entregador_saida]     INT          NULL,
    [vl_inss_nota_saida]          FLOAT (53)   NULL,
    [pc_inss_servico]             FLOAT (53)   NULL,
    [cd_serie_nota_fiscal]        INT          NULL,
    [vl_icms_desconto]            FLOAT (53)   NULL,
    [ic_etiqueta_nota_saida]      CHAR (1)     NULL,
    [ic_imposto_nota_saida]       CHAR (1)     NULL,
    [qt_cubagem_nota_saida]       FLOAT (53)   NULL,
    [ic_peso_recalcular]          CHAR (1)     NULL,
    [qt_formulario_nota_saida]    INT          NULL,
    [ic_reprocessar_dados_adic]   CHAR (1)     NULL,
    [vl_mp_aplicada_nota]         FLOAT (53)   NULL,
    [vl_mo_aplicada_nota]         FLOAT (53)   NULL,
    [ic_reprocessar_parcela]      CHAR (1)     NULL,
    [ic_sel_nota_saida]           CHAR (1)     NULL,
    [cd_ordem_carga]              INT          NULL,
    [cd_veiculo]                  INT          NULL,
    [cd_motorista]                INT          NULL,
    [cd_forma_pagamento]          INT          NULL,
    [ic_nfe_nota_saida]           CHAR (1)     NULL,
    [cd_motivo_dev_nota]          INT          NULL,
    [ic_nfp_nota_saida]           CHAR (1)     NULL,
    [dt_entrada_nota_saida]       DATETIME     NULL,
    [qt_serie_nota_fiscal]        INT          NULL,
    [cd_modelo_serie_nota]        CHAR (2)     NULL,
    [cd_finalidade_nfe]           INT          NULL,
    [cd_forma_emissao_nfe]        INT          NULL,
    [vl_pis_retencao]             FLOAT (53)   NULL,
    [vl_cofins_retencao]          FLOAT (53)   NULL,
    [hr_nota_saida]               VARCHAR (8)  NULL,
    CONSTRAINT [PK_Nota_Saida] PRIMARY KEY CLUSTERED ([cd_nota_saida] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [ix_dt_nota_saida]
    ON [dbo].[Nota_Saida]([dt_nota_saida] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [ix_cd_operacaco_fiscal]
    ON [dbo].[Nota_Saida]([cd_operacao_fiscal] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [ix_cd_status_nota]
    ON [dbo].[Nota_Saida]([cd_status_nota] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_Nota_Saida_Item]
    ON [dbo].[Nota_Saida]([cd_nota_saida] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_Identificacao_Nota_Saida]
    ON [dbo].[Nota_Saida]([cd_identificacao_nota_saida] ASC);

