CREATE TABLE [dbo].[Nota_Saida_Entrada_Item] (
    [cd_nota_entrada]            INT          NOT NULL,
    [cd_item_nota_entrada]       INT          NOT NULL,
    [nm_fantasia_produto]        VARCHAR (30) NULL,
    [ds_item_nota_entrada]       TEXT         NULL,
    [cd_pedido_compra]           INT          NULL,
    [cd_item_pedido_compra]      INT          NULL,
    [cd_posicao_item_nota]       VARCHAR (15) NULL,
    [cd_os_item_nota_entrada]    VARCHAR (15) NULL,
    [vl_unitario_item_nota]      FLOAT (53)   NULL,
    [dt_restricao_item_nota]     DATETIME     NULL,
    [ic_status_item_nota_entra]  CHAR (1)     NULL,
    [nm_motivo_restricao_item]   TEXT         NULL,
    [qt_devolucao_item_nota]     FLOAT (53)   NULL,
    [cd_requisicao_compra]       INT          NULL,
    [cd_item_rquisicao]          INT          NULL,
    [cd_produto]                 INT          NULL,
    [cd_procedencia_roduto]      INT          NULL,
    [cd_tributacao]              INT          NULL,
    [cd_grupo_categoria]         INT          NULL,
    [vl_total_item]              FLOAT (53)   NULL,
    [cd_unidade_medida]          CHAR (2)     NULL,
    [pc_icms]                    FLOAT (53)   NULL,
    [pc_ipi]                     FLOAT (53)   NULL,
    [vl_ipi]                     FLOAT (53)   NULL,
    [cd_usuario]                 INT          NULL,
    [dt_usuario]                 DATETIME     NULL,
    [qt_item_nota_entrada]       FLOAT (53)   NULL,
    [qt_liquido_item_nota]       FLOAT (53)   NULL,
    [qt_bruto_item_nota]         FLOAT (53)   NULL,
    [cd_item_pedido_venda]       INT          NULL,
    [cd_pedido_venda]            INT          NULL,
    [cd_grupo_produto]           INT          NULL,
    [cd_categoria_produto]       INT          NULL,
    [cd_classificacao_fiscal]    INT          NULL,
    [cd_situacao_tributaria]     CHAR (10)    NULL,
    [vl_frete_item]              FLOAT (53)   NULL,
    [vl_seguro_item]             FLOAT (53)   NULL,
    [vl_desp_acess_item]         FLOAT (53)   NULL,
    [pc_icms_desc_item]          FLOAT (53)   NULL,
    [dt_cancel_item_nota_entra]  DATETIME     NULL,
    [dt_nota_entrada]            DATETIME     NULL,
    [pc_desconto_item]           FLOAT (53)   NULL,
    [cd_tipo_calculo]            CHAR (1)     NULL,
    [vl_imposto_importacao]      FLOAT (53)   NULL,
    [pc_conversao_fob]           FLOAT (53)   NULL,
    [vl_fob_item]                FLOAT (53)   NULL,
    [cd_pd_compra_item_nota]     INT          NULL,
    [cd_pedido_compra_item_nota] VARCHAR (30) NULL
);

