CREATE TABLE [dbo].[Nota_Saida_Item_Registro] (
    [cd_nota_saida]             INT          NOT NULL,
    [cd_item_nota_saida]        INT          NOT NULL,
    [cd_item_registro_nota]     INT          NOT NULL,
    [cd_num_formulario_nota]    INT          NULL,
    [pc_ipi_item_nota_saida]    FLOAT (53)   NULL,
    [vl_base_ipi_item_nota]     FLOAT (53)   NULL,
    [vl_ipi_item_nota_saida]    FLOAT (53)   NULL,
    [vl_ipi_isento_item_nota]   FLOAT (53)   NULL,
    [vl_ipi_outras_item_nota]   FLOAT (53)   NULL,
    [vl_ipi_obs_item_nota]      FLOAT (53)   NULL,
    [pc_icms_item_nota_saida]   FLOAT (53)   NULL,
    [vl_base_icms_item_nota]    FLOAT (53)   NULL,
    [vl_icms_item_nota_saida]   FLOAT (53)   NULL,
    [vl_icms_isento_item_nota]  FLOAT (53)   NULL,
    [vl_icms_outras_item_nota]  FLOAT (53)   NULL,
    [vl_icms_obs_item_nota]     FLOAT (53)   NULL,
    [vl_contabil_item_nota]     FLOAT (53)   NULL,
    [vl_frete_item_nota_saida]  FLOAT (53)   NULL,
    [vl_seguro_item_nota_saida] FLOAT (53)   NULL,
    [vl_desp_acess_item_nota]   FLOAT (53)   NULL,
    [pc_icms_desconto_item]     FLOAT (53)   NULL,
    [cd_dispositivo_legal_icms] INT          NULL,
    [cd_dipositivo_legal_ipi]   INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_operacao_fiscal]        INT          NULL,
    [cd_conta]                  INT          NULL,
    [cd_dispositivo_legal_ipi]  INT          NULL,
    [cd_serie_nota]             INT          NULL,
    [cd_mascara_operacao]       CHAR (6)     NULL,
    [cd_mascara_conta]          VARCHAR (20) NULL,
    [sg_estado]                 CHAR (2)     NULL,
    [dt_nota_saida]             DATETIME     NULL,
    [ic_cancelada_item_nota]    CHAR (1)     NULL,
    [ic_servico_item_nota]      CHAR (1)     NULL,
    [ic_contribuinte_icms_nota] CHAR (1)     NULL,
    [ic_resumo_saida]           CHAR (1)     NULL,
    [cd_tributacao]             INT          NULL,
    [cd_destinacao_produto]     INT          NULL,
    [vl_icms_subs_item_nota]    FLOAT (53)   NULL,
    [vl_base_icms_subs_item]    FLOAT (53)   NULL,
    [vl_produto_item_nota]      FLOAT (53)   NULL,
    CONSTRAINT [PK_Nota_Saida_Item_Registro] PRIMARY KEY CLUSTERED ([cd_nota_saida] ASC, [cd_item_nota_saida] ASC, [cd_item_registro_nota] ASC) WITH (FILLFACTOR = 90)
);

