CREATE TABLE [dbo].[Nota_Entrada] (
    [cd_fornecedor]               INT          NOT NULL,
    [cd_nota_entrada]             INT          NOT NULL,
    [cd_serie_nota_fiscal]        INT          NOT NULL,
    [cd_operacao_fiscal]          INT          NOT NULL,
    [dt_receb_nota_entrada]       DATETIME     NULL,
    [dt_nota_entrada]             DATETIME     NULL,
    [nm_serie_nota_entrada]       VARCHAR (5)  NULL,
    [cd_tributacao]               INT          NULL,
    [cd_tipo_destinatario]        INT          NULL,
    [cd_condicao_pagamento]       INT          NULL,
    [ic_carta_cor_nota_entrada]   CHAR (1)     NULL,
    [vl_total_nota_entrada]       FLOAT (53)   NULL,
    [vl_prod_nota_entrada]        FLOAT (53)   NULL,
    [vl_bicms_nota_entrada]       FLOAT (53)   NULL,
    [vl_bipi_nota_entrada]        FLOAT (53)   NULL,
    [vl_icms_nota_entrada]        FLOAT (53)   NULL,
    [vl_ipi_nota_entrada]         FLOAT (53)   NULL,
    [vl_frete_nota_entrada]       FLOAT (53)   NULL,
    [vl_seguro_nota_entrada]      FLOAT (53)   NULL,
    [vl_despac_nota_entrada]      FLOAT (53)   NULL,
    [vl_bsticm_nota_entrada]      FLOAT (53)   NULL,
    [vl_sticm_nota_entrada]       FLOAT (53)   NULL,
    [vl_servico_nota_entrada]     FLOAT (53)   NULL,
    [vl_iss_nota_entrada]         FLOAT (53)   NULL,
    [vl_irrf_nota_entrada]        FLOAT (53)   NULL,
    [vl_inss_nota_entrada]        FLOAT (53)   NULL,
    [vl_biss_nota_entrada]        FLOAT (53)   NULL,
    [pc_iss_nota_entrada]         FLOAT (53)   NULL,
    [ic_conf_nota_entrada]        CHAR (1)     NULL,
    [dt_atual_nota_entrada]       DATETIME     NULL,
    [ic_sco]                      CHAR (1)     NULL,
    [ic_slf]                      CHAR (1)     NULL,
    [ic_sce]                      CHAR (1)     NULL,
    [ic_scu]                      CHAR (1)     NULL,
    [ic_scp]                      CHAR (1)     NULL,
    [ic_pcp]                      CHAR (1)     NULL,
    [ic_sep]                      CHAR (1)     NULL,
    [ic_simp]                     CHAR (1)     NULL,
    [ic_sct]                      CHAR (1)     NULL,
    [ic_diverg_nota_entrega]      CHAR (1)     NULL,
    [nm_obslivro_nota_entrada]    VARCHAR (15) NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [pc_inss_nota_entrada]        FLOAT (53)   NULL,
    [ic_fiscal_nota_entrada]      CHAR (1)     NULL,
    [nm_fantasia_destinatario]    VARCHAR (30) NULL,
    [nm_razao_social]             VARCHAR (50) NULL,
    [ic_emitida_nota_entrada]     CHAR (1)     NULL,
    [cd_operacao_origem]          INT          NULL,
    [cd_nota_saida]               INT          NULL,
    [cd_estado]                   INT          NULL,
    [sg_estado]                   CHAR (2)     NULL,
    [ds_obs_compl_nota_entrada]   TEXT         NULL,
    [qt_bruto_nota_entrada]       FLOAT (53)   NULL,
    [qt_liquido_nota_entrada]     FLOAT (53)   NULL,
    [qt_volume_nota_entrada]      FLOAT (53)   NULL,
    [nm_especie_nota_entrada]     VARCHAR (25) NULL,
    [nm_marca_nota_entrada]       VARCHAR (20) NULL,
    [nm_num_emb_nota_entrada]     VARCHAR (10) NULL,
    [cd_transportadora]           INT          NULL,
    [cd_tipo_pagamento_frete]     INT          NULL,
    [cd_placa_nota_saida]         VARCHAR (8)  NULL,
    [sg_estado_placa]             CHAR (2)     NULL,
    [cd_destinacao_produto]       INT          NULL,
    [cd_rem]                      INT          NULL,
    [dt_rem]                      DATETIME     NULL,
    [vl_bcinss_nota_entrada]      FLOAT (53)   NULL,
    [cd_guia_trafego_nota_ent]    INT          NULL,
    [vl_csll_nota_entrada]        FLOAT (53)   NULL,
    [vl_pis_nota_entrada]         FLOAT (53)   NULL,
    [vl_cofins_nota_entrada]      FLOAT (53)   NULL,
    [ic_reter_iss]                CHAR (1)     NULL,
    [ic_scp_retencao]             CHAR (1)     NULL,
    [ic_manutencao_fiscal]        CHAR (1)     NULL,
    [ic_manutencao_contabil]      CHAR (1)     NULL,
    [ic_lista_livro_saida]        CHAR (1)     NULL,
    [cd_loja]                     INT          NULL,
    [cd_moeda]                    INT          NULL,
    [dt_cambio_nota_entrada]      DATETIME     NULL,
    [vl_cambio_nota_entrada]      FLOAT (53)   NULL,
    [ic_provisao_nota_entrada]    CHAR (1)     NULL,
    [vl_icms_ciap_nota_entrada]   FLOAT (53)   NULL,
    [cd_ciap]                     INT          NULL,
    [pc_csll_nota_entrada]        FLOAT (53)   NULL,
    [pc_pis_nota_entrada]         FLOAT (53)   NULL,
    [pc_irrf_nota_entrada]        FLOAT (53)   NULL,
    [pc_cofins_nota_entrada]      FLOAT (53)   NULL,
    [cd_usuario_inclusao]         INT          NULL,
    [cd_tipo_destinatario_fatura] INT          NULL,
    [cd_destinatario_faturamento] INT          NULL,
    [cd_centro_custo]             INT          NULL,
    [cd_plano_financeiro]         INT          NULL,
    [cd_status_nota]              INT          NULL,
    [dt_cancelamento_nota]        DATETIME     NULL,
    [vl_desconto_nota_entrada]    FLOAT (53)   NULL,
    [vl_base_retencao_nota]       FLOAT (53)   NULL,
    [ic_nfe_nota_entrada]         CHAR (1)     NULL,
    [ic_xml_nota_entrada]         CHAR (1)     NULL,
    CONSTRAINT [PK_Nota_Entrada] PRIMARY KEY CLUSTERED ([cd_fornecedor] ASC, [cd_nota_entrada] ASC, [cd_serie_nota_fiscal] ASC, [cd_operacao_fiscal] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [ix_dt_receb_nota_entrada]
    ON [dbo].[Nota_Entrada]([dt_receb_nota_entrada] ASC) WITH (FILLFACTOR = 90);

