CREATE TABLE [dbo].[Nota_Entrada_Item] (
    [cd_fornecedor]              INT          NOT NULL,
    [cd_nota_entrada]            INT          NOT NULL,
    [cd_operacao_fiscal]         INT          NOT NULL,
    [cd_serie_nota_fiscal]       INT          NOT NULL,
    [cd_item_nota_entrada]       INT          NOT NULL,
    [cd_classificacao_fiscal]    INT          NULL,
    [cd_produto]                 INT          NULL,
    [nm_produto_nota_entrada]    VARCHAR (50) NULL,
    [cd_unidade_medida]          INT          NULL,
    [cd_pedido_compra]           INT          NULL,
    [cd_item_pedido_compra]      INT          NULL,
    [cd_procedencia_produto]     INT          NULL,
    [cd_tributacao]              INT          NULL,
    [qt_item_nota_entrada]       FLOAT (53)   NULL,
    [vl_item_nota_entrada]       FLOAT (53)   NULL,
    [pc_desc_nota_entrada]       FLOAT (53)   NULL,
    [qt_pesliq_nota_entrada]     FLOAT (53)   NULL,
    [qt_pesbru_nota_entrada]     FLOAT (53)   NULL,
    [pc_icms_nota_entrada]       FLOAT (53)   NULL,
    [vl_bicms_nota_entrada]      FLOAT (53)   NULL,
    [vl_icms_nota_entrada]       FLOAT (53)   NULL,
    [vl_icmsisen_nota_entrada]   FLOAT (53)   NULL,
    [vl_icmout_nota_entrada]     FLOAT (53)   NULL,
    [vl_icmobs_nota_entrada]     FLOAT (53)   NULL,
    [pc_ipi_nota_entrada]        FLOAT (53)   NULL,
    [vl_bipi_nota_entrada]       FLOAT (53)   NULL,
    [vl_ipi_nota_entrada]        FLOAT (53)   NULL,
    [vl_ipiisen_nota_entrada]    FLOAT (53)   NULL,
    [vl_ipiout_nota_entrada]     FLOAT (53)   NULL,
    [vl_ipiobs_nota_entrada]     FLOAT (53)   NULL,
    [vl_custo_nota_entrada]      FLOAT (53)   NULL,
    [vl_contabil_nota_entrada]   FLOAT (53)   NULL,
    [cd_plano_compra]            INT          NULL,
    [ic_peps_nota_entrada]       CHAR (1)     NULL,
    [dt_item_receb_nota_entrad]  DATETIME     NULL,
    [cd_situacao_tributaria]     CHAR (3)     NULL,
    [ic_basered_nota_entrada]    CHAR (1)     NULL,
    [cd_dispositivo_legal_ipi]   INT          NULL,
    [cd_dispositivo_legal_icm]   INT          NULL,
    [cd_contabilizacao]          INT          NULL,
    [cd_usuario]                 INT          NULL,
    [dt_usuario]                 DATETIME     NULL,
    [ic_tipo_nota_entrada_item]  CHAR (1)     NULL,
    [vl_total_nota_entr_item]    FLOAT (53)   NULL,
    [cd_conta]                   INT          NULL,
    [ic_item_inspecao_nota]      CHAR (1)     NULL,
    [cd_servico]                 INT          NULL,
    [ds_servico]                 TEXT         NULL,
    [vl_irrf_servico]            FLOAT (53)   NULL,
    [pc_irrf_servico]            FLOAT (53)   NULL,
    [vl_iss_servico]             FLOAT (53)   NULL,
    [pc_iss_servico]             FLOAT (53)   NULL,
    [cd_item_requisicao_compra]  INT          NULL,
    [cd_requisicao_compra]       INT          NULL,
    [cd_mascara_classificacao]   CHAR (10)    NULL,
    [pc_icms_red_nota_entrada]   FLOAT (53)   NULL,
    [ic_estocado_nota_entrada]   CHAR (1)     NULL,
    [ic_consig_nota_entrada]     CHAR (1)     NULL,
    [cd_lote_produto]            INT          NULL,
    [cd_lote_item_nota_entrada]  VARCHAR (20) NULL,
    [cd_num_serie_item_nota_ent] VARCHAR (30) NULL,
    [qt_destino_movimento]       FLOAT (53)   NULL,
    [qt_fator_produto_unidade]   FLOAT (53)   NULL,
    [cd_unidade_destino]         INT          NULL,
    [vl_custo_conversao]         FLOAT (53)   NULL,
    [vl_custo_net_nota_entrada]  FLOAT (53)   NULL,
    [vl_confis_item_nota]        FLOAT (53)   NULL,
    [vl_pis_item_nota]           FLOAT (53)   NULL,
    [pc_confis_item_nota]        FLOAT (53)   NULL,
    [pc_pis_item_nota]           FLOAT (53)   NULL,
    [dt_item_inspecao_nota]      DATETIME     NULL,
    [cd_usuario_inspecao]        INT          NULL,
    [ic_inventario]              CHAR (1)     NULL,
    [cd_bem]                     INT          NULL,
    [vl_icms_ciap_nota_entrada]  FLOAT (53)   NULL,
    [vl_ipi_apura_nota_entrada]  FLOAT (53)   NULL,
    [qt_mes_apura_nota_entrada]  FLOAT (53)   NULL,
    [vl_cofins_item_nota]        FLOAT (53)   NULL,
    [pc_cofins_item_nota]        FLOAT (53)   NULL,
    [cd_veiculo]                 INT          NULL,
    [cd_nota_saida]              INT          NULL,
    [cd_item_nota_saida]         INT          NULL,
    [vl_custo_produto]           FLOAT (53)   NULL,
    [cd_rnc]                     INT          NULL,
    [cd_centro_custo]            INT          NULL,
    [qt_area_produto]            FLOAT (53)   NULL,
    [cd_fase_produto]            INT          NULL,
    [ic_controle_saldo]          CHAR (1)     NULL,
    [cd_item_operacao_fiscal]    INT          NULL,
    [cd_laudo]                   INT          NULL,
    [vl_unitario_ipi_produto]    FLOAT (53)   NULL,
    [vl_frete_item_nota]         FLOAT (53)   NULL,
    [ic_item_bonificacao]        CHAR (1)     NULL,
    [cd_pedido_venda]            INT          NULL,
    [cd_item_pedido_venda]       INT          NULL,
    [vl_bc_subst_icms_item]      FLOAT (53)   NULL,
    [vl_icms_subst_icms_item]    FLOAT (53)   NULL,
    CONSTRAINT [PK_Nota_Entrada_Item] PRIMARY KEY CLUSTERED ([cd_fornecedor] ASC, [cd_nota_entrada] ASC, [cd_serie_nota_fiscal] ASC, [cd_operacao_fiscal] ASC, [cd_item_nota_entrada] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [IX_Nota_Entrada_Item_dt_receb]
    ON [dbo].[Nota_Entrada_Item]([dt_item_receb_nota_entrad] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_Nota_Entrada_Item_Pedido]
    ON [dbo].[Nota_Entrada_Item]([cd_pedido_compra] ASC, [cd_item_pedido_compra] ASC) WITH (FILLFACTOR = 90);

