CREATE TABLE [dbo].[Nota_Saida_Credito] (
    [cd_nota_saida]             INT          NOT NULL,
    [cd_num_formulario_nota]    INT          NULL,
    [cd_item_cred_nota_saida]   INT          NOT NULL,
    [dt_nota_saida_credito]     DATETIME     NULL,
    [vl_nota_saida_credito]     FLOAT (53)   NULL,
    [ic_nota_credito]           CHAR (1)     NULL,
    [nm_obs_nota_saida_cred]    VARCHAR (40) NULL,
    [cd_cliente]                INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [nm_obs_nota_saida_credito] VARCHAR (40) NULL,
    [vl_limite_credito_cliente] FLOAT (53)   NULL,
    [ic_cobranca_eletronica]    CHAR (1)     NULL,
    [ic_informacao_credito]     CHAR (1)     NULL,
    [qt_dia_atraso_cliente]     INT          NULL,
    [qt_media_atraso_cliente]   INT          NULL,
    [qt_pagamento_atraso]       INT          NULL,
    [vl_maior_fatura_cliente]   FLOAT (53)   NULL,
    [dt_maior_fatura_cliente]   DATETIME     NULL,
    [vl_ultimo_faturamento]     FLOAT (53)   NULL,
    [dt_ultimo_faturamento]     DATETIME     NULL,
    [qt_titulo_aberto_cliente]  INT          NULL,
    [qt_titulo_protesto]        INT          NULL,
    [qt_titulo_cartorio]        INT          NULL,
    [ds_observacao_credito]     TEXT         NULL,
    [ic_credito_suspenso]       CHAR (1)     NULL,
    [dt_suspensao_credito]      DATETIME     NULL,
    [qt_titulo_pago]            INT          NULL,
    [qt_maior_atraso]           INT          NULL,
    [dt_ultimo_pagamento_atras] DATETIME     NULL,
    [vl_total_faturamento]      FLOAT (53)   NULL,
    [vl_saldo_atual_aberto]     FLOAT (53)   NULL,
    [nm_credito_suspenso]       VARCHAR (30) NULL,
    [qt_total_documentos]       INT          NULL,
    [cd_usuario_cred_susp]      INT          NULL,
    [vl_maior_acumulo]          FLOAT (53)   NULL,
    [dt_maior_acumulo]          DATETIME     NULL,
    [qt_nota_debito]            INT          NULL,
    [vl_nota_debito]            FLOAT (53)   NULL,
    [vl_total_credito_pendente] FLOAT (53)   NULL
);

