CREATE TABLE [dbo].[Nota_Debito_Despesa] (
    [cd_nota_debito_despesa]    INT          NOT NULL,
    [dt_nota_debito_despesa]    DATETIME     NULL,
    [dt_inicio_ref_nota_debito] DATETIME     NULL,
    [dt_final_ref_nota_debito]  DATETIME     NULL,
    [cd_cliente]                INT          NULL,
    [nm_ref_nota_debito]        VARCHAR (60) NULL,
    [nm_obs_ref_nota_debito]    VARCHAR (40) NULL,
    [vl_nota_debito]            FLOAT (53)   NULL,
    [ds_nota_debito]            TEXT         NULL,
    [cd_conta_banco]            INT          NULL,
    [dt_baixa_nota_debito]      DATETIME     NULL,
    [dt_pagto_nota_debito]      DATETIME     NULL,
    [ic_emitida_nota_debito]    CHAR (1)     NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_projeto]                INT          NULL,
    [cd_pedido_venda]           INT          NULL,
    [cd_contato]                INT          NULL,
    [ic_scr_gerado]             CHAR (1)     NULL,
    [dt_vencimento_nota_debito] DATETIME     NULL,
    [cd_centro_custo]           INT          NULL,
    [cd_analista]               INT          NULL,
    [cd_identificacao_cliente]  VARCHAR (15) NULL,
    CONSTRAINT [PK_NOTA_DEBITO_DESPESA] PRIMARY KEY CLUSTERED ([cd_nota_debito_despesa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK__Conta_Agencia_Banco] FOREIGN KEY ([cd_conta_banco]) REFERENCES [dbo].[Conta_Agencia_Banco] ([cd_conta_banco]),
    CONSTRAINT [FK__Pedido_Venda] FOREIGN KEY ([cd_pedido_venda]) REFERENCES [dbo].[Pedido_Venda] ([cd_pedido_venda]),
    CONSTRAINT [FK__Projeto] FOREIGN KEY ([cd_projeto]) REFERENCES [dbo].[Projeto] ([cd_projeto])
);

