CREATE TABLE [dbo].[Nota_Saida_Registro] (
    [cd_nota_saida]             INT          NOT NULL,
    [cd_num_formulario_nota]    INT          NULL,
    [cd_item_nota_saida_regist] INT          NOT NULL,
    [cd_operacao_fiscal]        INT          NOT NULL,
    [vl_total_nota_saida]       FLOAT (53)   NULL,
    [vl_base_icms_nota_saida]   FLOAT (53)   NULL,
    [vl_icms_nota_saida]        FLOAT (53)   NULL,
    [vl_icms_isento_nota_saida] FLOAT (53)   NULL,
    [vl_icms_outras_nota_saida] FLOAT (53)   NULL,
    [vl_icms_obs_nota_saida]    FLOAT (53)   NULL,
    [vl_base_ipi_nota_saida]    FLOAT (53)   NULL,
    [vl_ipi_nota_saida]         FLOAT (53)   NULL,
    [vl_ipi_isento_nota_saida]  FLOAT (53)   NULL,
    [vl_ipi_outras_nota_saida]  FLOAT (53)   NULL,
    [vl_ipi_obs_nota_saida]     FLOAT (53)   NULL,
    [vl_frete_nota_saida]       FLOAT (53)   NULL,
    [vl_seguro_nota_saida]      FLOAT (53)   NULL,
    [vl_desp_acess_nota_saida]  FLOAT (53)   NULL,
    [vl_total_prod_nota_saida]  FLOAT (53)   NULL,
    [vl_base_icms_subs_n_saida] FLOAT (53)   NULL,
    [vl_icms_subs_nota_saida]   FLOAT (53)   NULL,
    [vl_iss_nota_saida]         FLOAT (53)   NULL,
    [vl_total_serv_nota_saida]  FLOAT (53)   NULL,
    [nm_obs_reg_nota_saida]     VARCHAR (30) NULL,
    [cd_conta]                  INT          NULL,
    [pc_aliq_ipi_nota_saida]    FLOAT (53)   NULL,
    [vl_contabil_nota_saida]    FLOAT (53)   NULL,
    [pc_aliq_icms_nota_saida]   FLOAT (53)   NULL,
    [pc_aliq_iss_nota_saida]    FLOAT (53)   NULL,
    [nm_obs_livro_saida]        VARCHAR (30) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_fiscal_nota_saida_reg]  CHAR (1)     NULL,
    [ic_manual_nota_saida_reg]  CHAR (1)     NULL,
    [cd_tributacao]             INT          NULL,
    [cd_destinacao_produto]     INT          NULL,
    [cd_livro_saida]            INT          NULL,
    [qt_folha_livro_saida]      INT          NULL,
    [vl_isento_pis_cofins]      FLOAT (53)   NULL
);

