CREATE TABLE [dbo].[Obreiro] (
    [cd_obreiro]              INT           NOT NULL,
    [nm_obreiro]              VARCHAR (50)  NULL,
    [cd_tipo_obreiro]         INT           NULL,
    [dt_nascimento_obreiro]   DATETIME      NULL,
    [cd_estado_civil]         INT           NULL,
    [cd_rg_obreiro]           VARCHAR (18)  NULL,
    [cd_cpf_obreiro]          VARCHAR (18)  NULL,
    [dt_registro_obreiro]     DATETIME      NULL,
    [dt_cadastro_obreiro]     DATETIME      NULL,
    [cd_pais]                 INT           NULL,
    [cd_estado]               INT           NULL,
    [cd_cidade]               INT           NULL,
    [cd_identifica_cep]       INT           NULL,
    [nm_endereco_obreiro]     VARCHAR (60)  NULL,
    [cd_numero_endereco]      VARCHAR (10)  NULL,
    [nm_complemento_endereco] VARCHAR (30)  NULL,
    [nm_bairro]               VARCHAR (25)  NULL,
    [nm_foto_obreiro]         VARCHAR (100) NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [cd_igreja]               INT           NULL,
    [ds_obreiro]              TEXT          NULL,
    [cd_ddd_obreiro]          CHAR (4)      NULL,
    [cd_fone_obreiro]         VARCHAR (15)  NULL,
    [cd_celular_obreiro]      VARCHAR (15)  NULL,
    CONSTRAINT [PK_Obreiro] PRIMARY KEY CLUSTERED ([cd_obreiro] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Obreiro_Igreja] FOREIGN KEY ([cd_igreja]) REFERENCES [dbo].[Igreja] ([cd_igreja])
);

