CREATE TABLE [dbo].[Ocorrencia] (
    [cd_ocorrencia]             INT           NOT NULL,
    [dt_ocorrencia]             DATETIME      NULL,
    [ds_ocorrencia]             TEXT          NULL,
    [cd_tipo_pagamento_frete]   INT           NULL,
    [nm_obs_transporte]         VARCHAR (50)  NULL,
    [dt_baixa_ocorrencia]       DATETIME      NULL,
    [cd_usuario_destino]        INT           NULL,
    [cd_documento]              INT           NULL,
    [cd_departamento]           INT           NULL,
    [cd_item_documento]         INT           NULL,
    [nm_obs_baixa]              VARCHAR (100) NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_tipo_assunto]           INT           NULL,
    [cd_transportadora]         INT           NULL,
    [nm_assunto_ocorrencia]     VARCHAR (40)  NULL,
    [cd_usuario_origem]         INT           NULL,
    [cd_status_ocorrencia]      INT           NULL,
    [cd_usuario_gerente]        INT           NULL,
    [ic_desliga]                CHAR (1)      NULL,
    [cd_tipo_doc_ocorrencia]    INT           NULL,
    [cd_tipo_custo]             INT           NULL,
    [ic_frete_conta_ocorrencia] CHAR (1)      NULL,
    [cd_pedido_venda]           INT           NULL,
    [cd_item_pedido_venda]      INT           NULL,
    [cd_nota_saida]             INT           NULL,
    [cd_item_nota_saida]        INT           NULL,
    [ic_mostra_ocorrencia]      CHAR (1)      NULL,
    [cd_com_copias]             VARCHAR (150) NULL,
    [nm_motivo_cancelamento]    VARCHAR (100) NULL,
    [dt_cancela_ocorrencia]     DATETIME      NULL,
    [ic_mostra_ocorrencia_cop]  VARCHAR (100) NULL,
    [ic_mostra_ocorrencia_sup]  CHAR (1)      NULL,
    [cd_tipo_destinatario]      INT           NULL,
    [cd_destinatario]           INT           NULL,
    [ds_custo_ocorrencia]       TEXT          NULL,
    [dt_custo_ocorrencia]       DATETIME      NULL,
    [cd_usuario_custo]          INT           NULL,
    [vl_custo_ocorrencia]       FLOAT (53)    NULL,
    [dt_email_ocorrencia]       DATETIME      NULL,
    [cd_baixa_com_copia]        VARCHAR (150) NULL,
    [cd_origem_ocorrencia]      INT           NULL,
    CONSTRAINT [PK_Ocorrencia] PRIMARY KEY CLUSTERED ([cd_ocorrencia] ASC) WITH (FILLFACTOR = 90)
);

