CREATE TABLE [dbo].[Operacao] (
    [cd_operacao]                 INT          NOT NULL,
    [nm_operacao]                 VARCHAR (40) NOT NULL,
    [nm_fantasia_operacao]        VARCHAR (15) NOT NULL,
    [sg_operacao]                 CHAR (10)    NULL,
    [ds_operacao]                 TEXT         NULL,
    [ic_processo_operacao]        CHAR (1)     NULL,
    [ic_mapa_operacao]            CHAR (1)     NULL,
    [ic_anterior_operacao]        CHAR (1)     NULL,
    [qt_dia_prog_operacao]        FLOAT (53)   NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [qt_hora_prog_operacao]       FLOAT (53)   NULL,
    [ic_mat_prima_operacao]       CHAR (1)     NULL,
    [cd_grupo_maquina]            INT          NULL,
    [cd_barra_operacao]           VARCHAR (20) NULL,
    [pc_programacao_operacao]     FLOAT (53)   NULL,
    [cd_mao_obra]                 INT          NULL,
    [vl_custo_operacao]           FLOAT (53)   NULL,
    [ic_layout_proc_operacao]     CHAR (1)     NULL,
    [qt_setup_padrao_operacao]    FLOAT (53)   NULL,
    [qt_tempo_padrao_operacao]    FLOAT (53)   NULL,
    [cd_classe]                   INT          NULL,
    [ic_inspecao_operacao]        CHAR (1)     NULL,
    [ic_tempo_unico_operacao]     CHAR (1)     NULL,
    [cd_unidade_medida]           INT          NULL,
    [qt_fator_conversao_operacao] FLOAT (53)   NULL,
    [ic_sinal_conversao_operacao] CHAR (1)     NULL,
    [ic_agrupamento_operacao]     CHAR (1)     NULL,
    [ic_analise_apontamento]      CHAR (1)     NULL,
    [ic_ativa_operacao]           CHAR (1)     NULL,
    CONSTRAINT [PK_Operação] PRIMARY KEY CLUSTERED ([cd_operacao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Operacao_Mao_Obra] FOREIGN KEY ([cd_mao_obra]) REFERENCES [dbo].[Mao_Obra] ([cd_mao_obra]),
    CONSTRAINT [FK_Operacao_Unidade_Medida] FOREIGN KEY ([cd_unidade_medida]) REFERENCES [dbo].[Unidade_Medida] ([cd_unidade_medida])
);

