CREATE TABLE [dbo].[Ordem_Servico] (
    [cd_ordem_servico]           INT          NOT NULL,
    [dt_ordem_servico]           DATETIME     NULL,
    [cd_cliente]                 INT          NULL,
    [cd_tecnico]                 INT          NULL,
    [cd_tipo_atendimento]        INT          NULL,
    [cd_lote_produto]            VARCHAR (40) NULL,
    [cd_condicao_pagamento]      INT          NULL,
    [ds_def_enc_ordem_servico]   TEXT         NULL,
    [ds_def_cli_ordem_servico]   TEXT         NULL,
    [ds_ordem_servico]           TEXT         NULL,
    [pc_desconto_ordem_servico]  FLOAT (53)   NULL,
    [vl_total_ordem_servico]     FLOAT (53)   NULL,
    [vl_servico_ordem_servico]   FLOAT (53)   NULL,
    [vl_produto_ordem_servico]   FLOAT (53)   NULL,
    [dt_ap_ordem_servico]        DATETIME     NULL,
    [dt_servico_ordem_servico]   DATETIME     NULL,
    [dt_visita_ordem_servico]    DATETIME     NULL,
    [qt_dia_entrega_ordem_serv]  FLOAT (53)   NULL,
    [dt_entrega_ordem_servico]   DATETIME     NULL,
    [cd_contato]                 INT          NULL,
    [cd_usuario]                 INT          NULL,
    [dt_usuario]                 DATETIME     NULL,
    [cd_tipo_defeito_cliente]    INT          NULL,
    [nm_contato_ap_ordem_serv]   VARCHAR (40) NULL,
    [cd_tipo_defeito_encontrado] INT          NULL,
    [vl_total_iss_ordem_serv]    FLOAT (53)   NULL,
    [vl_total_icms_ordem_serv]   FLOAT (53)   NULL,
    [vl_desc_ordem_servico]      FLOAT (53)   NULL,
    [ic_emitida_ordem_servico]   CHAR (1)     NULL,
    [ic_custo_financeiro]        CHAR (1)     NULL,
    [vl_tx_mensal_cust_fin]      FLOAT (53)   NULL,
    [cd_tipo_prioridade]         INT          NULL,
    [ic_cobra_visita_ordem_serv] CHAR (1)     NULL,
    [cd_tipo_nivel_atendimento]  INT          NULL,
    [vl_custo_financeiro]        FLOAT (53)   NULL,
    [ds_cancelamento_ordem_serv] TEXT         NULL,
    [nm_alteracao_ordem_serv]    VARCHAR (60) NULL,
    [dt_cancelamento_ordem_serv] DATETIME     NULL,
    [ds_ativacao_ordem_serv]     VARCHAR (60) NULL,
    [dt_ativacao_ordem_servico]  DATETIME     NULL,
    [dt_alteracao_ordem_serv]    DATETIME     NULL,
    [cd_status_ordem_servico]    INT          NULL,
    [cd_usuario_atende]          INT          NULL,
    [ic_fax_ordem_servico]       CHAR (1)     NULL,
    [ic_mail_ordem_servico]      CHAR (1)     NULL,
    [qt_liquido_ordem_servico]   FLOAT (53)   NULL,
    [qt_bruto_ordem_servico]     FLOAT (53)   NULL,
    [ic_fechamento_ordem_serv]   CHAR (1)     NULL,
    [dt_fechamento_ordem_serv]   DATETIME     NULL,
    [ic_fat_ordem_servico]       CHAR (1)     NULL,
    [cd_usuario_cred_ordem_serv] INT          NULL,
    [dt_credito_ordem_servico]   DATETIME     NULL,
    [vl_total_irrf_ordem_serv]   FLOAT (53)   NULL,
    [cd_equipamento_serie]       INT          NULL,
    [cd_vendedor_confirmacao]    INT          NULL,
    [dt_pagto_ordem_servico]     DATETIME     NULL,
    [nm_obs_pagto_ordem]         VARCHAR (40) NULL,
    [ic_ap_ordem_servico]        CHAR (1)     NULL,
    [cd_ap_ordem_servico]        INT          NULL,
    CONSTRAINT [PK_Ordem_Servico] PRIMARY KEY CLUSTERED ([cd_ordem_servico] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Ordem_Servico_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Ordem_Servico_Condicao_Pagamento] FOREIGN KEY ([cd_condicao_pagamento]) REFERENCES [dbo].[Condicao_Pagamento] ([cd_condicao_pagamento]),
    CONSTRAINT [FK_Ordem_Servico_Status_Ordem_Servico] FOREIGN KEY ([cd_status_ordem_servico]) REFERENCES [dbo].[Status_Ordem_Servico] ([cd_status_ordem_servico]),
    CONSTRAINT [FK_Ordem_Servico_Tipo_Atendimento] FOREIGN KEY ([cd_tipo_atendimento]) REFERENCES [dbo].[Tipo_Atendimento] ([cd_tipo_atendimento]),
    CONSTRAINT [FK_Ordem_Servico_Tipo_Nivel_Atendimento] FOREIGN KEY ([cd_tipo_nivel_atendimento]) REFERENCES [dbo].[Tipo_Nivel_Atendimento] ([cd_tipo_nivel_atendimento]),
    CONSTRAINT [FK_Ordem_Servico_Tipo_Prioridade] FOREIGN KEY ([cd_tipo_prioridade]) REFERENCES [dbo].[Tipo_Prioridade] ([cd_tipo_prioridade])
);

