CREATE TABLE [dbo].[Ordem_Servico_Analista] (
    [cd_ordem_servico]          INT          NOT NULL,
    [dt_ordem_servico]          DATETIME     NULL,
    [dt_lancto_ordem_servico]   DATETIME     NULL,
    [cd_cliente]                INT          NULL,
    [cd_contato]                INT          NULL,
    [cd_analista]               INT          NULL,
    [cd_atividade_analista]     INT          NULL,
    [nm_solicit_ordem_servico]  VARCHAR (40) NULL,
    [nm_depto_ordem_servico]    VARCHAR (40) NULL,
    [cd_servico]                INT          NULL,
    [cd_modulo]                 INT          NULL,
    [nm_obs_ordem_servico]      VARCHAR (40) NULL,
    [ds_ordem_servico]          TEXT         NULL,
    [cd_pedido_venda]           INT          NULL,
    [qt_total_despesa_ordem]    FLOAT (53)   NULL,
    [qt_total_normal_ordem]     FLOAT (53)   NULL,
    [qt_total_extra_ordem]      FLOAT (53)   NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_total_desloc_ordem]     FLOAT (53)   NULL,
    [cd_item_pedido_venda]      INT          NULL,
    [cd_departamento_cliente]   INT          NULL,
    [cd_centro_custo]           INT          NULL,
    [ic_nota_debito]            CHAR (1)     NULL,
    [cd_empresa_diversa]        INT          NULL,
    [cd_favorecido_empresa_div] INT          NULL,
    [cd_fornecedor]             INT          NULL,
    [dt_vencimento_despesa]     DATETIME     NULL,
    CONSTRAINT [PK_Ordem_Servico_Analista] PRIMARY KEY CLUSTERED ([cd_ordem_servico] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Ordem_Servico_Analista_Analista] FOREIGN KEY ([cd_analista]) REFERENCES [dbo].[Analista] ([cd_analista]),
    CONSTRAINT [FK_Ordem_Servico_Analista_Atividade_Analista] FOREIGN KEY ([cd_atividade_analista]) REFERENCES [dbo].[Atividade_Analista] ([cd_atividade_analista]),
    CONSTRAINT [FK_Ordem_Servico_Analista_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Ordem_Servico_Analista_Departamento_Cliente] FOREIGN KEY ([cd_departamento_cliente]) REFERENCES [dbo].[Departamento_Cliente] ([cd_departamento_cliente])
);

