CREATE TABLE [dbo].[Ordem_Servico_Grafica] (
    [cd_ordem_servico]      INT            NOT NULL,
    [dt_ordem_servico]      DATETIME       NULL,
    [cd_cliente]            INT            NULL,
    [cd_vendedor_interno]   INT            NULL,
    [cd_vendedor]           INT            NULL,
    [cd_condicao_pagamento] INT            NULL,
    [cd_transportadora]     INT            NULL,
    [cd_tipo_midia]         INT            NULL,
    [dt_entrada_ordem]      DATETIME       NULL,
    [vl_ordem_servico]      FLOAT (53)     NULL,
    [ds_ordem_servico]      VARCHAR (8000) NULL,
    [nm_local_entrega]      VARCHAR (100)  NULL,
    [nm_obs_ordem_servico]  VARCHAR (60)   NULL,
    [hr_entrega_ordem]      VARCHAR (8)    NULL,
    [cd_usuario]            INT            NULL,
    [dt_usuario]            DATETIME       NULL,
    [cd_contato]            INT            NULL,
    [dt_aprovacao_ordem]    DATETIME       NULL,
    [nm_contato_aprovacao]  VARCHAR (60)   NULL,
    [nm_obs_aprovacao]      VARCHAR (60)   NULL,
    [dt_fechamento_ordem]   DATETIME       NULL,
    [nm_obs_fechamento]     VARCHAR (60)   NULL,
    [cd_pedido_venda]       INT            NULL,
    [cd_tipo_endereco]      INT            NULL,
    [cd_entregador]         INT            NULL,
    [nm_recebimento_ordem]  VARCHAR (60)   NULL,
    [dt_recebimento_ordem]  DATETIME       NULL,
    [dt_saida_ordem]        DATETIME       NULL,
    [hr_saida_ordem]        VARCHAR (8)    NULL,
    [hr_recebimento_ordem]  VARCHAR (8)    NULL,
    [ds_ponto_referencia]   VARCHAR (8000) NULL,
    [cd_status_ordem]       INT            NULL,
    [ic_fechamento_servico] CHAR (1)       NULL,
    [status_os]             VARCHAR (10)   NULL,
    [dt_producao_ordem]     DATETIME       NULL,
    [nm_status_os]          VARCHAR (10)   NULL,
    [cd_usuario_original]   INT            NULL,
    [dt_alteracao_ordem]    DATETIME       NULL,
    [nm_alteracao_ordem]    VARCHAR (60)   NULL,
    CONSTRAINT [PK_Ordem_Servico_Grafica] PRIMARY KEY CLUSTERED ([cd_ordem_servico] ASC) WITH (FILLFACTOR = 90)
);

