CREATE TABLE [dbo].[Ordem_Servico_Item] (
    [cd_ordem_servico]            INT          NOT NULL,
    [cd_item_ordem_servico]       INT          NOT NULL,
    [ic_item_ordem_servico]       CHAR (1)     NULL,
    [cd_servico_produto]          INT          NULL,
    [dt_item_ordem_servico]       DATETIME     NULL,
    [qt_item_ordem_servico]       FLOAT (53)   NULL,
    [vl_item_ordem_servico]       FLOAT (53)   NULL,
    [nm_obs_item_ordem_servico]   VARCHAR (50) NULL,
    [ic_produto_especial]         CHAR (1)     NULL,
    [cd_grupo_produto]            INT          NULL,
    [cd_categoria_produto]        INT          NULL,
    [ds_observacao_fabrica]       TEXT         NULL,
    [ic_desc_ordem_serv_item]     CHAR (1)     NULL,
    [dt_desc_ordem_serv_item]     DATETIME     NULL,
    [pc_desc_ordem_serv_item]     FLOAT (53)   NULL,
    [vl_desc_ordem_serv_item]     FLOAT (53)   NULL,
    [cd_posicao_ordem_serv_item]  INT          NULL,
    [qt_liquido_ordem_serv_item]  FLOAT (53)   NULL,
    [qt_bruto_ordem_serv_item]    FLOAT (53)   NULL,
    [qt_saldo_ordem_serv_item]    FLOAT (53)   NULL,
    [cd_unidade_medida]           INT          NULL,
    [vl_lista_ordem_serv_item]    FLOAT (53)   NULL,
    [pc_iss_ordem_serv_item]      FLOAT (53)   NULL,
    [vl_iss_ordem_servico_item]   FLOAT (53)   NULL,
    [pc_icms_ordem_serv_item]     FLOAT (53)   NULL,
    [vl_icms_ordem_serv_item]     FLOAT (53)   NULL,
    [vl_total_ordem_serv_item]    FLOAT (53)   NULL,
    [qt_dia_ent_ordem_servico]    INT          NULL,
    [dt_ent_ordem_servico_item]   DATETIME     NULL,
    [dt_cancelamento_item]        DATETIME     NULL,
    [nm_canc_ordem_serv_item]     VARCHAR (60) NULL,
    [dt_ativacao_ordem_serv_item] DATETIME     NULL,
    [nm_ativ_ordem_serv_item]     VARCHAR (60) NULL,
    [ic_fatura_ordem_serv_item]   CHAR (1)     NULL,
    [ic_reserva_ordem_serv_item]  CHAR (1)     NULL,
    [ic_sel_fechamento]           CHAR (1)     NULL,
    [dt_fechamento_ordem_serv]    DATETIME     NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [pc_irrf_ordem_serv_item]     FLOAT (53)   NULL,
    [vl_irrf_ordem_serv_item]     FLOAT (53)   NULL,
    [nm_servico_produto_item]     VARCHAR (40) NULL,
    [ds_servico_produto_item]     TEXT         NULL,
    [nm_fantasia_produto_item]    VARCHAR (40) NULL,
    [nm_canc_item_ordem_serv]     VARCHAR (60) NULL,
    [qt_dia_garantia_servico]     FLOAT (53)   NULL
);

