CREATE TABLE [dbo].[Pais] (
    [cd_pais]                   INT           NOT NULL,
    [nm_pais]                   VARCHAR (40)  NOT NULL,
    [sg_pais]                   CHAR (5)      NULL,
    [cd_ddi_pais]               CHAR (4)      NULL,
    [cd_siscomex_pais]          INT           NULL,
    [sg_extensao_internet_pais] CHAR (2)      NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [ic_aladi_pais]             CHAR (1)      NULL,
    [ic_mercosul_pais]          CHAR (1)      NULL,
    [vl_limite_credito_pais]    MONEY         NULL,
    [cd_siscomex]               INT           NULL,
    [cd_moeda]                  INT           NULL,
    [cd_idioma]                 INT           NULL,
    [ic_pad_importacao_pais]    CHAR (1)      NULL,
    [vl_saldo_credito_pais]     MONEY         NULL,
    [nm_bandeira_pais]          VARCHAR (255) NULL,
    [cd_pais_mastersaf]         INT           NULL,
    [ic_analise_pais]           CHAR (1)      NULL,
    [cd_estado]                 INT           NULL,
    [cd_bacen_pais]             INT           NULL,
    [cd_continente]             INT           NULL,
    [cd_iso_pais]               CHAR (5)      NULL,
    [cd_area_negocio]           INT           NULL,
    CONSTRAINT [PK_Pais] PRIMARY KEY CLUSTERED ([cd_pais] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Pais_Area_Negocio] FOREIGN KEY ([cd_area_negocio]) REFERENCES [dbo].[Area_Negocio] ([cd_area_negocio]),
    CONSTRAINT [FK_Pais_Continente] FOREIGN KEY ([cd_continente]) REFERENCES [dbo].[Continente] ([cd_continente])
);

