CREATE TABLE [dbo].[Parametro_BDE] (
    [cd_empresa]             INT          NOT NULL,
    [user_name]              VARCHAR (20) NULL,
    [tds_packet_size]        VARCHAR (20) NULL,
    [sqlqrymode]             VARCHAR (20) NULL,
    [sqlpassthru_mode]       VARCHAR (20) NULL,
    [server_name]            VARCHAR (20) NULL,
    [schema_cache_time]      VARCHAR (20) NULL,
    [schema_cache_size]      VARCHAR (20) NULL,
    [schema_cache_dir]       VARCHAR (20) NULL,
    [open_mode]              VARCHAR (20) NULL,
    [national_language_name] VARCHAR (20) NULL,
    [max_rows]               VARCHAR (20) NULL,
    [max_query_time]         VARCHAR (20) NULL,
    [lang_driver]            VARCHAR (20) NULL,
    [host_name]              VARCHAR (20) NULL,
    [enable_schema_cache]    VARCHAR (20) NULL,
    [enable_bcd]             VARCHAR (20) NULL,
    [date_mode]              VARCHAR (20) NULL,
    [database_name]          VARCHAR (20) NULL,
    [blob_to_cache]          VARCHAR (20) NULL,
    [blob_size]              VARCHAR (20) NULL,
    [blob_edit_logging]      VARCHAR (20) NULL,
    [bath_count]             VARCHAR (20) NULL,
    [application_name]       VARCHAR (20) NULL,
    [max_dbprocesses]        VARCHAR (20) NULL,
    [trace_mode]             VARCHAR (20) NULL,
    [driver_flags]           VARCHAR (20) NULL,
    [connect_timeout]        VARCHAR (20) NULL,
    [vendor_init]            VARCHAR (20) NULL,
    [dt_usuario]             DATETIME     NULL,
    [cd_usuario]             INT          NULL,
    [batch_count]            VARCHAR (20) NULL,
    [timeout]                VARCHAR (20) NULL,
    CONSTRAINT [PK_Parametro_BDE] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90)
);

