CREATE TABLE [dbo].[Parametro_Manufatura] (
    [cd_empresa]                     INT           NOT NULL,
    [cd_usuario]                     INT           NULL,
    [dt_usuario]                     DATETIME      NULL,
    [qt_passo_seq_operacao]          INT           NULL,
    [ic_rel_proc_fabricacao]         CHAR (1)      NULL,
    [cd_fase_produto]                INT           NULL,
    [ic_mov_estrutura_produto]       CHAR (1)      NULL,
    [ic_numero_mapa_producao]        CHAR (1)      NULL,
    [qt_dia_fim_operacao]            INT           NULL,
    [qt_dia_inicio_operacao]         INT           NULL,
    [ic_filtro_maq_ope_empresa]      CHAR (1)      NULL,
    [qt_dia_processo_aguardo]        INT           NULL,
    [ic_controle_projeto]            CHAR (1)      NULL,
    [ic_baixa_estoque_processo]      CHAR (1)      NULL,
    [ic_qtd_proc_padrao_pc]          CHAR (1)      NULL,
    [ic_mostra_custo_proc_padr]      CHAR (1)      NULL,
    [ds_observacao_producao]         TEXT          NULL,
    [ic_embalagem_proc_padrao]       CHAR (1)      NULL,
    [ic_rel_processo_padrao]         CHAR (1)      NULL,
    [ic_orcamento_proc_producao]     CHAR (1)      NULL,
    [ic_mascara_componente]          CHAR (1)      NULL,
    [ic_apontamento_op_fechada]      CHAR (1)      NULL,
    [ic_padrao_cores]                CHAR (1)      NULL,
    [ic_montagem_placa_req]          CHAR (1)      NULL,
    [ic_item_orcamento_compra]       CHAR (1)      NULL,
    [ic_emb_processo_producao]       CHAR (1)      NULL,
    [ic_custo_prod_processo_padrao]  CHAR (1)      NULL,
    [ic_apontamento_fase]            CHAR (1)      NULL,
    [ic_obs_item_pv_os_producao]     CHAR (1)      NULL,
    [nm_imagem_item_critico]         VARCHAR (100) NULL,
    [ic_produto_processo_padrao]     CHAR (1)      NULL,
    [ic_baixa_estoque_apontamento]   CHAR (1)      NULL,
    [ic_modelo_os_empresa]           CHAR (1)      NULL,
    [ic_verifica_embalagem_embalado] CHAR (1)      NULL,
    [ic_mostrar_valor_grid_pv_prod]  CHAR (1)      NULL,
    [ic_gera_op_automatico_pv]       CHAR (1)      NULL,
    [ic_preenchimento_aut_op]        CHAR (1)      NULL,
    [ic_bloqueia_op_pedido_venda]    CHAR (1)      NULL,
    [ic_credito_ord_producao]        CHAR (1)      NULL,
    [ic_permite_apontamento_seq]     CHAR (1)      NULL,
    [ic_tipo_preco_custo]            CHAR (1)      NULL,
    [ic_op_pedido_faturado]          CHAR (1)      NULL,
    [cd_fase_produto_montagem]       INT           NULL,
    [qt_dia_elaborar_processo]       INT           NULL,
    [qt_dia_retifica_comp]           INT           NULL,
    [ic_ferramenta_processo]         CHAR (1)      NULL,
    [cd_unidade_medida]              INT           NULL,
    [ic_vincula_pv_it_prod_dif]      CHAR (1)      NULL,
    [ic_mostrar_descricao_mp_op]     CHAR (1)      NULL,
    [ic_qtd_pedido_processo]         CHAR (1)      NULL,
    [qt_linha_apontamento_op]        INT           NULL,
    [ic_processo_guia_fio]           CHAR (1)      NULL,
    [ic_apontamento_barra]           CHAR (1)      NULL,
    [ic_tipo_qtd_processo]           CHAR (1)      NULL,
    [ic_apontamento_mp]              CHAR (1)      NULL,
    [ic_gera_ordem_automatica]       CHAR (1)      NULL,
    [ic_custo_composicao]            CHAR (1)      NULL,
    [ic_detalhe_processo]            CHAR (1)      NULL,
    [ic_saldo_estoque]               CHAR (1)      NULL,
    [ic_estoque_requisicao]          CHAR (1)      NULL,
    [ic_custo_mp_unitario]           CHAR (1)      NULL,
    [ic_proc_conversao_hora]         CHAR (1)      NULL,
    [ic_estrutura_produto_op]        CHAR (1)      NULL,
    [ic_reserva_plano_envase]        CHAR (1)      NULL,
    [ic_reserva_op_automatico]       CHAR (1)      NULL,
    [ic_valida_senha_processo]       CHAR (1)      NULL,
    [ic_embalagem_composicao]        CHAR (1)      NULL,
    CONSTRAINT [PK_Parametro_Manufatura] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Manufatura_Fase_Produto] FOREIGN KEY ([cd_fase_produto_montagem]) REFERENCES [dbo].[Fase_Produto] ([cd_fase_produto]),
    CONSTRAINT [FK_Parametro_Manufatura_Unidade_Medida] FOREIGN KEY ([cd_unidade_medida]) REFERENCES [dbo].[Unidade_Medida] ([cd_unidade_medida])
);

