CREATE TABLE [dbo].[Parametro_Financeiro] (
    [cd_empresa]                  INT           NOT NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [ic_fluxo_caixa_empresa]      CHAR (1)      NULL,
    [cd_moeda]                    INT           NULL,
    [ic_serie_doc_rec_empresa]    CHAR (1)      NULL,
    [ic_ano_doc_rec_empresa]      CHAR (1)      NULL,
    [ic_1parc_doc_rec_empresa]    CHAR (1)      NULL,
    [cd_plano_financeiro]         INT           NULL,
    [cd_tipo_cobranca]            INT           NULL,
    [cd_tipo_documento]           INT           NULL,
    [cd_portador]                 INT           NULL,
    [pc_liquidez_empresa]         FLOAT (53)    NULL,
    [ic_centavo_fluxo_empresa]    CHAR (1)      NULL,
    [pc_taxa_cobranca_banco]      FLOAT (53)    NULL,
    [ic_centro_custo_scr]         CHAR (1)      NULL,
    [ic_centro_custo_scp]         CHAR (1)      NULL,
    [ic_plano_financeiro_scr]     CHAR (1)      NULL,
    [ic_plano_financeiro_scp]     CHAR (1)      NULL,
    [ic_desconto_scr_empresa]     CHAR (1)      NULL,
    [ic_lancdupl_traco_empresa]   CHAR (1)      NULL,
    [ic_zero_primeira_parcela]    CHAR (1)      NULL,
    [ic_contabilidade_scr]        CHAR (1)      NULL,
    [ic_contabilidade_scp]        CHAR (1)      NULL,
    [ic_razao_cliente_empresa]    CHAR (1)      NULL,
    [ic_razao_fornecedor_emp]     CHAR (1)      NULL,
    [cd_conta_cliente]            INT           NULL,
    [cd_conta_fornecedor]         INT           NULL,
    [ic_caracter_parcela]         CHAR (1)      NULL,
    [ic_instrucao_bx_doc_scr]     CHAR (1)      NULL,
    [ic_permit_baixa_adto_scp]    CHAR (1)      NULL,
    [ic_ultimo_aberto_scp]        CHAR (1)      NULL,
    [ic_ultimo_aberto_scr]        CHAR (1)      NULL,
    [ic_movto_banco_scp]          CHAR (1)      NULL,
    [cd_telefone_financeiro]      VARCHAR (30)  NULL,
    [ds_msg_det_nota_debito]      TEXT          NULL,
    [ds_msg_cab_nota_debito]      TEXT          NULL,
    [cd_conta_banco_n_debito]     INT           NULL,
    [cd_tipo_codigo_barra]        INT           NULL,
    [cd_tipo_conta_pagar]         INT           NULL,
    [ic_valida_limite_credito]    CHAR (1)      NULL,
    [nm_porta_impressao_dupl]     VARCHAR (100) NULL,
    [qt_min_dia_envio_magnetic]   INT           NULL,
    [ic_atualiza_fluxo_scr]       CHAR (1)      NULL,
    [ic_atualiza_fluxo_scp]       CHAR (1)      NULL,
    [ic_ord_plano_financ]         CHAR (1)      NULL,
    [ic_consulta_parcial_doc]     CHAR (1)      NULL,
    [ic_envia_doc_emitido]        CHAR (1)      NULL,
    [ic_autorizacao_pagamento]    CHAR (1)      NULL,
    [ic_credito_saldo_cliente]    CHAR (1)      NULL,
    [ic_executar_trigger_scr]     CHAR (1)      NULL,
    [dt_lib_inicial_pedido_venda] DATETIME      NULL,
    [ic_documento_entrada]        CHAR (1)      NULL,
    [ic_forma_impressao_cheque]   CHAR (1)      NULL,
    [ic_destinatario_scr]         CHAR (1)      NULL,
    [ic_comex_financeiro]         CHAR (1)      NULL,
    [ic_contab_financeiro]        CHAR (1)      NULL,
    [ic_bloqueia_fec_pedido]      CHAR (1)      NULL,
    [ic_vcto_scp_dia_util]        CHAR (1)      NULL,
    [qt_dia_atraso_bloqueio]      FLOAT (53)    NULL,
    [ic_pagamento_fluxo]          CHAR (1)      NULL,
    [ic_filtro_grupo_cliente]     CHAR (1)      NULL,
    [cd_tipo_cobranca_desconto]   INT           NULL,
    [ic_retorno_mov_conta]        CHAR (1)      NULL,
    [ic_tipo_ret_mov_conta]       CHAR (1)      NULL,
    [ic_layout_copia_cheque]      CHAR (1)      NULL,
    [vl_padrao_limite_credito]    FLOAT (53)    NULL,
    [qt_dia_validacao_credito]    FLOAT (53)    NULL,
    [ic_altera_pesq_cliente]      CHAR (1)      NULL,
    [ic_altera_limite_credito]    CHAR (1)      NULL,
    [ic_altera_credito_suspenso]  CHAR (1)      NULL,
    [ic_plano_financeiro_req]     CHAR (1)      NULL,
    [ic_altera_limite_cliente]    CHAR (1)      NULL,
    [ic_atraso_bloqueio]          CHAR (1)      NULL,
    [ic_conta_banco_copia_cheq]   CHAR (1)      NULL,
    [qt_dia_acerto_adto]          INT           NULL,
    [ic_previsao_saldo]           CHAR (1)      NULL,
    [ic_saldo_atual_fluxo]        CHAR (1)      NULL,
    [ic_exporta_competence]       CHAR (1)      NULL,
    [qt_dia_atraso_comercial]     INT           NULL,
    [ic_numera_parcela]           CHAR (1)      NULL,
    [ic_rateio_plano_categoria]   CHAR (1)      NULL,
    [ic_importacao_fluxo_caixa]   CHAR (1)      NULL,
    [cd_centro_custo]             INT           NULL,
    [qt_dia_atraso_fluxo_caixa]   FLOAT (53)    NULL,
    [ic_vcto_menor_emissao]       CHAR (1)      NULL,
    [pc_desconto_boleto]          FLOAT (53)    NULL,
    [ic_credito_pedido_fechado]   CHAR (1)      NULL,
    [cd_senha_scp]                VARCHAR (10)  NULL,
    [cd_senha_scr]                VARCHAR (10)  NULL,
    CONSTRAINT [PK_Parametro_Financeiro] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Financeiro_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Parametro_Financeiro_Tipo_Cobranca] FOREIGN KEY ([cd_tipo_cobranca_desconto]) REFERENCES [dbo].[Tipo_Cobranca] ([cd_tipo_cobranca])
);

