CREATE TABLE [dbo].[Parametro_Prestacao_Conta] (
    [cd_empresa]                INT           NOT NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [ds_obs_prestacao_conta]    TEXT          NULL,
    [ds_obs_receber]            TEXT          NULL,
    [ds_obs_restituir]          TEXT          NULL,
    [ic_texto_emitente]         CHAR (1)      NULL,
    [ic_contabilizacao]         CHAR (1)      NULL,
    [ds_emitente]               TEXT          NULL,
    [ic_tipo_conta_contabil]    CHAR (1)      NULL,
    [cd_conta_adiantamento]     INT           NULL,
    [cd_conta_adto_moeda]       INT           NULL,
    [cd_conta_banco]            INT           NULL,
    [cd_conta_caixa]            INT           NULL,
    [nm_titulo_prestacao_conta] VARCHAR (100) NULL,
    [pc_imposto]                FLOAT (53)    NULL,
    [cd_imposto]                INT           NULL,
    [ic_imposto]                CHAR (1)      NULL,
    [cd_tipo_despesa]           INT           NULL,
    [ic_projeto]                CHAR (1)      NULL,
    [ic_documento_prestacao]    CHAR (1)      NULL,
    [ic_tipo_pagamento]         CHAR (1)      NULL,
    [ic_cartao_gera_prestacao]  CHAR (1)      NULL,
    [ic_edita_cc_depto]         CHAR (1)      NULL,
    [ic_exclusao_adiantamento]  CHAR (1)      NULL,
    [ic_gera_email_aprovacao]   CHAR (1)      NULL,
    [nm_servidor_pagina_asp]    VARCHAR (255) NULL,
    [cd_funcionario]            INT           NULL,
    [cd_conta_estorno]          INT           NULL,
    [ic_gera_email_retorno]     CHAR (1)      NULL,
    [qt_dia_retorno_aviso]      INT           NULL,
    [vl_adiantamento_padrao]    FLOAT (53)    NULL,
    [ic_email_liberacao]        CHAR (1)      NULL,
    [ic_acesso_consulta]        CHAR (1)      NULL,
    [ic_motivo_prestacao]       CHAR (1)      NULL,
    [ic_aprovacao_especial]     CHAR (1)      NULL,
    [ic_filtro_cc_finalidade]   CHAR (1)      NULL,
    [cd_conta_fornecedor]       INT           NULL,
    CONSTRAINT [PK_Parametro_Prestacao_Conta] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Prestacao_Conta_Imposto] FOREIGN KEY ([cd_imposto]) REFERENCES [dbo].[Imposto] ([cd_imposto]),
    CONSTRAINT [FK_Parametro_Prestacao_Conta_Tipo_Despesa] FOREIGN KEY ([cd_tipo_despesa]) REFERENCES [dbo].[Tipo_Despesa] ([cd_tipo_despesa])
);

