CREATE TABLE [dbo].[Parametro_Fiscal] (
    [cd_empresa]                  INT      NOT NULL,
    [ds_cab_carta_correcao]       TEXT     NULL,
    [ds_rod_carta_correcao]       TEXT     NULL,
    [cd_usuario]                  INT      NULL,
    [dt_usuario]                  DATETIME NULL,
    [pc_base_ipi_equip_indl]      MONEY    NULL,
    [qt_pag_iss_empresa]          INT      NULL,
    [qt_pag_ipi_empresa]          INT      NULL,
    [qt_pag_icms_empresa]         INT      NULL,
    [qt_pag_inventario_empresa]   INT      NULL,
    [qt_pag_valoracao_peps]       INT      NULL,
    [ic_desagrupa_livro_saida]    CHAR (1) NULL,
    [qt_pag_registro_saida]       INT      NULL,
    [qt_pag_registro_entrada]     INT      NULL,
    [ic_total_pagina]             CHAR (1) NULL,
    [ic_total_pagina_livro]       CHAR (1) NULL,
    [ic_ipi_entrada_empresa]      CHAR (1) NULL,
    [ic_valida_cad_prod_Fiscal]   CHAR (1) NULL,
    [ic_forma_calculo_tributacao] CHAR (1) NULL,
    [cd_banco]                    INT      NULL,
    [ic_reducao_icms_importacao]  CHAR (1) NULL,
    [qt_mes_ciap]                 INT      NULL,
    [ic_gera_ciap]                CHAR (1) NULL,
    [ic_nf_entrada_livro_saida]   CHAR (1) NULL,
    [ic_tipo_emitente_livro]      CHAR (1) NULL,
    [ic_usuario_carta_correcao]   CHAR (1) NULL,
    [ic_nf_entrada_livro_entrada] CHAR (1) NULL,
    CONSTRAINT [PK_Parametro_Fiscal] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Fiscal_Banco] FOREIGN KEY ([cd_banco]) REFERENCES [dbo].[Banco] ([cd_banco])
);

