CREATE TABLE [dbo].[Parametro_Loja] (
    [cd_empresa]                  INT          NOT NULL,
    [ic_vendedor_obrigatorio]     CHAR (1)     NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [ic_montagem_kit]             CHAR (1)     NULL,
    [cd_banco_financeira]         INT          NULL,
    [cd_senha_liberacao_desc]     VARCHAR (10) NULL,
    [ic_credito_devolucao]        CHAR (1)     NULL,
    [ic_faturamento_disponivel]   CHAR (1)     NULL,
    [cd_loja]                     INT          NULL,
    [cd_cliente]                  INT          NULL,
    [ic_alteracao_preco]          CHAR (1)     NULL,
    [ic_alteracao_data_entrega]   CHAR (1)     NULL,
    [ic_altera_vcto_parcela]      CHAR (1)     NULL,
    [ic_tabela_preco_loja]        CHAR (1)     NULL,
    [cd_tabela_preco]             INT          NULL,
    [ic_senha_operador_venda]     CHAR (1)     NULL,
    [ic_tipo_foto_terminal]       CHAR (1)     NULL,
    [ic_dia_entrega_produto]      CHAR (1)     NULL,
    [ic_manut_pedido_venda_caixa] CHAR (1)     NULL,
    [ic_layout_recibo_loja]       CHAR (1)     NULL,
    [cd_condicao_pagamento]       INT          NULL,
    [ic_numero_controle_caixa]    CHAR (1)     NULL,
    [ic_obs_diario_caixa]         CHAR (1)     NULL,
    [ic_esconde_botoes_venda]     CHAR (1)     NULL,
    [nm_porta_impressao]          VARCHAR (50) NULL,
    [ic_gera_financeiro]          CHAR (1)     NULL,
    CONSTRAINT [PK_Parametro_Loja] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Loja_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Parametro_Loja_Condicao_Pagamento] FOREIGN KEY ([cd_condicao_pagamento]) REFERENCES [dbo].[Condicao_Pagamento] ([cd_condicao_pagamento]),
    CONSTRAINT [FK_Parametro_Loja_Loja] FOREIGN KEY ([cd_loja]) REFERENCES [dbo].[Loja] ([cd_loja]),
    CONSTRAINT [FK_Parametro_Loja_Tabela_Preco] FOREIGN KEY ([cd_tabela_preco]) REFERENCES [dbo].[Tabela_Preco] ([cd_tabela_preco])
);

