CREATE TABLE [dbo].[Parametro_Comercial] (
    [cd_empresa]                     INT           NOT NULL,
    [qt_dia_imediato_empresa]        INT           NULL,
    [cd_usuario]                     INT           NULL,
    [dt_usuario]                     DATETIME      NULL,
    [cd_fase_produto]                INT           NULL,
    [ic_auto_scr_empresa]            CHAR (1)      NULL,
    [ic_auto_scp_empresa]            CHAR (1)      NULL,
    [ic_orcamento]                   CHAR (1)      NULL,
    [ic_om]                          CHAR (1)      NULL,
    [ic_kogo]                        CHAR (1)      NULL,
    [ic_credito_automatico]          CHAR (1)      NULL,
    [ic_icms_proposta_empresa]       CHAR (1)      NULL,
    [ic_custo_finan_empresa]         CHAR (1)      NULL,
    [ic_desconto_grupo_produto]      CHAR (1)      NULL,
    [ic_desconto_serie_produto]      CHAR (1)      NULL,
    [ic_ipi_proposta_empresa]        CHAR (1)      NULL,
    [ic_custo_financeiro]            CHAR (1)      NULL,
    [qt_dia_validade_proposta]       INT           NULL,
    [ic_grade_empresa]               CHAR (1)      NULL,
    [ic_ambiente_empresa]            CHAR (1)      NULL,
    [ic_editar_cd_pedido_venda]      CHAR (1)      NULL,
    [ic_cod_barra_pedido_venda]      CHAR (1)      NULL,
    [ic_cod_barra_consulta]          CHAR (1)      NULL,
    [ic_dias_uteis_entrega]          CHAR (1)      NULL,
    [ic_cad_contato_pedido]          CHAR (1)      NULL,
    [ic_cad_contato_proposta]        CHAR (1)      NULL,
    [ic_cad_cliente_pedido]          CHAR (1)      NULL,
    [ic_cad_cliente_proposta]        CHAR (1)      NULL,
    [ic_consulta_preco_produto]      CHAR (1)      NULL,
    [cd_plano_financeiro]            INT           NULL,
    [ic_controle_multa]              CHAR (1)      NULL,
    [ic_manutencao_parcela]          CHAR (1)      NULL,
    [ic_gera_nota_saida_ped]         CHAR (1)      NULL,
    [cd_fase_produto_contrato]       INT           NULL,
    [ic_liberacao_desconto]          CHAR (1)      NULL,
    [ic_ord_separacao_vendedor]      CHAR (1)      NULL,
    [ic_bloqueia_credito_emp]        CHAR (1)      NULL,
    [ic_orcamento_proposta]          CHAR (1)      NULL,
    [ic_pega_ult_produto_grupo]      CHAR (1)      NULL,
    [ic_aba_parcela_pedido]          CHAR (1)      NULL,
    [ic_venda_embalagem]             CHAR (1)      NULL,
    [ic_aviso_licenca_federal]       CHAR (1)      NULL,
    [ic_checa_saldo_estrutura]       CHAR (1)      NULL,
    [ic_gera_reserva_estrutura]      CHAR (1)      NULL,
    [ic_validade_proposta]           CHAR (1)      NULL,
    [ic_venda_sem_lista]             CHAR (1)      NULL,
    [ic_complemento_cliente]         CHAR (1)      NULL,
    [ic_venda_kit_montagem]          CHAR (1)      NULL,
    [ic_identificacao_parcela]       CHAR (1)      NULL,
    [vl_atraso_cliente_empresa]      FLOAT (53)    NULL,
    [ic_atraso_cliente_empresa]      CHAR (1)      NULL,
    [ic_produto_cilindro]            CHAR (1)      NULL,
    [ic_bloqueia_desconto]           CHAR (1)      NULL,
    [ic_bloqueia_venda_cotacao]      CHAR (1)      NULL,
    [ic_cep_cadastro_cliente]        CHAR (1)      NULL,
    [ic_mostrar_valor_outra_moeda]   CHAR (1)      NULL,
    [ic_preco_tipo_pedido]           CHAR (1)      NULL,
    [ic_modelo_ped_venda]            CHAR (1)      NULL,
    [ic_dup_imprime_pedido]          CHAR (1)      NULL,
    [ic_loja_pedido_venda]           CHAR (1)      NULL,
    [ic_preenche_valor_outra_moeda]  CHAR (1)      NULL,
    [ic_gera_proejto]                CHAR (1)      NULL,
    [ic_promocao_empresa]            CHAR (1)      NULL,
    [ic_mensagem_preco_zero]         CHAR (1)      NULL,
    [ic_pesq_prod_carac_tecnic]      CHAR (1)      NULL,
    [ic_exclusao_cliente]            CHAR (1)      NULL,
    [ic_controle_emissao_ped]        CHAR (1)      NULL,
    [ic_pesq_sinonimo_produto]       CHAR (1)      NULL,
    [nm_senha_previsao]              VARCHAR (15)  NULL,
    [ic_apresentacao_produto_pedido] CHAR (1)      NULL,
    [ic_lib_desconto_proposta]       CHAR (1)      NULL,
    [ic_filtro_loja_meta]            CHAR (1)      NULL,
    [qt_dia_proposta_aberto]         INT           NULL,
    [ic_produto_impressao_pedido]    CHAR (1)      NULL,
    [ic_formata_moeda_exportacao]    CHAR (1)      NULL,
    [ic_altera_vendedor]             CHAR (1)      NULL,
    [ic_mostra_data_validade]        CHAR (1)      NULL,
    [ic_perfil_cliente]              CHAR (1)      NULL,
    [ic_opera_obs_fabricacao]        CHAR (1)      NULL,
    [ic_previa_faturamento]          CHAR (1)      NULL,
    [ic_edita_email]                 CHAR (1)      NULL,
    [ic_data_entrega_vendedor]       CHAR (1)      NULL,
    [nm_site_busca_endereco]         VARCHAR (100) NULL,
    [ic_duplicar_produto]            CHAR (1)      NULL,
    [ic_validar_lote]                CHAR (1)      NULL,
    [ic_end_cons_cliente]            CHAR (1)      NULL,
    [ic_perda_cancelamento]          CHAR (1)      NULL,
    [ic_permite_pv_sem_proposta]     CHAR (1)      NULL,
    [cd_motivo_perda_cancel_pv]      INT           NULL,
    [ic_lote_obrigatorio]            CHAR (1)      NULL,
    [ic_permite_venda_sem_prev]      CHAR (1)      NULL,
    [ic_dia_entrega_disponivel]      CHAR (1)      NULL,
    [ic_permite_produto_especial]    CHAR (1)      NULL,
    [qt_dia_orcamento_empresa]       INT           NULL,
    [ic_custo_financeiro_empresa]    CHAR (1)      NULL,
    [ic_editar_transportadora_venda] CHAR (1)      NULL,
    [ic_lancamento_visita]           CHAR (1)      NULL,
    [ic_dt_entrega_pedido]           CHAR (1)      NULL,
    [ic_data_entrada_pedido]         CHAR (1)      NULL,
    [ic_desconto_comercial]          CHAR (1)      NULL,
    [ic_desconto_composicao]         CHAR (1)      NULL,
    [ic_especial_grupo_fiscal]       CHAR (1)      NULL,
    [ic_controle_escala_desconto]    CHAR (1)      NULL,
    [ic_liberacao_cond_pagamento]    CHAR (1)      NULL,
    [cd_condicao_pagamento]          INT           NULL,
    [ic_recalcula_total_pedido_prop] CHAR (1)      NULL,
    [ic_inf_credito_vendedor]        CHAR (1)      NULL,
    [ic_operacao_credito_pedido]     CHAR (1)      NULL,
    [ic_requisicao_compra]           CHAR (1)      NULL,
    [ic_busca_ultimo_preco]          CHAR (1)      NULL,
    [ic_aviso_licenca]               CHAR (1)      NULL,
    [ic_edicao_vendedor_pedido]      CHAR (1)      NULL,
    [ic_forma_consulta_diario]       CHAR (1)      NULL,
    [ic_projeto_mercado]             CHAR (1)      NULL,
    [ic_revisao_proposta]            CHAR (1)      NULL,
    [ic_configurador_produto]        CHAR (1)      NULL,
    [ic_pesquisa_produto]            CHAR (1)      NULL,
    [ic_embalagem_unidade]           CHAR (1)      NULL,
    [ic_reserva_contrato]            CHAR (1)      NULL,
    [ic_gera_scr_pedido]             CHAR (1)      NULL,
    [ic_estoque_req_interna]         CHAR (1)      NULL,
    CONSTRAINT [PK_Parametro_Comercial] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Comercial_Condicao_Pagamento] FOREIGN KEY ([cd_condicao_pagamento]) REFERENCES [dbo].[Condicao_Pagamento] ([cd_condicao_pagamento])
);

