CREATE TABLE [dbo].[Parametro_Suprimento] (
    [cd_empresa]                   INT           NOT NULL,
    [cd_usuario]                   INT           NULL,
    [dt_usuario]                   DATETIME      NULL,
    [qt_mes_evolucao_empresa]      FLOAT (53)    NULL,
    [cd_fase_produto]              INT           NULL,
    [cd_fase_produto_entrada]      INT           NULL,
    [cd_tipo_movimento_req_e]      INT           NULL,
    [cd_tipo_movimento_req_s]      INT           NULL,
    [cd_tipo_movimento_comp_e]     INT           NULL,
    [cd_tipo_movimento_comp_s]     INT           NULL,
    [ic_valida_fornecedor]         CHAR (1)      NULL,
    [cd_plano_financeiro]          INT           NULL,
    [ic_liberado_comprador]        CHAR (1)      NULL,
    [vl_pedido_compra_empresa]     FLOAT (53)    NULL,
    [cd_tipo_assinatura]           INT           NULL,
    [ic_altera_data_pedido]        CHAR (1)      NULL,
    [ds_msg_rodape_pedido]         TEXT          NULL,
    [nm_email_setor_compra]        VARCHAR (100) NULL,
    [cd_telefone_compra]           VARCHAR (15)  NULL,
    [ic_medida_materia_prima]      CHAR (1)      NULL,
    [ic_libera_cotacao_req_ped]    CHAR (1)      NULL,
    [ic_apresentacao_mapa]         CHAR (1)      NULL,
    [ic_plano_financeiro_req]      CHAR (1)      NULL,
    [ic_identif_prod_cotacao]      CHAR (1)      NULL,
    [ic_identif_pro_pedido]        CHAR (1)      NULL,
    [ic_agrupa_cotacao_empresa]    CHAR (1)      NULL,
    [ic_entrega_necessidade]       CHAR (1)      NULL,
    [cd_fax_compra]                VARCHAR (15)  NULL,
    [ic_nec_somente_item_sco]      CHAR (1)      NULL,
    [ic_mapa_item_ped_compra]      CHAR (1)      NULL,
    [ic_modelo_ped_compra]         CHAR (1)      NULL,
    [ic_modelo_cotacao]            CHAR (1)      NULL,
    [ic_tipo_envio_email]          CHAR (1)      NULL,
    [dt_inicio_req_aberto]         DATETIME      NULL,
    [ic_filtro_nec_req_compra]     CHAR (1)      NULL,
    [ic_lib_comprador_mapa]        CHAR (1)      NULL,
    [ic_ipi_mapa_compra]           CHAR (1)      NULL,
    [ic_valor_plano_pedido]        CHAR (1)      NULL,
    [ic_bloqueia_pedido_liberacao] CHAR (1)      NULL,
    [ic_preco_reposicao_pedido]    CHAR (1)      NULL,
    [ic_modelo_pedido_compra]      CHAR (1)      NULL,
    [ic_edita_email]               CHAR (1)      NULL,
    [ic_req_auto_cadastro]         CHAR (1)      NULL,
    [ic_filtro_requisicao]         CHAR (1)      NULL,
    [cd_status_pedido]             INT           NULL,
    [ic_custo_pedido_imposto]      CHAR (1)      NULL,
    [cd_aplicacao_markup]          INT           NULL,
    [qt_pedido_controle]           INT           NULL,
    [ic_permite_trocar_item_pc]    CHAR (1)      NULL,
    [ic_orcamento_compra]          CHAR (1)      NULL,
    [ic_bloqueio_limite_compra]    CHAR (1)      NULL,
    CONSTRAINT [PK_Parametro_Suprimento] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Suprimento_Aplicacao_Markup] FOREIGN KEY ([cd_aplicacao_markup]) REFERENCES [dbo].[Aplicacao_Markup] ([cd_aplicacao_markup]),
    CONSTRAINT [FK_Parametro_Suprimento_Status_Pedido] FOREIGN KEY ([cd_status_pedido]) REFERENCES [dbo].[Status_Pedido] ([cd_status_pedido])
);

