CREATE TABLE [dbo].[Parametro_Requisicao] (
    [cd_empresa]                 INT         NOT NULL,
    [ic_req_logotipo_empresa]    CHAR (1)    NULL,
    [ic_req_endereco_empresa]    CHAR (1)    NULL,
    [ds_req_mensagem_empresa]    TEXT        NULL,
    [ds_req_obs_empresa]         TEXT        NULL,
    [ic_aco_empresa]             CHAR (1)    NULL,
    [cd_usuario]                 INT         NULL,
    [dt_usuario]                 DATETIME    NULL,
    [ic_tipo_req_obrigatorio]    CHAR (1)    NULL,
    [ic_motivo_obrigatorio]      VARCHAR (1) NULL,
    [ic_aplicacao_obrigatorio]   VARCHAR (1) NULL,
    [ic_destinacao_obrigatorio]  VARCHAR (1) NULL,
    [ic_plano_comp_obrigatorio]  VARCHAR (1) NULL,
    [ic_bloqueia_req_liberacao]  CHAR (1)    NULL,
    [qt_dias_prazo_req_compra]   INT         NULL,
    [ic_imp_autorizacao]         CHAR (1)    NULL,
    [ic_imp_valor_fob]           CHAR (1)    NULL,
    [ic_imp_desc_item]           CHAR (1)    NULL,
    [ic_imp_peso_bruto]          CHAR (1)    NULL,
    [ic_aviso_saldo_produto]     CHAR (1)    NULL,
    [ic_modelo_requisicao]       CHAR (1)    NULL,
    [ic_bloquear_alteracao_qtde] CHAR (1)    NULL,
    [ic_permite_importacao]      CHAR (1)    NULL,
    [ic_exclusao_requisicao]     CHAR (1)    NULL,
    [ic_imp_desctec_item]        CHAR (1)    NULL,
    [ic_aprov_requisicao]        CHAR (1)    NULL,
    CONSTRAINT [PK_Parametro_Requisicao] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90)
);

