CREATE TABLE [dbo].[Parametro_Importacao] (
    [cd_empresa]                   INT           NOT NULL,
    [cd_fase_produto]              INT           NULL,
    [cd_usuario]                   INT           NULL,
    [dt_usuario]                   DATETIME      NULL,
    [cd_idioma]                    INT           NULL,
    [cd_moeda]                     INT           NULL,
    [cd_porto_chegada_padrao]      INT           NULL,
    [pc_coeficiente_importacao]    FLOAT (53)    NULL,
    [pc_coeficiente_internacao]    FLOAT (53)    NULL,
    [sg_pais_identificacao_ped]    CHAR (2)      NULL,
    [ic_arquivo_importacao]        CHAR (1)      NULL,
    [ic_tipo_cab_relatorio]        CHAR (1)      NULL,
    [ic_edita_numero_pedido]       CHAR (1)      NULL,
    [ic_descricao_tecnica]         CHAR (1)      NULL,
    [cd_modelo_pedido_importacao]  INT           NULL,
    [nm_caminho_di_simbolica]      VARCHAR (100) NULL,
    [nm_caminho_di_oficial]        VARCHAR (100) NULL,
    [nm_caminho_arquivo_pedido]    VARCHAR (100) NULL,
    [ic_ativa_embarque]            CHAR (1)      NULL,
    [ic_tipo_envio_email]          CHAR (1)      NULL,
    [ic_atualiza_previsao_entrada] CHAR (1)      NULL,
    [ic_calculo_cpv_di]            CHAR (1)      NULL,
    [ic_tipo_numeracao]            CHAR (1)      NULL,
    [ic_custo_produto_importacao]  CHAR (1)      NULL,
    [qt_periodo_analise]           INT           NULL,
    [qt_giro]                      INT           NULL,
    [qt_duracao_dia_min]           INT           NULL,
    [qt_duracao_dia_max]           INT           NULL,
    [pc_pis_importacao]            FLOAT (53)    NULL,
    [pc_cofins_importacao]         FLOAT (53)    NULL,
    CONSTRAINT [PK_Parametro_Importacao] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Importacao_Fase_Produto] FOREIGN KEY ([cd_fase_produto]) REFERENCES [dbo].[Fase_Produto] ([cd_fase_produto]),
    CONSTRAINT [FK_Parametro_Importacao_Idioma] FOREIGN KEY ([cd_idioma]) REFERENCES [dbo].[Idioma] ([cd_idioma]),
    CONSTRAINT [FK_Parametro_Importacao_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda])
);

