CREATE TABLE [dbo].[Parametro_Comissao_Empresa] (
    [cd_empresa]                    INT        NOT NULL,
    [cd_aplicacao_markup]           INT        NULL,
    [cd_usuario]                    INT        NULL,
    [dt_usuario]                    DATETIME   NULL,
    [ic_descontar_frete]            CHAR (1)   NULL,
    [ic_pagamento_duplicata]        CHAR (1)   NULL,
    [ic_categoria_comissao]         CHAR (1)   NULL,
    [ic_estrutura_comissao]         CHAR (1)   NULL,
    [cd_lancamento_padrao]          INT        NULL,
    [ic_descontar_embalagem]        CHAR (1)   NULL,
    [ic_sempre_descontar_custofin]  CHAR (1)   NULL,
    [ic_local_frete]                CHAR (1)   NULL,
    [cd_tipo_documento]             INT        NULL,
    [cd_tipo_conta_pagar]           INT        NULL,
    [qt_dia_pagamento_comissao]     FLOAT (53) NULL,
    [ic_tipo_preco_comissao]        CHAR (1)   NULL,
    [ic_modelo_rel_comissao]        CHAR (1)   NULL,
    [ic_margem_contribuicao]        CHAR (1)   NULL,
    [cd_aplicacao_markup_base_calc] INT        NULL,
    [cd_plano_financeiro]           INT        NULL,
    [vl_arredondamento_comissao]    FLOAT (53) NULL,
    [ic_visita_comissao]            CHAR (1)   NULL,
    [qt_mes_visita_comissao]        FLOAT (53) NULL,
    [qt_dia_visita_comissao]        FLOAT (53) NULL,
    [ic_deducao_zona_franca]        CHAR (1)   NULL,
    [ic_movimento_caixa_comissao]   CHAR (1)   NULL,
    [pc_comissao_empresa]           FLOAT (53) NULL,
    [ic_atualiza_preco_custo]       CHAR (1)   NULL,
    [ic_deducao_icms_comissao]      CHAR (1)   NULL,
    [ic_deducao_ipi_comissao]       CHAR (1)   NULL,
    [ic_icms_zona_franca]           CHAR (1)   NULL,
    CONSTRAINT [PK_Parametro_Comissao_Empresa] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Comissao_Empresa_Aplicacao_Markup] FOREIGN KEY ([cd_aplicacao_markup]) REFERENCES [dbo].[Aplicacao_Markup] ([cd_aplicacao_markup]),
    CONSTRAINT [FK_Parametro_Comissao_Empresa_Lancamento_Padrao] FOREIGN KEY ([cd_lancamento_padrao]) REFERENCES [dbo].[Lancamento_Padrao] ([cd_lancamento_padrao]),
    CONSTRAINT [FK_Parametro_Comissao_Empresa_Tipo_Conta_Pagar] FOREIGN KEY ([cd_tipo_conta_pagar]) REFERENCES [dbo].[Tipo_Conta_Pagar] ([cd_tipo_conta_pagar]),
    CONSTRAINT [FK_Parametro_Comissao_Empresa_Tipo_Documento] FOREIGN KEY ([cd_tipo_documento]) REFERENCES [dbo].[Tipo_Documento] ([cd_tipo_documento])
);

