CREATE TABLE [dbo].[Parametro_Logistica] (
    [dt_usuario]                  DATETIME      NULL,
    [cd_usuario]                  INT           NULL,
    [cd_empresa]                  INT           NOT NULL,
    [qt_dia_max_nota_empresa]     INT           NULL,
    [ic_tipo_endereco_minuta]     CHAR (1)      NULL,
    [ic_cnpj_entrada_empresa]     CHAR (1)      NULL,
    [ic_inspecao_empresa]         CHAR (1)      NULL,
    [cd_usuario_guia_trafego]     INT           NULL,
    [ic_estoque_nota_entrada]     CHAR (1)      NULL,
    [nm_porta_impressao_nota]     VARCHAR (100) NULL,
    [cd_tipo_codigo_barra]        INT           NULL,
    [cd_obs_padrao_devolucao]     INT           NULL,
    [ic_gerar_pedido_compra]      CHAR (1)      NULL,
    [cd_ultima_ordem_estocagem]   INT           NULL,
    [nm_especie_padrao_nfe]       VARCHAR (5)   NULL,
    [cd_lancamento_padrao_irrf]   INT           NULL,
    [cd_lancamento_padrao_inss]   INT           NULL,
    [ic_custo_produto_entrada]    CHAR (1)      NULL,
    [pc_inss_entrada]             FLOAT (53)    NULL,
    [ic_sempre_liberar_aliq]      CHAR (1)      NULL,
    [ic_bloq_ident_parcela]       CHAR (1)      NULL,
    [ic_imposto_scp_automatico]   CHAR (1)      NULL,
    [dt_imposto_scp_automatico]   DATETIME      NULL,
    [ic_receb_pc_sem_liberar]     CHAR (1)      NULL,
    [ic_atualiza_custo_formula]   CHAR (1)      NULL,
    [cd_lancamento_padrao_iss]    INT           NULL,
    [cd_lancamento_padrao_pis]    INT           NULL,
    [cd_lancamento_padrao_cofins] INT           NULL,
    [cd_lancamento_padrao_csll]   INT           NULL,
    [ic_altera_plano_financeiro]  CHAR (1)      NULL,
    [qt_tolerancia_quantidade]    FLOAT (53)    NULL,
    [qt_dia_valida_necessidade]   INT           NULL,
    [ic_altera_classif_conta]     CHAR (1)      NULL,
    [ic_minuta_tipo_emissao]      CHAR (1)      NULL,
    [ic_devolucao_recebimento]    CHAR (1)      NULL,
    [ic_bloqueio_pc_liberacao]    CHAR (1)      NULL,
    [cd_plano_financeiro]         INT           NULL,
    [cd_modelo_ordem_receb]       INT           NULL,
    [ic_data_geracao_scp]         CHAR (1)      NULL,
    [nm_titulo_ordem_receb]       VARCHAR (100) NULL,
    CONSTRAINT [PK_Parametro_Logistica] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90)
);

