CREATE TABLE [dbo].[Parametro_Estoque] (
    [cd_empresa]                   INT      NOT NULL,
    [ic_estoque_lote_empresa]      CHAR (1) NULL,
    [cd_usuario]                   INT      NULL,
    [dt_usuario]                   DATETIME NULL,
    [ic_pesquisa_padrao_prod]      CHAR (1) NULL,
    [ic_baixa_estoque_negativo]    CHAR (1) NULL,
    [ic_atualiza_peps_entrada]     CHAR (1) NULL,
    [ic_baixa_composicao]          CHAR (1) NULL,
    [ic_edicao_analise_consumo]    CHAR (1) NULL,
    [ic_mostrar_mes_atual]         CHAR (1) NULL,
    [ic_ordem_prod_evol_consumo]   CHAR (1) NULL,
    [ic_nserie_ord_sep_empresa]    CHAR (1) NULL,
    [ic_lote_ord_sep_empresa]      CHAR (1) NULL,
    [ic_reposicao_estoque_min]     CHAR (1) NULL,
    [ic_producao_lote_fab]         CHAR (1) NULL,
    [ic_previsao_evolucao_consumo] CHAR (1) NULL,
    [ic_perfil_cliente_ordem]      CHAR (1) NULL,
    [cd_modelo_ord_sep]            INT      NULL,
    [ic_modelo_ord_sep]            CHAR (1) NULL,
    [ic_devolucao_estoque]         CHAR (1) NULL,
    [ic_visualiza_movto_lote]      CHAR (1) NULL,
    [ic_lote_inspecao]             CHAR (1) NULL,
    [ic_custo_entrada_manual]      CHAR (1) NULL,
    [cd_fase_produto_entreposto]   INT      NULL,
    [ic_modelo_etiqueta_sedex]     CHAR (1) NULL,
    [ic_modelo_etiqueta_emb]       CHAR (1) NULL,
    [ic_ajuste_composicao_produto] CHAR (1) NULL,
    [ic_tipo_saldo_minimo]         CHAR (1) NULL,
    [ic_alocacao_estoque_reserva]  CHAR (1) NULL,
    [ic_liberacao_separacao]       CHAR (1) NULL,
    [ic_composicao_separacao]      CHAR (1) NULL,
    CONSTRAINT [PK_Parametro_Estoque] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Parametro_Estoque_Fase_Produto] FOREIGN KEY ([cd_fase_produto_entreposto]) REFERENCES [dbo].[Fase_Produto] ([cd_fase_produto])
);

