CREATE TABLE [dbo].[Pedido_Compra_Item] (
    [cd_pedido_compra]            INT          NOT NULL,
    [cd_item_pedido_compra]       INT          NOT NULL,
    [cd_medida_retifica]          INT          NULL,
    [nm_medacab_mat_prima]        VARCHAR (30) NULL,
    [nm_medbruta_mat_prima]       VARCHAR (30) NULL,
    [cd_requisicao_compra_item]   INT          NULL,
    [cd_requisicao_compra]        INT          NULL,
    [ds_item_prodesp_ped_compr]   TEXT         NULL,
    [dt_item_pedido_compra]       DATETIME     NULL,
    [qt_item_pedido_compra]       FLOAT (53)   NULL,
    [qt_saldo_item_ped_compra]    FLOAT (53)   NULL,
    [dt_entrega_item_ped_compr]   DATETIME     NULL,
    [vl_custo_item_ped_compra]    FLOAT (53)   NULL,
    [vl_item_unitario_ped_comp]   FLOAT (53)   NULL,
    [ds_item_pedido_compra]       TEXT         NULL,
    [pc_item_descto_ped_compra]   FLOAT (53)   NULL,
    [cd_produto]                  INT          NULL,
    [cd_servico]                  INT          NULL,
    [cd_plano_compra]             INT          NULL,
    [cd_categoria_produto]        INT          NULL,
    [cd_ocorrencia]               INT          NULL,
    [cd_cotacao]                  INT          NULL,
    [cd_item_cotacao]             INT          NULL,
    [dt_item_nec_ped_compra]      DATETIME     NULL,
    [vl_cambio_item_ped_compra]   FLOAT (53)   NULL,
    [dt_item_cambio_ped_compra]   DATETIME     NULL,
    [cd_moeda]                    INT          NULL,
    [dt_item_canc_ped_compra]     DATETIME     NULL,
    [nm_item_motcanc_ped_compr]   VARCHAR (40) NULL,
    [qt_item_pesliq_ped_compra]   FLOAT (53)   NULL,
    [qt_item_pesbr_ped_compra]    FLOAT (53)   NULL,
    [cd_pedido_venda]             INT          NULL,
    [cd_item_pedido_venda]        INT          NULL,
    [qt_item_entrada_ped_compr]   FLOAT (53)   NULL,
    [cd_centro_custo]             INT          NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [nm_item_prodesp_ped_compr]   VARCHAR (40) NULL,
    [cd_unidade_medida]           INT          NULL,
    [nm_item_ativ_ped_compra]     VARCHAR (40) NULL,
    [dt_item_ativ_ped_compra]     DATETIME     NULL,
    [cd_maquina]                  INT          NULL,
    [ic_produto_especial]         CHAR (1)     NULL,
    [ic_pedido_compra_item]       CHAR (1)     NULL,
    [nm_fantasia_produto]         VARCHAR (30) NULL,
    [nm_produto]                  VARCHAR (50) NULL,
    [pc_ipi]                      FLOAT (53)   NULL,
    [qt_dia_entrega_item_ped]     INT          NULL,
    [cd_os_pedido_compra]         VARCHAR (15) NULL,
    [cd_posicao_pedido_compra]    VARCHAR (15) NULL,
    [ds_observacao_fabrica]       TEXT         NULL,
    [nm_marca_item_pedido]        VARCHAR (30) NULL,
    [cd_mascara_produto]          VARCHAR (20) NULL,
    [ds_obs_pedido_compra]        TEXT         NULL,
    [ic_aprov_comprador_pedido]   CHAR (1)     NULL,
    [cd_plano_financeiro]         INT          NULL,
    [cd_materia_prima]            INT          NULL,
    [cd_mascara_classificacao]    CHAR (10)    NULL,
    [cd_classificacao_fiscal]     INT          NULL,
    [pc_icms]                     FLOAT (53)   NULL,
    [pc_red_icms]                 FLOAT (53)   NULL,
    [vl_total_item_pedido_comp]   FLOAT (53)   NULL,
    [nm_placa]                    VARCHAR (18) NULL,
    [qt_espesbruta_Mat_prima]     FLOAT (53)   NULL,
    [qt_largbruta_Mat_prima]      FLOAT (53)   NULL,
    [qt_compbruta_Mat_prima]      FLOAT (53)   NULL,
    [ic_redondo_Mat_prima]        CHAR (1)     NULL,
    [cd_tipo_placa]               INT          NULL,
    [qt_espesacab_mat_prima]      FLOAT (53)   NULL,
    [qt_largacab_mat_prima]       FLOAT (53)   NULL,
    [qt_compacab_mat_prima]       FLOAT (53)   NULL,
    [qt_tolespesacab_mat_prima]   FLOAT (53)   NULL,
    [qt_tolcompacab_mat_prima]    FLOAT (53)   NULL,
    [vl_fornecedor_moeda]         FLOAT (53)   NULL,
    [vl_convertido_moeda]         FLOAT (53)   NULL,
    [cd_veiculo]                  INT          NULL,
    [ic_fluxo_caixa]              CHAR (1)     NULL,
    [dt_fluxo_caixa]              DATETIME     NULL,
    [dt_zera_saldo_pedido_item]   DATETIME     NULL,
    [cd_desenho_item_pedido]      VARCHAR (30) NULL,
    [cd_rev_des_item_pedido]      VARCHAR (5)  NULL,
    [qt_area_produto]             FLOAT (53)   NULL,
    [cd_lote_item_pedido]         VARCHAR (25) NULL,
    [cd_contrato_compra]          INT          NULL,
    [vl_ipi_item_pedido_compra]   FLOAT (53)   NULL,
    [vl_icms_item_pedido_compra]  FLOAT (53)   NULL,
    [vl_unitario_ipi_produto]     FLOAT (53)   NULL,
    [ic_item_bonificacao]         CHAR (1)     NULL,
    [ic_ordrec_pedido_compra]     CHAR (1)     NULL,
    [cd_produto_servico]          INT          NULL,
    [vl_frete_item_pedido_compra] FLOAT (53)   NULL,
    [vl_bc_icms_st]               FLOAT (53)   NULL,
    [vl_item_icms_st]             FLOAT (53)   NULL,
    [vl_desconto_item_pedido]     FLOAT (53)   NULL,
    CONSTRAINT [PK_Pedido_Compra_Item] PRIMARY KEY CLUSTERED ([cd_pedido_compra] ASC, [cd_item_pedido_compra] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [ix_cd_pedido_venda]
    ON [dbo].[Pedido_Compra_Item]([cd_pedido_venda] ASC, [cd_item_pedido_venda] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_Pedido_Compra_Item_Cotacao]
    ON [dbo].[Pedido_Compra_Item]([cd_cotacao] ASC, [dt_item_nec_ped_compra] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_Pedido_Compra_Item_Produto]
    ON [dbo].[Pedido_Compra_Item]([cd_produto] ASC) WITH (FILLFACTOR = 90);

