CREATE TABLE [dbo].[Pedido_Importacao_Item] (
    [cd_pedido_importacao]      INT           NOT NULL,
    [cd_item_ped_imp]           INT           NOT NULL,
    [cd_produto]                INT           NULL,
    [qt_item_ped_imp]           FLOAT (53)    NULL,
    [vl_item_ped_imp]           FLOAT (53)    NULL,
    [qt_pesliq_item_ped_imp]    FLOAT (53)    NULL,
    [qt_pesbruto_item_ped_imp]  FLOAT (53)    NULL,
    [cd_tipo_embalagem]         INT           NULL,
    [qt_emb_item_ped_imp]       FLOAT (53)    NULL,
    [cd_fabricante]             INT           NULL,
    [nm_ordem_compra_ped_imp]   VARCHAR (40)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [pc_desc_item_ped_imp]      FLOAT (53)    NULL,
    [nm_item_obs_ped_imp]       VARCHAR (100) NULL,
    [dt_entrega_ped_imp]        DATETIME      NULL,
    [qt_real_item_ped_imp]      FLOAT (53)    NULL,
    [pc_iimp_ped_imp]           FLOAT (53)    NULL,
    [vl_moeda_ped_imp]          FLOAT (53)    NULL,
    [vl_produto_ped_imp]        FLOAT (53)    NULL,
    [cd_pedido_venda]           INT           NULL,
    [cd_item_pedido_venda]      INT           NULL,
    [qt_saldo_item_ped_imp]     FLOAT (53)    NULL,
    [dt_prev_embarque_ped_imp]  DATETIME      NULL,
    [dt_cancel_item_ped_imp]    DATETIME      NULL,
    [cd_motivo_cancel_pedido]   INT           NULL,
    [nm_motivo_cancel_item_ped] VARCHAR (40)  NULL,
    [cd_pedido_compra]          INT           NULL,
    [cd_item_pedido_compra]     INT           NULL,
    [dt_moeda_ped_importacao]   DATETIME      NULL,
    [nm_produto_pedido]         VARCHAR (50)  NULL,
    [nm_fantasia_produto]       VARCHAR (30)  NULL,
    [qt_dia_entrega_ped_imp]    INT           NULL,
    [dt_fechamento_ped_imp]     DATETIME      NULL,
    [cd_unidade_medida]         INT           NULL,
    [nm_marca_item_ped_imp]     VARCHAR (30)  NULL,
    [cd_item_requisicao_compra] INT           NULL,
    [cd_requisicao_compra]      INT           NULL,
    [nm_motivo_ativ_item_ped]   VARCHAR (40)  NULL,
    [dt_ativ_item_ped_imp]      DATETIME      NULL,
    [cd_motivo_ativacao_pedido] INT           NULL,
    [qt_dia_embarque_ped_imp]   INT           NULL,
    CONSTRAINT [PK_Pedido_Importacao_Item] PRIMARY KEY CLUSTERED ([cd_pedido_importacao] ASC, [cd_item_ped_imp] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Pedido_Importacao_Item_Motivo_Ativacao_Pedido] FOREIGN KEY ([cd_motivo_ativacao_pedido]) REFERENCES [dbo].[Motivo_Ativacao_Pedido] ([cd_motivo_ativacao_pedido])
);

