CREATE TABLE [dbo].[Pedido_Venda_Exportacao] (
    [cd_pedido_venda]             INT          NULL,
    [cd_origem_pais]              INT          NULL,
    [cd_destino_pais]             INT          NULL,
    [cd_tipo_importacao]          INT          NULL,
    [cd_idioma]                   INT          NULL,
    [cd_despachante]              INT          NULL,
    [cd_porto_origem]             INT          NULL,
    [cd_porto_destino]            INT          NULL,
    [nm_emb_ped_venda]            VARCHAR (40) NULL,
    [cd_transitorio]              INT          NULL,
    [dt_prev_emb_ped_venda]       DATETIME     NULL,
    [cd_tipo_embalagem]           INT          NULL,
    [cd_termo_comercial]          INT          NULL,
    [cd_instrumento_negociacao]   INT          NULL,
    [cd_despesa_padrao_comex]     INT          NULL,
    [cd_notify]                   INT          NULL,
    [cd_seguradora]               INT          NULL,
    [cd_tipo_seguro]              INT          NULL,
    [nm_seg_prov_ped_venda]       VARCHAR (30) NULL,
    [cd_seguro_moeda]             INT          NULL,
    [vl_seguro_int_pedido_venda]  FLOAT (53)   NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [nm_responsavel]              VARCHAR (25) NULL,
    [nm_numero_carta_credito]     VARCHAR (25) NULL,
    [dt_vencimento_carta_credito] DATETIME     NULL,
    [cd_modalidade_pagamento]     INT          NULL,
    [nm_destino_final]            VARCHAR (40) NULL,
    [cd_consignatario]            INT          NULL,
    [cd_prestador_servico]        INT          NULL,
    [cd_enquadro_exportacao]      INT          NULL,
    [nm_licenca_importacao]       VARCHAR (20) NULL,
    [nm_marca_numero]             VARCHAR (40) NULL,
    [qt_peso_net]                 FLOAT (53)   NULL,
    [vl_outras_despesas]          FLOAT (53)   NULL,
    [qt_metragem_cubica]          FLOAT (53)   NULL,
    [cd_banco]                    INT          NULL,
    [ds_texto]                    TEXT         NULL,
    [dt_exp_embarque]             DATETIME     NULL,
    [dt_exp_negoc]                DATETIME     NULL,
    [nm_carta_triangular]         VARCHAR (25) NULL,
    [dt_emissao_carta_credito]    DATETIME     NULL,
    [vl_desp_frete_emb]           FLOAT (53)   NULL,
    [cd_tipo_transporte]          INT          NULL,
    [cd_moeda_frete]              INT          NULL,
    [cd_representante_com_ext]    INT          NULL,
    [cd_tipo_pag_comissao]        INT          NULL,
    [nm_proforma_invoice]         VARCHAR (30) NULL,
    [cd_tipo_container]           INT          NULL,
    [cd_contato_exportador]       INT          NULL,
    [ic_frete_prop_exportacao]    CHAR (1)     NULL,
    [ic_seguro_prop_exportacao]   CHAR (1)     NULL,
    [cd_aux_termo_comercial]      INT          NULL,
    CONSTRAINT [FK_Pedido_Venda_Exportacao_Representante_Com_Exterior] FOREIGN KEY ([cd_representante_com_ext]) REFERENCES [dbo].[Representante_Com_Exterior] ([cd_representante_com_ext]),
    CONSTRAINT [FK_Pedido_Venda_Exportacao_Tipo_Container] FOREIGN KEY ([cd_tipo_container]) REFERENCES [dbo].[Tipo_Container] ([cd_tipo_container]),
    CONSTRAINT [FK_Pedido_Venda_Exportacao_Tipo_Pagamento_Comissao] FOREIGN KEY ([cd_tipo_pag_comissao]) REFERENCES [dbo].[Tipo_Pagamento_Comissao] ([cd_tipo_pag_comissao])
);

