CREATE TABLE [dbo].[Pedido_Venda_Item] (
    [cd_pedido_venda]           INT          NOT NULL,
    [cd_item_pedido_venda]      INT          NOT NULL,
    [dt_item_pedido_venda]      DATETIME     NULL,
    [qt_item_pedido_venda]      FLOAT (53)   NULL,
    [qt_saldo_pedido_venda]     FLOAT (53)   NULL,
    [dt_entrega_vendas_pedido]  DATETIME     NULL,
    [dt_entrega_fabrica_pedido] DATETIME     NULL,
    [ds_produto_pedido_venda]   TEXT         NULL,
    [vl_unitario_item_pedido]   FLOAT (53)   NULL,
    [vl_lista_item_pedido]      FLOAT (53)   NULL,
    [pc_desconto_item_pedido]   FLOAT (53)   NULL,
    [dt_cancelamento_item]      DATETIME     NULL,
    [dt_estoque_item_pedido]    DATETIME     NULL,
    [cd_pdcompra_item_pedido]   VARCHAR (40) NULL,
    [dt_reprog_item_pedido]     DATETIME     NULL,
    [qt_liquido_item_pedido]    FLOAT (53)   NULL,
    [qt_bruto_item_pedido]      FLOAT (53)   NULL,
    [ic_fatura_item_pedido]     CHAR (1)     NULL,
    [ic_reserva_item_pedido]    CHAR (1)     NULL,
    [ic_tipo_montagem_item]     CHAR (1)     NULL,
    [ic_montagem_g_item_pedido] CHAR (1)     NULL,
    [ic_subs_tributaria_item]   CHAR (1)     NULL,
    [cd_posicao_item_pedido]    VARCHAR (15) NULL,
    [cd_os_tipo_pedido_venda]   VARCHAR (15) NULL,
    [ic_desconto_item_pedido]   CHAR (1)     NULL,
    [dt_desconto_item_pedido]   DATETIME     NULL,
    [vl_indice_item_pedido]     FLOAT (53)   NULL,
    [cd_grupo_produto]          INT          NULL,
    [cd_produto]                INT          NULL,
    [cd_grupo_categoria]        INT          NULL,
    [cd_categoria_produto]      INT          NULL,
    [cd_pedido_rep_pedido]      INT          NULL,
    [cd_item_pedidorep_pedido]  INT          NULL,
    [cd_ocorrencia]             INT          NULL,
    [cd_consulta]               INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [nm_mot_canc_item_pedido]   VARCHAR (60) NULL,
    [nm_obs_restricao_pedido]   VARCHAR (40) NULL,
    [cd_item_consulta]          INT          NULL,
    [ic_etiqueta_emb_pedido]    CHAR (1)     NULL,
    [pc_ipi_item]               FLOAT (53)   NULL,
    [pc_icms_item]              FLOAT (53)   NULL,
    [pc_reducao_base_item]      FLOAT (53)   NULL,
    [dt_necessidade_cliente]    DATETIME     NULL,
    [qt_dia_entrega_cliente]    INT          NULL,
    [dt_entrega_cliente]        DATETIME     NULL,
    [ic_smo_item_pedido_venda]  CHAR (1)     NULL,
    [cd_om]                     INT          NULL,
    [ic_controle_pcp_pedido]    CHAR (1)     NULL,
    [nm_mat_canc_item_pedido]   VARCHAR (40) NULL,
    [cd_servico]                INT          NULL,
    [ic_produto_especial]       CHAR (1)     NULL,
    [cd_produto_concorrente]    VARCHAR (30) NULL,
    [ic_orcamento_pedido_venda] CHAR (1)     NULL,
    [ds_produto_pedido]         TEXT         NULL,
    [nm_produto_pedido]         VARCHAR (50) NULL,
    [cd_serie_produto]          INT          NULL,
    [pc_ipi]                    FLOAT (53)   NULL,
    [pc_icms]                   FLOAT (53)   NULL,
    [qt_dia_entrega_pedido]     FLOAT (53)   NULL,
    [ic_sel_fechamento]         CHAR (1)     NULL,
    [dt_ativacao_item]          DATETIME     NULL,
    [nm_mot_ativ_item_pedido]   VARCHAR (60) NULL,
    [nm_fantasia_produto]       VARCHAR (30) NULL,
    [ic_etiqueta_emb_ped_venda] CHAR (1)     NULL,
    [dt_fechamento_pedido]      DATETIME     NULL,
    [ds_progfat_pedido_venda]   TEXT         NULL,
    [ic_pedido_venda_item]      CHAR (1)     NULL,
    [ic_ordsep_pedido_venda]    CHAR (1)     NULL,
    [ic_progfat_item_pedido]    CHAR (1)     NULL,
    [qt_progfat_item_pedido]    FLOAT (53)   NULL,
    [cd_referencia_produto]     INT          NULL,
    [ic_libpcp_item_pedido]     CHAR (1)     NULL,
    [ds_observacao_fabrica]     TEXT         NULL,
    [nm_observacao_fabrica1]    VARCHAR (40) NULL,
    [nm_observacao_fabrica2]    VARCHAR (40) NULL,
    [cd_unidade_medida]         INT          NULL,
    [pc_reducao_icms]           FLOAT (53)   NULL,
    [pc_desconto_sobre_desc]    FLOAT (53)   NULL,
    [nm_desconto_item_pedido]   VARCHAR (40) NULL,
    [cd_item_contrato]          INT          NULL,
    [cd_contrato_fornecimento]  INT          NULL,
    [nm_kardex_item_ped_venda]  VARCHAR (30) NULL,
    [ic_gprgcnc_pedido_venda]   CHAR (1)     NULL,
    [cd_pedido_importacao]      INT          NULL,
    [cd_item_pedido_importacao] INT          NULL,
    [dt_progfat_item_pedido]    DATETIME     NULL,
    [qt_cancelado_item_pedido]  FLOAT (53)   NULL,
    [qt_ativado_pedido_venda]   FLOAT (53)   NULL,
    [cd_mes]                    INT          NULL,
    [cd_ano]                    INT          NULL,
    [ic_mp66_item_pedido]       CHAR (1)     NULL,
    [ic_montagem_item_pedido]   CHAR (1)     NULL,
    [ic_reserva_estrutura_item] CHAR (1)     NULL,
    [ic_estrutura_item_pedido]  CHAR (1)     NULL,
    [vl_frete_item_pedido]      FLOAT (53)   NULL,
    [cd_usuario_lib_desconto]   INT          NULL,
    [dt_moeda_cotacao]          DATETIME     NULL,
    [vl_moeda_cotacao]          FLOAT (53)   NULL,
    [cd_moeda_cotacao]          INT          NULL,
    [dt_zera_saldo_pedido_item] DATETIME     NULL,
    [cd_lote_produto]           INT          NULL,
    [cd_num_serie_item_pedido]  VARCHAR (30) NULL,
    [cd_lote_item_pedido]       VARCHAR (25) NULL,
    [ic_controle_mapa_pedido]   CHAR (1)     NULL,
    [cd_tipo_embalagem]         INT          NULL,
    [dt_validade_item_pedido]   DATETIME     NULL,
    [cd_movimento_caixa]        INT          NULL,
    [vl_custo_financ_item]      FLOAT (53)   NULL,
    [qt_garantia_item_pedido]   INT          NULL,
    [cd_tipo_montagem]          INT          NULL,
    [cd_montagem]               INT          NULL,
    [cd_usuario_ordsep]         INT          NULL,
    [ic_kit_grupo_produto]      CHAR (1)     NULL,
    [cd_sub_produto_especial]   INT          NULL,
    [cd_plano_financeiro]       INT          NULL,
    [dt_fluxo_caixa]            DATETIME     NULL,
    [ic_fluxo_caixa]            CHAR (1)     NULL,
    [ds_servico_item_pedido]    TEXT         NULL,
    [dt_reservado_montagem]     DATETIME     NULL,
    [cd_usuario_montagem]       INT          NULL,
    [ic_imediato_produto]       CHAR (1)     NULL,
    [cd_mascara_classificacao]  CHAR (10)    NULL,
    [cd_desenho_item_pedido]    VARCHAR (30) NULL,
    [cd_rev_des_item_pedido]    VARCHAR (5)  NULL,
    [cd_centro_custo]           INT          NULL,
    [qt_area_produto]           FLOAT (53)   NULL,
    [cd_produto_estampo]        INT          NULL,
    [vl_digitado_item_desconto] FLOAT (53)   NULL,
    [cd_lote_Item_anterior]     VARCHAR (25) NULL,
    [cd_programacao_entrega]    INT          NULL,
    [ic_estoque_fatura]         CHAR (1)     NULL,
    [ic_estoque_venda]          CHAR (1)     NULL,
    [ic_manut_mapa_producao]    CHAR (1)     NULL,
    [pc_comissao_item_pedido]   FLOAT (53)   NULL,
    [cd_produto_servico]        INT          NULL,
    [ic_baixa_composicao_item]  CHAR (1)     NULL,
    [vl_unitario_ipi_produto]   FLOAT (53)   NULL,
    [ic_desc_prom_item_pedido]  CHAR (1)     NULL,
    [cd_tabela_preco]           INT          NULL,
    [cd_motivo_reprogramacao]   INT          NULL,
    [qt_estoque]                FLOAT (53)   NULL,
    [dt_estoque]                DATETIME     NULL,
    [dt_atendimento]            DATETIME     NULL,
    [qt_atendimento]            FLOAT (53)   NULL,
    [nm_forma]                  VARCHAR (10) NULL,
    [cd_documento]              INT          NULL,
    [cd_item_documento]         INT          NULL,
    [nm_obs_atendimento]        VARCHAR (60) NULL,
    [qt_atendimento_1]          FLOAT (53)   NULL,
    [qt_atendimento_2]          FLOAT (53)   NULL,
    [qt_atendimento_3]          FLOAT (53)   NULL,
    [vl_bc_icms_st]             FLOAT (53)   NULL,
    [vl_item_icms_st]           FLOAT (53)   NULL,
    [ic_sel_mrp_item_pedido]    CHAR (1)     NULL,
    CONSTRAINT [PK_Pedido_Venda_Item] PRIMARY KEY CLUSTERED ([cd_pedido_venda] ASC, [cd_item_pedido_venda] ASC) WITH (FILLFACTOR = 90)
);


GO
CREATE NONCLUSTERED INDEX [ix_dt_entrega_vendas_pedido]
    ON [dbo].[Pedido_Venda_Item]([dt_entrega_vendas_pedido] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [ix_dt_cancelamento_item]
    ON [dbo].[Pedido_Venda_Item]([dt_cancelamento_item] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [ix_cd_consulta]
    ON [dbo].[Pedido_Venda_Item]([cd_consulta] ASC, [cd_item_consulta] ASC) WITH (FILLFACTOR = 90);

