CREATE TABLE [dbo].[Pedido_Venda_Nextel] (
    [cd_pedido_venda]             INT          NULL,
    [cd_cliente]                  INT          NULL,
    [cd_vendedor]                 INT          NULL,
    [cd_nota_saida]               VARCHAR (20) NULL,
    [dt_pedido_venda_nextel]      DATETIME     NULL,
    [qt_dia_pagamento]            FLOAT (53)   NULL,
    [cd_status_pedido_nextel]     INT          NULL,
    [cd_produto]                  INT          NULL,
    [qt_item_pedido_venda_nextel] FLOAT (53)   NULL,
    [vl_item_total_pedido]        FLOAT (53)   NULL,
    [cd_tabela_preco]             INT          NULL,
    [qt_itens_pedido_venda]       FLOAT (53)   NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [cd_item_pedido_venda]        INT          NULL,
    [ic_gerado_pedido_venda]      CHAR (1)     NULL,
    [cd_condicao_pagamento]       INT          NULL,
    [cd_controle]                 INT          NULL,
    [cd_vendedor_interno]         INT          NULL,
    [dt_entrega_pedido]           DATETIME     NULL,
    [cd_destinacao_produto]       INT          NULL,
    [qt_saldo_produto]            FLOAT (53)   NULL,
    [cd_tabela_preco_padrao]      INT          NULL,
    [vl_saldo_cliente]            FLOAT (53)   NULL,
    [cd_condicao_pedido]          INT          NULL,
    [qt_estoque_produto]          FLOAT (53)   NULL,
    [cd_unidade_medida]           INT          NULL
);

