CREATE TABLE [dbo].[Pedido_Importacao_smc] (
    [ID]                INT            NOT NULL,
    [Numero]            INT            NOT NULL,
    [Fornecedor]        INT            NOT NULL,
    [Contato]           INT            NOT NULL,
    [Endereco]          INT            NOT NULL,
    [Moeda]             INT            NOT NULL,
    [Emissao]           DATETIME       NOT NULL,
    [Referencia]        VARCHAR (40)   NOT NULL,
    [CustoFinanceiro]   NUMERIC (7, 4) NOT NULL,
    [Total]             MONEY          NOT NULL,
    [Desconto]          NUMERIC (7, 4) NOT NULL,
    [CondicaoPagamento] CHAR (1)       NOT NULL,
    [Status]            CHAR (1)       NOT NULL,
    [TipoFrete]         CHAR (1)       NOT NULL,
    [Comprador]         CHAR (30)      NOT NULL,
    [Observacao]        TEXT           NULL,
    [EntregaParcial]    CHAR (1)       NOT NULL,
    [ContaFrete]        CHAR (1)       NOT NULL,
    [Notificacao]       VARCHAR (80)   NULL,
    [MarcaEmbalagem]    TEXT           NULL,
    [TermosEmbarque]    CHAR (1)       NOT NULL,
    [Consignado]        VARCHAR (80)   NULL,
    [AtencaoEspecial]   TEXT           NULL,
    [DestinoFrete]      VARCHAR (40)   NULL,
    [Destino]           VARCHAR (40)   NULL,
    [DataEntrega]       DATETIME       NOT NULL,
    [PrazoPagamento]    INT            NOT NULL
);

