CREATE TABLE [dbo].[Pedido_Importacao] (
    [cd_pedido_importacao]          INT          NOT NULL,
    [ds_pedido_importacao]          TEXT         NULL,
    [cd_notify]                     INT          NULL,
    [cd_transitorio]                INT          NULL,
    [vl_taxa_cambio_fechamento]     FLOAT (53)   NULL,
    [dt_pedido_importacao]          DATETIME     NULL,
    [cd_idioma]                     INT          NULL,
    [cd_condicao_pagamento]         INT          NULL,
    [cd_fornecedor]                 INT          NULL,
    [cd_origem_pais]                INT          NULL,
    [cd_destino_pais]               INT          NULL,
    [cd_transportadora]             INT          NULL,
    [cd_instrumento_negociacao]     INT          NULL,
    [nm_emb_ped_imp]                VARCHAR (40) NULL,
    [cd_moeda]                      INT          NULL,
    [cd_termo_comercial]            INT          NULL,
    [dt_prev_emb_ped_imp]           DATETIME     NULL,
    [dt_abertuta_ped_imp]           DATETIME     NULL,
    [ic_cobertura_cambial]          CHAR (1)     NULL,
    [ic_entrepostagem_pedido]       CHAR (1)     NULL,
    [cd_conta_banco]                INT          NULL,
    [nm_ordem_compra_pedido]        VARCHAR (20) NULL,
    [cd_usuario]                    INT          NULL,
    [dt_usuario]                    DATETIME     NULL,
    [cd_comprador]                  INT          NULL,
    [cd_importador]                 INT          NULL,
    [cd_despachante]                INT          NULL,
    [cd_fabricante]                 INT          NULL,
    [cd_consignatario]              INT          NULL,
    [cd_prestador_servico]          INT          NULL,
    [cd_corretora_cambio]           INT          NULL,
    [nm_ref_ped_imp]                VARCHAR (40) NULL,
    [pc_cusfin_ped_imp]             FLOAT (53)   NULL,
    [vl_pedido_importacao]          FLOAT (53)   NULL,
    [dt_entrega_ped_imp]            DATETIME     NULL,
    [cd_forma_entrega]              INT          NULL,
    [qt_pesoliq_ped_imp]            FLOAT (53)   NULL,
    [qt_pesobru_ped_imp]            FLOAT (53)   NULL,
    [cd_status_pedido]              INT          NULL,
    [dt_canc_pedido_importacao]     DATETIME     NULL,
    [nm_canc_pedido_importacao]     VARCHAR (40) NULL,
    [cd_motivo_canc_ped_imp]        INT          NULL,
    [pc_desconto_imp_ped]           FLOAT (53)   NULL,
    [cd_tipo_frete]                 INT          NULL,
    [ds_obs_ped_imp]                TEXT         NULL,
    [cd_porto]                      INT          NULL,
    [ic_conta_frete]                CHAR (1)     NULL,
    [ic_fab_desconhecido]           CHAR (1)     NULL,
    [cd_despesa_padrao_comex]       INT          NULL,
    [cd_contato_fornecedor]         INT          NULL,
    [cd_tipo_pedido]                INT          NULL,
    [dt_alteracao_pedido_imp]       DATETIME     NULL,
    [nm_alteracao_pedido_imp]       VARCHAR (60) NULL,
    [cd_modalidade_pagamento]       INT          NULL,
    [vl_outra_despesa_ped_imp]      FLOAT (53)   NULL,
    [cd_representante_com_ext]      INT          NULL,
    [ic_fax_pedido_importacao]      CHAR (1)     NULL,
    [cd_tipo_embalagem]             INT          NULL,
    [ic_email_pedido_imp]           CHAR (1)     NULL,
    [ic_fechado_ped_importacao]     CHAR (1)     NULL,
    [dt_fechado_ped_importacao]     DATETIME     NULL,
    [cd_porto_origem]               INT          NULL,
    [cd_tipo_importacao]            INT          NULL,
    [nm_local_embarque]             VARCHAR (30) NULL,
    [cd_motivo_canc_mot_ped_imp]    INT          NULL,
    [cd_motivo_canc_mot_pedimp]     INT          NULL,
    [cd_banco]                      INT          NULL,
    [cd_usuario_requisitante]       INT          NULL,
    [dt_ativacao_pedido_importacao] DATETIME     NULL,
    [nm_ativacao_pedido_importacao] VARCHAR (40) NULL,
    [cd_motivo_ativacao_pedido]     INT          NULL,
    [cd_motivo_cancel_pedido]       INT          NULL,
    [cd_pais_procedencia]           INT          NULL,
    [cd_motivo_requisicao]          INT          NULL,
    [cd_tipo_pagamento_frete]       INT          NULL,
    [vl_moeda_ped_imp]              FLOAT (53)   NULL,
    [dt_moeda_ped_imp]              DATETIME     NULL,
    [vl_desp_frete_ped_imp]         FLOAT (53)   NULL,
    [vl_frete_int_ped_imp]          FLOAT (53)   NULL,
    [cd_moeda_frete]                INT          NULL,
    [cd_identificacao_pedido]       VARCHAR (20) NULL,
    [cd_destino_compra]             INT          NULL,
    [cd_motivo_alteracao]           INT          NULL,
    [ic_ident_pedido_compl]         CHAR (5)     NULL,
    [cd_tipo_container]             INT          NULL,
    [cd_tipo_containerx]            INT          NULL,
    [cd_plano_compra]               INT          NULL,
    [cd_licenca_importacao]         VARCHAR (20) NULL,
    [dt_registro_licenca]           DATETIME     NULL,
    [dt_validade_licenca]           DATETIME     NULL,
    [ic_frete_prop_importacao]      CHAR (1)     NULL,
    [ic_seguro_prop_importacao]     CHAR (1)     NULL,
    [cd_aux_termo_comercial]        INT          NULL,
    CONSTRAINT [PK_Pedido_Importacao] PRIMARY KEY CLUSTERED ([cd_pedido_importacao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Pedido_Importacao_Comprador] FOREIGN KEY ([cd_comprador]) REFERENCES [dbo].[Comprador] ([cd_comprador]),
    CONSTRAINT [FK_Pedido_Importacao_Condicao_Pagamento] FOREIGN KEY ([cd_condicao_pagamento]) REFERENCES [dbo].[Condicao_Pagamento] ([cd_condicao_pagamento]),
    CONSTRAINT [FK_Pedido_Importacao_Consignatario] FOREIGN KEY ([cd_consignatario]) REFERENCES [dbo].[Consignatario] ([cd_consignatario]),
    CONSTRAINT [FK_Pedido_Importacao_Corretora_Cambio] FOREIGN KEY ([cd_corretora_cambio]) REFERENCES [dbo].[Corretora_Cambio] ([cd_corretora_cambio]),
    CONSTRAINT [FK_Pedido_Importacao_Despachante] FOREIGN KEY ([cd_despachante]) REFERENCES [dbo].[Despachante] ([cd_despachante]),
    CONSTRAINT [FK_Pedido_Importacao_Despesa_Padrao_comex] FOREIGN KEY ([cd_despesa_padrao_comex]) REFERENCES [dbo].[Despesa_Padrao_comex] ([cd_despesa_padrao_comex]),
    CONSTRAINT [FK_Pedido_Importacao_Fabricante] FOREIGN KEY ([cd_fabricante]) REFERENCES [dbo].[Fabricante] ([cd_fabricante]),
    CONSTRAINT [FK_Pedido_Importacao_Forma_Entrega] FOREIGN KEY ([cd_forma_entrega]) REFERENCES [dbo].[Forma_Entrega] ([cd_forma_entrega]),
    CONSTRAINT [FK_Pedido_Importacao_Fornecedor] FOREIGN KEY ([cd_fornecedor]) REFERENCES [dbo].[Fornecedor] ([cd_fornecedor]),
    CONSTRAINT [FK_Pedido_Importacao_Idioma] FOREIGN KEY ([cd_idioma]) REFERENCES [dbo].[Idioma] ([cd_idioma]),
    CONSTRAINT [FK_Pedido_Importacao_Importador] FOREIGN KEY ([cd_importador]) REFERENCES [dbo].[Importador] ([cd_importador]),
    CONSTRAINT [FK_Pedido_Importacao_Instrumento_Negociacao] FOREIGN KEY ([cd_instrumento_negociacao]) REFERENCES [dbo].[Instrumento_Negociacao] ([cd_instrumento_negociacao]),
    CONSTRAINT [FK_Pedido_Importacao_Modalidade_Pagamento] FOREIGN KEY ([cd_modalidade_pagamento]) REFERENCES [dbo].[Modalidade_Pagamento] ([cd_modalidade_pagamento]),
    CONSTRAINT [FK_Pedido_Importacao_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda]),
    CONSTRAINT [FK_Pedido_Importacao_Motivo_Cancelamento_Pedido] FOREIGN KEY ([cd_motivo_canc_ped_imp]) REFERENCES [dbo].[Motivo_Cancelamento_Pedido] ([cd_motivo_cancel_pedido]),
    CONSTRAINT [FK_Pedido_Importacao_Motivo_Requisicao] FOREIGN KEY ([cd_motivo_requisicao]) REFERENCES [dbo].[Motivo_Requisicao] ([cd_motivo_requisicao]),
    CONSTRAINT [FK_Pedido_Importacao_Origem_Pais] FOREIGN KEY ([cd_origem_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Pedido_Importacao_Pais] FOREIGN KEY ([cd_destino_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Pedido_Importacao_Plano_Compra] FOREIGN KEY ([cd_plano_compra]) REFERENCES [dbo].[Plano_Compra] ([cd_plano_compra]),
    CONSTRAINT [FK_Pedido_Importacao_Tipo_Embalagem] FOREIGN KEY ([cd_tipo_embalagem]) REFERENCES [dbo].[Tipo_Embalagem] ([cd_tipo_embalagem]),
    CONSTRAINT [FK_Pedido_Importacao_Tipo_Frete] FOREIGN KEY ([cd_tipo_frete]) REFERENCES [dbo].[Tipo_Frete] ([cd_tipo_frete]),
    CONSTRAINT [FK_Pedido_Importacao_Tipo_Importacao] FOREIGN KEY ([cd_tipo_importacao]) REFERENCES [dbo].[Tipo_Importacao] ([cd_tipo_importacao]),
    CONSTRAINT [FK_Pedido_Importacao_Transitorio] FOREIGN KEY ([cd_transitorio]) REFERENCES [dbo].[Transportadora] ([cd_transportadora]),
    CONSTRAINT [FK_Pedido_Importacao_Transportadora] FOREIGN KEY ([cd_transportadora]) REFERENCES [dbo].[Transportadora] ([cd_transportadora])
);

