CREATE TABLE [dbo].[Plano_Compra] (
    [cd_plano_compra]           INT          NOT NULL,
    [cd_grupo_compra]           INT          NULL,
    [cd_mascara_plano_compra]   VARCHAR (20) NULL,
    [nm_plano_compra]           VARCHAR (40) NULL,
    [sg_plano_compra]           CHAR (10)    NULL,
    [ic_mapa_plano_compra]      CHAR (1)     NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_tipo_conta_pagar]       INT          NULL,
    [cd_categoria_produto]      INT          NULL,
    [cd_plano_compra_pai]       INT          NULL,
    [vl_limite_plano_compra]    FLOAT (53)   NULL,
    [cd_grupo_categoria]        INT          NULL,
    [ic_ativo_plano_compra]     CHAR (1)     NULL,
    [ic_mp_plano_compra]        CHAR (1)     NULL,
    [ic_lancamento_plano]       CHAR (1)     NULL,
    [cd_plano_financeiro]       INT          NULL,
    [ic_indicador_plano_compra] CHAR (1)     NULL,
    [cd_destinacao_produto]     INT          NULL,
    [cd_tipo_produto_espessura] INT          NULL,
    [cd_tipo_requisicao]        INT          NULL,
    [cd_aplicacao_produto]      INT          NULL,
    CONSTRAINT [PK_Plano_Compra] PRIMARY KEY CLUSTERED ([cd_plano_compra] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Plano_Compra_Aplicacao_Produto] FOREIGN KEY ([cd_aplicacao_produto]) REFERENCES [dbo].[Aplicacao_Produto] ([cd_aplicacao_produto]),
    CONSTRAINT [FK_Plano_Compra_Destinacao_Produto] FOREIGN KEY ([cd_destinacao_produto]) REFERENCES [dbo].[Destinacao_Produto] ([cd_destinacao_produto]),
    CONSTRAINT [FK_Plano_Compra_Tipo_Produto_Espessura] FOREIGN KEY ([cd_tipo_produto_espessura]) REFERENCES [dbo].[Tipo_Produto_Espessura] ([cd_tipo_produto_espessura]),
    CONSTRAINT [FK_Plano_Compra_Tipo_Requisicao] FOREIGN KEY ([cd_tipo_requisicao]) REFERENCES [dbo].[Tipo_Requisicao] ([cd_tipo_requisicao])
);

