CREATE TABLE [dbo].[Plano_Financeiro] (
    [cd_plano_financeiro]          INT           NOT NULL,
    [nm_conta_plano_financeiro]    VARCHAR (50)  NULL,
    [sg_conta_plano_financeiro]    CHAR (10)     NULL,
    [cd_mascara_plano_financeiro]  VARCHAR (20)  NULL,
    [nm_rotina_atualizacao]        VARCHAR (100) NULL,
    [cd_grupo_financeiro]          INT           NULL,
    [cd_usuario]                   INT           NULL,
    [dt_usuario]                   DATETIME      NULL,
    [cd_plano_financeiro_pai]      INT           NULL,
    [vl_realizado_financeiro]      FLOAT (53)    NULL,
    [vl_previsto_financeiro]       FLOAT (53)    NULL,
    [ic_conta_analitica]           CHAR (1)      NULL,
    [pc_liq_plano_financeiro]      FLOAT (53)    NULL,
    [cd_centro_custo]              INT           NULL,
    [cd_lancamento_padrao]         INT           NULL,
    [cd_centro_receita]            INT           NULL,
    [ic_fluxo_plano_financeiro]    CHAR (1)      NULL,
    [ic_importcao_plano_fin]       CHAR (1)      NULL,
    [cd_tipo_operacao]             INT           NULL,
    [cd_categoria_financeiro]      INT           NULL,
    [ic_cpv_plano_financeiro]      CHAR (1)      NULL,
    [cd_conta]                     INT           NULL,
    [ic_plano_operacional]         CHAR (1)      NULL,
    [ic_conta_orcamento]           CHAR (1)      NULL,
    [cd_procedimento]              INT           NULL,
    [cd_plano_competence]          VARCHAR (25)  NULL,
    [ic_redutora_plano_financeiro] CHAR (1)      NULL,
    [ic_prod_plano_financeiro]     CHAR (1)      NULL,
    [cd_historico_contabil]        INT           NULL,
    [cd_interface]                 VARCHAR (20)  NULL,
    CONSTRAINT [PK_Plano_Financeiro] PRIMARY KEY CLUSTERED ([cd_plano_financeiro] ASC) WITH (FILLFACTOR = 90)
);

