CREATE TABLE [dbo].[Plano_Controle] (
    [cd_plano_controle]         INT           NOT NULL,
    [dt_plano_controle]         DATETIME      NULL,
    [cd_planta]                 INT           NULL,
    [cd_cliente]                INT           NULL,
    [cd_produto]                INT           NULL,
    [nm_desenho_plano]          VARCHAR (40)  NULL,
    [nm_caminho_desenho]        VARCHAR (100) NULL,
    [dt_desenho_plano]          DATETIME      NULL,
    [nm_revisao_desenho]        VARCHAR (5)   NULL,
    [cd_materia_prima]          INT           NULL,
    [dt_revisao_plano_controle] DATETIME      NULL,
    [nm_aprov_eng_plano]        VARCHAR (50)  NULL,
    [dt_aprov_eng_plano]        DATETIME      NULL,
    [nm_aprov_qualidade_plano]  VARCHAR (50)  NULL,
    [dt_aprov_qualidade_plano]  DATETIME      NULL,
    [nm_aprov_out1_plano]       VARCHAR (50)  NULL,
    [dt_aprov_out1_plano]       DATETIME      NULL,
    [nm_aprov_out2_plano]       VARCHAR (50)  NULL,
    [dt_aprov_out2_plano]       DATETIME      NULL,
    [nm_info_cliente_plano]     VARCHAR (50)  NULL,
    [cd_usuario_plano_controle] INT           NULL,
    [cd_fone_usuario_plano]     VARCHAR (15)  NULL,
    [cd_grupo_plano_controle]   INT           NULL,
    [dt_aprov_plano_controle]   DATETIME      NULL,
    [cd_usuario_aprov_plano]    INT           NULL,
    [nm_obs_plano_controle]     VARCHAR (40)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_processo]               INT           NULL,
    CONSTRAINT [PK_Plano_Controle] PRIMARY KEY CLUSTERED ([cd_plano_controle] ASC) WITH (FILLFACTOR = 90)
);

