CREATE TABLE [dbo].[Prestacao_Conta_Composicao] (
    [cd_prestacao]              INT          NOT NULL,
    [cd_item_prestacao]         INT          NOT NULL,
    [cd_tipo_despesa]           INT          NULL,
    [qt_item_despesa]           FLOAT (53)   NULL,
    [dt_item_despesa]           DATETIME     NULL,
    [vl_item_despesa]           FLOAT (53)   NULL,
    [vl_total_despesa]          FLOAT (53)   NULL,
    [cd_documento_despesa]      VARCHAR (15) NULL,
    [ic_tipo_pagamento_despesa] CHAR (1)     NULL,
    [nm_obs_item_despesa]       VARCHAR (40) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_tipo_cartao_credito]    INT          NULL,
    [cd_projeto_viagem]         INT          NULL,
    [ic_projeto_despesa]        CHAR (1)     NULL,
    [nm_projeto_viagem]         VARCHAR (40) NULL,
    [cd_cliente]                INT          NULL,
    [nm_cliente_despesa]        VARCHAR (40) NULL,
    [ic_imposto_despesa]        CHAR (1)     NULL,
    [cd_centro_custo]           INT          NULL,
    [ic_tipo_lancamento]        CHAR (1)     NULL,
    [ic_comprovante]            CHAR (1)     NULL,
    [dt_vencimento_documento]   DATETIME     NULL,
    [cd_funcionario_composicao] INT          NULL,
    CONSTRAINT [PK_Prestacao_Conta_Composicao] PRIMARY KEY CLUSTERED ([cd_prestacao] ASC, [cd_item_prestacao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Prestacao_Conta_Composicao_Tipo_Despesa] FOREIGN KEY ([cd_tipo_despesa]) REFERENCES [dbo].[Tipo_Despesa] ([cd_tipo_despesa])
);

