CREATE TABLE [dbo].[Prestacao_Conta] (
    [cd_prestacao]                  INT            NOT NULL,
    [dt_prestacao]                  DATETIME       NULL,
    [cd_tipo_prestacao]             INT            NULL,
    [ds_prestacao]                  TEXT           NULL,
    [cd_funcionario]                INT            NULL,
    [cd_departamento]               INT            NULL,
    [cd_centro_custo]               INT            NULL,
    [ic_status_prestacao]           CHAR (1)       NULL,
    [cd_usuario]                    INT            NULL,
    [dt_usuario]                    DATETIME       NULL,
    [cd_motivo_prestacao]           INT            NULL,
    [cd_requisicao_viagem]          INT            NULL,
    [cd_moeda]                      INT            NULL,
    [vl_prestacao]                  FLOAT (53)     NULL,
    [cd_solicitacao_adiantamento]   INT            NULL,
    [dt_fechamento_prestacao]       DATETIME       NULL,
    [ic_tipo_deposito_prestacao]    CHAR (1)       NULL,
    [cd_ap]                         INT            NULL,
    [ic_utiliza_nao_reembolsavel]   CHAR (1)       NULL,
    [vl_adiantamento]               FLOAT (53)     NULL,
    [cd_projeto_viagem]             INT            NULL,
    [cd_cartao_credito]             INT            NULL,
    [vl_despesa_prestacao]          FLOAT (53)     NULL,
    [vl_imposto_prestacao]          FLOAT (53)     NULL,
    [vl_devolucao_moeda]            FLOAT (53)     NULL,
    [ic_sel_adiantamento_prestacao] CHAR (1)       NULL,
    [dt_conf_prestacao]             DATETIME       NULL,
    [dt_liberacao_prestacao]        DATETIME       NULL,
    [cd_assunto_viagem]             INT            NULL,
    [dt_competencia_prestacao]      DATETIME       NULL,
    [cd_tipo_diaria]                INT            NULL,
    [cd_usuario_aprovacao]          INT            NULL,
    [cd_funcionario_aprovacao]      INT            NULL,
    [ic_email_prestacao]            CHAR (1)       NULL,
    [cd_usuario_prestacao]          INT            NULL,
    [cd_usuario_liberacao]          INT            NULL,
    [dt_inicio_prestacao]           DATETIME       NULL,
    [dt_fim_prestacao]              DATETIME       NULL,
    [cd_local_viagem]               INT            NULL,
    [nm_local_prestacao]            VARCHAR (100)  NULL,
    [ds_temp_obs_aprovacao]         VARCHAR (8000) NULL,
    [dt_liberacao_aprovacao]        DATETIME       NULL,
    [cd_secretaria]                 INT            NULL,
    [dt_prevista_aprovacao]         DATETIME       NULL,
    [dt_reenvio_aprovacao]          DATETIME       NULL,
    [cd_funcionario_liberacao]      INT            NULL,
    [dt_pagamento_prestacao]        DATETIME       NULL,
    [dt_liberacao_fornecedor]       DATETIME       NULL,
    [dt_pagamento_fornecedor]       DATETIME       NULL,
    [cd_nota_entrada]               INT            NULL,
    [dt_conf_fornecedor]            DATETIME       NULL,
    [dt_vencimento_prestacao]       DATETIME       NULL,
    [ic_controlada_prestacao]       CHAR (1)       NULL,
    [cd_beneficio]                  INT            NULL,
    [cd_deposito]                   INT            NULL,
    CONSTRAINT [PK_Prestacao_Conta] PRIMARY KEY CLUSTERED ([cd_prestacao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Prestacao_Conta_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo])
);

