CREATE TABLE [dbo].[Previsao_Venda] (
    [cd_previsao_venda]         INT          NOT NULL,
    [dt_inicio_previsao_venda]  DATETIME     NOT NULL,
    [dt_final_previsao_venda]   DATETIME     NOT NULL,
    [cd_vendedor]               INT          NULL,
    [cd_cliente]                INT          NULL,
    [cd_categoria_produto]      INT          NULL,
    [cd_grupo_produto]          INT          NULL,
    [cd_produto]                INT          NOT NULL,
    [cd_fase_produto]           INT          NOT NULL,
    [qt_produto_previsao_venda] FLOAT (53)   NULL,
    [vl_produto_previsao_venda] FLOAT (53)   NULL,
    [nm_obs_previsao_venda]     VARCHAR (40) NULL,
    [qt_hora_previsao_venda]    FLOAT (53)   NULL,
    [qt_servico_previsao_venda] FLOAT (53)   NULL,
    [ic_plano_mestre]           CHAR (1)     NULL,
    [ic_plano_simulacao]        CHAR (1)     NULL,
    [cd_usuario]                INT          NULL,
    [cd_servico]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_anterior_previsao]      FLOAT (53)   NULL,
    [dt_ini_anterior_previsao]  DATETIME     NULL,
    [dt_fim_anterior_previsao]  DATETIME     NULL,
    [qt_potencial_previsao]     FLOAT (53)   NULL,
    [qt_programado_previsao]    FLOAT (53)   NULL,
    [cd_produto_desenv]         INT          NULL,
    [dt_ultima_compra_cliente]  DATETIME     NULL,
    [qt_ranking_cliente]        INT          NULL,
    [cd_cliente_prospeccao]     INT          NULL,
    [cd_moeda]                  INT          NULL,
    [cd_pais]                   INT          NULL,
    CONSTRAINT [PK_Previsao_Venda] PRIMARY KEY CLUSTERED ([cd_previsao_venda] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Previsao_Venda_Cliente_Prospeccao] FOREIGN KEY ([cd_cliente_prospeccao]) REFERENCES [dbo].[Cliente_Prospeccao] ([cd_cliente_prospeccao]),
    CONSTRAINT [FK_Previsao_Venda_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda])
);

