CREATE TABLE [dbo].[Processo_Juridico] (
    [cd_processo_juridico]        INT          NOT NULL,
    [cd_identificacao_processo]   INT          NULL,
    [cd_arquivo_interno_processo] VARCHAR (15) NULL,
    [dt_entrada_processo]         DATETIME     NULL,
    [dt_distribuicao_processo]    DATETIME     NULL,
    [cd_tipo_processo_juridico]   INT          NULL,
    [cd_natureza_processo]        INT          NULL,
    [cd_posicao_processo]         INT          NULL,
    [cd_comarca]                  INT          NULL,
    [cd_forum]                    INT          NULL,
    [cd_forum_vara]               INT          NULL,
    [cd_cartorio]                 INT          NULL,
    [nm_cartorio_processo]        VARCHAR (60) NULL,
    [nm_setor_cartorio]           VARCHAR (40) NULL,
    [cd_fase_processo]            INT          NULL,
    [cd_liminar]                  INT          NULL,
    [cd_advogado]                 INT          NULL,
    [ds_processo_juridico]        TEXT         NULL,
    [cd_pais]                     INT          NULL,
    [cd_estado]                   INT          NULL,
    [cd_cidade]                   INT          NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [dt_baixa_processo]           DATETIME     NULL,
    [cd_baixa_processo]           INT          NULL,
    [nm_motivo_baixa_processo]    VARCHAR (40) NULL,
    CONSTRAINT [PK_Processo_Juridico] PRIMARY KEY CLUSTERED ([cd_processo_juridico] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Processo_Juridico_Baixa_Processo_Juridico] FOREIGN KEY ([cd_baixa_processo]) REFERENCES [dbo].[Baixa_Processo_Juridico] ([cd_baixa_processo]),
    CONSTRAINT [FK_Processo_Juridico_Estado] FOREIGN KEY ([cd_estado]) REFERENCES [dbo].[Estado] ([cd_estado])
);

