CREATE TABLE [dbo].[Processo_Producao_Apontamento] (
    [cd_processo]               INT          NOT NULL,
    [cd_item_processo]          INT          NOT NULL,
    [cd_processo_apontamento]   INT          NOT NULL,
    [cd_grupo_maquina]          INT          NULL,
    [cd_maquina]                INT          NULL,
    [cd_operador]               INT          NULL,
    [dt_processo_apontamento]   DATETIME     NULL,
    [hr_inicial_apontamento]    VARCHAR (8)  NULL,
    [hr_final_apontamento]      VARCHAR (8)  NULL,
    [hr_setup_apontamento]      VARCHAR (8)  NULL,
    [qt_peca_boa_apontamento]   FLOAT (53)   NULL,
    [qt_peca_ruim_produzida]    FLOAT (53)   NULL,
    [ic_operacao_concluida]     CHAR (1)     NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_processo_apontamento]   FLOAT (53)   NULL,
    [qt_setup_apontamento]      FLOAT (53)   NULL,
    [nm_obs_apontamento]        VARCHAR (40) NULL,
    [cd_operacao]               INT          NULL,
    [ic_movimenta_estoque]      CHAR (1)     NULL,
    [ic_apontamento_estornado]  CHAR (1)     NULL,
    [qt_peca_aprov_apontamento] FLOAT (53)   NULL,
    [cd_causa_refugo]           INT          NULL,
    CONSTRAINT [PK_Processo_Producao_Apontamento] PRIMARY KEY CLUSTERED ([cd_processo] ASC, [cd_item_processo] ASC, [cd_processo_apontamento] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Processo_Producao_Apontamento_Operacao] FOREIGN KEY ([cd_operacao]) REFERENCES [dbo].[Operacao] ([cd_operacao]),
    CONSTRAINT [FK_Processo_Producao_Apontamento_Processo_Producao_Composicao] FOREIGN KEY ([cd_processo], [cd_item_processo]) REFERENCES [dbo].[Processo_Producao_Composicao] ([cd_processo], [cd_item_processo])
);

