CREATE TABLE [dbo].[Processo_Padrao_Composicao] (
    [cd_processo_padrao]        INT          NOT NULL,
    [cd_composicao_proc_padrao] INT          NOT NULL,
    [cd_operacao]               INT          NULL,
    [ic_placa_processo_padrao]  CHAR (1)     NULL,
    [ic_codificaplaca_proc_pad] CHAR (1)     NULL,
    [ic_matprima_processo_pad]  CHAR (1)     NULL,
    [ic_apontamento_proc_pad]   CHAR (1)     NULL,
    [nm_obs_processo_padrao]    VARCHAR (40) NULL,
    [ic_mapa_processo_padrao]   CHAR (1)     NULL,
    [qt_dia_prog_processo_pad]  FLOAT (53)   NULL,
    [qt_depopant_processo_pad]  FLOAT (53)   NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_hora_setup]             FLOAT (53)   NULL,
    [qt_hora_operacao]          FLOAT (53)   NULL,
    [cd_maquina]                INT          NULL,
    [cd_grupo_maquina]          INT          NULL,
    [qt_peca_ciclo]             FLOAT (53)   NULL,
    [ic_calculo_setup_unico]    CHAR (1)     NULL,
    [cd_ordem]                  INT          NULL,
    [nm_obs_placa_excessao]     VARCHAR (40) NULL,
    [ic_movimenta_estoque]      CHAR (1)     NULL,
    [ic_operacao_priorizada]    CHAR (1)     NULL,
    [vl_custo_operacao]         FLOAT (53)   NULL,
    [vl_custo_maquina]          FLOAT (53)   NULL,
    [vl_custo_total]            FLOAT (53)   NULL,
    [vl_custo_total_maquina]    FLOAT (53)   NULL,
    [vl_custo_total_operacao]   FLOAT (53)   NULL,
    [cd_servico_especial]       INT          NULL,
    [vl_custo_servico]          FLOAT (53)   NULL,
    [qt_dia_servico_fornecedor] FLOAT (53)   NULL,
    [cd_fornecedor]             INT          NULL,
    [vl_custo_total_servico]    FLOAT (53)   NULL,
    [ic_opcional_operacao]      CHAR (1)     NULL,
    [ic_inspecao_operacao]      CHAR (1)     NULL,
    [ic_calculo_operacao_unico] CHAR (1)     NULL,
    CONSTRAINT [PK_Processo_Padrao_Composicao] PRIMARY KEY CLUSTERED ([cd_processo_padrao] ASC, [cd_composicao_proc_padrao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Processo_Padrao_Composicao_Operacao] FOREIGN KEY ([cd_operacao]) REFERENCES [dbo].[Operacao] ([cd_operacao]),
    CONSTRAINT [FK_Processo_Padrao_Composicao_Processo_Padrao] FOREIGN KEY ([cd_processo_padrao]) REFERENCES [dbo].[Processo_Padrao] ([cd_processo_padrao]) ON DELETE CASCADE ON UPDATE CASCADE
);

