CREATE TABLE [dbo].[Processo_Categoria_Apontamento] (
    [cd_processo_apontamento]  INT          NOT NULL,
    [cd_processo]              INT          NOT NULL,
    [cd_item_processo]         INT          NOT NULL,
    [cd_categoria_apontamento] INT          NULL,
    [cd_operacao]              INT          NULL,
    [cd_maquina]               INT          NULL,
    [cd_operador]              INT          NULL,
    [qt_apontamento]           FLOAT (53)   NULL,
    [dt_inicio]                DATETIME     NULL,
    [dt_fim]                   DATETIME     NULL,
    [hr_inicio]                VARCHAR (8)  NULL,
    [hr_fim]                   VARCHAR (8)  NULL,
    [nm_obs_apontamento]       VARCHAR (40) NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [qt_peca_boa_apontamento]  FLOAT (53)   NULL,
    [qt_peca_ruim_apontamento] FLOAT (53)   NULL,
    [qt_processo_apontamento]  FLOAT (53)   NULL,
    [qt_setup_apontamento]     FLOAT (53)   NULL,
    [cd_grupo_maquina]         INT          NULL,
    [ic_operacao_concluida]    CHAR (1)     NULL,
    [dt_processo_apontamento]  DATETIME     NULL,
    [cd_operacao_composicao]   INT          NULL,
    [hr_setup]                 VARCHAR (8)  NULL,
    [ic_apontamento_estornado] CHAR (1)     NULL,
    [ic_movimenta_estoque]     CHAR (1)     NULL,
    CONSTRAINT [PK_Processo_Categoria_Apontamento] PRIMARY KEY CLUSTERED ([cd_processo_apontamento] ASC, [cd_processo] ASC, [cd_item_processo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Processo_Categoria_Apontamento_Operacao] FOREIGN KEY ([cd_operacao]) REFERENCES [dbo].[Operacao] ([cd_operacao])
);

