CREATE TABLE [dbo].[Processo_Padrao_Produto] (
    [cd_processo_padrao]        INT           NOT NULL,
    [cd_produto_proc_padrao]    INT           NOT NULL,
    [cd_serie_produto]          INT           NULL,
    [cd_grupo_produto]          INT           NULL,
    [cd_sub_produto_especial]   INT           NULL,
    [nm_obs_proc_padrao_prod]   VARCHAR (40)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [nm_imagem_produto_padrao]  VARCHAR (100) NULL,
    [cd_produto]                INT           NULL,
    [cd_fase_produto]           INT           NULL,
    [qt_produto_processo]       FLOAT (53)    NULL,
    [pc_refugo_processo]        FLOAT (53)    NULL,
    [vl_custo_produto]          FLOAT (53)    NULL,
    [vl_custo_produto_processo] FLOAT (53)    NULL,
    [cd_ordem]                  INT           NULL,
    [cd_unidade_medida]         INT           NULL,
    [cd_materia_prima]          INT           NULL,
    [nm_medida_comp_processo]   VARCHAR (25)  NULL,
    [nm_comp_processo]          VARCHAR (15)  NULL,
    [ic_componente_priorizado]  CHAR (1)      NULL,
    [cd_produto_anterior]       INT           NULL,
    [cd_desenho_item_processo]  VARCHAR (30)  NULL,
    [cd_rev_res_item_processo]  VARCHAR (5)   NULL,
    [ic_custo_produto_processo] CHAR (1)      NULL,
    CONSTRAINT [PK_Processo_Padrao_Produto] PRIMARY KEY CLUSTERED ([cd_processo_padrao] ASC, [cd_produto_proc_padrao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Processo_Padrao_Produto_Grupo_Produto] FOREIGN KEY ([cd_grupo_produto]) REFERENCES [dbo].[Grupo_Produto] ([cd_grupo_produto]),
    CONSTRAINT [FK_Processo_Padrao_Produto_Processo_Padrao] FOREIGN KEY ([cd_processo_padrao]) REFERENCES [dbo].[Processo_Padrao] ([cd_processo_padrao]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_Processo_Padrao_Produto_Produto] FOREIGN KEY ([cd_produto]) REFERENCES [dbo].[Produto] ([cd_produto]),
    CONSTRAINT [FK_Processo_Padrao_Produto_Serie_Produto] FOREIGN KEY ([cd_serie_produto]) REFERENCES [dbo].[Serie_Produto] ([cd_serie_produto]),
    CONSTRAINT [FK_Processo_Padrao_Produto_Sub_Produto_Especial] FOREIGN KEY ([cd_sub_produto_especial]) REFERENCES [dbo].[Sub_Produto_Especial] ([cd_sub_produto_especial])
);

