CREATE TABLE [dbo].[Produto_Composicao] (
    [cd_produto_pai]            INT          NOT NULL,
    [cd_produto]                INT          NOT NULL,
    [cd_item_produto]           INT          NULL,
    [qt_item_produto]           INT          NULL,
    [qt_produto_composicao]     FLOAT (53)   NULL,
    [qt_peso_liquido_produto]   FLOAT (53)   NULL,
    [qt_peso_bruto_produto]     FLOAT (53)   NULL,
    [cd_ordem_produto]          INT          NULL,
    [cd_fase_produto]           INT          NULL,
    [cd_materia_prima]          INT          NULL,
    [cd_bitola]                 INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [nm_obs_produto_composicao] VARCHAR (40) NULL,
    [ic_calculo_peso_produto]   CHAR (1)     NULL,
    [pc_composicao_produto]     FLOAT (53)   NULL,
    [ic_montagemg_produto]      CHAR (1)     NULL,
    [ic_montagemq_produto]      CHAR (1)     NULL,
    [ic_tipo_montagem_produto]  CHAR (1)     NULL,
    [cd_versao_produto_comp]    INT          NOT NULL,
    [cd_ordem_produto_comp]     INT          NULL,
    [cd_produto_composicao]     INT          NULL,
    [cd_versao_produto]         INT          NULL,
    [nm_produto_comp]           VARCHAR (50) NULL,
    CONSTRAINT [PK_Produto_Composicao] PRIMARY KEY CLUSTERED ([cd_produto_pai] ASC, [cd_produto] ASC, [cd_versao_produto_comp] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Produto_Composicao_Produto] FOREIGN KEY ([cd_produto]) REFERENCES [dbo].[Produto] ([cd_produto]),
    CONSTRAINT [FK_Produto_Composicao_Produto2] FOREIGN KEY ([cd_produto_pai]) REFERENCES [dbo].[Produto] ([cd_produto])
);

