CREATE TABLE [dbo].[Produto_Custo] (
    [cd_produto]                   INT          NOT NULL,
    [ic_peps_produto]              CHAR (1)     NULL,
    [ic_lista_preco_produto]       CHAR (1)     NULL,
    [ic_lista_rep_produto]         CHAR (1)     NULL,
    [ic_reposicao_produto]         CHAR (1)     NULL,
    [vl_custo_produto]             FLOAT (53)   NULL,
    [ic_estoque_produto]           CHAR (1)     NULL,
    [ic_orcamento_produto]         CHAR (1)     NULL,
    [ic_imediato_produto]          CHAR (1)     NULL,
    [ic_importacao_produto]        CHAR (1)     NULL,
    [ic_reserva_estoque_produto]   CHAR (1)     NULL,
    [ic_estoque_fatura_produto]    CHAR (1)     NULL,
    [ic_estoque_venda_produto]     CHAR (1)     NULL,
    [ic_venda_saldo_negativo]      CHAR (1)     NULL,
    [ic_controle_desconto_produto] CHAR (1)     NULL,
    [ic_fechamento_mensal_produto] CHAR (1)     NULL,
    [qt_dia_valoracao]             FLOAT (53)   NULL,
    [cd_tipo_valoracao]            INT          NULL,
    [cd_tipo_lucro]                INT          NULL,
    [cd_aplicacao]                 INT          NULL,
    [cd_grupo_preco_produto]       INT          NULL,
    [cd_cab_lista_preco]           INT          NULL,
    [cd_usuario]                   INT          NULL,
    [dt_usuario]                   DATETIME     NULL,
    [qt_mes_consumo_produto]       INT          NULL,
    [cd_grupo_produto]             INT          NULL,
    [cd_tipo_valoracao_produto]    INT          NULL,
    [ic_exportacao_produto]        CHAR (1)     NULL,
    [vl_custo_anterior_produto]    FLOAT (53)   NULL,
    [cd_mat_prima]                 INT          NULL,
    [qt_consumo_mensal]            FLOAT (53)   NULL,
    [ic_reserva_estoque_produt]    CHAR (1)     NULL,
    [ic_fechamento_mensal_prod]    CHAR (1)     NULL,
    [ic_controle_desconto_prod]    CHAR (1)     NULL,
    [cd_aplicacao_markup]          INT          NULL,
    [cd_plano_financeiro]          INT          NULL,
    [ic_smo_produto]               CHAR (1)     NULL,
    [vl_custo_contabil_produto]    FLOAT (53)   NULL,
    [vl_custo_medio_produto]       FLOAT (53)   NULL,
    [ic_atualiza_custo_nf]         CHAR (1)     NULL,
    [cd_grupo_inventario]          INT          NULL,
    [cd_bitola]                    INT          NULL,
    [cd_metodo_valoracao]          INT          NULL,
    [cd_lancamento_padrao]         INT          NULL,
    [vl_net_outra_moeda]           FLOAT (53)   NULL,
    [cd_grupo_estoque]             INT          NULL,
    [nm_obs_custo_produto]         VARCHAR (40) NULL,
    [dt_custo_produto]             DATETIME     NULL,
    [vl_base_custo_produto]        FLOAT (53)   NULL,
    [dt_base_custo_produto]        DATETIME     NULL,
    [vl_simulado_custo_produto]    FLOAT (53)   NULL,
    [dt_simulado_custo_produto]    DATETIME     NULL,
    [vl_temp_custo_produto]        FLOAT (53)   NULL,
    [dt_temp_custo_produto]        DATETIME     NULL,
    [cd_overprice]                 INT          NULL,
    [dt_net_outra_moeda]           DATETIME     NULL,
    [vl_custo_previsto_produto]    FLOAT (53)   NULL,
    [ic_mat_prima_produto]         CHAR (1)     NULL,
    [vl_custo_exportacao]          FLOAT (53)   NULL,
    [vl_custo_fracionado_produto]  FLOAT (53)   NULL,
    [ic_deducao_imposto]           CHAR (1)     NULL,
    [vl_custo_comissao]            FLOAT (53)   NULL,
    [ic_custo_moeda_produto]       CHAR (1)     NULL,
    [cd_moeda]                     INT          NULL,
    [vl_custo_producao_produto]    FLOAT (53)   NULL,
    [vl_custo_frete_produto]       FLOAT (53)   NULL,
    CONSTRAINT [PK_Produto_Custo] PRIMARY KEY CLUSTERED ([cd_produto] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Produto_Custo_Grupo_Estoque] FOREIGN KEY ([cd_grupo_estoque]) REFERENCES [dbo].[Grupo_Estoque] ([cd_grupo_estoque]),
    CONSTRAINT [FK_Produto_Custo_Lancamento_Padrao] FOREIGN KEY ([cd_lancamento_padrao]) REFERENCES [dbo].[Lancamento_Padrao] ([cd_lancamento_padrao]),
    CONSTRAINT [FK_Produto_Custo_Metodo_Valoracao] FOREIGN KEY ([cd_metodo_valoracao]) REFERENCES [dbo].[Metodo_Valoracao] ([cd_metodo_valoracao])
);


GO
CREATE NONCLUSTERED INDEX [IX_Produto_Custo]
    ON [dbo].[Produto_Custo]([cd_produto] ASC) WITH (FILLFACTOR = 90);

