//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financeiro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.ContaCorrente = new HashSet<ContaCorrente>();
        }
    
        public int Codigo { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
    }
}
