//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financeiro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaCorrente
    {
        public ContaCorrente()
        {
            this.Movimento = new HashSet<Movimento>();
        }
    
        public int Id { get; set; }
        public int Empresa { get; set; }
        public int Banco { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        public virtual ICollection<Movimento> Movimento { get; set; }
    }
}
