//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financeiro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAContext : DbContext
    {
        public SAContext()
            : base("name=SAContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Banco> Banco { get; set; }
        public DbSet<ContaCorrente> ContaCorrente { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Movimento> Movimento { get; set; }
    }
}
