
/****** Object:  Stored Procedure dbo.SPFA_NOTAFISCAL_ALTERAR    Script Date: 23/10/2010 13:58:21 ******/


/****** Object:  Stored Procedure dbo.SPFA_NOTAFISCAL_ALTERAR    Script Date: 25/08/1999 20:11:41 ******/
CREATE PROCEDURE SPFA_NOTAFISCAL_ALTERAR
	
   @NotaFiscal          int,
   @TipoNota            char(1),
   @DataNota            smalldatetime,
   @Pedido              int,
   @CNPJ                char(14),
   @Inscricao           char(14),
   @ClienteFornecedor   char(1),
   @Estado              char(2),
   @CFOP                char(6),
   @DescricaoCFOP varchar(40),
   @ICMS                char(2),
   @ValorTotal          money,
   @BaseCalculoICMS     money,
   @ValorIPI            money,
   @ValorIPIOutros      money,
   @ValorICMS           money,
   @ValorICMSOutros     money,
   @Situacao1           int,
   @Situacao2           int,
   @Representante       char(3),
   @Comissao               real,
   @QtdePagto             tinyint,
   @Vencimento1         smalldatetime,
   @Vencimento2         smalldatetime,
   @Vencimento3         smalldatetime,
   @Vencimento4         smalldatetime,
   @Vencimento5         smalldatetime,
   @Vencimento6         smalldatetime,
   @Vencimento7         smalldatetime,
   @Vencimento8         smalldatetime,
   @Pagamento1          money,
   @Pagamento2          money, 
   @Pagamento3          money,
   @Pagamento4          money, 
   @Pagamento5          money,
   @Pagamento6          money, 
   @Pagamento7          money,
   @Pagamento8          money,
   @NfVinculada           int
AS
BEGIN
          UPDATE FA_NotaFiscal
          SET fanf_TipoNota          = @TipoNota,
           fanf_DataNota          = @DataNota,
           fanf_Pedido            = @Pedido,
           fanf_CNPJ              = @CNPJ,
           fanf_Inscricao         = @Inscricao,
           fanf_ClienteFornecedor = @ClienteFornecedor,
           fanf_Estado            = @Estado,
           fanf_CFOP              = @CFOP,
           fanf_DescricaoCFOP = @DescricaoCFOP,
           fanf_ICMS              = @ICMS,
           fanf_ValorTotal        = @ValorTotal,
           fanf_BaseCalculoICMS   = @BaseCalculoICMS,
           fanf_ValorIPI          = @ValorIPI,
           fanf_ValorIPIOutros    = @ValorIPIOutros,
           fanf_ValorICMS         = @ValorICMS,
           fanf_ValorICMSOutros   = @ValorICMSOutros,
           fanf_Situacao1         = @Situacao1,
           fanf_Situacao2         = @Situacao2,
           fanf_Representante     = @Representante,
           fanf_Comissao             = @Comissao,
           fanf_QtdePagto           = @QtdePagto,
           fanf_Vencimento1       = @Vencimento1,
           fanf_Vencimento2       = @Vencimento2,
           fanf_Vencimento3       = @Vencimento3,
           fanf_Vencimento4       = @Vencimento4,
           fanf_Vencimento5       = @Vencimento5,
           fanf_Vencimento6       = @Vencimento6,
           fanf_Vencimento7       = @Vencimento7,
           fanf_Vencimento8       = @Vencimento8,
           fanf_Pagamento1        = @Pagamento1,
           fanf_Pagamento2        = @Pagamento2, 
           fanf_Pagamento3        = @Pagamento3,
           fanf_Pagamento4        = @Pagamento4, 
           fanf_Pagamento5        = @Pagamento5,
           fanf_Pagamento6        = @Pagamento6, 
           fanf_Pagamento7        = @Pagamento7,
           fanf_Pagamento8        = @Pagamento8,
           fanf_NfVinculada        = @NfVinculada
       
         WHERE fanf_NotaFiscal = @NotaFiscal
END

