CREATE VIEW [dbo].[GPIMAC.CodigoSequencial]
AS
SELECT     CONCOD AS Id, CONULTPC AS [PreCliente.Codigo], CONULTMOV, CONULTPED, CONULTNOT, CONULTREC, CONULTBOR, CONTJD, CONULFLUX, CONULRECC, 
                      CONULREDI, CONULPEDC, CONULRIR, CONULTNOT1, CONULEPRO, CONULPEDI, CONULCOTA, CONULTTMP1, CONTROLE, CONNFPSNF, CONNFMSNF, 
                      CONNFDSNF, CONULTCV, CONULTCT, CONULTAT, CONULCVD, CONULGLF, CONULTORDFAB, CONULTPRGPRO, CONULBAROF, CONNFE, CONGUIA, CONULCliEx, 
                      CONBenEnvValDias, CONULTEMB
FROM         GPIMAC_Altamira.dbo.CONTRN AS IdControle










