CREATE TABLE [dbo].[Config_Geral] (
    [Dir_sistema]          NVARCHAR (100) NULL,
    [Dir_padrao_dados]     NVARCHAR (100) NULL,
    [Dir_resumo]           NVARCHAR (100) NULL,
    [Prof_estr_gond]       INT            NULL,
    [Prof_estr_gond_ponta] INT            NULL,
    [Sufixo_gond]          NVARCHAR (2)   NULL,
    [Sufixo_gond_estr]     NVARCHAR (2)   NULL,
    [Compr_ang_int]        INT            NULL,
    [Alt_txt_planta]       REAL           NULL,
    [Alt_txt_corte]        REAL           NULL,
    [Dist_hori_corte]      INT            NULL,
    [Dist_vert_corte]      INT            NULL,
    [Num_col_cortes]       INT            NULL,
    [Esc_des_formato]      INT            NULL,
    [Alt_text_formato]     INT            NULL,
    [Corte_gond_pad]       NVARCHAR (45)  NULL,
    [Alt_gond_pad]         INT            NULL,
    [Prof_gond_pad]        INT            NULL,
    [Fundo_gond_pad]       NVARCHAR (49)  NULL,
    [Frente_gond_pad]      NVARCHAR (50)  NULL,
    [Base_gond_pad]        NVARCHAR (50)  NULL,
    [Pad_lista_Gond]       NVARCHAR (20)  NULL,
    [Bloco_legenda]        NVARCHAR (100) NULL,
    [Afast_vert]           INT            NULL,
    [Afast_Hori]           INT            NULL,
    [Pad_lista_exp]        NVARCHAR (20)  NULL,
    [Pad_lista_Camara]     NVARCHAR (20)  NULL,
    [Pad_lista_Maq]        NVARCHAR (20)  NULL,
    [Perfil_Config]        NVARCHAR (50)  NULL,
    [comp_min_gond]        INT            NULL,
    [comp_max_gond]        INT            NULL,
    [prefixo_orcamento]    NVARCHAR (4)   NULL,
    [dir_cartas]           NVARCHAR (100) NULL,
    [dir_imagens]          NVARCHAR (100) NULL,
    [inc_pai]              BIT            CONSTRAINT [DF_Config_Geral_inc_pai] DEFAULT ((0)) NOT NULL,
    [inc_teto]             BIT            CONSTRAINT [DF_Config_Geral_inc_teto] DEFAULT ((0)) NOT NULL,
    [inc_piso]             BIT            CONSTRAINT [DF_Config_Geral_inc_piso] DEFAULT ((0)) NOT NULL,
    [dir_dwg]              NVARCHAR (150) NULL,
    [Tipomed]              NVARCHAR (50)  NULL,
    [autocad]              BIT            CONSTRAINT [DF_Config_Geral_autocad] DEFAULT ((0)) NOT NULL,
    [comp_min_gab]         NVARCHAR (5)   NULL,
    [comp_max_gab]         NVARCHAR (5)   NULL,
    [dwg_padrao]           NVARCHAR (255) NULL,
    [t_salvar]             INT            NULL,
    [hab_prop]             SMALLINT       NULL,
    [hab_vis]              SMALLINT       NULL,
    [sufixo_gond_pta]      NVARCHAR (2)   NULL,
    [Corte_gond_pta_pad]   NVARCHAR (20)  NULL,
    [fundo_gond_pta_pad]   NVARCHAR (50)  NULL,
    [base_gond_pta_pad]    NVARCHAR (50)  NULL,
    [cfgPassword]          NVARCHAR (50)  NULL,
    [DIR_MOB_USUARIO]      NVARCHAR (100) NULL,
    [IdConfigGeral]        INT            IDENTITY (1, 1) NOT NULL
);

