CREATE TABLE [dbo].[conf_empresa] (
    [Empresa]            NVARCHAR (60)  NULL,
    [CGC]                NVARCHAR (15)  NULL,
    [IE]                 NVARCHAR (15)  NULL,
    [ENDERECO]           NVARCHAR (60)  NULL,
    [BAIRRO]             NVARCHAR (50)  NULL,
    [CIDADE]             NVARCHAR (50)  NULL,
    [CEP]                NVARCHAR (9)   NULL,
    [ESTADO]             NVARCHAR (2)   NULL,
    [CAMINHO_BASE]       NVARCHAR (MAX) NULL,
    [CAMINHO_FIGURA]     NVARCHAR (MAX) NULL,
    [texto_bloco]        BIT            CONSTRAINT [DF_conf_empresa_texto_bloco] DEFAULT ((0)) NOT NULL,
    [altura_texto]       FLOAT (53)     NULL,
    [bloco_legenda]      NVARCHAR (50)  NULL,
    [af_horizontal]      FLOAT (53)     NULL,
    [af_vertical]        FLOAT (53)     NULL,
    [caminho_alt_figura] NVARCHAR (MAX) NULL,
    [fone]               NVARCHAR (20)  NULL,
    [fax]                NVARCHAR (20)  NULL,
    [home]               NVARCHAR (30)  NULL,
    [texto_resumo]       NVARCHAR (30)  NULL,
    [viz_ver]            BIT            CONSTRAINT [DF_conf_empresa_viz_ver] DEFAULT ((0)) NOT NULL,
    [precisao]           FLOAT (53)     NULL,
    [End_completo]       NVARCHAR (MAX) NULL,
    [DBFClientes]        NVARCHAR (MAX) NULL,
    [TabsClientes]       NVARCHAR (255) NULL,
    [DBFPrecos]          NVARCHAR (MAX) NULL,
    [TabsPrecos]         NVARCHAR (255) NULL,
    [TipoClientes]       NVARCHAR (50)  NULL,
    [TipoPrecos]         NVARCHAR (50)  NULL,
    [trata_rel]          INT            NULL,
    [numeracao_1]        INT            NULL,
    [numeracao_2]        INT            NULL,
    [tipoVendedor]       NVARCHAR (50)  NULL,
    [DbfVendedor]        NVARCHAR (MAX) NULL,
    [TabsVendedor]       NVARCHAR (255) NULL,
    [arquivo_mat]        NVARCHAR (MAX) NULL,
    [set_acess]          BIT            CONSTRAINT [DF_conf_empresa_set_acess] DEFAULT ((0)) NOT NULL,
    [ref_externa]        BIT            CONSTRAINT [DF_conf_empresa_ref_externa] DEFAULT ((0)) NOT NULL,
    [fator_conv]         FLOAT (53)     NULL,
    [imagem_cli]         NVARCHAR (70)  NULL,
    [ajust_imagem]       BIT            CONSTRAINT [DF_conf_empresa_ajust_imagem] DEFAULT ((0)) NOT NULL,
    [fator_desc]         FLOAT (53)     NULL,
    [compl_esp]          NVARCHAR (50)  NULL,
    [Validade]           NVARCHAR (5)   NULL,
    [Prazo_entrega]      NVARCHAR (5)   NULL,
    [Posto]              NVARCHAR (80)  NULL,
    [OrdenCad]           BIT            CONSTRAINT [DF_conf_empresa_OrdenCad] DEFAULT ((0)) NOT NULL,
    [ValFamilia]         BIT            CONSTRAINT [DF_conf_empresa_ValFamilia] DEFAULT ((0)) NOT NULL,
    [IR]                 NVARCHAR (5)   NULL,
    [OndeVerStatus]      NVARCHAR (MAX) NULL,
    [ValidStatus]        BIT            CONSTRAINT [DF_conf_empresa_ValidStatus] DEFAULT ((0)) NOT NULL,
    [BloqMaior]          BIT            CONSTRAINT [DF_conf_empresa_BloqMaior] DEFAULT ((0)) NOT NULL,
    [PermValZero]        BIT            CONSTRAINT [DF_conf_empresa_PermValZero] DEFAULT ((0)) NOT NULL,
    [TipoRevisao]        SMALLINT       NULL,
    [TipoFrete]          NVARCHAR (50)  NULL,
    [Def_pessoa]         BIT            CONSTRAINT [DF_conf_empresa_Def_pessoa] DEFAULT ((0)) NOT NULL,
    [Acessar_ev]         BIT            CONSTRAINT [DF_conf_empresa_Acessar_ev] DEFAULT ((0)) NOT NULL,
    [Perm_impress]       BIT            CONSTRAINT [DF_conf_empresa_Perm_impress] DEFAULT ((0)) NOT NULL,
    [Perm_Gravar]        BIT            CONSTRAINT [DF_conf_empresa_Perm_Gravar] DEFAULT ((0)) NOT NULL,
    [Viz_Proj_Acess]     BIT            CONSTRAINT [DF_conf_empresa_Viz_Proj_Acess] DEFAULT ((0)) NOT NULL,
    [foco_usua]          BIT            CONSTRAINT [DF_conf_empresa_foco_usua] DEFAULT ((0)) NOT NULL,
    [Caminho_nOrca]      NVARCHAR (254) NULL,
    [Lista_de_Precos]    NVARCHAR (50)  NULL,
    [LogoTipo]           NVARCHAR (100) NULL,
    [EMAIL2]             NVARCHAR (255) NULL,
    [idConfEmpresa]      INT            IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([idConfEmpresa] ASC)
);

