CREATE TABLE [dbo].[INTEGRACAO_ORCINC] (
    [ORCNUM]    NVARCHAR (8)  NOT NULL,
    [ORCDAT]    DATETIME      NULL,
    [CLINOM]    NVARCHAR (50) NULL,
    [CLIEND]    NVARCHAR (50) NULL,
    [CLIFON]    NVARCHAR (20) NULL,
    [CLIFAX]    NVARCHAR (20) NULL,
    [CLIEMA]    NVARCHAR (70) NULL,
    [CLICON]    NVARCHAR (40) NULL,
    [USRCOD]    NVARCHAR (20) NULL,
    [ESTCOD]    NVARCHAR (2)  NULL,
    [TIPVNDCOD] NVARCHAR (50) NULL,
    [REPCOD]    NVARCHAR (20) NULL,
    [ACADSC]    NVARCHAR (50) NULL,
    [CLIMUN]    NVARCHAR (50) NULL,
    CONSTRAINT [PK_INTEGRACAO_ORCINC] PRIMARY KEY CLUSTERED ([ORCNUM] ASC)
);


GO
GRANT INSERT
    ON OBJECT::[dbo].[INTEGRACAO_ORCINC] TO [interclick]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[INTEGRACAO_ORCINC] TO [interclick]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[INTEGRACAO_ORCINC] TO [interclick]
    AS [dbo];

