CREATE TABLE [dbo].[mob_cadastro] (
    [descricao]            NVARCHAR (50)  NULL,
    [cod_direito]          NVARCHAR (50)  NULL,
    [cod_esquerdo]         NVARCHAR (50)  NULL,
    [desenho]              NVARCHAR (100) NULL,
    [comp_padrao]          INT            NULL,
    [comp_min]             INT            NULL,
    [comp_max]             INT            NULL,
    [prof_padrao]          INT            NULL,
    [prof_min]             INT            NULL,
    [prof_max]             INT            NULL,
    [alt_padrao]           INT            NULL,
    [alt_min]              INT            NULL,
    [alt_max]              INT            NULL,
    [alt_solo]             INT            NULL,
    [complemento]          NVARCHAR (20)  NULL,
    [visivel]              BIT            NULL,
    [bandeira]             NVARCHAR (50)  NULL,
    [familia]              NVARCHAR (50)  NULL,
    [corte]                NVARCHAR (50)  NULL,
    [grupo_cor]            NVARCHAR (50)  NULL,
    [nome_eqpto]           NVARCHAR (50)  NULL,
    [opcao]                NVARCHAR (1)   NULL,
    [consumo_eletrico]     INT            NULL,
    [consumo_tipo]         NVARCHAR (50)  NULL,
    [subgrupo]             NVARCHAR (50)  NULL,
    [travar_representante] BIT            NULL,
    [tipo_cobrar]          NVARCHAR (50)  NULL,
    [codigo_montavel]      NVARCHAR (20)  NULL,
    [desenho_montavel]     NVARCHAR (20)  NULL,
    [grupo_caracteristica] NVARCHAR (20)  NULL,
    [texto_p_corte]        NVARCHAR (60)  NULL,
    [corte_montavel]       NVARCHAR (50)  NULL,
    [parte_reta]           FLOAT (53)     NULL,
    [angulo]               FLOAT (53)     NULL,
    [grupo_restricao]      NVARCHAR (50)  NULL,
    [prioridade]           INT            NULL,
    [mensagem_ao_inserir]  NVARCHAR (50)  NULL,
    [idMobCadastro]        INT            IDENTITY (1, 1) NOT NULL
);

