CREATE TABLE [dbo].[orccab1] (
    [numeroOrcamento]                NCHAR (9)       NOT NULL,
    [BANDEIRA]                       NVARCHAR (50)   NULL,
    [COMISSAO_FATOR]                 MONEY           NULL,
    [GrupoImpostos]                  NVARCHAR (50)   NULL,
    [orccab_Area]                    MONEY           NULL,
    [orccab_bloqueado]               BIT             NULL,
    [orccab_bloquear_icad]           BIT             NULL,
    [orccab_Cadastro]                DATETIME        NULL,
    [orccab_caminho_dwg]             NVARCHAR (255)  NULL,
    [orccab_chave]                   NVARCHAR (40)   NULL,
    [orccab_cliente_bmp]             NVARCHAR (255)  NULL,
    [orccab_cliente_CGC_cpf]         NVARCHAR (18)   NULL,
    [orccab_cliente_Codigo]          INT             NULL,
    [orccab_cliente_end_bairro]      NVARCHAR (30)   NULL,
    [orccab_cliente_end_cep]         NVARCHAR (9)    NULL,
    [orccab_cliente_end_complemento] NVARCHAR (30)   NULL,
    [orccab_cliente_end_endereco]    NVARCHAR (50)   NULL,
    [orccab_cliente_end_especie]     NVARCHAR (4)    NULL,
    [orccab_cliente_end_numero]      NVARCHAR (6)    NULL,
    [orccab_cliente_Nome]            NVARCHAR (50)   NULL,
    [orccab_contato]                 NVARCHAR (40)   NULL,
    [ORCCAB_CONTATO_EMAIL]           NVARCHAR (70)   NULL,
    [OrcCab_data_email]              DATETIME        NULL,
    [orccab_Data_preco_Cor]          DATETIME        NULL,
    [orccab_Data_Status]             DATETIME        NULL,
    [orccab_desconto_valor]          MONEY           NULL,
    [OrcCab_Diferenca]               MONEY           NULL,
    [orccab_diferenca_valor]         MONEY           NULL,
    [OrcCab_email]                   INT             NULL,
    [orccab_emissao]                 DATETIME        NULL,
    [orccab_encargos_perc]           MONEY           NULL,
    [orccab_encargos_valor]          MONEY           NULL,
    [orccab_fax]                     NVARCHAR (20)   NULL,
    [orccab_fone]                    NVARCHAR (20)   NULL,
    [orccab_frete_valor]             MONEY           NULL,
    [OrcCab_FRETE1]                  MONEY           NULL,
    [orccab_gerente]                 NVARCHAR (50)   NULL,
    [orccab_ie_rg]                   NVARCHAR (18)   NULL,
    [orccab_ipi_valor]               MONEY           NULL,
    [orccab_Lista]                   NVARCHAR (20)   NULL,
    [orccab_loja]                    NVARCHAR (23)   NULL,
    [OrcCab_Montagem]                MONEY           NULL,
    [orccab_motivo]                  NVARCHAR (40)   NULL,
    [orccab_municipio]               NVARCHAR (23)   NULL,
    [orccab_nova_reforma]            NVARCHAR (1)    NULL,
    [orccab_nr_orc_vnd]              NVARCHAR (10)   NULL,
    [orccab_opcao_comissao]          NVARCHAR (50)   NULL,
    [orccab_opcao_resumo]            NVARCHAR (50)   NULL,
    [orccab_orcamentista]            NVARCHAR (50)   NULL,
    [orccab_pedido]                  NVARCHAR (15)   NULL,
    [orccab_Pedido_Data]             DATETIME        NULL,
    [orccab_Pedido_Usuario]          NVARCHAR (255)  NULL,
    [OrcCab_Preco_lista_Sem]         MONEY           NULL,
    [orccab_projetista]              NVARCHAR (50)   NULL,
    [orccab_ramo]                    NVARCHAR (30)   NULL,
    [ORCCAB_REFERENCIA]              NVARCHAR (8)    NULL,
    [orccab_revisao]                 NVARCHAR (1)    NULL,
    [orccab_revisao_orc]             NVARCHAR (1)    NULL,
    [orccab_Status]                  INT             NULL,
    [orccab_suframa]                 NVARCHAR (18)   NULL,
    [orccab_Temperatura]             INT             NULL,
    [orccab_total]                   MONEY           NULL,
    [orccab_total_geral]             MONEY           NULL,
    [ORCCAB_TOTAL1]                  MONEY           NULL,
    [ORCCAB_TOTAL2]                  MONEY           NULL,
    [orccab_UF]                      NVARCHAR (2)    NULL,
    [orccab_vendedor]                NVARCHAR (50)   NULL,
    [orccab_versao_dat]              NVARCHAR (10)   NULL,
    [ORCCAB_VINCULAR]                INT             NULL,
    [ORCCABDATAENTREGA]              DATETIME        NULL,
    [ORCCABDATAFATURAMENTO]          DATETIME        NULL,
    [ORCCABDATAULTATUALIZACAO]       DATETIME        NULL,
    [OrccabFlagImpostos]             BIT             NULL,
    [OrcCabPrecoLista]               MONEY           NULL,
    [OrccabTextoProposta]            NVARCHAR (MAX)  NULL,
    [ORCCABVALORFINAL1]              MONEY           NULL,
    [ORCCABVALORFINAL2]              MONEY           NULL,
    [ORCCABVALORFINAL3]              MONEY           NULL,
    [ORCCABVALORFINAL4]              MONEY           NULL,
    [ORCCABVALORFINAL5]              MONEY           NULL,
    [ORCCABVALORFINAL6]              MONEY           NULL,
    [ORCCABTROCARFINAL1]             BIT             NULL,
    [ORCCABTROCARFINAL2]             BIT             NULL,
    [ORCCABTROCARFINAL3]             BIT             NULL,
    [ORCCABTROCARFINAL4]             BIT             NULL,
    [ORCCABTROCARFINAL5]             BIT             NULL,
    [ORCCABTROCARFINAL6]             BIT             NULL,
    [ORCCABVALORBASE1]               MONEY           NULL,
    [ORCCABVALORBASE2]               MONEY           NULL,
    [ORCCABVALORBASE3]               MONEY           NULL,
    [ORCCABVALORBASE4]               MONEY           NULL,
    [ORCCABVALORBASE5]               MONEY           NULL,
    [ORCCABVALORBASE6]               MONEY           NULL,
    [PAISCODIGO]                     NVARCHAR (5)    NULL,
    [PgtCabCodigo]                   NVARCHAR (1024) NULL,
    [QtdeAlteradas]                  INT             NULL,
    [TipoVenda]                      NVARCHAR (50)   NULL,
    [condicaoPagamento]              NVARCHAR (MAX)  NULL,
    [condicaoPagamentoDescricao]     NVARCHAR (255)  NULL,
    [orccab_pedido_cliente]          NVARCHAR (50)   NULL,
    [orccab_cliente_et_especie]      NVARCHAR (4)    NULL,
    [orccab_cliente_et_endereco]     NVARCHAR (40)   NULL,
    [orccab_cliente_et_numero]       NVARCHAR (6)    NULL,
    [orccab_cliente_et_complemento]  NVARCHAR (30)   NULL,
    [orccab_cliente_et_bairro]       NVARCHAR (30)   NULL,
    [orccab_cliente_et_municipio]    NVARCHAR (30)   NULL,
    [orccab_cliente_et_uf]           NVARCHAR (2)    NULL,
    [orccab_cliente_et_cep]          NVARCHAR (9)    NULL,
    [orccab_cliente_et_pais]         NVARCHAR (5)    NULL,
    [orccab_cliente_cb_especie]      NVARCHAR (4)    NULL,
    [orccab_cliente_cb_endereco]     NVARCHAR (40)   NULL,
    [orccab_cliente_cb_numero]       NVARCHAR (6)    NULL,
    [orccab_cliente_cb_complemento]  NVARCHAR (30)   NULL,
    [orccab_cliente_cb_bairro]       NVARCHAR (30)   NULL,
    [orccab_cliente_cb_municipio]    NVARCHAR (30)   NULL,
    [orccab_cliente_cb_uf]           NVARCHAR (2)    NULL,
    [orccab_cliente_cb_cep]          NVARCHAR (9)    NULL,
    [orccab_cliente_cb_pais]         NVARCHAR (5)    NULL,
    [ObservacoesEntrega]             NVARCHAR (255)  NULL,
    [orccab_cliente_et_utilizar]     BIT             NULL,
    [orccab_cliente_cb_utilizar]     BIT             NULL,
    [condicaoPagamentoFator]         FLOAT (53)      NULL,
    [concorrentes]                   NVARCHAR (1000) NULL,
    CONSTRAINT [PK_ORCCAB1] PRIMARY KEY CLUSTERED ([numeroOrcamento] ASC)
);

