CREATE TABLE [dbo].[ORCDETAUX] (
    [orcdet_grupo]           INT            NULL,
    [orcdet_subgrupo]        NVARCHAR (2)   NULL,
    [orcdet_corte]           NVARCHAR (50)  NULL,
    [orcdet_nr_seq]          INT            NULL,
    [orcdet_nr_seq_crt]      NVARCHAR (50)  NULL,
    [orcdet_codigo]          NVARCHAR (100) NULL,
    [orcdet_cor]             NVARCHAR (20)  NULL,
    [orcdet_qtde]            MONEY          NULL,
    [dep_alt]                BIT            NOT NULL,
    [dep_compr]              BIT            NOT NULL,
    [dep_prof]               BIT            NOT NULL,
    [DEPARTAMENTO]           NVARCHAR (50)  NULL,
    [IDCJTO]                 INT            NULL,
    [MATERIALEXTRA]          INT            NULL,
    [orcdet_acessorio]       NVARCHAR (70)  NULL,
    [ORCDET_AGRUPAMENTO]     NVARCHAR (255) NULL,
    [orcdet_Altura]          MONEY          NULL,
    [orcdet_chb]             NVARCHAR (50)  NULL,
    [ORCDET_CODIGO_ORI]      NVARCHAR (100) NULL,
    [orcdet_Comprimento]     MONEY          NULL,
    [ORCDET_CORESADC]        NVARCHAR (100) NULL,
    [orcdet_fator_ref]       MONEY          NULL,
    [orcdet_flag_imprimir]   BIT            NOT NULL,
    [orcdet_flag_suprimir]   BIT            NOT NULL,
    [orcdet_identificador]   NVARCHAR (2)   NULL,
    [orcdet_obs]             NVARCHAR (40)  NULL,
    [orcdet_onde_incluir]    NVARCHAR (50)  NULL,
    [orcdet_peso]            MONEY          NULL,
    [ORCDET_PRC_ALTURA]      INT            NULL,
    [ORCDET_PRC_COMPRIMENTO] INT            NULL,
    [ORCDET_PRC_FORMULA]     INT            NULL,
    [ORCDET_PRC_LARGURA]     INT            NULL,
    [orcdet_prd_ref]         INT            NULL,
    [orcdet_preco_lista]     MONEY          NULL,
    [orcdet_Profundidade]    MONEY          NULL,
    [ORCDETBASALT]           MONEY          NULL,
    [orcdetbase]             NVARCHAR (50)  NULL,
    [ORCDETBASPRF1]          MONEY          NULL,
    [ORCDETBASPRF2]          MONEY          NULL,
    [ORCDETBASPRFEST]        MONEY          NULL,
    [ORCDETBASQTD]           INT            NULL,
    [orcdetcorpesquisa]      NVARCHAR (20)  NULL,
    [OrcDetPrecoLista]       MONEY          NULL,
    [OrcDetProdutoImagem]    NVARCHAR (255) NULL,
    [ORCDETPROPOSTAGRUPO]    INT            NULL,
    [OrcDetTipoProduto]      NVARCHAR (20)  NULL,
    [ori_alt]                INT            NULL,
    [ori_compr]              INT            NULL,
    [ori_prof]               INT            NULL,
    [SETOR]                  NVARCHAR (50)  NULL,
    [UTILIZACAO]             NVARCHAR (50)  NULL,
    [varusr]                 NVARCHAR (MAX) NULL,
    [ORCDETCMPMULTI]         INT            NULL,
    [ORCDET_COUNTER]         INT            NOT NULL,
    [ORCDET_EXP_FLAG_CMP]    BIT            NOT NULL,
    [ORCDET_EXP_FLAG_ALT]    BIT            NOT NULL,
    [ORCDET_EXP_FLAG_LRG]    BIT            NOT NULL,
    [ORCDET_KCAL]            MONEY          NULL,
    [controleCAD]            NVARCHAR (255) NULL,
    [vizatras]               NVARCHAR (50)  NULL,
    [orcdet_area]            FLOAT (53)     NULL,
    [vizinicial]             NVARCHAR (50)  NULL,
    [vizfinal]               NVARCHAR (50)  NULL,
    [quantidadeOriginal]     FLOAT (53)     NULL,
    [orcdet_item]            VARCHAR (20)   NULL,
    CONSTRAINT [PK_ORCDETAUX] PRIMARY KEY CLUSTERED ([ORCDET_COUNTER] ASC)
);

