CREATE TABLE [dbo].[OrcGrid] (
    [numeroOrcamento]         NVARCHAR (9)   NULL,
    [acessorio]               NVARCHAR (255) NULL,
    [altura]                  MONEY          NULL,
    [codigo]                  NVARCHAR (100) NULL,
    [comprimento]             MONEY          NULL,
    [conjunto]                NVARCHAR (50)  NULL,
    [controle]                INT            NULL,
    [cor]                     NVARCHAR (50)  NULL,
    [corte]                   NVARCHAR (50)  NULL,
    [dep_alt]                 BIT            NOT NULL,
    [dep_compr]               BIT            NOT NULL,
    [dep_prof]                BIT            NOT NULL,
    [departamento]            NVARCHAR (50)  NULL,
    [descritivo]              NVARCHAR (50)  NULL,
    [flag_imprimir]           BIT            NOT NULL,
    [grupo_descricao]         NVARCHAR (50)  NULL,
    [id_cad]                  NVARCHAR (50)  NULL,
    [IDCJTO]                  INT            NULL,
    [item]                    INT            NULL,
    [lista]                   NVARCHAR (50)  NULL,
    [MATERIALEXTRA]           INT            NULL,
    [n_grupo]                 NVARCHAR (50)  NULL,
    [n_subgrupo]              NVARCHAR (50)  NULL,
    [onde_incluir]            NVARCHAR (50)  NULL,
    [ORCGRID_CODIGO_ORI]      NVARCHAR (100) NULL,
    [ORCGRID_PRC_ALTURA]      INT            NULL,
    [ORCGRID_PRC_COMPRIMENTO] INT            NULL,
    [ORCGRID_PRC_FORMULA]     INT            NULL,
    [ORCGRID_PRC_LARGURA]     INT            NULL,
    [orcgridbase]             NVARCHAR (50)  NULL,
    [orcgridcorpesquisa]      NVARCHAR (20)  NULL,
    [OrcGridPeso]             MONEY          NULL,
    [OrcGridPrecoLista]       MONEY          NULL,
    [OrcGridProdutoImagem]    NVARCHAR (255) NULL,
    [OrcGridTipoProduto]      NVARCHAR (20)  NULL,
    [ori_alt]                 INT            NULL,
    [ori_compr]               INT            NULL,
    [ori_prof]                INT            NULL,
    [posicao_modulo]          NVARCHAR (50)  NULL,
    [profundidade]            MONEY          NULL,
    [qtde]                    FLOAT (53)     NULL,
    [setor]                   NVARCHAR (50)  NULL,
    [total]                   NVARCHAR (50)  NULL,
    [utilizacao]              NVARCHAR (50)  NULL,
    [valor]                   MONEY          NULL,
    [valor_unitario]          MONEY          NULL,
    [varusr]                  NVARCHAR (MAX) NULL,
    [vizatras]                NVARCHAR (50)  NULL,
    [vizfinal]                NVARCHAR (50)  NULL,
    [vizinicial]              NVARCHAR (50)  NULL,
    [orcgrid_counter]         INT            IDENTITY (1, 1) NOT NULL,
    [orcgrid_kcal]            MONEY          NULL,
    [controleCad]             NVARCHAR (255) NULL,
    [quantidadeOriginal]      FLOAT (53)     NULL,
    CONSTRAINT [PK_OrcGrid] PRIMARY KEY CLUSTERED ([orcgrid_counter] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_OrcGrid]
    ON [dbo].[OrcGrid]([numeroOrcamento] ASC, [orcgrid_counter] ASC);

