CREATE TABLE [dbo].[OrcMat] (
    [numeroOrcamento]        NVARCHAR (50)  NOT NULL,
    [COMISSAO_FATOR]         MONEY          NULL,
    [ENCARGOS_VALOR]         MONEY          NULL,
    [FreteValor]             MONEY          NULL,
    [IcmsBase]               MONEY          NULL,
    [IcmsFator]              MONEY          NULL,
    [IcmsRedutor]            MONEY          NULL,
    [IcmsValor]              MONEY          NULL,
    [IpiBase]                MONEY          NULL,
    [IpiFator]               MONEY          NULL,
    [IpiValor]               MONEY          NULL,
    [MontagemValor]          MONEY          NULL,
    [NATUREZA]               NVARCHAR (20)  NULL,
    [orcmat_codigo]          NVARCHAR (100) NULL,
    [orcmat_codigo_pai]      NVARCHAR (100) NULL,
    [orcmat_cor]             NVARCHAR (20)  NULL,
    [orcmat_descricao]       NVARCHAR (255) NULL,
    [ORCMAT_FORNECEDOR]      NVARCHAR (20)  NULL,
    [ORCMAT_IDMDESCRICAO]    NVARCHAR (70)  NULL,
    [ORCMAT_IDMUNIDADE]      NVARCHAR (5)   NULL,
    [orcmat_peso]            MONEY          NULL,
    [ORCMAT_PRC_ALTURA]      INT            NULL,
    [ORCMAT_PRC_COMPRIMENTO] INT            NULL,
    [ORCMAT_PRC_FORMULA]     INT            NULL,
    [ORCMAT_SEMCENTAVOS]     BIT            NULL,
    [ORCMAT_PRC_LARGURA]     INT            NULL,
    [ORCMAT_PRDUNIDADE]      NVARCHAR (5)   NULL,
    [orcmat_preco]           MONEY          NULL,
    [orcmat_preco_lista]     MONEY          NULL,
    [orcmat_preco_lista_sem] MONEY          NULL,
    [ORCMAT_PRECO_TAB]       MONEY          NULL,
    [orcmat_qtde]            FLOAT (53)     NULL,
    [ORCMATALTURA]           FLOAT (53)     NULL,
    [orcmatbase]             NVARCHAR (50)  NULL,
    [ORCMATCOMPRIMENTO]      FLOAT (53)     NULL,
    [OrcMatCorPesquisa]      NVARCHAR (20)  NULL,
    [ORCMATDESCONTO]         MONEY          NULL,
    [OrcMatGrupo]            INT            NULL,
    [ORCMATLARGURA]          FLOAT (53)     NULL,
    [orcmatlista]            NVARCHAR (20)  NULL,
    [ORCMATSITUACAO]         NVARCHAR (20)  NULL,
    [OrcMatSubGrupo]         NVARCHAR (2)   NULL,
    [PISCOFINSFATOR]         MONEY          NULL,
    [PISCOFINSVALOR]         MONEY          NULL,
    [PRDORCCHK]              INT            NULL,
    [preco_fixo]             MONEY          NULL,
    [PISFATOR]               MONEY          NULL,
    [COFINSFATOR]            MONEY          NULL,
    [ROYALTIES_CALCULO]      MONEY          NULL,
    [CUSTO_CALCULO]          MONEY          NULL,
    [REPASSE_CALCULO]        MONEY          NULL,
    [FRETE_CALCULO]          MONEY          NULL,
    [INDICE_COMPRA]          MONEY          NULL,
    [INDICE_FATURAMENTO]     MONEY          NULL,
    [IPI_NAO_INCLUSO]        MONEY          NULL,
    [orcmat_counter]         INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_OrcMat] PRIMARY KEY CLUSTERED ([numeroOrcamento] ASC, [orcmat_counter] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_OrcMat]
    ON [dbo].[OrcMat]([numeroOrcamento] ASC);

