CREATE TABLE [dbo].[ORCVARPRJ] (
    [idORCVARPRJ]        INT            IDENTITY (1, 1) NOT NULL,
    [ORCVARPRJ_VARIAVEL] NVARCHAR (30)  NOT NULL,
    [ORCVARPRJ_VALOR]    NVARCHAR (MAX) NULL,
    [numeroOrcamento]    NVARCHAR (9)   NOT NULL,
    CONSTRAINT [PK_ORCVARPRJ] PRIMARY KEY CLUSTERED ([ORCVARPRJ_VARIAVEL] ASC, [numeroOrcamento] ASC)
);

