CREATE TABLE [dbo].[Pescab] (
    [pescab_codigo]          INT           NOT NULL,
    [pescab_nome]            NVARCHAR (40) NULL,
    [pescab_lc_especie]      NVARCHAR (4)  NULL,
    [pescab_lc_endereco]     NVARCHAR (40) NULL,
    [pescab_lc_numero]       NVARCHAR (6)  NULL,
    [pescab_lc_complemento]  NVARCHAR (30) NULL,
    [pescab_lc_bairro]       NVARCHAR (30) NULL,
    [pescab_lc_municipio]    NVARCHAR (30) NULL,
    [pescab_uf]              NVARCHAR (2)  NULL,
    [pescab_cep]             INT           NULL,
    [pescab_ie]              NVARCHAR (18) NULL,
    [pescab_rg]              NVARCHAR (18) NULL,
    [pescab_im]              NVARCHAR (30) NULL,
    [pescab_suframa]         NVARCHAR (18) NULL,
    [pescab_ramo]            NVARCHAR (30) NULL,
    [pescab_visita]          INT           NULL,
    [PAISCODIGO]             NVARCHAR (5)  NULL,
    [PESCAB_CONTATO]         NVARCHAR (40) NULL,
    [PESCAB_FONE]            NVARCHAR (20) NULL,
    [PESCAB_FAX]             NVARCHAR (20) NULL,
    [PESCAB_EMAIL]           NVARCHAR (50) NULL,
    [pescab_cob_cep]         INT           NULL,
    [pescab_cob_especie]     NVARCHAR (4)  NULL,
    [pescab_cob_endereco]    NVARCHAR (40) NULL,
    [pescab_cob_numero]      NVARCHAR (6)  NULL,
    [pescab_cob_complemento] NVARCHAR (30) NULL,
    [pescab_cob_bairro]      NVARCHAR (30) NULL,
    [pescab_cob_municipio]   NVARCHAR (30) NULL,
    [pescab_cob_uf]          NVARCHAR (2)  NULL,
    [pescab_integracao]      NVARCHAR (20) NULL,
    [PESCAB_CODINOME]        NVARCHAR (50) NULL,
    [concorrente]            BIT           NULL,
    [idPescab]               INT           IDENTITY (1, 1) NOT NULL
);

