CREATE TABLE [dbo].[PRDEST] (
    [PRDORCCODIGOPAI]             NVARCHAR (20)  NULL,
    [PRDESTSEQUENCIAL]            INT            NULL,
    [PRDORCCODIGOFILHO]           NVARCHAR (20)  NULL,
    [PRDESTCONDICAO]              NVARCHAR (MAX) NULL,
    [PRDESTFORMULA]               NVARCHAR (MAX) NULL,
    [PRDESTDEPARA]                NVARCHAR (MAX) NULL,
    [FORMULAPRECO]                NVARCHAR (MAX) NULL,
    [COMPRIMENTO]                 NVARCHAR (255) NULL,
    [ALTURA]                      NVARCHAR (255) NULL,
    [PROFUNDIDADE]                NVARCHAR (255) NULL,
    [FANTASMA]                    BIT            NULL,
    [ATUALIZADOEM]                DATETIME       NULL,
    [IMPORTADOEM]                 DATETIME       NULL,
    [PRDEST_FORMULA_COMPRIMENTO]  NVARCHAR (MAX) NULL,
    [PRDEST_FORMULA_ALTURA]       NVARCHAR (MAX) NULL,
    [PRDEST_FORMULA_PROFUNDIDADE] NVARCHAR (MAX) NULL,
    [PRDEST_QTDE]                 NVARCHAR (MAX) NULL,
    [PRDEST_PESO]                 NVARCHAR (MAX) NULL,
    [PRDEST_PESO_FIXO]            NVARCHAR (MAX) NULL,
    [PRDEST_PESO_COMPRIMENTO]     NVARCHAR (MAX) NULL,
    [PRDEST_PESO_ALTURA]          NVARCHAR (MAX) NULL,
    [PRDEST_PESO_PROFUNDIDADE]    NVARCHAR (MAX) NULL,
    [PRDEST_FORMULA_MULTIPLICAR]  NVARCHAR (MAX) NULL
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[PRDEST] TO [interclick]
    AS [dbo];

