CREATE TABLE [dbo].[prdgrpAuxiliar] (
    [Grupo]                    INT            NULL,
    [Subgrupo]                 NVARCHAR (2)   NULL,
    [Descricao]                NVARCHAR (50)  NULL,
    [Tipo_cad]                 NVARCHAR (4)   NULL,
    [Proposta_ordem]           INT            NULL,
    [Proposta_grupo]           INT            NULL,
    [Proposta_descricao]       NVARCHAR (50)  NULL,
    [Proposta_imagem]          NVARCHAR (255) NULL,
    [Proposta_texto_item]      NVARCHAR (150) NULL,
    [Proposta_texto_base]      NVARCHAR (150) NULL,
    [Agrupamento]              NVARCHAR (255) NULL,
    [Imprimir_sempre]          BIT            NULL,
    [Preco_cor]                BIT            NULL,
    [Data_preco_cor]           DATETIME       NULL,
    [Tipo_produto]             NVARCHAR (30)  NULL,
    [listar_dtc_produtos]      BIT            NULL,
    [BancoUsar]                NVARCHAR (50)  NULL,
    [GrupoBusca]               NVARCHAR (50)  NULL,
    [dividir_qtde_por_dois]    BIT            NULL,
    [base]                     NVARCHAR (50)  NULL,
    [suprimir_impressao_itens] BIT            NULL,
    [VARUSR]                   NVARCHAR (MAX) NULL,
    [RTFOPCAO]                 INT            NULL,
    [RTFCAMPOSNORMAIS]         NVARCHAR (100) NULL,
    [RTFCAMPOSESPECIAIS]       NVARCHAR (100) NULL,
    [RTFCAMINHO]               NVARCHAR (50)  NULL,
    [GRUPO_CHECK]              INT            NULL,
    [PRDGRPIMPRESSAOOPCOES]    NVARCHAR (MAX) NULL,
    [LIMITEVALOR]              FLOAT (53)     NULL,
    [PRDGRP_IMPRIMIR_PELO]     NVARCHAR (20)  NULL,
    [PRDGRP_QTDE_MOD]          FLOAT (53)     NULL,
    [PRDGRP_AGRUPAR_QTDE_MOD]  FLOAT (53)     NULL,
    [PRDGRP_IMP_COMP_QTDE]     BIT            NULL,
    [DSCFAT]                   NVARCHAR (150) NULL,
    [TABELA_CORTE]             NVARCHAR (50)  NULL,
    [TABELA_COMPR]             NVARCHAR (50)  NULL,
    [PRDGRP_OUTROS]            NVARCHAR (MAX) NULL,
    [PRDGRPCMPMULT]            INT            NULL,
    [imprimir_utilizacao]      BIT            NULL,
    [idPrdGrp]                 INT            IDENTITY (1, 1) NOT NULL
);

