CREATE TABLE [dbo].[VARCAB] (
    [VARCABCODIGO]       NVARCHAR (3)  NULL,
    [VARCABDESCRICAO]    NVARCHAR (50) NULL,
    [VARDETCODIGOPADRAO] NVARCHAR (3)  NULL,
    [VARCABTIPO]         NVARCHAR (20) NULL
);

