CREATE TABLE [dbo].[VARPRDEST] (
    [VARPRDESTCOD] NVARCHAR (20)  NULL,
    [VARPRDESTDSC] NVARCHAR (50)  NULL,
    [VALOR]        FLOAT (53)     NULL,
    [VARPRDESTDTC] NVARCHAR (MAX) NULL,
    [VARPRDESTTIP] INT            NULL
);

