CREATE TABLE [dbo].[Produto_Importacao] (
    [cd_produto]                INT          NOT NULL,
    [qt_leadtime_prod_import]   INT          NULL,
    [qt_transtime_prod_import]  INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_fase_produto]           INT          NULL,
    [cd_pais]                   INT          NULL,
    [cd_moeda]                  INT          NULL,
    [vl_produto_importacao]     FLOAT (53)   NULL,
    [cd_regime_tributacao]      INT          NULL,
    [cd_norma_origem]           INT          NULL,
    [nm_obs_produto_importacao] VARCHAR (40) NULL,
    [qt_lead_time_produto]      INT          NULL,
    [qt_transtime_produto]      FLOAT (53)   NULL,
    [cd_fabricante]             INT          NULL,
    [cd_pais_procedencia]       INT          NULL,
    [qt_multiplo_embalagem]     FLOAT (53)   NULL,
    [ds_produto_importacao]     TEXT         NULL,
    [cd_part_number_produto]    VARCHAR (30) NULL,
    [qt_minimo_importacao]      FLOAT (53)   NULL,
    [ic_pis_importacao]         CHAR (1)     NULL,
    [ic_confins_importacao]     CHAR (1)     NULL,
    [ic_ipi_importacao]         CHAR (1)     NULL,
    [ic_icms_importacao]        CHAR (1)     NULL,
    CONSTRAINT [PK_Produto_Importacao] PRIMARY KEY CLUSTERED ([cd_produto] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Produto_Importacao_Fase_Produto] FOREIGN KEY ([cd_fase_produto]) REFERENCES [dbo].[Fase_Produto] ([cd_fase_produto]),
    CONSTRAINT [FK_Produto_Importacao_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda]),
    CONSTRAINT [FK_Produto_Importacao_Norma_Origem] FOREIGN KEY ([cd_norma_origem]) REFERENCES [dbo].[Norma_Origem] ([cd_norma_origem]),
    CONSTRAINT [FK_Produto_Importacao_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Produto_Importacao_Regime_Tributacao] FOREIGN KEY ([cd_regime_tributacao]) REFERENCES [dbo].[Regime_Tributacao] ([cd_regime_tributacao])
);

