CREATE TABLE [dbo].[Produto_Objeto] (
    [cd_produto]              INT           NOT NULL,
    [cd_tipo_objeto]          INT           NOT NULL,
    [nm_titulo_produto]       VARCHAR (60)  NULL,
    [nm_compl_titulo_produto] VARCHAR (40)  NULL,
    [cd_editora]              INT           NULL,
    [cd_isbn_produto]         VARCHAR (20)  NULL,
    [nm_edicao_produto]       VARCHAR (20)  NULL,
    [cd_pais]                 INT           NULL,
    [cd_idioma]               INT           NULL,
    [ds_sinopse_produto]      TEXT          NULL,
    [nm_imagem_produto]       VARCHAR (100) NULL,
    [ds_sumario_produto]      TEXT          NULL,
    [nm_formato_produto]      VARCHAR (10)  NULL,
    [qt_pagina_produto]       INT           NULL,
    [dt_lancamento_produto]   DATETIME      NULL,
    [cd_ano_produto]          INT           NULL,
    [nm_plataforma_produto]   VARCHAR (60)  NULL,
    [nm_direcao_produto]      VARCHAR (100) NULL,
    [ds_elenco_produto]       TEXT          NULL,
    [nm_duracao_produto]      VARCHAR (15)  NULL,
    [cd_genero_produto]       INT           NULL,
    [cd_assunto_produto]      INT           NULL,
    [cd_area_produto]         INT           NULL,
    [cd_distribuidor]         INT           NULL,
    [cd_produtora]            INT           NULL,
    [nm_trailler_produto]     VARCHAR (100) NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    CONSTRAINT [PK_Produto_Objeto] PRIMARY KEY CLUSTERED ([cd_produto] ASC, [cd_tipo_objeto] ASC) WITH (FILLFACTOR = 90)
);

