CREATE TABLE [dbo].[Produto_Saldo] (
    [cd_produto]                INT          NOT NULL,
    [cd_fase_produto]           INT          NOT NULL,
    [qt_saldo_reserva_produto]  FLOAT (53)   NULL,
    [qt_saldo_atual_produto]    FLOAT (53)   NULL,
    [qt_implantacao_produto]    FLOAT (53)   NULL,
    [qt_consig_produto]         FLOAT (53)   NULL,
    [qt_terceiro_produto]       FLOAT (53)   NULL,
    [qt_entrada_produto]        FLOAT (53)   NULL,
    [qt_saida_produto]          FLOAT (53)   NULL,
    [qt_minimo_produto]         FLOAT (53)   NULL,
    [qt_maximo_produto]         FLOAT (53)   NULL,
    [qt_consumo_produto]        FLOAT (53)   NULL,
    [qt_prev_ent1_produto]      FLOAT (53)   NULL,
    [qt_prev_ent2_produto]      FLOAT (53)   NULL,
    [qt_prev_ent3_produto]      FLOAT (53)   NULL,
    [dt_prev_ent1_produto]      DATETIME     NULL,
    [dt_prev_ent2_produto]      DATETIME     NULL,
    [dt_prev_ent3_produto]      DATETIME     NULL,
    [qt_req_compra_produto]     FLOAT (53)   NULL,
    [qt_pd_compra_produto]      FLOAT (53)   NULL,
    [dt_atual_produto]          DATETIME     NULL,
    [dt_implantacao_produto]    DATETIME     NULL,
    [dt_consig_produto]         DATETIME     NULL,
    [dt_terceiro_produto]       DATETIME     NULL,
    [dt_reserva_produto]        DATETIME     NULL,
    [dt_ultima_entrada_produto] DATETIME     NULL,
    [dt_ultima_saida_produto]   DATETIME     NULL,
    [qt_importacao_produto]     FLOAT (53)   NULL,
    [qt_minimo_imp_produto]     FLOAT (53)   NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_reserva_saldo_produto]  FLOAT (53)   NULL,
    [cd_ped_comp_imp1]          INT          NULL,
    [dt_ped_comp_imp1]          DATETIME     NULL,
    [qt_ped_comp_imp1]          FLOAT (53)   NULL,
    [cd_ped_comp_imp2]          INT          NULL,
    [dt_ped_comp_imp2]          DATETIME     NULL,
    [qt_ped_comp_imp2]          FLOAT (53)   NULL,
    [cd_ped_comp_imp3]          INT          NULL,
    [dt_ped_comp_imp3]          DATETIME     NULL,
    [qt_ped_comp_imp3]          FLOAT (53)   NULL,
    [nm_di1]                    VARCHAR (40) NULL,
    [nm_di2]                    VARCHAR (40) NULL,
    [nm_di3]                    VARCHAR (40) NULL,
    [qt_padrao_compra]          FLOAT (53)   NULL,
    [qt_padrao_estoque]         FLOAT (53)   NULL,
    [qt_padrao_lote_compra]     FLOAT (53)   NULL,
    [qt_prev_entrada_produto]   FLOAT (53)   NULL,
    [vl_fob_produto]            FLOAT (53)   NULL,
    [vl_custo_contabil_produto] FLOAT (53)   NULL,
    [vl_fob_convertido]         FLOAT (53)   NULL,
    [qt_real_produto]           FLOAT (53)   NULL,
    [qt_producao_produto]       FLOAT (53)   NULL,
    [cd_loja]                   INT          NULL,
    [qt_peso_reserva_produto]   FLOAT (53)   NULL,
    [qt_peso_atual_produto]     FLOAT (53)   NULL,
    [ic_fixo_estoque_minimo]    CHAR (1)     NULL,
    [qt_alocado_produto]        FLOAT (53)   NULL,
    CONSTRAINT [PK_Produto_Saldo] PRIMARY KEY CLUSTERED ([cd_produto] ASC, [cd_fase_produto] ASC) WITH (FILLFACTOR = 90)
);

