CREATE TABLE [dbo].[Programacao_Composicao] (
    [cd_programacao]            INT           NOT NULL,
    [cd_item_programacao]       INT           NOT NULL,
    [cd_processo]               INT           NULL,
    [cd_item_processo]          INT           NULL,
    [cd_operacao]               INT           NULL,
    [cd_numero_operacao]        INT           NULL,
    [qt_hora_prog_operacao]     FLOAT (53)    NULL,
    [qt_hora_real_producao]     FLOAT (53)    NULL,
    [dt_ini_prod_operacao]      DATETIME      NULL,
    [dt_fim_prod_operacao]      DATETIME      NULL,
    [dt_reprog_prod_operacao]   DATETIME      NULL,
    [dt_canc_prod_operacao]     DATETIME      NULL,
    [cd_operacao_cancelamento]  INT           NULL,
    [nm_motivo_canc_operacao]   VARCHAR (40)  NULL,
    [dt_susp_prod_operacao]     DATETIME      NULL,
    [cd_suspenso_producao]      INT           NULL,
    [dt_mat_prima_operacao]     DATETIME      NULL,
    [dt_aponta_prod_operacao]   DATETIME      NULL,
    [ic_desenho_operacao]       CHAR (1)      NULL,
    [ic_projeto_operacao]       CHAR (1)      NULL,
    [ic_cnc_operacao]           CHAR (1)      NULL,
    [nm_obs_operacao]           VARCHAR (60)  NULL,
    [ic_ordem_fab]              CHAR (1)      NULL,
    [ic_emitida_ordem_fab]      CHAR (1)      NULL,
    [dt_emitida_ordem_fab]      DATETIME      NULL,
    [cd_ordem_fab]              INT           NULL,
    [ic_antecipada_operacao]    CHAR (1)      NULL,
    [ic_reserva_operacao]       CHAR (1)      NULL,
    [cd_programador_cnc]        INT           NULL,
    [dt_lanc_mapa_programacao]  DATETIME      NULL,
    [hr_ini_prod_operacao]      VARCHAR (8)   NULL,
    [hr_fim_prod_operacao]      VARCHAR (8)   NULL,
    [ic_tipo_lancamento]        CHAR (1)      NULL,
    [ds_prog_composicao]        TEXT          NULL,
    [dt_lancamento_baixa_item]  DATETIME      NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_operador]               INT           NULL,
    [dt_programa_cnc]           DATETIME      NULL,
    [nm_programa_cnc]           VARCHAR (40)  NULL,
    [nm_obs_programa_cnc]       VARCHAR (40)  NULL,
    [nm_doc_programa_cnc]       VARCHAR (100) NULL,
    [cd_pedido_venda]           INT           NULL,
    [cd_item_pedido_venda]      INT           NULL,
    [cd_reserva_programacao]    INT           NULL,
    [nm_obs_item_programacao]   VARCHAR (60)  NULL,
    [qt_item_programacao]       FLOAT (53)    NULL,
    [qt_saldo_item_programacao] FLOAT (53)    NULL
);

