CREATE TABLE [dbo].[Projeto_Composicao] (
    [cd_projeto]                INT           NOT NULL,
    [cd_item_projeto]           INT           NOT NULL,
    [dt_item_projeto]           DATETIME      NULL,
    [qt_item_projeto]           INT           NULL,
    [cd_desenho_projeto]        INT           NULL,
    [cd_tipo_projeto]           INT           NULL,
    [cd_projetista]             INT           NULL,
    [dt_conf_projeto]           DATETIME      NULL,
    [dt_aprov_projeto]          DATETIME      NULL,
    [nm_item_obs_projeto]       TEXT          NULL,
    [nm_item_desenho_projeto]   VARCHAR (50)  NULL,
    [nm_item_caminho_projeto]   VARCHAR (200) NULL,
    [ic_lista_material_projeto] CHAR (1)      NULL,
    [cd_cod_projeto]            INT           NULL,
    [cd_status_projeto]         INT           NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [nm_projeto_composicao]     VARCHAR (40)  NULL,
    [cd_tipo_produto_projeto]   INT           NULL,
    [dt_liberacao_item_projeto] DATETIME      NULL,
    [dt_inicio_projeto]         DATETIME      NULL,
    [dt_fim_projeto]            DATETIME      NULL,
    [cd_projetista_liberacao]   INT           NULL,
    [qt_hora_estimada_item]     FLOAT (53)    NULL,
    [qt_hora_real_item]         FLOAT (53)    NULL,
    [cd_ref_item_projeto]       INT           NULL,
    [dt_conclusao_item_projeto] DATETIME      NULL,
    CONSTRAINT [PK_Projeto_Composicao] PRIMARY KEY CLUSTERED ([cd_projeto] ASC, [cd_item_projeto] ASC) WITH (FILLFACTOR = 90)
);

