CREATE TABLE [dbo].[Projeto] (
    [cd_projeto]                INT           NOT NULL,
    [dt_entrada_projeto]        DATETIME      NULL,
    [cd_interno_projeto]        CHAR (15)     NOT NULL,
    [dt_inicio_projeto]         DATETIME      NULL,
    [dt_fim_projeto]            DATETIME      NULL,
    [dt_info_cliente_projeto]   DATETIME      NULL,
    [dt_info_processo_projeto]  DATETIME      NULL,
    [dt_entrega_cliente]        DATETIME      NULL,
    [ic_padrao_projeto]         CHAR (1)      NULL,
    [cd_pedido_venda]           INT           NULL,
    [cd_item_pedido_venda]      INT           NULL,
    [nm_produto_cliente]        VARCHAR (40)  NULL,
    [qt_espessura_projeto]      FLOAT (53)    NULL,
    [qt_largura_projeto]        FLOAT (53)    NULL,
    [qt_comprimento_projeto]    FLOAT (53)    NULL,
    [ic_revisado_projeto]       CHAR (1)      NULL,
    [ds_projeto]                TEXT          NULL,
    [cd_status_projeto]         INT           NOT NULL,
    [cd_tipo_projeto]           INT           NULL,
    [cd_projetista]             INT           NULL,
    [cd_material_plastico]      INT           NULL,
    [ic_desenho_projeto]        CHAR (1)      NULL,
    [ic_simulacao_injecao]      CHAR (1)      NULL,
    [nm_caminho_simulacao]      VARCHAR (100) NULL,
    [nm_comp_material_plastico] VARCHAR (20)  NULL,
    [cd_pedido_venda_molde]     INT           NULL,
    [cd_item_pedido_molde]      INT           NULL,
    [ic_cancelamento_projeto]   CHAR (1)      NULL,
    [ic_garantia_projeto]       CHAR (1)      NULL,
    [cd_consulta]               INT           NULL,
    [qt_distancia_centros]      FLOAT (53)    NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_item_consulta]          INT           NULL,
    [nm_caminho_produto_final]  VARCHAR (200) NULL,
    [nm_projeto]                VARCHAR (40)  NULL,
    [cd_cliente]                INT           NULL,
    [dt_liberacao_item_projeto] DATETIME      NULL,
    [nm_desenho_projeto]        VARCHAR (50)  NULL,
    [cd_projetista_liberacao]   INT           NULL,
    [qt_hora_real_projeto]      FLOAT (53)    NULL,
    [qt_hora_estimada_projeto]  FLOAT (53)    NULL,
    [vl_total_fab_projeto]      FLOAT (53)    NULL,
    [vl_total_compra_projeto]   FLOAT (53)    NULL,
    [vl_custo_real_projeto]     FLOAT (53)    NULL,
    [vl_custo_estimado_projeto] FLOAT (53)    NULL,
    [vl_total_projeto]          FLOAT (53)    NULL,
    [qt_peso_produto_projeto]   FLOAT (53)    NULL,
    [ic_montagem_prod_cliente]  CHAR (1)      NULL,
    [cd_centro_custo]           INT           NULL,
    CONSTRAINT [PK_Projeto] PRIMARY KEY NONCLUSTERED ([cd_projeto] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Projeto_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo])
);

