CREATE TABLE [dbo].[Prospeccao_Historico] (
    [cd_prospeccao]             INT          NOT NULL,
    [cd_item_prospeccao]        INT          NOT NULL,
    [ic_apresentacao]           CHAR (1)     NULL,
    [ic_negocio]                CHAR (1)     NULL,
    [ic_email]                  CHAR (1)     NULL,
    [ic_visita]                 CHAR (1)     NULL,
    [ds_historico_Prospeccao]   TEXT         NULL,
    [nm_historico_prospeccao]   VARCHAR (30) NULL,
    [dt_prospeccao_historico]   DATETIME     NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_usuario]                INT          NULL,
    [dt_historico_retorno]      DATETIME     NULL,
    [dt_real_retorno]           DATETIME     NULL,
    [cd_cliente_assunto]        INT          NULL,
    [nm_assunto_prospeccao]     VARCHAR (40) NULL,
    [cd_acao_prospeccao]        INT          NULL,
    [cd_vendedor]               INT          NULL,
    [cd_operador_telemarketing] INT          NULL,
    [cd_prospeccao_contato]     INT          NULL,
    [cd_concorrente]            INT          NULL,
    [cd_cliente_fase]           INT          NULL,
    [cd_cliente_prospeccao]     INT          NULL,
    CONSTRAINT [PK_Prospeccao_Historico] PRIMARY KEY CLUSTERED ([cd_prospeccao] ASC, [cd_item_prospeccao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Prospeccao_Historico_Acao_Prospeccao] FOREIGN KEY ([cd_acao_prospeccao]) REFERENCES [dbo].[Acao_Prospeccao] ([cd_acao_prospeccao]),
    CONSTRAINT [FK_Prospeccao_Historico_Cliente_Fase] FOREIGN KEY ([cd_cliente_fase]) REFERENCES [dbo].[Cliente_Fase] ([cd_cliente_fase]),
    CONSTRAINT [FK_Prospeccao_Historico_Cliente_Prospeccao] FOREIGN KEY ([cd_cliente_prospeccao]) REFERENCES [dbo].[Cliente_Prospeccao] ([cd_cliente_prospeccao]),
    CONSTRAINT [FK_Prospeccao_Historico_Concorrente] FOREIGN KEY ([cd_concorrente]) REFERENCES [dbo].[Concorrente] ([cd_concorrente]),
    CONSTRAINT [FK_Prospeccao_Historico_Operador_Telemarketing] FOREIGN KEY ([cd_operador_telemarketing]) REFERENCES [dbo].[Operador_Telemarketing] ([cd_operador_telemarketing]),
    CONSTRAINT [FK_Prospeccao_Historico_Prospeccao] FOREIGN KEY ([cd_prospeccao]) REFERENCES [dbo].[Prospeccao] ([cd_prospeccao]),
    CONSTRAINT [FK_Prospeccao_Historico_Vendedor] FOREIGN KEY ([cd_vendedor]) REFERENCES [dbo].[Vendedor] ([cd_vendedor])
);

