CREATE TABLE [dbo].[Prospeccao] (
    [cd_prospeccao]             INT           NOT NULL,
    [cd_campanha]               INT           NULL,
    [dt_prospeccao]             DATETIME      NULL,
    [cd_operador_telemarketing] INT           NULL,
    [cd_cliente_prospeccao]     INT           NULL,
    [cd_vendedor]               INT           NULL,
    [cd_tipo_destinatario]      INT           NULL,
    [cd_status_prospeccao]      INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_usuario]                INT           NULL,
    [nm_obs_prospeccao]         VARCHAR (200) NULL,
    [dt_perda]                  DATETIME      NULL,
    [dt_fechamento]             DATETIME      NULL,
    [dt_visita]                 DATETIME      NULL,
    [dt_retorno_prospeccao]     DATETIME      NULL,
    [qt_dia_retorno]            INT           NULL,
    [cd_concorrente]            INT           NULL,
    [dt_apresentacao]           DATETIME      NULL,
    [cd_vendedor_apresentacao]  INT           NULL,
    [cd_vendedor_visita]        INT           NULL,
    [pc_prospeccao]             FLOAT (53)    NULL,
    [nm_obs_proposta]           VARCHAR (50)  NULL,
    [cd_consulta]               INT           NULL,
    [dt_proposta_prospeccao]    DATETIME      NULL,
    [cd_acao_prospeccao]        INT           NULL,
    [dt_email_prospeccao]       DATETIME      NULL,
    [cd_vendedor_email]         INT           NULL,
    [nm_documento_prospeccao]   VARCHAR (100) NULL,
    [cd_prospeccao_contato]     INT           NULL,
    [ds_prospeccao]             TEXT          NULL,
    CONSTRAINT [PK_Prospeccao] PRIMARY KEY CLUSTERED ([cd_prospeccao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Prospeccao_Acao_Prospeccao] FOREIGN KEY ([cd_acao_prospeccao]) REFERENCES [dbo].[Acao_Prospeccao] ([cd_acao_prospeccao]),
    CONSTRAINT [FK_Prospeccao_Campanha] FOREIGN KEY ([cd_campanha]) REFERENCES [dbo].[Campanha] ([cd_campanha]),
    CONSTRAINT [FK_Prospeccao_Cliente_Prospeccao] FOREIGN KEY ([cd_cliente_prospeccao]) REFERENCES [dbo].[Cliente_Prospeccao] ([cd_cliente_prospeccao]),
    CONSTRAINT [FK_Prospeccao_Concorrente] FOREIGN KEY ([cd_concorrente]) REFERENCES [dbo].[Concorrente] ([cd_concorrente]),
    CONSTRAINT [FK_Prospeccao_Consulta] FOREIGN KEY ([cd_consulta]) REFERENCES [dbo].[Consulta] ([cd_consulta]),
    CONSTRAINT [FK_Prospeccao_Operador_Telemarketing] FOREIGN KEY ([cd_operador_telemarketing]) REFERENCES [dbo].[Operador_Telemarketing] ([cd_operador_telemarketing]),
    CONSTRAINT [FK_Prospeccao_Tipo_Destinatario] FOREIGN KEY ([cd_tipo_destinatario]) REFERENCES [dbo].[Tipo_Destinatario] ([cd_tipo_destinatario]),
    CONSTRAINT [FK_Prospeccao_Vendedor] FOREIGN KEY ([cd_vendedor]) REFERENCES [dbo].[Vendedor] ([cd_vendedor])
);

