CREATE TABLE [dbo].[Receita_Federal] (
    [cd_receita_federal]        INT           NOT NULL,
    [nm_fantasia_receita_fed]   VARCHAR (15)  NULL,
    [ds_receita_federal]        TEXT          NULL,
    [nm_endereco_receita_fed]   VARCHAR (40)  NULL,
    [nm_bairro_receita_federal] VARCHAR (30)  NULL,
    [cd_pais]                   INT           NULL,
    [cd_estado]                 INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_cep]                    CHAR (9)      NULL,
    [cd_identificacao_agencia]  CHAR (10)     NULL,
    [cd_ddd_receita_federal]    CHAR (4)      NULL,
    [cd_fone_receita_federal]   VARCHAR (15)  NULL,
    [cd_fax_receita_federal]    VARCHAR (15)  NULL,
    [nm_site_receita_federal]   VARCHAR (100) NULL,
    [nm_email_receita_federal]  VARCHAR (100) NULL,
    [nm_contato_receita_fed]    VARCHAR (30)  NULL,
    [nm_email_contato_receita]  VARCHAR (100) NULL,
    [nm_observacao_receita_fed] VARCHAR (60)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [dt_cadastro_receita_fed]   DATETIME      NULL,
    [nm_complemento_endereco]   VARCHAR (30)  NULL,
    [cd_numero_endereco]        CHAR (10)     NULL,
    [cd_identifica_cep]         INT           NULL,
    [cd_inscestadual]           VARCHAR (18)  NULL,
    [cd_cnpj]                   VARCHAR (18)  NULL,
    [cd_siscomex]               INT           NULL,
    CONSTRAINT [PK_RECEITA_FEDERAL] PRIMARY KEY CLUSTERED ([cd_receita_federal] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais])
);

