CREATE TABLE [dbo].[Reducao_Z] (
    [cd_controle]             INT         NOT NULL,
    [dt_reducao]              DATETIME    NULL,
    [hr_reducao]              VARCHAR (8) NULL,
    [cd_coo]                  INT         NULL,
    [dt_movimento_reducao]    DATETIME    NULL,
    [qt_contador_reducao]     INT         NULL,
    [qt_contador_reinicio]    INT         NULL,
    [qt_geral_nao_fiscal]     INT         NULL,
    [qt_comprovante]          INT         NULL,
    [qt_geral_cancelada]      INT         NULL,
    [qt_geral_gerencial]      FLOAT (53)  NULL,
    [qt_cupom_fiscal]         INT         NULL,
    [qt_cupom_cancelado]      INT         NULL,
    [vl_totalizador_geral]    FLOAT (53)  NULL,
    [vl_venda_bruta_diaria]   FLOAT (53)  NULL,
    [vl_cancelamento_icms]    FLOAT (53)  NULL,
    [vl_desconto_icms]        FLOAT (53)  NULL,
    [vl_total_issqn]          FLOAT (53)  NULL,
    [vl_cancelamento_issqn]   FLOAT (53)  NULL,
    [vl_desconto_issqn]       FLOAT (53)  NULL,
    [vl_venda_liquida]        FLOAT (53)  NULL,
    [vl_acrescimo_icms]       FLOAT (53)  NULL,
    [vl_acrescimo_iss]        FLOAT (53)  NULL,
    [vl_base_icms]            FLOAT (53)  NULL,
    [vl_icms]                 FLOAT (53)  NULL,
    [vl_base_issqn]           FLOAT (53)  NULL,
    [vl_issqn]                FLOAT (53)  NULL,
    [vl_totalizador_nt]       FLOAT (53)  NULL,
    [vl_st_icms]              FLOAT (53)  NULL,
    [vl_isento_icms]          FLOAT (53)  NULL,
    [vl_nao_incidencia_ICMS]  FLOAT (53)  NULL,
    [vl_st_issqn]             FLOAT (53)  NULL,
    [vl_isento_issqn]         FLOAT (53)  NULL,
    [vl_nao_incidencia_issqn] FLOAT (53)  NULL,
    [cd_usuario]              INT         NULL,
    [dt_usuario]              DATETIME    NULL,
    [vl_canc_nao_fiscal]      FLOAT (53)  NULL,
    [vl_desc_nao_fiscal]      FLOAT (53)  NULL,
    [vl_acrescimo_nao_fiscal] FLOAT (53)  NULL,
    [qt_sangria]              INT         NULL,
    [vl_sangria]              FLOAT (53)  NULL,
    [qt_suprimento]           INT         NULL,
    [vl_suprimento]           FLOAT (53)  NULL,
    [vl_total_nao_fiscal]     FLOAT (53)  NULL,
    [qt_relatorio_gerencial]  INT         NULL,
    [vl_dinheiro]             FLOAT (53)  NULL,
    [vl_cartao]               FLOAT (53)  NULL,
    [vl_cartao_credito]       FLOAT (53)  NULL,
    [vl_cheque]               FLOAT (53)  NULL,
    [vl_cartao_debito]        FLOAT (53)  NULL,
    [vl_troco]                FLOAT (53)  NULL,
    [qt_cupom_nao_emitido]    FLOAT (53)  NULL,
    [hr_tempo_emitindo]       VARCHAR (8) NULL,
    [hr_tempo_operacional]    VARCHAR (8) NULL,
    [qt_reducao_restante]     INT         NULL,
    [dt_final_reducao]        DATETIME    NULL,
    [hr_final_emissao]        VARCHAR (8) NULL,
    CONSTRAINT [PK_Reducao_Z] PRIMARY KEY CLUSTERED ([cd_controle] ASC) WITH (FILLFACTOR = 90)
);

