CREATE TABLE [dbo].[Registro_Suporte] (
    [cd_registro_suporte]     INT           NOT NULL,
    [dt_registro_suporte]     DATETIME      NOT NULL,
    [cd_prioridade_suporte]   INT           NULL,
    [cd_nivel_suporte]        INT           NULL,
    [cd_modulo]               INT           NOT NULL,
    [cd_versao_modulo]        VARCHAR (15)  NULL,
    [dt_ocorrencia_suporte]   DATETIME      NULL,
    [ds_ocorrencia_suporte]   TEXT          NULL,
    [ds_mensagem_suporte]     TEXT          NULL,
    [ds_observacao_suporte]   TEXT          NULL,
    [cd_menu_historico]       INT           NULL,
    [nm_doc_registro_suporte] VARCHAR (100) NULL,
    [dt_solucao_registro]     DATETIME      NULL,
    [cd_consultor]            INT           NULL,
    [nm_solucao_registro]     VARCHAR (100) NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [dt_solucao_dev]          DATETIME      NULL,
    [ds_solucao]              TEXT          NULL,
    [dt_retorno_cliente]      DATETIME      NULL,
    [cd_funcao]               INT           NULL,
    [cd_menu]                 INT           NULL,
    [nm_rs]                   VARCHAR (25)  NULL,
    [cd_status_suporte]       INT           NULL,
    [cd_cliente]              INT           NULL,
    [cd_contato]              INT           NULL,
    [dt_previsao_solucao]     DATETIME      NULL,
    [cd_consultor_solucao]    INT           NULL,
    [ic_agendar_visita]       CHAR (1)      NULL,
    CONSTRAINT [PK_Registro_Suporte] PRIMARY KEY CLUSTERED ([cd_registro_suporte] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Registro_Suporte_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Registro_Suporte_Consultor_Implantacao] FOREIGN KEY ([cd_consultor_solucao]) REFERENCES [dbo].[Consultor_Implantacao] ([cd_consultor])
);

