CREATE TABLE [dbo].[Registro_Inventario] (
    [cd_registro_inventario]        INT          NOT NULL,
    [dt_registro_inventario]        DATETIME     NULL,
    [cd_produto]                    INT          NOT NULL,
    [qt_registro_inventario]        FLOAT (53)   NULL,
    [vl_registro_inventario]        FLOAT (53)   NULL,
    [vl_total_registro_inventario]  FLOAT (53)   NULL,
    [cd_usuario]                    INT          NULL,
    [dt_usuario]                    DATETIME     NULL,
    [nm_obs_registro_inventario]    VARCHAR (40) NULL,
    [ic_registro_inventario]        CHAR (1)     NOT NULL,
    [cd_fase_produto]               INT          NULL,
    [cd_grupo_inventario]           INT          NULL,
    [cd_grupo_produto]              INT          NULL,
    [cd_grupo_estoque]              INT          NULL,
    [cd_classificacao_fiscal]       INT          NULL,
    [cd_unidade_medida]             INT          NULL,
    [cd_metodo_valoracao]           INT          NULL,
    [ic_origem_registro_inventario] CHAR (1)     NULL,
    [cd_mat_prima]                  INT          NULL,
    [cd_bitola]                     INT          NULL,
    [ic_especial]                   CHAR (1)     NULL,
    [cd_controle]                   INT          NULL,
    [ic_tipo_lancamento]            CHAR (1)     NULL,
    [cd_lancamento_padrao]          INT          NULL,
    CONSTRAINT [PK_Registro_Inventario] PRIMARY KEY CLUSTERED ([cd_registro_inventario] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Registro_Inventario_Lancamento_Padrao] FOREIGN KEY ([cd_lancamento_padrao]) REFERENCES [dbo].[Lancamento_Padrao] ([cd_lancamento_padrao])
);

