CREATE TABLE [dbo].[Relatorio_Diario_Vendas] (
    [cd_diario_venda]         INT          NOT NULL,
    [dt_diario_venda]         DATETIME     NULL,
    [cd_vendedor]             INT          NULL,
    [cd_cliente]              INT          NULL,
    [cd_regiao_venda]         INT          NULL,
    [cd_nivel_cliente]        INT          NULL,
    [cd_categoria_cliente]    INT          NULL,
    [cd_cliente_foco]         INT          NULL,
    [cd_cliente_oem]          INT          NULL,
    [cd_tipo_informacao]      INT          NULL,
    [ds_diario_venda]         TEXT         NULL,
    [cd_cliente_global]       INT          NULL,
    [nm_contato_diario_venda] VARCHAR (40) NULL,
    [ic_negocio_diario]       CHAR (1)     NULL,
    [nm_ref_negocio_diario]   VARCHAR (40) NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    CONSTRAINT [PK_Relatorio_Diario_Vendas] PRIMARY KEY CLUSTERED ([cd_diario_venda] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Cliente_Foco] FOREIGN KEY ([cd_cliente_foco]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Cliente_Global] FOREIGN KEY ([cd_cliente_global]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Cliente_OEM] FOREIGN KEY ([cd_cliente_oem]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Nivel_Cliente] FOREIGN KEY ([cd_nivel_cliente]) REFERENCES [dbo].[Nivel_Cliente] ([cd_nivel_cliente]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Regiao_Venda] FOREIGN KEY ([cd_regiao_venda]) REFERENCES [dbo].[Regiao_Venda] ([cd_regiao_venda]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Tipo_Informacao] FOREIGN KEY ([cd_tipo_informacao]) REFERENCES [dbo].[Tipo_Informacao] ([cd_tipo_informacao]),
    CONSTRAINT [FK_Relatorio_Diario_Vendas_Vendedor] FOREIGN KEY ([cd_vendedor]) REFERENCES [dbo].[Vendedor] ([cd_vendedor])
);

