CREATE TABLE [dbo].[REMESSA_VIAGEM_PARCELA] (
    [CD_REMESSA_VIAGEM]         INT           NOT NULL,
    [CD_PARCELA_REMESSA_VIAGEM] INT           NOT NULL,
    [CD_IDENTIFICACAO_PARCELA]  VARCHAR (30)  NULL,
    [DT_VENCIMENTO_REMESSA]     DATETIME      NULL,
    [VL_PARCELA_REMESSA]        FLOAT (53)    NULL,
    [NM_PARCELA_REMESSA]        VARCHAR (100) NULL,
    [CD_DOCUMENTO_PAGAR]        INT           NULL,
    [CD_USUARIO]                INT           NULL,
    [DT_USUARIO]                DATETIME      NULL,
    CONSTRAINT [PK_REMESSA_VIAGEM_PARCELA] PRIMARY KEY CLUSTERED ([CD_REMESSA_VIAGEM] ASC, [CD_PARCELA_REMESSA_VIAGEM] ASC) WITH (FILLFACTOR = 90)
);

