CREATE TABLE [dbo].[REMESSA_VIAGEM_DESPESA] (
    [CD_REMESSA_VIAGEM]          INT           NOT NULL,
    [CD_REMESSA_VIAGEM_DESPESA]  INT           NOT NULL,
    [CD_TIPO_DESPESA_VIAGEM]     INT           NULL,
    [VL_DEBITO_DESPESA]          FLOAT (53)    NULL,
    [VL_CREDITO_REEMBOLSO]       FLOAT (53)    NULL,
    [NM_REMESSA_VIAGEM_DESPESA]  VARCHAR (100) NULL,
    [CD_USUARIO]                 INT           NULL,
    [DT_USUARIO]                 DATETIME      NULL,
    [ic_valor_comercial_despesa] CHAR (1)      NULL,
    CONSTRAINT [PK_REMESSA_VIAGEM_DESPESA] PRIMARY KEY CLUSTERED ([CD_REMESSA_VIAGEM] ASC, [CD_REMESSA_VIAGEM_DESPESA] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_REMESSA_VIAGEM_DESPESA_Tipo_Despesa_Viagem] FOREIGN KEY ([CD_TIPO_DESPESA_VIAGEM]) REFERENCES [dbo].[Tipo_Despesa_Viagem] ([cd_despesa_viagem])
);

