CREATE TABLE [dbo].[REMESSA_VIAGEM_PEDIDO_PARCELA] (
    [CD_REMESSA_VIAGEM]        INT           NOT NULL,
    [CD_PEDIDO_VENDA]          INT           NOT NULL,
    [CD_PARCELA_RECEBIMENTO]   INT           NOT NULL,
    [CD_TIPO_PAGAMENTO]        INT           NULL,
    [CD_IDENTIFICACAO_PARCELA] VARCHAR (30)  NULL,
    [DT_VENCIMENTO_PARCELA]    DATETIME      NULL,
    [VL_PARCELA_RECEBIMENTO]   FLOAT (53)    NULL,
    [VL_DESCONTO_RECEBIMENTO]  FLOAT (53)    NULL,
    [NM_PARCELA_RECEBIMENTO]   VARCHAR (100) NULL,
    [CD_DOCUMENTO_RECEBER]     INT           NULL,
    [CD_USUARIO]               INT           NULL,
    [DT_USUARIO]               DATETIME      NULL,
    [vl_parcela_original]      FLOAT (53)    NULL,
    [cd_tipo_documento]        INT           NULL,
    CONSTRAINT [PK_REMESSA_VIAGEM_PEDIDO_PARCELA] PRIMARY KEY CLUSTERED ([CD_REMESSA_VIAGEM] ASC, [CD_PEDIDO_VENDA] ASC, [CD_PARCELA_RECEBIMENTO] ASC) WITH (FILLFACTOR = 90)
);

