CREATE TABLE [dbo].[Representante_Com_Exterior] (
    [cd_representante_com_ext] INT           NOT NULL,
    [nm_fantasia]              VARCHAR (15)  NULL,
    [nm_razao_social]          VARCHAR (40)  NULL,
    [nm_dominio]               VARCHAR (50)  NULL,
    [dt_cadastro]              DATETIME      NULL,
    [ds_prestador_servico]     TEXT          NULL,
    [cd_banco]                 INT           NULL,
    [cd_agencia_banco]         VARCHAR (15)  NULL,
    [cd_conta_banco]           VARCHAR (20)  NULL,
    [cd_tipo_pessoa]           INT           NULL,
    [cd_fax]                   VARCHAR (15)  NULL,
    [cd_telefone]              VARCHAR (15)  NULL,
    [cd_ddd]                   CHAR (4)      NULL,
    [cd_pais]                  INT           NULL,
    [nm_bairro]                VARCHAR (25)  NULL,
    [nm_complemento_endereco]  VARCHAR (30)  NULL,
    [cd_numero_endereco]       CHAR (10)     NULL,
    [nm_endereco]              VARCHAR (60)  NULL,
    [cd_cep]                   CHAR (9)      NULL,
    [cd_inscmunicipal]         VARCHAR (18)  NULL,
    [cd_inscestadual]          VARCHAR (18)  NULL,
    [cd_cnpj]                  VARCHAR (18)  NULL,
    [cd_identifica_cep]        INT           NULL,
    [cd_siscomex]              INT           NULL,
    [cd_usuario]               INT           NULL,
    [dt_usuario]               DATETIME      NULL,
    [nm_contato]               VARCHAR (50)  NULL,
    [nm_logotipo]              VARCHAR (100) NULL,
    [ds_perfil]                TEXT          NULL,
    [cd_cidade]                INT           NULL,
    [cd_estado]                INT           NULL,
    [nm_swift]                 VARCHAR (30)  NULL,
    [nm_aba_blz]               VARCHAR (30)  NULL,
    [pc_comissao]              FLOAT (53)    NULL,
    [cd_tipo_pagto_comissao]   INT           NULL,
    [cd_pagamento_comissao]    INT           NULL,
    [ds_representante_com_ext] TEXT          NULL,
    [cd_tipo_mercado]          INT           NULL,
    [ic_pad_imp_representante] CHAR (1)      NULL,
    [ic_pad_exp_representante] CHAR (1)      NULL,
    CONSTRAINT [PK_Representante_Com_Exterior] PRIMARY KEY CLUSTERED ([cd_representante_com_ext] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Representante_Com_Exterior_Banco] FOREIGN KEY ([cd_banco]) REFERENCES [dbo].[Banco] ([cd_banco]),
    CONSTRAINT [FK_Representante_Com_Exterior_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Representante_Com_Exterior_Tipo_Pessoa] FOREIGN KEY ([cd_tipo_pessoa]) REFERENCES [dbo].[Tipo_Pessoa] ([cd_tipo_pessoa])
);

