CREATE TABLE [dbo].[Requisicao_Viagem] (
    [cd_requisicao_viagem]       INT            NOT NULL,
    [dt_requisicao_viagem]       DATETIME       NULL,
    [cd_assunto_viagem]          INT            NULL,
    [cd_funcionario]             INT            NULL,
    [cd_departamento]            INT            NULL,
    [cd_centro_custo]            INT            NULL,
    [cd_tipo_viagem]             INT            NULL,
    [cd_projeto_viagem]          INT            NULL,
    [cd_tipo_prioridade]         INT            NULL,
    [nm_local_viagem]            VARCHAR (100)  NULL,
    [ds_requisicao_viagem]       TEXT           NULL,
    [vl_adto_viagem]             FLOAT (53)     NULL,
    [dt_inicio_viagem]           DATETIME       NULL,
    [dt_fim_viagem]              DATETIME       NULL,
    [cd_usuario]                 INT            NULL,
    [dt_usuario]                 DATETIME       NULL,
    [cd_politica_viagem]         INT            NULL,
    [cd_moeda]                   INT            NULL,
    [dt_aprovacao_req_viagem]    DATETIME       NULL,
    [cd_usuario_aprovacao]       INT            NULL,
    [vl_total_viagem]            FLOAT (53)     NULL,
    [vl_reembolso_viagem]        FLOAT (53)     NULL,
    [vl_despesa_viagem]          FLOAT (53)     NULL,
    [vl_cartao_viagem]           FLOAT (53)     NULL,
    [cd_veiculo]                 INT            NULL,
    [cd_moeda_estrangeira]       INT            NULL,
    [vl_adto_moeda]              FLOAT (53)     NULL,
    [dt_necessidade_viagem]      DATETIME       NULL,
    [dt_usuario_liberacao]       DATETIME       NULL,
    [cd_usuario_liberacao]       INT            NULL,
    [cd_status_requisicao]       INT            NULL,
    [dt_moeda_requisicao]        DATETIME       NULL,
    [vl_cotacao_requisicao]      FLOAT (53)     NULL,
    [vl_total_moeda_requisicao]  FLOAT (53)     NULL,
    [nm_obs_liberacao]           VARCHAR (100)  NULL,
    [cd_ap]                      INT            NULL,
    [cd_tipo_adiantamento]       INT            NULL,
    [cd_funcionario_aprovacao]   INT            NULL,
    [ic_email_requisicao]        CHAR (1)       NULL,
    [cd_usuario_requisicao]      INT            NULL,
    [ic_orcamento_requisicao]    CHAR (1)       NULL,
    [cd_local_viagem]            INT            NULL,
    [ds_temp_obs_aprovacao]      VARCHAR (8000) NULL,
    [dt_liberacao_aprovacao]     DATETIME       NULL,
    [cd_secretaria]              INT            NULL,
    [dt_autorizacao_requisicao]  DATETIME       NULL,
    [cd_funcionario_autorizacao] INT            NULL,
    [dt_prevista_aprovacao]      DATETIME       NULL,
    [dt_reenvio_aprovacao]       DATETIME       NULL,
    [cd_funcionario_liberacao]   INT            NULL,
    [cd_documento_pagar]         INT            NULL,
    CONSTRAINT [PK_Requisicao_Viagem] PRIMARY KEY CLUSTERED ([cd_requisicao_viagem] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Requisicao_Viagem_Local_Viagem] FOREIGN KEY ([cd_local_viagem]) REFERENCES [dbo].[Local_Viagem] ([cd_local_viagem]),
    CONSTRAINT [FK_Requisicao_Viagem_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda]),
    CONSTRAINT [FK_Requisicao_Viagem_Status_Req_Viagem] FOREIGN KEY ([cd_status_requisicao]) REFERENCES [dbo].[Status_Req_Viagem] ([cd_status_requisicao]),
    CONSTRAINT [FK_Requisicao_Viagem_Usuario] FOREIGN KEY ([cd_usuario_aprovacao]) REFERENCES [dbo].[Usuario] ([cd_usuario]),
    CONSTRAINT [FK_Requisicao_Viagem_Veiculo] FOREIGN KEY ([cd_veiculo]) REFERENCES [dbo].[Veiculo] ([cd_veiculo])
);

