CREATE TABLE [dbo].[Requisicao_Viagem_Composicao] (
    [cd_requisicao_viagem]      INT          NOT NULL,
    [cd_item_requisicao_viagem] INT          NOT NULL,
    [cd_hotel]                  INT          NULL,
    [nm_hotel_opcional]         VARCHAR (40) NULL,
    [nm_motivo_hotel_opcional]  VARCHAR (40) NULL,
    [cd_cia_aerea]              INT          NULL,
    [nm_aereo_opcional]         VARCHAR (40) NULL,
    [nm_motivo_aereo_opcional]  VARCHAR (40) NULL,
    [cd_cia_taxi]               INT          NULL,
    [cd_locadora_auto]          INT          NULL,
    [nm_terrestre_opcional]     VARCHAR (40) NULL,
    [nm_motivo_terrestre_opcio] VARCHAR (40) NULL,
    [cd_despesa_viagem]         INT          NULL,
    [vl_custo_item_req_viagem]  FLOAT (53)   NULL,
    [nm_opcao_item_req_viagem]  VARCHAR (40) NULL,
    [nm_obs_item_req_viagem]    VARCHAR (40) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_item_viagem]            FLOAT (53)   NULL,
    [vl_item_viagem]            FLOAT (53)   NULL,
    [vl_total_viagem]           FLOAT (53)   NULL,
    [nm_item_opcional_viagem]   VARCHAR (40) NULL,
    [nm_item_motivo_viagem]     VARCHAR (40) NULL,
    [cd_categoria_viagem]       INT          NULL,
    [ic_servico_categoria]      CHAR (1)     NULL,
    CONSTRAINT [PK_Requisicao_Viagem_Composicao] PRIMARY KEY CLUSTERED ([cd_requisicao_viagem] ASC, [cd_item_requisicao_viagem] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Requisicao_Viagem_Composicao_Categoria_Viagem] FOREIGN KEY ([cd_categoria_viagem]) REFERENCES [dbo].[Categoria_Viagem] ([cd_categoria_viagem])
);

