CREATE TABLE [dbo].[REQUISICAO_INTERNA_ITEM] (
    [cd_requisicao_interna]      INT           NOT NULL,
    [cd_item_req_interna]        INT           NOT NULL,
    [cd_produto]                 INT           NULL,
    [qt_item_req_interna]        FLOAT (53)    NULL,
    [qt_item_requisicao]         FLOAT (53)    NULL,
    [qt_entregue_req_interna]    FLOAT (53)    NULL,
    [qt_entregue_item]           FLOAT (53)    NULL,
    [nm_produto_req_interna]     VARCHAR (50)  NULL,
    [nm_item_requisicao]         VARCHAR (50)  NULL,
    [nm_servico_req_interna]     VARCHAR (50)  NULL,
    [cd_unidade_medida]          INT           NULL,
    [nm_obs_req_interna]         VARCHAR (100) NULL,
    [ic_estoque_req_interna]     CHAR (1)      NULL,
    [cd_servico]                 INT           NULL,
    [ic_estoque_requisicao]      CHAR (1)      NULL,
    [ds_requisicao_interna]      TEXT          NULL,
    [cd_usuario]                 INT           NOT NULL,
    [dt_usuario]                 DATETIME      NOT NULL,
    [dt_item_estoque_req]        DATETIME      NULL,
    [cd_fase_produto]            INT           NULL,
    [cd_mascara_produto]         VARCHAR (20)  NULL,
    [cd_maquina]                 INT           NULL,
    [cd_projeto]                 INT           NULL,
    [cd_item_projeto]            INT           NULL,
    [cd_projeto_material]        INT           NULL,
    [cd_pedido_venda]            INT           NULL,
    [cd_item_pedido_venda]       INT           NULL,
    [cd_movimento_caixa]         INT           NULL,
    [qt_saldo_item_req_interna]  FLOAT (53)    NULL,
    [cd_veiculo]                 INT           NULL,
    [cd_historico_estoque]       INT           NULL,
    [cd_lote_produto]            VARCHAR (25)  NULL,
    [cd_guia_fracionamento]      INT           NULL,
    [cd_item_guia_fracionamento] INT           NULL,
    [cd_programacao_entrega]     INT           NULL,
    [cd_processo]                INT           NULL,
    [cd_componente_processo]     INT           NULL,
    [ic_transferencia]           CHAR (1)      NULL,
    [cd_plano_mrp]               INT           NULL,
    [cd_item_plano_mrp]          INT           NULL,
    [cd_consulta]                INT           NULL,
    [cd_funcionario]             INT           NULL,
    CONSTRAINT [PK_REQUISICAO_INTERNA_ITEM] PRIMARY KEY CLUSTERED ([cd_requisicao_interna] ASC, [cd_item_req_interna] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Requisicao_Interna_Item_Maquina] FOREIGN KEY ([cd_maquina]) REFERENCES [dbo].[Maquina] ([cd_maquina]),
    CONSTRAINT [FK_REQUISICAO_INTERNA_ITEM_Requisicao_Interna] FOREIGN KEY ([cd_requisicao_interna]) REFERENCES [dbo].[Requisicao_Interna] ([cd_requisicao_interna]) ON DELETE CASCADE ON UPDATE CASCADE
);

