CREATE TABLE [dbo].[Requisicao_Faturamento_Item] (
    [cd_requisicao_faturamento] INT          NOT NULL,
    [cd_item_req_fat]           INT          NOT NULL,
    [cd_grupo_produto]          INT          NULL,
    [cd_produto]                INT          NULL,
    [cd_unidade_medida]         INT          NULL,
    [qt_peso_unitario_req_fat]  FLOAT (53)   NULL,
    [nm_produto_requisicao_fat] VARCHAR (40) NULL,
    [pc_icm_requisicao_faturam] FLOAT (53)   NULL,
    [pc_ipi_requisicao_faturam] FLOAT (53)   NULL,
    [vl_unitario_requisicao_fa] FLOAT (53)   NULL,
    [qt_requisicao_faturamento] FLOAT (53)   NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_usuario]                INT          NULL,
    [ds_produto_requisicao_fat] TEXT         NULL,
    [cd_classificao_fiscal]     INT          NULL,
    [cd_procedencia_produto]    INT          NULL,
    [cd_classificacao_fiscal]   INT          NULL,
    [qt_peso_bruto_item]        FLOAT (53)   NULL,
    [cd_item_nota_entrada]      INT          NULL,
    [cd_serie_nota_fiscal]      INT          NULL,
    [cd_nota_entrada]           INT          NULL,
    [cd_categoria_produto]      INT          NULL,
    [cd_item_pedido_venda]      INT          NULL,
    [cd_pedido_venda]           INT          NULL,
    [cd_fornecedor]             INT          NULL,
    [cd_operacao_fiscal]        INT          NULL,
    [cd_veiculo]                INT          NULL,
    [cd_nota_saida_origem]      INT          NULL,
    [cd_item_nota_saida_origem] INT          NULL,
    [cd_processo]               INT          NULL,
    [nm_fantasia_req_fat]       VARCHAR (30) NULL,
    CONSTRAINT [PK_Item_Requisicao_Faturamento] PRIMARY KEY CLUSTERED ([cd_requisicao_faturamento] ASC, [cd_item_req_fat] ASC) WITH (FILLFACTOR = 90)
);

