CREATE TABLE [dbo].[Requisicao_Faturamento] (
    [cd_requisicao_faturamento] INT          NOT NULL,
    [dt_requisicao_faturamento] DATETIME     NULL,
    [dt_necessidade_requisicao] DATETIME     NULL,
    [cd_departamento]           INT          NULL,
    [cd_operacao_fiscal]        INT          NULL,
    [ds_requisicao_faturamento] TEXT         NULL,
    [nm_fantasia_requisicao_fa] CHAR (15)    NULL,
    [ic_tipo_pessoa_requisicao] CHAR (1)     NULL,
    [cd_transportadora]         INT          NULL,
    [nm_local_entrega_req_fat]  VARCHAR (50) NULL,
    [cd_especie_embalagem]      INT          NULL,
    [qt_peso_bruto_req_fat]     FLOAT (53)   NULL,
    [qt_peso_liq_req_fat]       FLOAT (53)   NULL,
    [qt_volume_req_fat]         FLOAT (53)   NULL,
    [nm_volume_req_fat]         VARCHAR (30) NULL,
    [cd_obs_padrao_nf]          INT          NULL,
    [ic_Impresso_req_fat]       CHAR (1)     NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_usuario]                INT          NULL,
    [cd_condicao_pagamento_req] INT          NULL,
    [nm_observacao_requisicao]  VARCHAR (40) NULL,
    [cd_destinatario]           INT          NULL,
    [cd_tipo_destinatario]      INT          NULL,
    [ic_req_fat_cancelamento]   CHAR (1)     NULL,
    [nm_cancel_req_faturamento] VARCHAR (50) NULL,
    [dt_cancel_req_faturamento] DATETIME     NULL,
    [vl_frete_req_faturamento]  FLOAT (53)   NULL,
    [cd_tipo_local_entrega]     INT          NULL,
    [cd_destinacao_produto]     INT          NULL,
    [vl_ipi_obs]                FLOAT (53)   NULL,
    [vl_ipi_outros]             FLOAT (53)   NULL,
    [vl_ipi_isento]             FLOAT (53)   NULL,
    [vl_ipi]                    FLOAT (53)   NULL,
    [vl_bc_ipi]                 FLOAT (53)   NULL,
    [vl_icms_obs]               FLOAT (53)   NULL,
    [vl_icms_outros]            FLOAT (53)   NULL,
    [vl_icms_isento]            FLOAT (53)   NULL,
    [vl_icms]                   FLOAT (53)   NULL,
    [vl_bc_icms]                FLOAT (53)   NULL,
    [ic_lib_procfat_requisicao] CHAR (1)     NULL,
    [cd_usuario_solicitante]    INT          NULL,
    [cd_vendedor]               INT          NULL,
    [cd_loja]                   INT          NULL,
    [cd_tipo_requisicao]        INT          NULL,
    [cd_tipo_pagamento_frete]   INT          NULL,
    [cd_contato]                INT          NULL,
    CONSTRAINT [PK_Requisicao_Faturamento] PRIMARY KEY CLUSTERED ([cd_requisicao_faturamento] ASC) WITH (FILLFACTOR = 90)
);

