CREATE TABLE [dbo].[Sequencia_Usinagem_Composicao] (
    [cd_maquina]                INT           NULL,
    [cd_magazine]               INT           NULL,
    [cd_sequencia_usinagem]     INT           NULL,
    [cd_placa]                  INT           NULL,
    [cd_posicao_ferramenta]     INT           NULL,
    [cd_ciclo_fixo_ferrramenta] INT           NULL,
    [cd_sub_rotina]             INT           NULL,
    [cd_bloco_prog_cnc]         INT           NULL,
    [cd_ordem]                  INT           NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_ciclo_fixo_maquina]     INT           NULL,
    [qt_peso_min]               FLOAT (53)    NULL,
    [qt_peso_max]               FLOAT (53)    NULL,
    [ic_montagem_g]             CHAR (1)      NULL,
    [ic_rotina_pos]             CHAR (1)      NULL,
    [ic_chk_curso_ext]          CHAR (1)      NULL,
    [ic_uti_montagem_g]         CHAR (1)      NULL,
    [ic_usi_placa_especial]     CHAR (1)      NULL,
    [ic_chk_rotina_rasgo]       CHAR (1)      NULL,
    [ic_chk_rotina_proc_esp]    CHAR (1)      NULL,
    [ic_bloco_barrado]          CHAR (1)      NULL,
    [nm_obsevacao]              VARCHAR (100) NULL,
    [cd_item]                   INT           NULL,
    [nm_observacao]             VARCHAR (40)  NULL,
    CONSTRAINT [FK_Sequencia_Usinagem_Composicao_Ciclo_Fixo_Ferramenta] FOREIGN KEY ([cd_ciclo_fixo_ferrramenta]) REFERENCES [dbo].[Ciclo_Fixo_Ferramenta] ([cd_ciclo_fixo_ferramenta]),
    CONSTRAINT [FK_Sequencia_Usinagem_Composicao_Magazine] FOREIGN KEY ([cd_magazine]) REFERENCES [dbo].[Magazine] ([cd_magazine]),
    CONSTRAINT [FK_Sequencia_Usinagem_Composicao_Maquina] FOREIGN KEY ([cd_maquina]) REFERENCES [dbo].[Maquina] ([cd_maquina]),
    CONSTRAINT [FK_Sequencia_Usinagem_Composicao_Placa] FOREIGN KEY ([cd_placa]) REFERENCES [dbo].[Placa] ([cd_placa]),
    CONSTRAINT [FK_Sequencia_Usinagem_Composicao_Sequencia_Usinagem] FOREIGN KEY ([cd_sequencia_usinagem]) REFERENCES [dbo].[Sequencia_Usinagem] ([cd_sequencia_usinagem]),
    CONSTRAINT [FK_Sequencia_Usinagem_Composicao_Sub_Rotina_Prog_CNC] FOREIGN KEY ([cd_sub_rotina]) REFERENCES [dbo].[Sub_Rotina_Prog_CNC] ([cd_sub_rotina])
);

