CREATE TABLE [dbo].[Serie_Nota_Fiscal] (
    [cd_serie_nota_fiscal]        INT           NOT NULL,
    [sg_serie_nota_fiscal]        CHAR (10)     NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [nm_serie_nota_fiscal]        VARCHAR (30)  NULL,
    [qt_col_serie_nota_fiscal]    INT           NULL,
    [qt_lin_serie_nota_fiscal]    INT           NULL,
    [ic_cond_serie_nota_fiscal]   CHAR (1)      NULL,
    [qt_max_item_serie_nota]      INT           NULL,
    [cd_modelo_serie_nota]        CHAR (2)      NULL,
    [ic_tipo_emitente_nota]       CHAR (1)      NULL,
    [nm_porta_impressao_nota]     VARCHAR (100) NULL,
    [nm_especie_livro_saida]      CHAR (10)     NULL,
    [nm_serie_livro_saida]        CHAR (10)     NULL,
    [ic_gerar_livro_saida]        CHAR (1)      NULL,
    [qt_max_item_serie_nota_serv] INT           NULL,
    [cd_estilo_impressao]         INT           NULL,
    [ic_rel_contab_serie_nota]    CHAR (1)      NULL,
    [qt_max_serie_nota_fiscal]    INT           NULL,
    [ic_ativa_serie_nota_fiscal]  CHAR (1)      NULL,
    [qt_serie_nota_fiscal]        INT           NULL,
    [ic_pcd_serie_nota_fiscal]    CHAR (1)      NULL,
    [cd_modelo_documento]         INT           NULL,
    [cd_nfe_serie]                INT           NULL,
    [cd_inicio_serie_nota]        INT           NULL,
    [cd_fim_serie_nota]           INT           NULL,
    CONSTRAINT [PK_Serie_Nota_Fiscal] PRIMARY KEY CLUSTERED ([cd_serie_nota_fiscal] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Serie_Nota_Fiscal_Modelo_Documento_Fiscal] FOREIGN KEY ([cd_modelo_documento]) REFERENCES [dbo].[Modelo_Documento_Fiscal] ([cd_modelo_documento])
);

