CREATE TABLE [dbo].[Serie_Produto_Componente] (
    [cd_serie_produto]          INT          NOT NULL,
    [cd_tipo_serie_produto]     INT          NOT NULL,
    [cd_item_serie_prod_comp]   INT          NOT NULL,
    [cd_placa]                  INT          NULL,
    [cd_produto]                INT          NULL,
    [qt_componente_serie_prod]  FLOAT (53)   NULL,
    [ic_procfab_serie_produto]  CHAR (1)     NULL,
    [ic_orcamento_serie_prod]   CHAR (1)     NULL,
    [ic_progcnc_serie_produto]  CHAR (1)     NULL,
    [qt_espessura_serie_prod]   FLOAT (53)   NULL,
    [qt_largura_serie_produto]  FLOAT (53)   NULL,
    [qt_comprimento_serie_prod] FLOAT (53)   NULL,
    [qt_profrasgo_serie_prod]   FLOAT (53)   NULL,
    [qt_larrasgo_serie_produto] FLOAT (53)   NULL,
    [qt_comprasgo_serie_prod]   FLOAT (53)   NULL,
    [cd_grupo_esquadro]         INT          NULL,
    [ic_curso_serie_produto]    CHAR (1)     NULL,
    [ic_base_serie_produto]     CHAR (1)     NULL,
    [ic_molde_serie_produto]    CHAR (1)     NULL,
    [ic_cpc_serie_produto]      CHAR (1)     NULL,
    [qt_bc_serie_produto]       FLOAT (53)   NULL,
    [qt_diambc_serie_produto]   FLOAT (53)   NULL,
    [qt_furo_serie_produto]     FLOAT (53)   NULL,
    [nm_obs_serie_produto]      VARCHAR (40) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    CONSTRAINT [PK_Serie_Produto_Componente] PRIMARY KEY CLUSTERED ([cd_serie_produto] ASC, [cd_tipo_serie_produto] ASC, [cd_item_serie_prod_comp] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Serie_Produto_Componente_Grupo_Esquadro] FOREIGN KEY ([cd_grupo_esquadro]) REFERENCES [dbo].[Grupo_Esquadro] ([cd_grupo_esquadro]),
    CONSTRAINT [FK_Serie_Produto_Componente_Placa] FOREIGN KEY ([cd_placa]) REFERENCES [dbo].[Placa] ([cd_placa]),
    CONSTRAINT [FK_Serie_Produto_Componente_Produto] FOREIGN KEY ([cd_produto]) REFERENCES [dbo].[Produto] ([cd_produto])
);

