CREATE TABLE [dbo].[Serie_Produto_BKP] (
    [cd_serie_produto]          INT          NOT NULL,
    [nm_serie_produto]          VARCHAR (40) COLLATE SQL_Latin1_General_CP1250_CI_AS NOT NULL,
    [sg_serie_produto]          CHAR (10)    COLLATE SQL_Latin1_General_CP1250_CI_AS NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_usuario]                INT          NULL,
    [ds_serie_produto]          TEXT         COLLATE SQL_Latin1_General_CP1250_CI_AS NULL,
    [cd_substituto_serie]       INT          NULL,
    [pc_desconto_serie_produto] FLOAT (53)   NULL,
    [pc_acresc_serie_produto]   FLOAT (53)   NULL,
    [ic_especial]               CHAR (1)     COLLATE SQL_Latin1_General_CP1250_CI_AS NULL,
    [pc_imposto_imp_serie_prod] FLOAT (53)   NULL,
    [ic_import_serie_produto]   CHAR (1)     COLLATE SQL_Latin1_General_CP1250_CI_AS NULL,
    [ic_lote_serie_produto]     CHAR (1)     NULL,
    [qt_dia_garantia_serie_pro] INT          NULL,
    [ic_serie_serie_produto]    CHAR (1)     NULL,
    [ic_ras_serie_produto]      CHAR (1)     NULL,
    [ic_garantia_serie_produto] CHAR (1)     NULL,
    [cd_termo_garantia]         INT          NULL,
    [ic_produto_serie_produto]  CHAR (1)     NULL,
    [ic_procfab_serie_produto]  CHAR (1)     NULL,
    [ic_orcam_serie_produto]    CHAR (1)     NULL,
    [ic_producao_serie_produto] CHAR (1)     NULL,
    [qt_comprimento_rasgo]      FLOAT (53)   NULL,
    [qt_largura_rasgo]          FLOAT (53)   NULL,
    [qt_furo_fixacao]           FLOAT (53)   NULL,
    [qt_largura_serie_produto]  FLOAT (53)   NULL,
    [qt_comprimento_serie]      FLOAT (53)   NULL,
    [qt_comprimento_aba_serie]  FLOAT (53)   NULL,
    [cd_mercado]                INT          NULL,
    [qt_profundidade_coluna]    FLOAT (53)   NULL,
    [qt_profundidade_bucha]     FLOAT (53)   NULL,
    [qt_furo_encosto_padrao]    FLOAT (53)   NULL,
    [cd_processo_usinagem]      INT          NULL,
    [qt_profundidade_rasgo]     FLOAT (53)   NULL,
    [ic_fechamento_mensal]      CHAR (1)     NULL
);

