CREATE TABLE [dbo].[Servico] (
    [cd_grupo_servico]         INT          NOT NULL,
    [cd_servico]               INT          NOT NULL,
    [cd_mascara_servico]       VARCHAR (20) NULL,
    [nm_servico]               VARCHAR (40) NULL,
    [sg_servico]               CHAR (10)    NULL,
    [ds_servico]               TEXT         NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [cd_unidade_medida]        INT          NULL,
    [cd_grupo_produto]         INT          NULL,
    [vl_servico]               FLOAT (53)   NULL,
    [dt_cadastro]              DATETIME     NULL,
    [cd_unidade_servico]       INT          NULL,
    [pc_irrf_servico]          FLOAT (53)   NULL,
    [pc_iss_servico]           FLOAT (53)   NULL,
    [pc_comissao_servico]      FLOAT (53)   NULL,
    [cd_iss_grupo_servico]     INT          NULL,
    [cd_operacao_fiscal]       INT          NULL,
    [cd_categoria_produto]     INT          NULL,
    [ic_garantia_servico]      CHAR (1)     NULL,
    [qt_dia_garantia_servico]  INT          NULL,
    [qt_fator_conv_extra]      FLOAT (53)   NULL,
    [ic_retencao_servico]      CHAR (1)     NULL,
    [ic_rentecao_iss_obrig]    CHAR (1)     NULL,
    [ic_retencao_fed_servico]  CHAR (1)     NULL,
    [ic_livro_iss_servico]     CHAR (1)     NULL,
    [cd_op_fisc_interestadual] INT          NULL,
    [pc_desconto_servico]      FLOAT (53)   NULL,
    [ic_sat_servico]           CHAR (1)     NULL,
    [ic_lp_servico]            CHAR (1)     NULL,
    [cd_grupo_preco_produto]   INT          NULL,
    [vl_custo_servico]         FLOAT (53)   NULL,
    [ic_retencao_inss_servico] CHAR (1)     NULL,
    [pc_inss_servico]          FLOAT (53)   NULL,
    [ic_processo_servico]      CHAR (1)     NULL,
    [cd_tipo_produto]          INT          NULL,
    [cd_modalidade_servico]    INT          NULL,
    [ic_pcp_servico]           CHAR (1)     NULL,
    CONSTRAINT [PK_Servico] PRIMARY KEY CLUSTERED ([cd_grupo_servico] ASC, [cd_servico] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Servico_Grupo_Preco_Produto] FOREIGN KEY ([cd_grupo_preco_produto]) REFERENCES [dbo].[Grupo_Preco_Produto] ([cd_grupo_preco_produto]),
    CONSTRAINT [FK_Servico_Modalidade_Servico] FOREIGN KEY ([cd_modalidade_servico]) REFERENCES [dbo].[Modalidade_Servico] ([cd_modalidade_servico]),
    CONSTRAINT [FK_Servico_Tipo_Produto] FOREIGN KEY ([cd_tipo_produto]) REFERENCES [dbo].[Tipo_Produto] ([cd_tipo_produto])
);

