CREATE TABLE [dbo].[Sindicato] (
    [cd_sindicato]                INT           NOT NULL,
    [nm_sindicato]                VARCHAR (50)  NULL,
    [nm_complemento_sindicato]    VARCHAR (50)  NULL,
    [nm_fantasia_sindicato]       VARCHAR (50)  NULL,
    [nm_endereco_sindicato]       VARCHAR (50)  NULL,
    [nm_bairro_sindicato]         VARCHAR (25)  NULL,
    [cd_ddd_sindicato]            CHAR (4)      NULL,
    [cd_fone_sindicato]           VARCHAR (15)  NULL,
    [cd_fax_sindicato]            VARCHAR (15)  NULL,
    [nm_contato_sindicato]        VARCHAR (40)  NULL,
    [nm_email_sindicato]          VARCHAR (100) NULL,
    [nm_site_sindicato]           VARCHAR (100) NULL,
    [cd_classe_sindicato]         VARCHAR (10)  NULL,
    [cd_identifica_cep]           INT           NULL,
    [cd_pais]                     INT           NULL,
    [cd_estado]                   INT           NULL,
    [cd_cidade]                   INT           NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [dt_dissidio_sindicato]       DATETIME      NULL,
    [cd_cep]                      VARCHAR (9)   NULL,
    [nm_periodo_sindicato]        VARCHAR (5)   NULL,
    [ic_contribuicao_funcionario] CHAR (1)      NULL,
    [qt_mes_contribuicao]         FLOAT (53)    NULL,
    [pc_assistencial_sindicato]   FLOAT (53)    NULL,
    [pc_confederativa_sindicato]  FLOAT (53)    NULL,
    CONSTRAINT [PK_Sindicato] PRIMARY KEY CLUSTERED ([cd_sindicato] ASC) WITH (FILLFACTOR = 90)
);

