CREATE TABLE [dbo].[Solicitacao_Adiantamento] (
    [cd_solicitacao]                INT            NOT NULL,
    [dt_solicitacao]                DATETIME       NULL,
    [dt_necessidade]                DATETIME       NULL,
    [cd_funcionario]                INT            NOT NULL,
    [cd_centro_custo]               INT            NULL,
    [cd_departamento]               INT            NULL,
    [cd_finalidade_adiantamento]    INT            NOT NULL,
    [cd_requisicao_viagem]          INT            NULL,
    [ds_solicitacao]                TEXT           NULL,
    [dt_vencimento]                 DATETIME       NULL,
    [cd_moeda]                      INT            NULL,
    [vl_adiantamento]               FLOAT (53)     NULL,
    [vl_saldo_adiantamento]         FLOAT (53)     NULL,
    [cd_usuario]                    INT            NULL,
    [dt_usuario]                    DATETIME       NULL,
    [dt_liberacao_adiantamento]     DATETIME       NULL,
    [cd_usuario_liberacao]          INT            NULL,
    [dt_moeda_solicitacao]          DATETIME       NULL,
    [vl_cotacao_solicitacao]        FLOAT (53)     NULL,
    [vl_total_moeda_solicitacao]    FLOAT (53)     NULL,
    [cd_prestacao]                  INT            NULL,
    [ic_tipo_adiantamento]          INT            NULL,
    [cd_tipo_adiantamento]          INT            NULL,
    [cd_ap]                         INT            NULL,
    [dt_pagamento_solicitacao]      DATETIME       NULL,
    [dt_contabilizacao_solicitacao] DATETIME       NULL,
    [cd_conta]                      INT            NULL,
    [dt_conf_solicitacao]           DATETIME       NULL,
    [cd_projeto_viagem]             INT            NULL,
    [ic_sel_deposito_adiantamento]  CHAR (1)       NULL,
    [cd_assunto_viagem]             INT            NULL,
    [cd_usuario_aprovacao]          INT            NULL,
    [cd_funcionario_aprovacao]      INT            NULL,
    [ic_email_solicitacao]          CHAR (1)       NULL,
    [dt_financeiro_solicitacao]     DATETIME       NULL,
    [cd_usuario_solicitacao]        INT            NULL,
    [vl_solicitacao_moeda]          FLOAT (53)     NULL,
    [ds_temp_obs_aprovacao]         VARCHAR (8000) NULL,
    [dt_liberacao_aprovacao]        DATETIME       NULL,
    [cd_secretaria]                 INT            NULL,
    [dt_aviso_cobranca]             DATETIME       NULL,
    [cd_cartao_credito]             INT            NULL,
    [dt_lib_viagem_internacional]   DATETIME       NULL,
    [dt_prevista_aprovacao]         DATETIME       NULL,
    [dt_reenvio_aprovacao]          DATETIME       NULL,
    [cd_funcionario_liberacao]      INT            NULL,
    [cd_documento_pagar]            INT            NULL,
    CONSTRAINT [PK_Solicitacao_Adiantamento] PRIMARY KEY CLUSTERED ([cd_solicitacao] ASC) WITH (FILLFACTOR = 90)
);

