CREATE TABLE [dbo].[Solicitacao_Pagamento] (
    [cd_solicitacao]                INT            NOT NULL,
    [dt_solicitacao]                DATETIME       NULL,
    [cd_departamento]               INT            NULL,
    [cd_centro_custo]               INT            NULL,
    [dt_necessidade]                DATETIME       NULL,
    [cd_fornecedor]                 INT            NULL,
    [dt_vencimento]                 DATETIME       NULL,
    [cd_funcionario]                INT            NULL,
    [cd_favorecido_empresa_div]     INT            NULL,
    [cd_empresa_diversa]            INT            NULL,
    [cd_tipo_solicitacao]           INT            NULL,
    [cd_tipo_pagamento]             INT            NULL,
    [cd_usuario_aprovado]           INT            NULL,
    [ds_solicitacao]                TEXT           NULL,
    [dt_usuario_aprovado]           DATETIME       NULL,
    [cd_documento_pagar]            INT            NULL,
    [dt_usuario]                    DATETIME       NULL,
    [cd_usuario]                    INT            NULL,
    [cd_ap]                         INT            NULL,
    [dt_pagamento_solicitacao]      DATETIME       NULL,
    [cd_usuario_liberacao]          INT            NULL,
    [cd_finalidade_pagamento]       INT            NULL,
    [cd_moeda]                      INT            NULL,
    [dt_moeda_solicitacao]          DATETIME       NULL,
    [vl_cotacao_solicitacao]        FLOAT (53)     NULL,
    [vl_cotacao_moeda]              FLOAT (53)     NULL,
    [dt_contabilizacao_solicitacao] DATETIME       NULL,
    [dt_liberacao_pagamento]        DATETIME       NULL,
    [vl_total_moeda_solicitacao]    FLOAT (53)     NULL,
    [vl_pagamento]                  FLOAT (53)     NULL,
    [dt_conf_solicitacao]           DATETIME       NULL,
    [nm_favorecido_solicitacao]     VARCHAR (40)   NULL,
    [cd_assunto_viagem]             INT            NULL,
    [cd_usuario_aprovacao]          INT            NULL,
    [cd_funcionario_aprovacao]      INT            NULL,
    [ic_email_solicitacao]          CHAR (1)       NULL,
    [dt_financeiro_solicitacao]     DATETIME       NULL,
    [cd_usuario_solicitacao]        INT            NULL,
    [ds_temp_obs_aprovacao]         VARCHAR (8000) NULL,
    [dt_liberacao_aprovacao]        DATETIME       NULL,
    [cd_secretaria]                 INT            NULL,
    [dt_prevista_aprovacao]         DATETIME       NULL,
    [dt_reenvio_aprovacao]          DATETIME       NULL,
    [cd_funcionario_liberacao]      INT            NULL,
    CONSTRAINT [PK_Solicitacao_Pagamento] PRIMARY KEY CLUSTERED ([cd_solicitacao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Solicitacao_Pagamento_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Solicitacao_Pagamento_Documento_Pagar] FOREIGN KEY ([cd_documento_pagar]) REFERENCES [dbo].[Documento_Pagar] ([cd_documento_pagar]),
    CONSTRAINT [FK_Solicitacao_Pagamento_Fornecedor] FOREIGN KEY ([cd_fornecedor]) REFERENCES [dbo].[Fornecedor] ([cd_fornecedor]),
    CONSTRAINT [FK_Solicitacao_Pagamento_Tipo_Pagamento_Documento] FOREIGN KEY ([cd_tipo_pagamento]) REFERENCES [dbo].[Tipo_Pagamento_Documento] ([cd_tipo_pagamento]),
    CONSTRAINT [FK_Solicitacao_Pagamento_Tipo_Solicitacao_Pagamento] FOREIGN KEY ([cd_tipo_solicitacao]) REFERENCES [dbo].[Tipo_Solicitacao_Pagamento] ([cd_tipo_solicitacao])
);

