CREATE TABLE [dbo].[Tecnico] (
    [cd_tecnico]                INT           NOT NULL,
    [nm_tecnico]                VARCHAR (50)  NOT NULL,
    [sg_tecnico]                CHAR (10)     NULL,
    [cd_usuario]                INT           NOT NULL,
    [dt_usuario]                DATETIME      NOT NULL,
    [nm_fantasia_tecnico]       VARCHAR (15)  NULL,
    [nm_endereco_tecnico]       VARCHAR (50)  NULL,
    [nm_bairro_tecnico]         VARCHAR (25)  NULL,
    [cd_fone_tecnico]           VARCHAR (9)   NULL,
    [cd_fax_tecnico]            VARCHAR (9)   NULL,
    [cd_ddd_tecnico]            CHAR (4)      NULL,
    [cd_cnpj_tecnico]           VARCHAR (18)  NULL,
    [cd_insc_est_tecnico]       VARCHAR (20)  NULL,
    [nm_contato_tecnico]        VARCHAR (40)  NULL,
    [nm_email_tecnico]          VARCHAR (100) NULL,
    [nm_logotipo_tecnico]       VARCHAR (100) NULL,
    [cd_pais]                   INT           NULL,
    [cd_estado]                 INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_tipo_pessoa]            INT           NULL,
    [dt_cadastro]               DATETIME      NULL,
    [cd_banco]                  INT           NULL,
    [cd_celular]                VARCHAR (15)  NULL,
    [cd_tipo_tecnico]           INT           NULL,
    [cd_conta_corrente]         VARCHAR (20)  NULL,
    [cd_agencia_banco]          VARCHAR (15)  NULL,
    [cd_insmunicipal]           VARCHAR (18)  NULL,
    [nm_complemento_endereco]   VARCHAR (10)  NULL,
    [cd_numero_endereco]        INT           NULL,
    [ds_perfil_tecnico]         TEXT          NULL,
    [ds_tecnico]                TEXT          NULL,
    [cd_cep]                    VARCHAR (9)   NULL,
    [nm_ponto_ref_tecnico]      VARCHAR (100) NULL,
    [cd_ddd_vendedor]           VARCHAR (4)   NULL,
    [cd_insmunicipal_vendedor]  VARCHAR (18)  NULL,
    [cd_agencia_banco_vendedor] VARCHAR (15)  NULL,
    [cd_crq]                    CHAR (10)     NULL,
    [sg_registro_tecnico]       CHAR (10)     NULL,
    [nm_caminho_imagem_rubrica] VARCHAR (255) NULL,
    [cd_registro]               VARCHAR (30)  NULL,
    [ic_ativo_tecnico]          CHAR (1)      NULL,
    [qt_visita_diaria_tecnico]  FLOAT (53)    NULL,
    [cd_usuario_cadastro]       INT           NULL
);

