CREATE TABLE [dbo].[Terminal_Carga] (
    [cd_terminal_carga]       INT           NOT NULL,
    [nm_fantasia]             VARCHAR (15)  NULL,
    [nm_razao_social]         VARCHAR (40)  NULL,
    [nm_dominio]              VARCHAR (50)  NULL,
    [dt_cadastro]             DATETIME      NULL,
    [ds_prestador_servico]    TEXT          NULL,
    [cd_banco]                INT           NULL,
    [cd_agencia_banco]        VARCHAR (15)  NULL,
    [cd_conta_banco]          VARCHAR (20)  NULL,
    [cd_tipo_pessoa]          INT           NULL,
    [cd_fax]                  VARCHAR (15)  NULL,
    [cd_telefone]             VARCHAR (15)  NULL,
    [cd_ddd]                  CHAR (4)      NULL,
    [cd_pais]                 INT           NULL,
    [nm_bairro]               VARCHAR (25)  NULL,
    [nm_complemento_endereco] VARCHAR (30)  NULL,
    [cd_numero_endereco]      CHAR (10)     NULL,
    [nm_endereco]             VARCHAR (60)  NULL,
    [cd_cep]                  CHAR (9)      NULL,
    [cd_inscmunicipal]        VARCHAR (18)  NULL,
    [cd_inscestadual]         VARCHAR (18)  NULL,
    [cd_cnpj]                 VARCHAR (18)  NULL,
    [cd_identifica_cep]       INT           NULL,
    [cd_siscomex]             INT           NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [cd_cidade]               INT           NULL,
    [cd_estado]               INT           NULL,
    [ds_perfil]               TEXT          NULL,
    [nm_logotipo]             VARCHAR (100) NULL,
    [nm_contato]              VARCHAR (50)  NULL,
    [ds_terminal_carga]       TEXT          NULL,
    [cd_tipo_mercado]         INT           NULL,
    CONSTRAINT [PK_Terminal_Carga] PRIMARY KEY CLUSTERED ([cd_terminal_carga] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Terminal_Carga_Banco] FOREIGN KEY ([cd_banco]) REFERENCES [dbo].[Banco] ([cd_banco]),
    CONSTRAINT [FK_Terminal_Carga_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Terminal_Carga_Tipo_Pessoa] FOREIGN KEY ([cd_tipo_pessoa]) REFERENCES [dbo].[Tipo_Pessoa] ([cd_tipo_pessoa])
);

