CREATE TABLE [dbo].[Tipo_Despesa_Comex] (
    [cd_tipo_despesa_comex]     INT          NOT NULL,
    [nm_tipo_despesa_comex]     VARCHAR (30) NULL,
    [sg_tipo_despesa_comex]     CHAR (10)    NULL,
    [ic_imp_import_tipo_despes] CHAR (1)     NULL,
    [ic_ipi_tipo_despesa_comex] CHAR (1)     NULL,
    [ic_desembaraco_tipo_desp]  CHAR (1)     NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_icms_tip_desp_comex]    CHAR (1)     NULL,
    [vl_tipo_despesa_comex]     FLOAT (53)   NULL,
    [cd_plano_financeiro]       INT          NULL,
    [cd_tipo_conta_pagar]       INT          NULL,
    [cd_empresa_diversa]        INT          NULL,
    [cd_favorecido_empresa]     INT          NULL,
    [ic_cpv_tipo_despesa]       CHAR (1)     NULL,
    [ic_nf_tipo_despesa]        CHAR (1)     NULL,
    [ic_rateio_tipo_despesa]    CHAR (1)     NULL,
    [cd_conta]                  INT          NULL,
    [qt_dia_pagamento_despesa]  INT          NULL,
    [cd_historico_financeiro]   INT          NULL,
    [cd_centro_custo]           INT          NULL,
    [nm_obs_tipo_despesa]       VARCHAR (40) NULL,
    [cd_moeda]                  INT          NULL,
    [ic_conversao_moeda]        CHAR (1)     NULL,
    [ic_data_tipo_despesa]      CHAR (1)     NULL,
    [cd_tipo_documento]         INT          NULL,
    CONSTRAINT [PK_Tipo_Despesa_Comex] PRIMARY KEY CLUSTERED ([cd_tipo_despesa_comex] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Tipo_Despesa_Comex_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Tipo_Despesa_Comex_Historico_Financeiro] FOREIGN KEY ([cd_historico_financeiro]) REFERENCES [dbo].[Historico_Financeiro] ([cd_historico_financeiro]),
    CONSTRAINT [FK_Tipo_Despesa_Comex_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda]),
    CONSTRAINT [FK_Tipo_Despesa_Comex_Tipo_Documento] FOREIGN KEY ([cd_tipo_documento]) REFERENCES [dbo].[Tipo_Documento] ([cd_tipo_documento])
);

