CREATE TABLE [dbo].[Tipo_Embalagem] (
    [cd_tipo_embalagem]         INT          NOT NULL,
    [nm_tipo_embalagem]         VARCHAR (30) COLLATE Latin1_General_CI_AS NULL,
    [sg_tipo_embalagem]         CHAR (10)    COLLATE Latin1_General_CI_AS NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_unidade_tipo_embalagem] FLOAT (53)   NULL,
    [cd_unidade_medida]         INT          NULL,
    [ic_pad_nf_tipo_embalagem]  CHAR (1)     NULL,
    [ic_cobra_aluguel]          CHAR (1)     NULL,
    [cd_tipo_aluguel]           INT          NULL,
    [ic_incluso_produto]        CHAR (1)     NULL,
    [cd_produto]                INT          NULL,
    [cd_grupo_categoria]        INT          NULL,
    [cd_categoria_produto]      INT          NULL,
    [ic_ordem_separacao]        CHAR (1)     NULL,
    [ic_embalagem_cliente]      CHAR (1)     NULL,
    [qt_peso_tipo_embalagem]    FLOAT (53)   NULL,
    [ds_tipo_embalagem]         TEXT         NULL,
    [ic_container_embalagem]    CHAR (1)     NULL,
    [qt_cd_tipo_embalagem]      INT          NULL,
    [qt_altura_embalagem]       FLOAT (53)   NULL,
    [qt_largura_embalagem]      FLOAT (53)   NULL,
    [qt_comprimento_embalagem]  FLOAT (53)   NULL,
    [qt_cubagem_embalagem]      FLOAT (53)   NULL,
    [ic_carga_tipo_embalagem]   CHAR (1)     NULL,
    CONSTRAINT [PK_Tipo_Embalagem] PRIMARY KEY CLUSTERED ([cd_tipo_embalagem] ASC) WITH (FILLFACTOR = 90)
);

