CREATE TABLE [dbo].[Tipo_Pedido] (
    [cd_tipo_pedido]              INT          NOT NULL,
    [nm_tipo_pedido]              VARCHAR (30) NULL,
    [sg_tipo_pedido]              CHAR (10)    NULL,
    [cd_tipo_operacao]            INT          NULL,
    [cd_usuario]                  INT          NULL,
    [dt_usuario]                  DATETIME     NULL,
    [ic_tipo_pedido]              CHAR (1)     NULL,
    [cd_passo_tipo_pedido]        INT          NULL,
    [ic_scr_tipo_pedido]          CHAR (1)     NULL,
    [ic_sce_tipo_pedido]          CHAR (1)     NULL,
    [ic_padrao_tipo_pedido]       CHAR (1)     NULL,
    [ic_imposto_tipo_pedido]      CHAR (1)     NULL,
    [ic_scp_tipo_pedido]          CHAR (1)     NULL,
    [pc_duplicacao_tipo_pedido]   FLOAT (53)   NULL,
    [pc_desconto_tipo_pedido]     FLOAT (53)   NULL,
    [ic_pedido_mat_prima]         CHAR (1)     NULL,
    [pc_carregar_nota_fiscal]     FLOAT (53)   NULL,
    [ic_sem_valor_remessa]        CHAR (1)     NULL,
    [ic_especial_tipo_pedido]     CHAR (1)     NULL,
    [ic_realiza_saida_entreposto] CHAR (1)     NULL,
    [nm_titulo_tipo_pedido]       VARCHAR (40) NULL,
    [cd_tipo_documento_estoque]   INT          NULL,
    [sg_mercardor_tipo_pedido]    CHAR (3)     NULL,
    [ic_gera_fluxo_caixa]         CHAR (1)     NULL,
    [ic_gera_bi]                  CHAR (1)     NULL,
    [cd_tipo_fluxo_caixa]         INT          NULL,
    [ic_qtd_analise]              CHAR (1)     NULL,
    [ic_ordsep_tipo_pedido]       CHAR (1)     NULL,
    [ic_previsao_tipo_pedido]     CHAR (1)     NULL,
    [ic_alocacao_tipo_pedido]     CHAR (1)     NULL,
    CONSTRAINT [PK_Tipo_Pedido] PRIMARY KEY CLUSTERED ([cd_tipo_pedido] ASC) WITH (FILLFACTOR = 90)
);

