CREATE TABLE [dbo].[Tipo_Despesa] (
    [cd_tipo_despesa]              INT          NOT NULL,
    [nm_tipo_despesa]              VARCHAR (50) NOT NULL,
    [sg_tipo_despesa]              CHAR (10)    COLLATE Latin1_General_CI_AS NULL,
    [cd_usuario]                   INT          NULL,
    [dt_usuario]                   DATETIME     NULL,
    [cd_plano_financeiro]          INT          NULL,
    [ic_empresa_tipo_despesa]      CHAR (1)     NULL,
    [ic_cliente_tipo_despesa]      CHAR (1)     NULL,
    [ic_consultor_tipo_despesa]    CHAR (1)     NULL,
    [ic_scp_tipo_despesa]          CHAR (1)     NULL,
    [cd_tipo_conta_pagar]          INT          NULL,
    [cd_tipo_documento]            INT          NULL,
    [vl_tipo_despesa]              FLOAT (53)   NULL,
    [ic_reembolsavel_despesa]      CHAR (1)     NULL,
    [cd_conta]                     INT          NULL,
    [nm_obs_tipo_despesa]          VARCHAR (40) NULL,
    [ic_sct_tipo_despesa]          CHAR (1)     NULL,
    [ic_edita_valor_padrao]        CHAR (1)     NULL,
    [ic_edita_valor_limite]        CHAR (1)     NULL,
    [ic_sel_cliente_tipo_despesa]  CHAR (1)     NULL,
    [ic_sel_obs_tipo_despesa]      CHAR (1)     NULL,
    [ic_sel_km_tipo_despesa]       CHAR (1)     NULL,
    [ic_sel_diaria_tipo_despesa]   CHAR (1)     NULL,
    [ic_sel_pc_tipo_despesa]       CHAR (1)     NULL,
    [ic_sel_sp_tipo_despesa]       CHAR (1)     NULL,
    [cd_tipo_diaria]               INT          NULL,
    [ic_setor_tipo_despesa]        CHAR (1)     NULL,
    [ic_cento_custo_tipo_despesa]  CHAR (1)     NULL,
    [ic_projeto_tipo_despesa]      CHAR (1)     NULL,
    [ic_centro_custo_tipo_despesa] CHAR (1)     NULL,
    [ic_tipo_contabilizacao]       CHAR (1)     NULL,
    [ic_sel_fo_tipo_despesa]       CHAR (1)     NULL,
    [ic_beneficio_tipo_despesa]    CHAR (1)     NULL,
    [ic_ir_resumo_tipo_despesa]    CHAR (1)     NULL,
    CONSTRAINT [PK_Tipo_Despesa] PRIMARY KEY CLUSTERED ([cd_tipo_despesa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Tipo_Despesa_Tipo_Conta_Pagar] FOREIGN KEY ([cd_tipo_conta_pagar]) REFERENCES [dbo].[Tipo_Conta_Pagar] ([cd_tipo_conta_pagar]),
    CONSTRAINT [FK_Tipo_Despesa_Tipo_Diaria_Hotel] FOREIGN KEY ([cd_tipo_diaria]) REFERENCES [dbo].[Tipo_Diaria_Hotel] ([cd_tipo_diaria]),
    CONSTRAINT [FK_Tipo_Despesa_Tipo_Documento] FOREIGN KEY ([cd_tipo_documento]) REFERENCES [dbo].[Tipo_Documento] ([cd_tipo_documento])
);

