CREATE TABLE [dbo].[TMP_Campo] (
    [cd_sessao_documento]     INT          NOT NULL,
    [cd_campo_magnetico]      INT          NULL,
    [cd_tipo_campo]           INT          NULL,
    [qt_tamanho]              INT          NULL,
    [qt_decimal]              INT          NULL,
    [ic_arredondamento_valor] CHAR (1)     NULL,
    [cd_inicio_posicao]       INT          NULL,
    [cd_fim_posicao]          INT          NULL,
    [nm_conteudo_fixo]        VARCHAR (50) NULL,
    [nm_tabela_origem]        VARCHAR (40) NULL,
    [nm_campo_origem]         VARCHAR (50) NULL,
    [nm_campo_chave]          VARCHAR (50) NULL,
    [nm_conteudo_chave]       VARCHAR (50) NULL,
    [nm_tabela_ligacao]       VARCHAR (40) NULL,
    [nm_campo_ligacao]        VARCHAR (50) NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    [nm_instrucao_sql]        TEXT         NULL,
    [nm_campo]                VARCHAR (40) NULL,
    [ds_campo]                VARCHAR (40) NULL,
    [cd_arquivo_magnetico]    INT          NULL,
    [ic_groupby]              CHAR (1)     NULL,
    [ic_valor_digitado]       CHAR (1)     NULL,
    [cd_posicao_orderby]      INT          NULL,
    [ic_incluir_no_arquivo]   CHAR (1)     NULL,
    [ic_mostrar_no_relatorio] CHAR (1)     NULL,
    [ic_totalizacao_grid]     CHAR (1)     NULL
);

