CREATE TABLE [dbo].[Valor_Bem] (
    [cd_bem]                     INT        NOT NULL,
    [vl_original_bem]            FLOAT (53) NULL,
    [cd_moeda]                   INT        NULL,
    [vl_cor_acumulada_bem]       FLOAT (53) NULL,
    [vl_deprec_acumulada_bem]    FLOAT (53) NULL,
    [qt_original_bem]            FLOAT (53) NULL,
    [pc_depreciacao_bem]         FLOAT (53) NULL,
    [pc_deprec_acelerada_bem]    FLOAT (53) NULL,
    [vl_mercado_bem]             FLOAT (53) NULL,
    [vl_residual_bem]            FLOAT (53) NULL,
    [vl_lucro_bem]               FLOAT (53) NULL,
    [qt_residual_bem]            FLOAT (53) NULL,
    [qt_lucro_bem]               FLOAT (53) NULL,
    [cd_usuario]                 INT        NULL,
    [dt_usuario]                 DATETIME   NULL,
    [pc_plano_conta_depreciacao] INT        NULL,
    [pc_depreciado_bem]          FLOAT (53) NULL,
    [pc_saldo_depreciacao_bem]   FLOAT (53) NULL,
    [vl_maximo_seguro_bem]       FLOAT (53) NULL,
    [vl_icms_bem]                FLOAT (53) NULL,
    [vl_ipi_bem]                 FLOAT (53) NULL,
    [pc_icms_bem]                FLOAT (53) NULL,
    [pc_ipi_bem]                 FLOAT (53) NULL,
    [ic_apuracao_bem]            CHAR (1)   NULL,
    [ic_ciap_bem]                CHAR (1)   NULL,
    [qt_mes_apuracao_bem]        INT        NULL,
    [vl_fixo_depreciacao_bem]    FLOAT (53) NULL,
    [pc_producao_bem]            FLOAT (53) NULL,
    [dt_fim_depreciacao_bem]     DATETIME   NULL,
    [vl_saldo_depreciacao_bem]   FLOAT (53) NULL,
    [vl_baixa_bem]               FLOAT (53) NULL,
    [vl_dep_periodo_bem]         FLOAT (53) NULL,
    CONSTRAINT [FK_Valor_Bem_Bem] FOREIGN KEY ([cd_bem]) REFERENCES [dbo].[Bem] ([cd_bem]),
    CONSTRAINT [FK_Valor_Bem_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda])
);

