CREATE TABLE [dbo].[Veiculo] (
    [cd_veiculo]                INT           NOT NULL,
    [nm_veiculo]                VARCHAR (40)  NULL,
    [cd_marca_veiculo]          INT           NULL,
    [cd_tipo_combustivel]       INT           NULL,
    [aa_veiculo]                INT           NULL,
    [dt_aquisicao_veiculo]      DATETIME      NULL,
    [qt_revisao_veiculo]        FLOAT (53)    NULL,
    [ds_veiculo]                TEXT          NULL,
    [qt_combustivel_veiculo]    FLOAT (53)    NULL,
    [qt_km_inicial_veiculo]     INT           NULL,
    [qt_km_media_veiculo]       FLOAT (53)    NULL,
    [qt_km_atual_veiculo]       FLOAT (53)    NULL,
    [cd_motivo_baixa_veiculo]   INT           NULL,
    [dt_baixa_veiculo]          DATETIME      NULL,
    [cd_empresa]                INT           NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [nm_foto_veiculo]           VARCHAR (150) NULL,
    [cd_placa_veiculo]          VARCHAR (8)   NULL,
    [cd_grupo_veiculo]          INT           NULL,
    [qt_consumo_veiculo]        FLOAT (53)    NULL,
    [qt_entrega_diaria_veiculo] FLOAT (53)    NULL,
    [cd_renavam_veiculo]        VARCHAR (12)  NULL,
    [cd_chassi_veiculo]         VARCHAR (18)  NULL,
    [cd_estado]                 INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_cor]                    INT           NULL,
    [cd_tipo_veiculo]           INT           NULL,
    [aa_modelo_veiculo]         INT           NULL,
    [nm_modelo_veiculo]         VARCHAR (30)  NULL,
    [cd_tag_veiculo]            VARCHAR (15)  NULL,
    [ic_mapa_carga_veiculo]     CHAR (1)      NULL,
    CONSTRAINT [PK_veiculo] PRIMARY KEY CLUSTERED ([cd_veiculo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Marca_Veiculo] FOREIGN KEY ([cd_marca_veiculo]) REFERENCES [dbo].[Marca_Veiculo] ([cd_marca_veiculo]),
    CONSTRAINT [FK_Motivo_Baixa_Veiculo] FOREIGN KEY ([cd_motivo_baixa_veiculo]) REFERENCES [dbo].[Motivo_Baixa_Veiculo] ([cd_motivo_baixa_veiculo]),
    CONSTRAINT [FK_Tipo_Combustivel] FOREIGN KEY ([cd_tipo_combustivel]) REFERENCES [dbo].[Tipo_Combustivel] ([cd_tipo_combustivel]),
    CONSTRAINT [FK_Veiculo_Cor] FOREIGN KEY ([cd_cor]) REFERENCES [dbo].[Cor] ([cd_cor]),
    CONSTRAINT [FK_Veiculo_Grupo_Veiculo] FOREIGN KEY ([cd_grupo_veiculo]) REFERENCES [dbo].[Grupo_Veiculo] ([cd_grupo_veiculo]),
    CONSTRAINT [FK_Veiculo_Tipo_Veiculo] FOREIGN KEY ([cd_tipo_veiculo]) REFERENCES [dbo].[Tipo_Veiculo] ([cd_tipo_veiculo])
);

