CREATE TABLE [dbo].[Vendedor] (
    [cd_vendedor]               INT           NOT NULL,
    [nm_vendedor]               VARCHAR (40)  NOT NULL,
    [nm_fantasia_vendedor]      VARCHAR (15)  NULL,
    [sg_vendedor]               CHAR (10)     NULL,
    [nm_endereco_vendedor]      VARCHAR (50)  NULL,
    [cd_numero_endereco]        VARCHAR (10)  NULL,
    [nm_complemento_endereco]   VARCHAR (40)  NULL,
    [nm_bairro_vendedor]        VARCHAR (30)  NULL,
    [cd_ddd_vendedor]           CHAR (4)      NULL,
    [cd_telefone_vendedor]      VARCHAR (15)  NULL,
    [cd_fax_vendedor]           VARCHAR (15)  NULL,
    [cd_cnpj_vendedor]          VARCHAR (18)  NULL,
    [cd_inscestadual_vendedor]  VARCHAR (18)  NULL,
    [cd_insmunicipal_vendedor]  VARCHAR (18)  NULL,
    [nm_dominio_vendedor]       VARCHAR (100) NULL,
    [nm_email_vendedor]         VARCHAR (100) NULL,
    [nm_email_particular]       VARCHAR (100) NULL,
    [pc_aliquota_irpj]          FLOAT (53)    NULL,
    [pc_comissao_vendedor]      FLOAT (53)    NULL,
    [nm_contato_vendedor]       VARCHAR (40)  NULL,
    [qt_visita_diaria_vendedor] INT           NULL,
    [cd_agencia_banco_vendedor] VARCHAR (15)  NULL,
    [cd_conta_corrente]         VARCHAR (20)  NULL,
    [cd_cep]                    CHAR (9)      NULL,
    [cd_banco]                  INT           NULL,
    [cd_pais]                   INT           NULL,
    [cd_estado]                 INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_tipo_pessoa]            INT           NULL,
    [cd_tipo_vendedor]          INT           NULL,
    [cd_usuario]                INT           NOT NULL,
    [dt_usuario]                DATETIME      NOT NULL,
    [ic_ativo]                  CHAR (1)      NULL,
    [vl_meta]                   FLOAT (53)    NULL,
    [cd_celular]                VARCHAR (15)  NULL,
    [ic_repnet_vendedor]        CHAR (1)      NULL,
    [ic_wapnet_vendedor]        CHAR (1)      NULL,
    [nm_logotipo_vendedor]      VARCHAR (100) NULL,
    [dt_acesso_repnet_vendedor] DATETIME      NULL,
    [dt_acesso_wapnet_vendedor] DATETIME      NULL,
    [vl_salario_vendedor]       FLOAT (53)    NULL,
    [ic_recibo_comis_vendedor]  CHAR (1)      NULL,
    [dt_base_pagto_comissao]    DATETIME      NULL,
    [dt_base_final_comissao]    DATETIME      NULL,
    [ic_calcula_data_final]     CHAR (1)      NULL,
    [ic_consiste_preco_orcado]  CHAR (1)      NULL,
    [cd_tipo_comissao]          INT           NULL,
    [vl_piso_comissao_vendedor] FLOAT (53)    NULL,
    [vl_teto_comissao_vendedor] FLOAT (53)    NULL,
    [vl_salario_comis_vendedor] FLOAT (53)    NULL,
    [cd_senha_reg_vendedor]     VARCHAR (15)  NULL,
    [cd_celular_vendedor]       CHAR (15)     NULL,
    [dt_base_pagamento_comis]   DATETIME      NULL,
    [nm_ponto_ref_vendedor]     VARCHAR (100) NULL,
    [ic_email_orcam_vendedor]   CHAR (1)      NULL,
    [cd_estrutura_venda]        INT           NULL,
    [cd_tipo_desconto_comissao] INT           NULL,
    [cd_senha_operador_caixa]   CHAR (10)     NULL,
    [ic_email_venda_vendedor]   CHAR (1)      NULL,
    [pc_desconto_max_vendedor]  FLOAT (53)    NULL,
    [ic_empresa_vendedor]       CHAR (1)      NULL,
    [ic_cad_proposta_vendedor]  CHAR (1)      NULL,
    [nm_obs_proposta_vendedor]  VARCHAR (60)  NULL,
    [ic_observacao_vendedor]    CHAR (1)      NULL,
    [ic_frete_vendedor]         CHAR (1)      NULL,
    [ic_tel_vendedor_proposta]  CHAR (1)      NULL,
    [cd_centro_receita]         INT           NULL,
    [cd_centro_custo]           INT           NULL,
    [cd_departamento]           INT           NULL,
    [cd_loja]                   INT           NULL,
    [pc_iss_vendedor]           FLOAT (53)    NULL,
    [cd_empresa_diversa]        INT           NULL,
    [cd_fornecedor]             INT           NULL,
    [cd_favorecido_empresa]     INT           NULL,
    [nm_assinatura_vendedor]    VARCHAR (100) NULL,
    [ic_copia_email_vendedor]   CHAR (1)      NULL,
    [ic_fec_proposta_vendedor]  CHAR (1)      NULL,
    [ic_analise_vendedor]       CHAR (1)      NULL,
    [ic_acesso_vendedor]        CHAR (1)      NULL,
    [ic_permite_edicao_cliente] CHAR (1)      NULL,
    [ic_email_visita_vendedor]  CHAR (1)      NULL,
    [ds_perfil_vendedor]        TEXT          NULL,
    [cd_regional_venda]         INT           NULL,
    [cd_area_atuacao_venda]     INT           NULL,
    [cd_regiao_venda]           INT           NULL,
    [cd_interface]              VARCHAR (15)  NULL,
    CONSTRAINT [PK_Vendedor] PRIMARY KEY CLUSTERED ([cd_vendedor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Vendedor_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Vendedor_Centro_Receita] FOREIGN KEY ([cd_centro_receita]) REFERENCES [dbo].[Centro_Receita] ([cd_centro_receita]),
    CONSTRAINT [FK_Vendedor_Empresa_Diversa] FOREIGN KEY ([cd_empresa_diversa]) REFERENCES [dbo].[Empresa_Diversa] ([cd_empresa_diversa]),
    CONSTRAINT [FK_Vendedor_Estrutura_Venda] FOREIGN KEY ([cd_estrutura_venda]) REFERENCES [dbo].[Estrutura_Venda] ([cd_estrutura_venda]),
    CONSTRAINT [FK_Vendedor_Fornecedor] FOREIGN KEY ([cd_fornecedor]) REFERENCES [dbo].[Fornecedor] ([cd_fornecedor]),
    CONSTRAINT [FK_Vendedor_Loja] FOREIGN KEY ([cd_loja]) REFERENCES [dbo].[Loja] ([cd_loja]),
    CONSTRAINT [FK_Vendedor_Tipo_Desconto_Comissao] FOREIGN KEY ([cd_tipo_desconto_comissao]) REFERENCES [dbo].[Tipo_Desconto_Comissao] ([cd_tipo_desconto_comissao])
);

