CREATE TABLE [dbo].[Versao_NFE] (
    [cd_versao_nfe]            INT           NOT NULL,
    [nm_versao_nfe]            VARCHAR (40)  NULL,
    [sg_versao_nfe]            CHAR (10)     NOT NULL,
    [ic_ativa_versao_nfe]      CHAR (1)      NULL,
    [cd_usuario]               INT           NULL,
    [dt_usuario]               DATETIME      NULL,
    [nm_processo_emissao_nfe]  VARCHAR (20)  NULL,
    [cd_digito_processo_nfe]   CHAR (1)      NULL,
    [cd_finalidade_nfe]        CHAR (1)      NULL,
    [cd_ambiente_nfe]          CHAR (1)      NULL,
    [cd_forma_emissao_nfe]     CHAR (1)      NULL,
    [cd_formato_danfe_nfe]     CHAR (1)      NULL,
    [cd_documento_magnetico]   INT           NULL,
    [nm_servidor_cliente]      VARCHAR (150) NULL,
    [nm_local_xml_nfe]         VARCHAR (200) NULL,
    [nm_local_xml_entrada_nfe] VARCHAR (200) NULL,
    [nm_local_log_nfe]         VARCHAR (200) NULL,
    [cd_tipo_formato_nfe]      INT           NULL,
    [ic_codigo_destinatario]   CHAR (1)      NULL,
    [ic_quadro_complemento]    CHAR (1)      NULL,
    [qt_decimal_produto]       INT           NULL,
    [qt_unitario_produto]      INT           NULL,
    [nm_contingencia_nfe]      VARCHAR (150) NULL,
    [cd_empresa]               INT           NULL,
    [cd_regime_tributario]     INT           NULL,
    [cd_nota_saida]            INT           NULL,
    [qt_via_padrao_danfe]      INT           NULL,
    CONSTRAINT [PK_Versao_NFE] PRIMARY KEY CLUSTERED ([cd_versao_nfe] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Versao_NFE_Regime_Tributario] FOREIGN KEY ([cd_regime_tributario]) REFERENCES [dbo].[Regime_Tributario] ([cd_regime_tributario])
);

