CREATE TABLE [dbo].[Visita] (
    [cd_visita]                 INT          NOT NULL,
    [dt_visita]                 DATETIME     NOT NULL,
    [cd_tipo_visita]            INT          NULL,
    [cd_vendedor]               INT          NOT NULL,
    [cd_cliente]                INT          NULL,
    [cd_contato]                INT          NULL,
    [ic_retorno_visita]         CHAR (1)     NULL,
    [dt_retorno_visita]         DATETIME     NULL,
    [ds_visita]                 TEXT         NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [nm_assunto_visita]         VARCHAR (50) COLLATE Latin1_General_CI_AS NULL,
    [ds_visita_retorno]         TEXT         COLLATE Latin1_General_CI_AS NULL,
    [dt_agenda_visita]          DATETIME     NULL,
    [cd_operador_telemarketing] INT          NULL,
    [cd_cliente_prospeccao]     INT          NULL,
    [nm_obs_visita]             VARCHAR (40) NULL,
    [cd_motivo_visita]          INT          NULL,
    [qt_dia_lembrete_visita]    INT          NULL,
    [ic_lembrete_visita]        CHAR (1)     NULL,
    [ic_particular_visita]      CHAR (1)     NULL,
    [hr_fim_visita]             VARCHAR (8)  NULL,
    [hr_inicio_visita]          VARCHAR (8)  NULL,
    [cd_prospeccao_contato]     INT          NULL,
    [cd_prospeccao]             INT          NULL,
    [cd_cancelamento_visita]    INT          NULL,
    [dt_cancelamento_visita]    DATETIME     NULL,
    [cd_tipo_horario_visita]    INT          NULL,
    CONSTRAINT [PK_Visita] PRIMARY KEY CLUSTERED ([cd_visita] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Visita_Motivo_Cancelamento_Visita] FOREIGN KEY ([cd_cancelamento_visita]) REFERENCES [dbo].[Motivo_Cancelamento_Visita] ([cd_cancelamento_visita]),
    CONSTRAINT [FK_Visita_Motivo_Visita] FOREIGN KEY ([cd_motivo_visita]) REFERENCES [dbo].[Motivo_Visita] ([cd_motivo_visita]),
    CONSTRAINT [FK_Visita_Operador_Telemarketing] FOREIGN KEY ([cd_operador_telemarketing]) REFERENCES [dbo].[Operador_Telemarketing] ([cd_operador_telemarketing])
);

