CREATE TABLE [dbo].[Visitante] (
    [cd_visitante]            INT          NOT NULL,
    [dt_visita_visitante]     DATETIME     NULL,
    [cd_tipo_visita_empresa]  INT          NULL,
    [cd_departamento]         INT          NULL,
    [cd_usuario_departamento] INT          NULL,
    [nm_visitante]            VARCHAR (40) NULL,
    [nm_especificacao_visita] VARCHAR (40) NULL,
    [cd_ddd_visitante]        INT          NULL,
    [cd_fone_Visitante]       VARCHAR (15) NULL,
    [cd_rg_visitante]         VARCHAR (18) NULL,
    [cd_cpf_visitante]        VARCHAR (18) NULL,
    [cd_tipo_veiculo]         INT          NULL,
    [cd_placa_visitante]      VARCHAR (18) NULL,
    [ds_visitante]            TEXT         NULL,
    [hr_entrada_visitante]    VARCHAR (8)  NULL,
    [hr_saida_visitante]      VARCHAR (8)  NULL,
    [cd_motivo_aceno]         INT          NULL,
    [nm_empresa_visitante]    VARCHAR (40) NULL,
    [cd_tipo_visitante]       INT          NULL,
    [nm_imagem_visitante]     VARCHAR (40) NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    [cd_motivo_acesso]        INT          NULL,
    [cd_portaria]             INT          NULL,
    [cd_recepcao]             INT          NULL,
    [hr_inicio_visita]        VARCHAR (8)  NULL,
    [hr_fim_visita]           VARCHAR (8)  NULL,
    [ic_particular_visita]    CHAR (1)     NULL,
    [ic_lembrete_visita]      CHAR (1)     NULL,
    [qt_dia_lembre_visita]    INT          NULL,
    [cd_motivo_visita]        INT          NULL,
    [nm_obs_visita]           VARCHAR (40) NULL,
    CONSTRAINT [PK_Visitante] PRIMARY KEY CLUSTERED ([cd_visitante] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Visitante_Motivo_Acesso] FOREIGN KEY ([cd_motivo_acesso]) REFERENCES [dbo].[Motivo_Acesso] ([cd_motivo_acesso]),
    CONSTRAINT [FK_Visitante_Motivo_Visita] FOREIGN KEY ([cd_motivo_visita]) REFERENCES [dbo].[Motivo_Visita] ([cd_motivo_visita]),
    CONSTRAINT [FK_Visitante_Portaria] FOREIGN KEY ([cd_portaria]) REFERENCES [dbo].[Portaria] ([cd_portaria]),
    CONSTRAINT [FK_Visitante_Recepcao] FOREIGN KEY ([cd_recepcao]) REFERENCES [dbo].[Recepcao] ([cd_recepcao]),
    CONSTRAINT [FK_Visitante_Tipo_Visitante] FOREIGN KEY ([cd_tipo_visitante]) REFERENCES [dbo].[Tipo_Visitante] ([cd_tipo_visitante])
);

