CREATE TABLE [dbo].[Visita_Tecnico] (
    [cd_visita]              INT          NOT NULL,
    [dt_visita]              DATETIME     NULL,
    [cd_tipo_visita]         INT          NULL,
    [cd_tecnico]             INT          NULL,
    [cd_cliente]             INT          NULL,
    [cd_contato]             INT          NULL,
    [ic_retorno_visita]      CHAR (1)     NULL,
    [dt_retorno_visita]      DATETIME     NULL,
    [ds_visita]              TEXT         NULL,
    [hr_inicio_visita]       VARCHAR (8)  NULL,
    [hr_fim_visita]          VARCHAR (8)  NULL,
    [ic_particular_visita]   CHAR (1)     NULL,
    [ic_lembrete_visita]     CHAR (1)     NULL,
    [qt_dia_lembrete_visita] INT          NULL,
    [cd_motivo_visita]       INT          NULL,
    [nm_obs_visita]          VARCHAR (40) NULL,
    [dt_agenda_visita]       DATETIME     NULL,
    [cd_cancelamento_visita] INT          NULL,
    [dt_cancelamento_visita] DATETIME     NULL,
    [cd_usuario]             INT          NULL,
    [dt_usuario]             DATETIME     NULL,
    [nm_assunto_visita]      VARCHAR (50) NULL,
    [cd_tipo_horario_visita] INT          NULL,
    [ds_visita_retorno]      TEXT         NULL,
    CONSTRAINT [PK_Visita_Tecnico] PRIMARY KEY CLUSTERED ([cd_visita] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Visita_Tecnico_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente])
);

