CREATE TABLE [dbo].[CABAM1] (
    [CBACOD]   CHAR (3)     NOT NULL,
    [CBADATD]  DATETIME     NOT NULL,
    [CBAREGD]  INT          NOT NULL,
    [CBADOCD]  DECIMAL (10) NULL,
    [CBADATD1] DATETIME     NULL,
    [CBDESD]   CHAR (40)    NULL,
    [CBDEBD]   MONEY        NULL,
    [CBCRED]   MONEY        NULL,
    [CBREGBC]  INT          NULL,
    [CBFLUDRG] INT          NULL,
    PRIMARY KEY CLUSTERED ([CBACOD] ASC, [CBADATD] ASC, [CBAREGD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCABAM1A]
    ON [dbo].[CABAM1]([CBACOD] ASC, [CBADATD] ASC, [CBFLUDRG] ASC);


GO
CREATE NONCLUSTERED INDEX [UCABAM1B]
    ON [dbo].[CABAM1]([CBACOD] ASC, [CBADATD] DESC, [CBFLUDRG] ASC);

