CREATE TABLE [dbo].[CACLF2] (
    [CClf0Cod]     CHAR (5)   NOT NULL,
    [CCLF0UFST]    CHAR (2)   NOT NULL,
    [CClf0STTrb]   CHAR (1)   NULL,
    [CClf0STMgC]   SMALLMONEY NULL,
    [CCLf0STIVAST] SMALLMONEY NULL,
    [CCLF0GNRE]    SMALLMONEY NULL,
    PRIMARY KEY CLUSTERED ([CClf0Cod] ASC, [CCLF0UFST] ASC)
);

