CREATE TABLE [dbo].[CACLIPAG] (
    [CCCGC]    CHAR (18) NOT NULL,
    [CCPAGSEQ] SMALLINT  NOT NULL,
    [CCPAGTIP] CHAR (2)  NULL,
    [CCPAGEST] CHAR (1)  NULL,
    [CCPAGDIA] SMALLINT  NULL,
    PRIMARY KEY CLUSTERED ([CCCGC] ASC, [CCPAGSEQ] ASC)
);

