CREATE TABLE [dbo].[CAFUN] (
    [CaFCod]    SMALLINT       NOT NULL,
    [CaFNom]    CHAR (80)      NULL,
    [CaFApe]    CHAR (30)      NULL,
    [CaFNDep]   SMALLINT       NULL,
    [CSETCOD]   CHAR (3)       NULL,
    [CaFCPF]    CHAR (14)      NULL,
    [CaFRG]     CHAR (14)      NULL,
    [CaFHa]     CHAR (15)      NULL,
    [CaFTE]     CHAR (15)      NULL,
    [CaFTEZ]    CHAR (5)       NULL,
    [CaFTES]    CHAR (5)       NULL,
    [CaFCP]     CHAR (20)      NULL,
    [CaFCor]    CHAR (1)       NULL,
    [CaFCPS]    CHAR (5)       NULL,
    [CaFNBan]   CHAR (27)      NULL,
    [CaFAgBan]  DECIMAL (10)   NULL,
    [CaFCCBan]  DECIMAL (10)   NULL,
    [CaFTCBan]  CHAR (2)       NULL,
    [CaFEnd]    CHAR (100)     NULL,
    [CaFCmp]    CHAR (20)      NULL,
    [CaFCid]    CHAR (30)      NULL,
    [CECOD]     CHAR (2)       NULL,
    [CaFBai]    CHAR (30)      NULL,
    [CaFCep]    CHAR (9)       NULL,
    [CaFVlHr]   MONEY          NULL,
    [CaFGEsc]   SMALLINT       NULL,
    [CaFEml]    CHAR (100)     NULL,
    [CaFSex]    CHAR (1)       NULL,
    [CaFVlSal]  MONEY          NULL,
    [CaFVlVl]   MONEY          NULL,
    [CaFTur]    CHAR (10)      NULL,
    [CaFTelF]   CHAR (9)       NULL,
    [CaFTelR]   CHAR (9)       NULL,
    [CaFTelC]   CHAR (9)       NULL,
    [CaFTelO]   CHAR (9)       NULL,
    [CaFObsT]   CHAR (80)      NULL,
    [CaFVT]     CHAR (1)       NULL,
    [CaFVR]     CHAR (1)       NULL,
    [CaFAO]     CHAR (1)       NULL,
    [CaFSV]     CHAR (1)       NULL,
    [CaFVA]     CHAR (1)       NULL,
    [CaFVC]     CHAR (1)       NULL,
    [CaFAC]     CHAR (1)       NULL,
    [CaFAF]     CHAR (1)       NULL,
    [CaFCr]     CHAR (1)       NULL,
    [CaFAM]     CHAR (1)       NULL,
    [CaFAT]     CHAR (1)       NULL,
    [CaFTC]     CHAR (1)       NULL,
    [CaFCB]     CHAR (1)       NULL,
    [CaFDtN]    DATETIME       NULL,
    [CaFDtA]    DATETIME       NULL,
    [CaFDtD]    DATETIME       NULL,
    [CaFDtE]    DATETIME       NULL,
    [CaFDtPE]   DATETIME       NULL,
    [CaFDtRg]   DATETIME       NOT NULL,
    [CaFMDe]    VARCHAR (5000) NULL,
    [CaFEstC]   CHAR (2)       NULL,
    [CaFFun]    CHAR (30)      NULL,
    [CaFAtv]    CHAR (1)       NULL,
    [CaFObsG]   VARCHAR (5000) NULL,
    [CaFHist]   VARCHAR (5000) NULL,
    [CaFFPai]   CHAR (80)      NULL,
    [CaFFMae]   CHAR (80)      NULL,
    [CaFNPai]   CHAR (20)      NULL,
    [CaFNMae]   CHAR (20)      NULL,
    [CaFNac]    CHAR (20)      NULL,
    [CaFHorEnt] CHAR (5)       NULL,
    [CaFHorSai] CHAR (5)       NULL,
    [CaFPis]    CHAR (20)      NULL,
    PRIMARY KEY CLUSTERED ([CaFCod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAFUN1]
    ON [dbo].[CAFUN]([CECOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ICAFUN2]
    ON [dbo].[CAFUN]([CSETCOD] ASC);

