CREATE TABLE [dbo].[CAGNC] (
    [CagCod] SMALLINT  NOT NULL,
    [CBACOD] CHAR (3)  NOT NULL,
    [CagDv]  SMALLINT  NULL,
    [CagNom] CHAR (40) NULL,
    PRIMARY KEY CLUSTERED ([CagCod] ASC, [CBACOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAGNC1]
    ON [dbo].[CAGNC]([CBACOD] ASC);

