CREATE TABLE [dbo].[CALSTSOLPRO] (
    [LSP0Cod] CHAR (60)  NOT NULL,
    [LSP0Nom] CHAR (120) NULL,
    [LSP0Fam] CHAR (20)  NULL,
    CONSTRAINT [PK__CALSTSOL__853708315B638405] PRIMARY KEY CLUSTERED ([LSP0Cod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCALSTSOLPROA]
    ON [dbo].[CALSTSOLPRO]([LSP0Nom] ASC);


GO
CREATE NONCLUSTERED INDEX [UCALSTSOLPROB]
    ON [dbo].[CALSTSOLPRO]([LSP0Fam] ASC);

