CREATE TABLE [dbo].[CAMAQ] (
    [CMAQCOD] CHAR (5)  NOT NULL,
    [CMAQDES] CHAR (30) NULL,
    [CMAQHOR] SMALLINT  NULL,
    [CMAQQUA] SMALLINT  NULL,
    [CMQADIA] SMALLINT  NULL,
    PRIMARY KEY CLUSTERED ([CMAQCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAMAQA]
    ON [dbo].[CAMAQ]([CMAQDES] ASC);

