CREATE TABLE [dbo].[CAMAQMA2] (
    [LMACOD]   CHAR (6)        NOT NULL,
    [LMAQPSEQ] SMALLINT        NOT NULL,
    [LMAQPDAT] DATETIME        NULL,
    [LMAQPDES] CHAR (35)       NULL,
    [LMAQPRES] CHAR (10)       NULL,
    [LMAQPRSE] CHAR (10)       NULL,
    [LMAQPCUS] DECIMAL (13, 4) NULL,
    [LMAQHOR]  SMALLMONEY      NULL,
    PRIMARY KEY CLUSTERED ([LMACOD] ASC, [LMAQPSEQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAMAQMA2A]
    ON [dbo].[CAMAQMA2]([LMACOD] ASC, [LMAQPDAT] ASC);

