CREATE TABLE [dbo].[CAMAQMA3] (
    [LMACOD]  CHAR (6)   NOT NULL,
    [LMAFDAT] DATETIME   NOT NULL,
    [LMAFDES] CHAR (30)  NULL,
    [LMAFTIP] CHAR (3)   NULL,
    [LMAFPER] SMALLMONEY NULL,
    PRIMARY KEY CLUSTERED ([LMACOD] ASC, [LMAFDAT] ASC)
);

