CREATE TABLE [dbo].[CAMAQMA1] (
    [LMACOD]     CHAR (6)   NOT NULL,
    [LMAQDAT]    DATETIME   NOT NULL,
    [LMAQTIP]    CHAR (6)   NULL,
    [LMAQDES]    CHAR (70)  NULL,
    [LMAQRES]    CHAR (10)  NULL,
    [LMAQRSE]    CHAR (10)  NULL,
    [LMAQHORMan] SMALLMONEY NULL,
    PRIMARY KEY CLUSTERED ([LMACOD] ASC, [LMAQDAT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAMAQMA1A]
    ON [dbo].[CAMAQMA1]([LMACOD] ASC, [LMAQTIP] ASC, [LMAQDAT] ASC);

