CREATE TABLE [dbo].[CAMAQMA] (
    [LMACOD]     CHAR (6)  NOT NULL,
    [LMANOM]     CHAR (50) NULL,
    [LMATIP]     CHAR (12) NULL,
    [LMAMAR]     CHAR (8)  NULL,
    [LMAANO]     SMALLINT  NULL,
    [LMANUM]     CHAR (16) NULL,
    [LMAFAB]     CHAR (30) NULL,
    [CMAQCOD]    CHAR (5)  NULL,
    [CSETCOD]    CHAR (3)  NULL,
    [LMAGAL]     SMALLINT  NULL,
    [LMACOR]     SMALLINT  NULL,
    [LMAFIL]     SMALLINT  NULL,
    [LMAMES]     SMALLINT  NULL,
    [LMASEM]     SMALLINT  NULL,
    [LMAREA]     CHAR (1)  NULL,
    [LMAODIA]    SMALLINT  NULL,
    [LMAOTUR]    SMALLINT  NULL,
    [LMAODIAV]   SMALLINT  NULL,
    [LMAODIAINI] SMALLINT  NULL,
    PRIMARY KEY CLUSTERED ([LMACOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAMAQMAB]
    ON [dbo].[CAMAQMA]([CSETCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ICAMAQMA]
    ON [dbo].[CAMAQMA]([CMAQCOD] ASC);

