CREATE TABLE [dbo].[CAMPRLEVEL1] (
    [CMPCOD]      CHAR (60)       NOT NULL,
    [CMPCotCCCGC] CHAR (18)       NOT NULL,
    [CMPCotCCCon] CHAR (20)       NULL,
    [CMPCotDDD]   CHAR (3)        NULL,
    [CMPCotFone]  CHAR (9)        NULL,
    [CMPCotICMS]  SMALLMONEY      NULL,
    [CMPCotIPI]   SMALLMONEY      NULL,
    [CMPCotQtde]  DECIMAL (11, 4) NULL,
    [CMPCotPre]   DECIMAL (13, 4) NULL,
    [CMPCotDat]   DATETIME        NULL,
    [CMPCotNNf]   INT             NULL,
    PRIMARY KEY CLUSTERED ([CMPCOD] ASC, [CMPCotCCCGC] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAMPR1A]
    ON [dbo].[CAMPRLEVEL1]([CMPCotDat] DESC);


GO
CREATE NONCLUSTERED INDEX [UCAMPR1B]
    ON [dbo].[CAMPRLEVEL1]([CMPCotDat] ASC);


GO
CREATE NONCLUSTERED INDEX [ICAMPRLEVEL1]
    ON [dbo].[CAMPRLEVEL1]([CMPCotCCCGC] ASC);

