CREATE TABLE [dbo].[CAOCO] (
    [COCOCOD] CHAR (3)  NOT NULL,
    [COCODES] CHAR (30) NULL,
    [COCOHOR] CHAR (1)  NULL,
    PRIMARY KEY CLUSTERED ([COCOCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAOCOA]
    ON [dbo].[CAOCO]([COCODES] ASC);

