CREATE TABLE [dbo].[CAOPE] (
    [COPECOD]    CHAR (3)   NOT NULL,
    [COPENOM]    CHAR (50)  NULL,
    [CSETCOD]    CHAR (3)   NULL,
    [COPEPRO]    SMALLMONEY NULL,
    [CSETFOT]    CHAR (100) NULL,
    [COPEUsuCod] CHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([COPECOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAOPEB]
    ON [dbo].[CAOPE]([CSETCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [UCAOPEA]
    ON [dbo].[CAOPE]([COPENOM] ASC);


GO
CREATE NONCLUSTERED INDEX [ICAOPEC]
    ON [dbo].[CAOPE]([COPEUsuCod] ASC);

