CREATE TABLE [dbo].[CAPLA] (
    [C1PLA]    CHAR (3)  NOT NULL,
    [C1NOM]    CHAR (30) NULL,
    [C1CodCnt] CHAR (11) NULL,
    PRIMARY KEY CLUSTERED ([C1PLA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAPLAA]
    ON [dbo].[CAPLA]([C1NOM] ASC);


GO
CREATE NONCLUSTERED INDEX [ICAPLAB]
    ON [dbo].[CAPLA]([C1CodCnt] ASC);

