CREATE TABLE [dbo].[CAPROEPSEX] (
    [CPROCOD]       CHAR (60)  NOT NULL,
    [CPRO1EP]       CHAR (2)   NOT NULL,
    [CTSERCO]       CHAR (7)   NOT NULL,
    [CPRO1EPSExOrd] SMALLINT   NULL,
    [CTSerObsS]     CHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([CPROCOD] ASC, [CPRO1EP] ASC, [CTSERCO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAPROEPSEXA]
    ON [dbo].[CAPROEPSEX]([CTSERCO] ASC);

