CREATE TABLE [dbo].[CAPROEPCAD] (
    [CPROCOD]   CHAR (60)       NOT NULL,
    [CPRO1SEQ]  SMALLINT        NOT NULL,
    [CPROCPRO1] SMALLINT        NULL,
    [CPRO1IMG]  VARBINARY (MAX) NULL,
    [CPRO1EXT]  CHAR (5)        NULL,
    [CPRO1DES]  CHAR (50)       NULL,
    PRIMARY KEY CLUSTERED ([CPROCOD] ASC, [CPRO1SEQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAPROEPCADA]
    ON [dbo].[CAPROEPCAD]([CPROCOD] ASC, [CPRO1DES] ASC);

