CREATE TABLE [dbo].[CAPROEMP] (
    [CPROCOD]     CHAR (60)       NOT NULL,
    [CPRO2EmpCod] CHAR (2)        NOT NULL,
    [CPROESTMIN]  DECIMAL (11, 4) NULL,
    PRIMARY KEY CLUSTERED ([CPROCOD] ASC, [CPRO2EmpCod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAPRO13]
    ON [dbo].[CAPROEMP]([CPRO2EmpCod] ASC);

