CREATE TABLE [dbo].[CAPROEPMPR] (
    [CPROCOD]       CHAR (60)       NOT NULL,
    [CPRO1EP]       CHAR (2)        NOT NULL,
    [CMPCOD]        CHAR (60)       NOT NULL,
    [CMPQtd]        DECIMAL (11, 4) NULL,
    [CPRO1EPMPrOrd] SMALLINT        NULL,
    PRIMARY KEY CLUSTERED ([CPROCOD] ASC, [CPRO1EP] ASC, [CMPCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICAPROEPMPRA]
    ON [dbo].[CAPROEPMPR]([CMPCOD] ASC);

