CREATE TABLE [dbo].[CAREP1] (
    [CVCOD]  CHAR (3)  NOT NULL,
    [CVCDAT] DATETIME  NOT NULL,
    [CVCEMP] CHAR (20) NULL,
    [CVCCOM] CHAR (15) NULL,
    [CVCFON] CHAR (9)  NULL,
    [CVCRAM] INT       NULL,
    [CVCASS] CHAR (30) NULL,
    PRIMARY KEY CLUSTERED ([CVCOD] ASC, [CVCDAT] ASC)
);

