CREATE TABLE [dbo].[CASETFINACE] (
    [CSETCOD]       CHAR (3)  NOT NULL,
    [CSETSgPer0Cod] CHAR (20) NOT NULL,
    PRIMARY KEY CLUSTERED ([CSETCOD] ASC, [CSETSgPer0Cod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICASETFINACE]
    ON [dbo].[CASETFINACE]([CSETSgPer0Cod] ASC);

