CREATE TABLE [dbo].[CASET] (
    [CSETCOD] CHAR (3)  NOT NULL,
    [CSETNOM] CHAR (30) NULL,
    [CSETRES] CHAR (15) NULL,
    PRIMARY KEY CLUSTERED ([CSETCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCASETA]
    ON [dbo].[CASET]([CSETNOM] ASC);

