CREATE TABLE [dbo].[CASIN1] (
    [CSERCOD] CHAR (8) NOT NULL,
    [LMACOD]  CHAR (6) NOT NULL,
    PRIMARY KEY CLUSTERED ([CSERCOD] ASC, [LMACOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ICASIN1B]
    ON [dbo].[CASIN1]([LMACOD] ASC);

