CREATE TABLE [dbo].[CASIN] (
    [CSERCOD]  CHAR (8)        NOT NULL,
    [CSERNOM]  CHAR (30)       NULL,
    [CSERUNI]  CHAR (2)        NULL,
    [CMAQCOD]  CHAR (5)        NULL,
    [CSERHOR]  SMALLMONEY      NULL,
    [CSERFUN]  SMALLINT        NULL,
    [CSERSAL]  MONEY           NULL,
    [CSERENC]  MONEY           NULL,
    [CSERANO]  SMALLINT        NULL,
    [CSERDEP]  MONEY           NULL,
    [CSERNDE]  SMALLINT        NULL,
    [CSERCUST] DECIMAL (13, 4) NULL,
    PRIMARY KEY CLUSTERED ([CSERCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCASINA]
    ON [dbo].[CASIN]([CSERNOM] ASC);


GO
CREATE NONCLUSTERED INDEX [ICASINB]
    ON [dbo].[CASIN]([CMAQCOD] ASC);

