CREATE TABLE [dbo].[CAUF] (
    [CECOD]    CHAR (2)   NOT NULL,
    [CENOM]    CHAR (20)  NULL,
    [CEFRA]    CHAR (1)   NULL,
    [CEICM]    SMALLMONEY NULL,
    [CRgf0Cod] CHAR (2)   NULL,
    [CEICMST]  SMALLMONEY NULL,
    PRIMARY KEY CLUSTERED ([CECOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UCAUFA]
    ON [dbo].[CAUF]([CENOM] ASC);


GO
CREATE NONCLUSTERED INDEX [ICAUF]
    ON [dbo].[CAUF]([CRgf0Cod] ASC);

