CREATE TABLE [dbo].[CFGPAR] (
    [CFGEMP] CHAR (2)   NOT NULL,
    [CFGPAR] CHAR (50)  NOT NULL,
    [CFGVal] CHAR (50)  NULL,
    [CFGDes] CHAR (50)  NULL,
    [CFGPRM] CHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([CFGEMP] ASC, [CFGPAR] ASC)
);

