CREATE TABLE [dbo].[FFC] (
    [LFLUREG]  INT            NOT NULL,
    [LFLU1SEQ] SMALLINT       NOT NULL,
    [LFLU1HOR] CHAR (10)      NULL,
    [LFLU1RET] DATETIME       NULL,
    [LFLU1DAT] DATETIME       NULL,
    [LFLU1DES] VARCHAR (5000) NULL,
    [LFLU1USU] CHAR (30)      NULL,
    PRIMARY KEY CLUSTERED ([LFLUREG] ASC, [LFLU1SEQ] ASC)
);

