CREATE TABLE [dbo].[LACUST3] (
    [LNCCOD]  CHAR (60)       NOT NULL,
    [LNCSeq]  CHAR (2)        NOT NULL,
    [CPROCOD] CHAR (60)       NOT NULL,
    [LC4QU1]  DECIMAL (11, 4) NULL,
    PRIMARY KEY CLUSTERED ([LNCCOD] ASC, [LNCSeq] ASC, [CPROCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILACUST3B]
    ON [dbo].[LACUST3]([CPROCOD] ASC);

