CREATE TABLE [dbo].[LACUST4] (
    [LNCCOD]  CHAR (60) NOT NULL,
    [LNCSeq]  CHAR (2)  NOT NULL,
    [CTSERCO] CHAR (7)  NOT NULL,
    [LCCPES]  MONEY     NULL,
    [LCCTIP]  CHAR (2)  NULL,
    PRIMARY KEY CLUSTERED ([LNCCOD] ASC, [LNCSeq] ASC, [CTSERCO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILACUST4B]
    ON [dbo].[LACUST4]([CTSERCO] ASC);

