CREATE TABLE [dbo].[LACUST2] (
    [LNCCOD] CHAR (60)       NOT NULL,
    [LNCSeq] CHAR (2)        NOT NULL,
    [CMPCOD] CHAR (60)       NOT NULL,
    [LC3QUA] DECIMAL (11, 4) NULL,
    PRIMARY KEY CLUSTERED ([LNCCOD] ASC, [LNCSeq] ASC, [CMPCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILACUST2B]
    ON [dbo].[LACUST2]([CMPCOD] ASC);

