CREATE TABLE [dbo].[LADUP] (
    [DUPTIP]    CHAR (2)   NOT NULL,
    [DUPNUM]    INT        NOT NULL,
    [DUPSEQ]    CHAR (1)   NOT NULL,
    [DUPTipNF]  CHAR (1)   NOT NULL,
    [DUPIMP]    CHAR (1)   NULL,
    [CCCGC]     CHAR (18)  NULL,
    [DUPEMI]    DATETIME   NULL,
    [DUPVCT]    DATETIME   NULL,
    [DUPVCO]    DATETIME   NULL,
    [DUPVAL]    MONEY      NULL,
    [DUPDATBOR] DATETIME   NULL,
    [DUPSBo]    CHAR (2)   NULL,
    [CBACOD]    CHAR (3)   NULL,
    [DUPVPG]    DATETIME   NULL,
    [DUPPAG]    MONEY      NULL,
    [DUPDES]    MONEY      NULL,
    [DUPJUR]    MONEY      NULL,
    [DupObs]    CHAR (70)  NULL,
    [DUPFAT]    CHAR (1)   NULL,
    [DUPSEB]    CHAR (20)  NULL,
    [DUPMORA]   MONEY      NULL,
    [DUPTAX]    SMALLMONEY NULL,
    [DUPBAN]    CHAR (12)  NULL,
    [DUPCAR]    CHAR (1)   NULL,
    [DupDat]    DATETIME   NULL,
    [DupLib]    CHAR (1)   NULL,
    [DupCarDup] CHAR (1)   NULL,
    [DUPSAI]    DATETIME   NULL,
    [DUPCAN]    DATETIME   NULL,
    [DUPFECDat] DATETIME   NULL,
    [DUPUsuCri] CHAR (20)  NULL,
    [DUPDthCri] DATETIME   NULL,
    [DUPUsuAlt] CHAR (20)  NULL,
    [DUPDthAlt] DATETIME   NULL,
    [DUPTIPCOB] CHAR (1)   NULL,
    [CagCod]    SMALLINT   NULL,
    [CcoCod]    CHAR (11)  NULL,
    [DuPBOLSEQ] SMALLINT   NULL,
    [DupFluReg] INT        NULL,
    [DupTipPgt] CHAR (5)   NULL,
    [DupDDPDel] SMALLINT   NULL,
    PRIMARY KEY CLUSTERED ([DUPTIP] ASC, [DUPNUM] ASC, [DUPSEQ] ASC, [DUPTipNF] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ULADUPA]
    ON [dbo].[LADUP]([DUPEMI] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPB]
    ON [dbo].[LADUP]([DUPEMI] DESC);


GO
CREATE NONCLUSTERED INDEX [ULADUPC]
    ON [dbo].[LADUP]([DUPVCT] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPD]
    ON [dbo].[LADUP]([DUPVCT] DESC);


GO
CREATE NONCLUSTERED INDEX [ULADUPE]
    ON [dbo].[LADUP]([DUPVPG] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPF]
    ON [dbo].[LADUP]([DUPVPG] DESC);


GO
CREATE NONCLUSTERED INDEX [ULADUPG]
    ON [dbo].[LADUP]([DUPDATBOR] ASC, [DUPSBo] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPH]
    ON [dbo].[LADUP]([DUPNUM] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPI]
    ON [dbo].[LADUP]([DUPNUM] DESC);


GO
CREATE NONCLUSTERED INDEX [ULADUPJ]
    ON [dbo].[LADUP]([CCCGC] ASC, [DUPTIP] ASC, [DUPNUM] ASC, [DUPTipNF] ASC, [DUPSEQ] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPK]
    ON [dbo].[LADUP]([DUPTIP] ASC, [DUPNUM] ASC, [DUPTipNF] ASC, [DUPSEQ] ASC);


GO
CREATE NONCLUSTERED INDEX [ILADUPC]
    ON [dbo].[LADUP]([CcoCod] ASC, [CagCod] ASC, [CBACOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPL]
    ON [dbo].[LADUP]([DUPTIP] ASC, [DupFluReg] ASC);


GO
CREATE NONCLUSTERED INDEX [ULADUPM]
    ON [dbo].[LADUP]([DupFluReg] ASC);

