CREATE TABLE [dbo].[LAESPPED] (
    [Ped0EMP]    CHAR (2)   NOT NULL,
    [Ped0NUM]    INT        NOT NULL,
    [Ped0Tip]    CHAR (1)   NOT NULL,
    [Ped0TIPVEN] SMALLINT   NULL,
    [Ped0PV0]    INT        NULL,
    [CCCGC]      CHAR (18)  NULL,
    [Ped0CECOD]  CHAR (2)   NULL,
    [Ped0SPE]    CHAR (18)  NULL,
    [Ped0PC0]    SMALLMONEY NULL,
    [Ped0DATPED] DATETIME   NULL,
    [Ped0DATENT] DATETIME   NULL,
    [COCOD]      CHAR (6)   NULL,
    [Ped0CON]    CHAR (20)  NULL,
    [Ped0FRE]    CHAR (1)   NULL,
    [Ped0EMPCOD] CHAR (2)   NULL,
    [CACODI]     SMALLINT   NULL,
    [Ped0MOE]    CHAR (1)   NULL,
    [Ped0MAR]    CHAR (8)   NULL,
    [Ped0QVO]    INT        NULL,
    [Ped0ESP]    CHAR (20)  NULL,
    [Ped0VOL]    CHAR (8)   NULL,
    [Ped0PLQ]    MONEY      NULL,
    [Ped0PBR]    MONEY      NULL,
    [Ped0DATEMI] DATETIME   NULL,
    [Ped0VALTOT] MONEY      NULL,
    [Ped0VALSUF] MONEY      NULL,
    [Ped0BASICM] MONEY      NULL,
    [Ped0PERICM] SMALLMONEY NULL,
    [Ped0VALICM] MONEY      NULL,
    [Ped0TOTPRO] MONEY      NULL,
    [Ped0VALIPI] MONEY      NULL,
    [Ped0VALCOM] MONEY      NULL,
    [Ped0IMP]    CHAR (1)   NULL,
    [Ped0OF]     INT        NULL,
    [Ped0EST]    CHAR (1)   NULL,
    [Ped0ELI]    CHAR (3)   NULL,
    [Ped0BAS1]   MONEY      NULL,
    [Ped0VFRE]   MONEY      NULL,
    [Ped0PERIPI] SMALLMONEY NULL,
    [Ped0VEN]    CHAR (3)   NULL,
    [Ped0CPAG]   CHAR (3)   NULL,
    [Ped0TRAC]   CHAR (5)   NULL,
    [Ped0ENT]    CHAR (1)   NULL,
    [Ped0SIPI]   MONEY      NULL,
    PRIMARY KEY CLUSTERED ([Ped0EMP] ASC, [Ped0NUM] ASC, [Ped0Tip] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDB]
    ON [dbo].[LAESPPED]([Ped0TRAC] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDC]
    ON [dbo].[LAESPPED]([Ped0CPAG] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDD]
    ON [dbo].[LAESPPED]([Ped0VEN] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDE]
    ON [dbo].[LAESPPED]([Ped0EMPCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDF]
    ON [dbo].[LAESPPED]([Ped0CECOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDG]
    ON [dbo].[LAESPPED]([CACODI] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDH]
    ON [dbo].[LAESPPED]([COCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAESPPEDI]
    ON [dbo].[LAESPPED]([CCCGC] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAESPPEDA]
    ON [dbo].[LAESPPED]([Ped0DATEMI] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAESPPEDB]
    ON [dbo].[LAESPPED]([Ped0DATEMI] DESC);


GO
CREATE NONCLUSTERED INDEX [ULAESPPEDC]
    ON [dbo].[LAESPPED]([Ped0NUM] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAESPPEDD]
    ON [dbo].[LAESPPED]([Ped0NUM] DESC);

