CREATE TABLE [dbo].[LAFLUAUT] (
    [CEMPCOD]      CHAR (2)  NOT NULL,
    [FluNum]       INT       NOT NULL,
    [FLUDOC]       INT       NULL,
    [FLUSIT]       CHAR (1)  NULL,
    [FluCcCgc]     CHAR (18) NULL,
    [FLUDAT]       DATETIME  NULL,
    [FLUDIA]       SMALLINT  NULL,
    [FLUNOM]       CHAR (30) NULL,
    [FLUVAL]       MONEY     NULL,
    [FLUDES]       SMALLINT  NULL,
    [FLUPAG]       CHAR (1)  NULL,
    [CSETCOD]      CHAR (3)  NULL,
    [C1PLA]        CHAR (3)  NULL,
    [C2PLA]        CHAR (3)  NULL,
    [FLUDTAESP]    SMALLINT  NULL,
    [FLUEOM]       SMALLINT  NULL,
    [CBACOD]       CHAR (3)  NULL,
    [FluCaPlC0Cod] CHAR (11) NULL,
    PRIMARY KEY CLUSTERED ([CEMPCOD] ASC, [FluNum] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAFLUAUTB]
    ON [dbo].[LAFLUAUT]([FluCcCgc] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAFLUAUTA]
    ON [dbo].[LAFLUAUT]([FluNum] DESC);


GO
CREATE NONCLUSTERED INDEX [ILAFLUAUT]
    ON [dbo].[LAFLUAUT]([C2PLA] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAFLUAUT1]
    ON [dbo].[LAFLUAUT]([C1PLA] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAFLUAUT3]
    ON [dbo].[LAFLUAUT]([CSETCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAFLUAUT2]
    ON [dbo].[LAFLUAUT]([CBACOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAFLUAUT4]
    ON [dbo].[LAFLUAUT]([FluCaPlC0Cod] ASC);

