CREATE TABLE [dbo].[LAFLUFECDIA] (
    [LFluFD0EmpCod]    CHAR (2)  NOT NULL,
    [LFluFD0CbaCod]    CHAR (3)  NOT NULL,
    [LFluFD0Dat]       DATETIME  NOT NULL,
    [LFluFD0SalAnt]    MONEY     NULL,
    [LFluFD0TotEnt]    MONEY     NULL,
    [LFluFD0TotSai]    MONEY     NULL,
    [LFluFD0SgUsu0Cod] CHAR (20) NULL,
    [LFluFD0SgUsu0DtH] DATETIME  NULL,
    PRIMARY KEY CLUSTERED ([LFluFD0EmpCod] ASC, [LFluFD0CbaCod] ASC, [LFluFD0Dat] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAFLUFECDIAB]
    ON [dbo].[LAFLUFECDIA]([LFluFD0CbaCod] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAFLUFECDIAA]
    ON [dbo].[LAFLUFECDIA]([LFluFD0EmpCod] ASC, [LFluFD0CbaCod] ASC, [LFluFD0Dat] DESC);


GO
CREATE NONCLUSTERED INDEX [ULAFECDIAB]
    ON [dbo].[LAFLUFECDIA]([LFluFD0SgUsu0Cod] ASC, [LFluFD0EmpCod] ASC, [LFluFD0CbaCod] ASC, [LFluFD0Dat] ASC);

