CREATE TABLE [dbo].[LAMPRREQ] (
    [LCEMP]    CHAR (2)  NOT NULL,
    [LCCOD]    INT       NOT NULL,
    [CSETCOD]  CHAR (3)  NULL,
    [LCRET]    CHAR (10) NULL,
    [TRACOD]   CHAR (6)  NULL,
    [LCENT]    DATETIME  NULL,
    [LCSAI]    DATETIME  NULL,
    [LCULTSEQ] SMALLINT  NULL,
    [LCCSTA]   CHAR (1)  NULL,
    PRIMARY KEY CLUSTERED ([LCEMP] ASC, [LCCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAMPRREQB]
    ON [dbo].[LAMPRREQ]([TRACOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAMPRREQC]
    ON [dbo].[LAMPRREQ]([CSETCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAMPRREQA]
    ON [dbo].[LAMPRREQ]([LCENT] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAMPRREQB]
    ON [dbo].[LAMPRREQ]([LCENT] DESC);


GO
CREATE NONCLUSTERED INDEX [ULAMPRREQC]
    ON [dbo].[LAMPRREQ]([LCEMP] ASC, [LCCOD] DESC);

