CREATE TABLE [dbo].[LAMPRREQ1] (
    [LCEMP]  CHAR (2)   NOT NULL,
    [LCCOD]  INT        NOT NULL,
    [LCSeq]  SMALLINT   NOT NULL,
    [CMPCOD] CHAR (60)  NULL,
    [LCQUA]  SMALLMONEY NULL,
    [LCOF]   INT        NULL,
    [LCRIR]  INT        NULL,
    PRIMARY KEY CLUSTERED ([LCEMP] ASC, [LCCOD] ASC, [LCSeq] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAMPRREQ1B]
    ON [dbo].[LAMPRREQ1]([CMPCOD] ASC);

