CREATE TABLE [dbo].[LANFCARCOR] (
    [NCCEmp] CHAR (2)  NOT NULL,
    [NCCNum] INT       NOT NULL,
    [NCCTip] CHAR (1)  NOT NULL,
    [NOT1]   CHAR (1)  NULL,
    [NOT2]   CHAR (1)  NULL,
    [NOT3]   CHAR (1)  NULL,
    [NOT4]   CHAR (1)  NULL,
    [NOT5]   CHAR (1)  NULL,
    [NOT6]   CHAR (1)  NULL,
    [NOT7]   CHAR (1)  NULL,
    [NOT8]   CHAR (1)  NULL,
    [NOT9]   CHAR (1)  NULL,
    [NOT10]  CHAR (1)  NULL,
    [NOT11]  CHAR (1)  NULL,
    [NOT12]  CHAR (1)  NULL,
    [NOT13]  CHAR (1)  NULL,
    [NOT14]  CHAR (1)  NULL,
    [NOT15]  CHAR (1)  NULL,
    [NOT16]  CHAR (1)  NULL,
    [NOT17]  CHAR (1)  NULL,
    [NOT18]  CHAR (1)  NULL,
    [NOT19]  CHAR (1)  NULL,
    [NOT20]  CHAR (1)  NULL,
    [NOT21]  CHAR (1)  NULL,
    [NOT22]  CHAR (1)  NULL,
    [NOT23]  CHAR (1)  NULL,
    [NOT24]  CHAR (1)  NULL,
    [NOT25]  CHAR (1)  NULL,
    [NOT26]  CHAR (1)  NULL,
    [NOT27]  CHAR (1)  NULL,
    [NOT28]  CHAR (1)  NULL,
    [NOT29]  CHAR (1)  NULL,
    [NOT30]  CHAR (1)  NULL,
    [NOT31]  CHAR (1)  NULL,
    [NOT32]  CHAR (1)  NULL,
    [NOT33]  CHAR (1)  NULL,
    [NRET1]  CHAR (2)  NULL,
    [NRET2]  CHAR (2)  NULL,
    [NRET3]  CHAR (2)  NULL,
    [NRET4]  CHAR (2)  NULL,
    [NRET5]  CHAR (2)  NULL,
    [NRET6]  CHAR (2)  NULL,
    [NDRET1] CHAR (90) NULL,
    [NDRET2] CHAR (90) NULL,
    [NDRET3] CHAR (90) NULL,
    [NDRET4] CHAR (90) NULL,
    [NDRET5] CHAR (90) NULL,
    [NDRET6] CHAR (90) NULL,
    PRIMARY KEY CLUSTERED ([NCCEmp] ASC, [NCCNum] ASC, [NCCTip] ASC)
);

