CREATE TABLE [dbo].[LAOPESERREA] (
    [COPECOD] CHAR (3)        NOT NULL,
    [LSESEQ]  INT             NOT NULL,
    [LSEDAT]  DATETIME        NULL,
    [LSEHOI]  SMALLINT        NULL,
    [LSEHOF]  SMALLINT        NULL,
    [LSEMII]  SMALLINT        NULL,
    [LSEMIF]  SMALLINT        NULL,
    [LSEALM]  CHAR (1)        NULL,
    [COCOCOD] CHAR (3)        NULL,
    [OrdCod]  INT             NULL,
    [LSEPRO]  DECIMAL (11, 4) NULL,
    [LSEPER]  DECIMAL (11, 4) NULL,
    [LSEPCE]  SMALLMONEY      NULL,
    [OrdEmp]  CHAR (2)        NULL,
    [CPSSeq]  SMALLINT        NULL,
    PRIMARY KEY CLUSTERED ([COPECOD] ASC, [LSESEQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAOPESERREAB]
    ON [dbo].[LAOPESERREA]([COCOCOD] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAOPESERREAA]
    ON [dbo].[LAOPESERREA]([LSEDAT] ASC);


GO
CREATE NONCLUSTERED INDEX [ILAOPESERREA1]
    ON [dbo].[LAOPESERREA]([OrdEmp] ASC, [OrdCod] ASC, [CPSSeq] ASC);

