CREATE TABLE [dbo].[LAORVAUX] (
    [Empresa]                            VARCHAR (2)    NOT NULL,
    [Número]                             NCHAR (8)      NOT NULL,
    [Revisão]                            VARCHAR (1)    NOT NULL,
    [Codigo da Situação]                 INT            NOT NULL,
    [Origem]                             VARCHAR (6)    NOT NULL,
    [Data do Cadastro]                   DATETIME       NOT NULL,
    [Data de Validade]                   NVARCHAR (10)  NULL,
    [Nome do Usuário]                    VARCHAR (6)    NOT NULL,
    [Cliente]                            INT            NOT NULL,
    [Nome Fantasia]                      NVARCHAR (100) NOT NULL,
    [Razão Social]                       NVARCHAR (100) NOT NULL,
    [Logradouro]                         VARCHAR (1)    NOT NULL,
    [Endereço]                           NVARCHAR (200) NULL,
    [Número do Endereço]                 CHAR (10)      NULL,
    [Complemento do Endereço]            CHAR (30)      NULL,
    [Bairro]                             CHAR (200)     NULL,
    [CEP]                                CHAR (9)       NULL,
    [Cidade]                             CHAR (200)     NULL,
    [Estado]                             CHAR (2)       NULL,
    [DDD do Telefone]                    CHAR (3)       NULL,
    [Telefone]                           VARCHAR (9)    NULL,
    [Ramal do Telefone]                  CHAR (5)       NULL,
    [DDD do Fax]                         CHAR (3)       NULL,
    [Fax]                                VARCHAR (9)    NULL,
    [Ramal do Fax]                       CHAR (5)       NULL,
    [ID do Contato]                      INT            NOT NULL,
    [Nome do Contato]                    CHAR (200)     NULL,
    [Departamento do Contato]            CHAR (100)     NULL,
    [Cargo do Contato]                   VARCHAR (1)    NOT NULL,
    [DDD do Telefone do Contato]         CHAR (3)       NULL,
    [Telefone do Contato]                VARCHAR (9)    NULL,
    [Ramal do Telefone do Contato]       CHAR (5)       NULL,
    [DDD do Fax do Contato]              CHAR (3)       NULL,
    [Fax do Contato]                     VARCHAR (9)    NULL,
    [Ramal do Fax do Contato]            CHAR (5)       NULL,
    [DDD do Celular do Contato]          CHAR (3)       NULL,
    [Celular do Contato]                 VARCHAR (9)    NULL,
    [Email]                              NVARCHAR (200) NULL,
    [Código do Representante]            CHAR (10)      NOT NULL,
    [Nome do Representante]              NVARCHAR (50)  NOT NULL,
    [Representante ou Vendedor]          VARCHAR (1)    NOT NULL,
    [Código da Condição de Pagamento]    VARCHAR (1)    NOT NULL,
    [Descrição da Condição de Pagamento] VARCHAR (1)    NOT NULL,
    [Observação]                         VARCHAR (5000) NULL,
    [Referencia]                         VARCHAR (1)    NOT NULL,
    [Impostos]                           VARCHAR (1)    NOT NULL,
    [Tipo de Venda]                      VARCHAR (9)    NOT NULL,
    [Data da Situação]                   DATETIME       NULL,
    [Descrição da Situação]              CHAR (50)      NULL,
    [Número do Pedido de Venda]          INT            NULL,
    [Probabilidade de Fechamento]        INT            NOT NULL,
    [Data do Próximo Contato]            DATETIME       NULL,
    [Tipo de Material]                   VARCHAR (1)    NOT NULL,
    [Nome dos Concorrentes]              VARCHAR (1)    NOT NULL,
    [E-mail Enviado]                     NVARCHAR (1)   NULL,
    [Data do Envio do E-mail]            DATETIME       NULL,
    [Data e Hora do Envio do E-Mail]     DATETIME       NULL,
    [Usuário do Envio do E-Mail]         CHAR (20)      NULL,
    [Sequencia do Envio do E-Mail]       SMALLINT       NULL
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[LAORVAUX] TO [altanet]
    AS [dbo];

