CREATE TABLE [dbo].[LAPRGPRO1] (
    [LPP0Emp] CHAR (2)        NOT NULL,
    [LPP0CO]  INT             NOT NULL,
    [Lpp0seq] SMALLINT        NOT NULL,
    [CPROCOD] CHAR (60)       NULL,
    [LPP1ENT] DATETIME        NULL,
    [LPP1QUA] DECIMAL (11, 4) NULL,
    [LPP1DA1] DATETIME        NULL,
    [LPP1DA2] DATETIME        NULL,
    [LPP1DA3] DATETIME        NULL,
    [LPP1DA4] DATETIME        NULL,
    [LPP1Q1]  DECIMAL (11, 4) NULL,
    [LPP1Q2]  DECIMAL (11, 4) NULL,
    [LPP1Q3]  DECIMAL (11, 4) NULL,
    [LPP1Q4]  DECIMAL (11, 4) NULL,
    [CPRO1EP] CHAR (2)        NULL,
    [LPP1OP]  INT             NULL,
    PRIMARY KEY CLUSTERED ([LPP0Emp] ASC, [LPP0CO] ASC, [Lpp0seq] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAPRGPRO1C]
    ON [dbo].[LAPRGPRO1]([CPROCOD] ASC, [CPRO1EP] ASC);

