CREATE TABLE [dbo].[LAPRGPRO] (
    [LPP0Emp] CHAR (2)  NOT NULL,
    [LPP0CO]  INT       NOT NULL,
    [LPP0D1]  DATETIME  NULL,
    [LPP0D2]  DATETIME  NULL,
    [LPP0DE]  CHAR (40) NULL,
    [CCCGC]   CHAR (18) NULL,
    [LPP0GER] CHAR (1)  NULL,
    PRIMARY KEY CLUSTERED ([LPP0Emp] ASC, [LPP0CO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILAPRGPROB]
    ON [dbo].[LAPRGPRO]([CCCGC] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAPRGPROA]
    ON [dbo].[LAPRGPRO]([LPP0D2] ASC, [LPP0D1] ASC);


GO
CREATE NONCLUSTERED INDEX [ULAPRGPROB]
    ON [dbo].[LAPRGPRO]([LPP0CO] ASC);

