CREATE TABLE [dbo].[LISCAT2] (
    [Lis0Cod] SMALLINT   NOT NULL,
    [LisGru]  SMALLINT   NOT NULL,
    [Lis1Cod] SMALLINT   NOT NULL,
    [CPROCOD] CHAR (60)  NULL,
    [Lis1Des] CHAR (120) NULL,
    CONSTRAINT [PK__LISCAT2__4C871E757EE1CA6C] PRIMARY KEY CLUSTERED ([Lis0Cod] ASC, [LisGru] ASC, [Lis1Cod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILISPROLEVEL11]
    ON [dbo].[LISCAT2]([CPROCOD] ASC);

