CREATE TABLE [dbo].[LNFGRT] (
    [LnfGrT0Emp]       CHAR (2)        NOT NULL,
    [LnfGrT0Usu]       CHAR (20)       NOT NULL,
    [LnfGrT0Cnpj]      CHAR (18)       NOT NULL,
    [LnfGrT0Ped]       INT             NOT NULL,
    [LnfGrT0Ite]       SMALLINT        NOT NULL,
    [LnfGrT0ProCod]    CHAR (60)       NOT NULL,
    [LnfGrT0ProTip]    CHAR (2)        NOT NULL,
    [LnfGrT0QuaNF]     DECIMAL (11, 4) NULL,
    [LnfGrT0ProUniNF]  CHAR (2)        NULL,
    [LnfGrT0QuaEst]    DECIMAL (11, 4) NULL,
    [LnfGrT0Pre]       DECIMAL (13, 4) NULL,
    [LnfGrT0ProAju]    SMALLMONEY      NULL,
    [LnfGrT0CST]       CHAR (3)        NULL,
    [LnfGrT0CoCod]     CHAR (6)        NULL,
    [LnfGrT0CF]        CHAR (5)        NULL,
    [LnfGrT0NCM]       CHAR (10)       NULL,
    [LnfGrT0UsoCon]    CHAR (1)        NULL,
    [LnfGrT0IpiAli]    SMALLMONEY      NULL,
    [LnfGrT0IpiAju]    SMALLINT        NULL,
    [LnfGrT0IcmBasRed] SMALLMONEY      NULL,
    [LnfGrT0IcmAli]    SMALLMONEY      NULL,
    [LnfGrT0IcmAju]    SMALLMONEY      NULL,
    [LnfGrT0FreIte]    MONEY           NULL,
    [LnfGrT0IcSTrb]    CHAR (1)        NULL,
    [LnfGrT0IcSMRC]    SMALLMONEY      NULL,
    [LnfGrT0IcSAli]    SMALLMONEY      NULL,
    [LnfGrT0IcSAju]    SMALLMONEY      NULL,
    [LnfGrt0ProSom]    CHAR (1)        NULL,
    PRIMARY KEY CLUSTERED ([LnfGrT0Emp] ASC, [LnfGrT0Usu] ASC, [LnfGrT0Cnpj] ASC, [LnfGrT0Ped] ASC, [LnfGrT0Ite] ASC, [LnfGrT0ProCod] ASC, [LnfGrT0ProTip] ASC)
);

