CREATE TABLE [dbo].[LOC] (
    [LOC0COD]  INT        NOT NULL,
    [LOC0EMP]  CHAR (2)   NOT NULL,
    [LOC0CNPJ] CHAR (18)  NOT NULL,
    [LOC0DAT]  DATETIME   NULL,
    [LOC0PEN]  CHAR (20)  NULL,
    [LOC0ENT]  CHAR (100) NULL,
    [Loc0Pag]  CHAR (3)   NULL,
    [LOC0GER]  CHAR (1)   NULL,
    PRIMARY KEY CLUSTERED ([LOC0COD] ASC, [LOC0EMP] ASC, [LOC0CNPJ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ILOCB]
    ON [dbo].[LOC]([LOC0CNPJ] ASC);


GO
CREATE NONCLUSTERED INDEX [ILOCC]
    ON [dbo].[LOC]([Loc0Pag] ASC);


GO
CREATE NONCLUSTERED INDEX [ULOCA]
    ON [dbo].[LOC]([LOC0COD] DESC);


GO
CREATE NONCLUSTERED INDEX [ULOCB]
    ON [dbo].[LOC]([LOC0EMP] ASC, [LOC0COD] ASC, [LOC0CNPJ] ASC);


GO
CREATE NONCLUSTERED INDEX [ULOCC]
    ON [dbo].[LOC]([LOC0EMP] ASC, [LOC0COD] DESC, [LOC0CNPJ] ASC);

