CREATE TABLE [dbo].[LOC1] (
    [LOC0COD]    INT             NOT NULL,
    [LOC0EMP]    CHAR (2)        NOT NULL,
    [LOC0CNPJ]   CHAR (18)       NOT NULL,
    [LOC1SEQ]    SMALLINT        NOT NULL,
    [LOC1PROCOD] CHAR (60)       NULL,
    [LOC1PRE]    MONEY           NULL,
    [LOC1QUA]    DECIMAL (11, 4) NULL,
    [LOC1IPI]    SMALLMONEY      NULL,
    [LOC1PRONOM] CHAR (120)      NULL,
    [Loc1Tip]    CHAR (2)        NULL,
    [LOC1UNI]    CHAR (2)        NULL,
    CONSTRAINT [PK__LOC1__93CFB9E00DCF0841] PRIMARY KEY CLUSTERED ([LOC0COD] ASC, [LOC0EMP] ASC, [LOC0CNPJ] ASC, [LOC1SEQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ULOC1A]
    ON [dbo].[LOC1]([LOC0EMP] ASC, [LOC0COD] ASC, [LOC1SEQ] ASC);


GO
CREATE NONCLUSTERED INDEX [ULOC1B]
    ON [dbo].[LOC1]([LOC0EMP] ASC, [LOC0COD] ASC, [LOC0CNPJ] ASC, [LOC1SEQ] DESC);

