CREATE TABLE [dbo].[M0121021] (
    [CTABCOD] SMALLINT NOT NULL,
    [CDCOD]   CHAR (6) NOT NULL,
    [CTABATU] MONEY    NULL,
    PRIMARY KEY CLUSTERED ([CTABCOD] ASC, [CDCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IM012106]
    ON [dbo].[M0121021]([CDCOD] ASC);

