CREATE TABLE [dbo].[M012102] (
    [CTABCOD] SMALLINT   NOT NULL,
    [CTABNOM] CHAR (30)  NULL,
    [CTABFUN] INT        NULL,
    [CTABHOR] SMALLMONEY NULL,
    [CATCUST] MONEY      NULL,
    PRIMARY KEY CLUSTERED ([CTABCOD] ASC)
);

