CREATE TABLE [dbo].[M0121011] (
    [CDCOD] CHAR (6) NOT NULL,
    [CDDAT] DATETIME NOT NULL,
    [CDVAL] MONEY    NULL,
    [CDVAR] MONEY    NULL,
    PRIMARY KEY CLUSTERED ([CDCOD] ASC, [CDDAT] ASC)
);

