CREATE TABLE [dbo].[M01214] (
    [CDIMCOD] CHAR (3)   NOT NULL,
    [CDIMNOM] CHAR (30)  NULL,
    [CDIMVAL] SMALLMONEY NULL,
    [CDITIPO] CHAR (1)   NULL,
    PRIMARY KEY CLUSTERED ([CDIMCOD] ASC)
);

