CREATE TABLE [dbo].[M0204021] (
    [LCDCOD]  INT             NOT NULL,
    [LCDEMP]  CHAR (2)        NOT NULL,
    [LCDSEQ]  SMALLINT        NOT NULL,
    [CDIVCOD] CHAR (60)       NULL,
    [LCDBAI]  CHAR (1)        NULL,
    [LCDQUA]  DECIMAL (11, 4) NULL,
    [LCDQUA1] DECIMAL (11, 4) NULL,
    PRIMARY KEY CLUSTERED ([LCDCOD] ASC, [LCDEMP] ASC, [LCDSEQ] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IM02040212]
    ON [dbo].[M0204021]([CDIVCOD] ASC);

