CREATE TABLE [dbo].[OPROMITEMHISTORICO] (
    [OPR0Emp]    CHAR (2)      NOT NULL,
    [OPR0Cod]    INT           NOT NULL,
    [OPR1OPEmp]  CHAR (2)      NOT NULL,
    [OPR1OPCod]  INT           NOT NULL,
    [OPR1CPbCod] CHAR (60)     NOT NULL,
    [OPR3HisSeq] SMALLINT      NOT NULL,
    [OPR3HisDat] DATETIME      NULL,
    [OPR3HisDtH] DATETIME      NULL,
    [OPR3HisUsu] CHAR (20)     NULL,
    [OPR3HisObs] VARCHAR (500) NULL,
    CONSTRAINT [PK_OPRomItemHistorico] PRIMARY KEY CLUSTERED ([OPR0Emp] ASC, [OPR0Cod] ASC, [OPR1OPEmp] ASC, [OPR1OPCod] ASC, [OPR1CPbCod] ASC, [OPR3HisSeq] ASC)
);


GO
CREATE NONCLUSTERED INDEX [UOPROMITEMHISTORICOC]
    ON [dbo].[OPROMITEMHISTORICO]([OPR0Emp] ASC, [OPR0Cod] ASC, [OPR1OPEmp] ASC, [OPR1OPCod] ASC, [OPR3HisDtH] DESC);


GO
CREATE NONCLUSTERED INDEX [UOPROMITEMHISTORICOB]
    ON [dbo].[OPROMITEMHISTORICO]([OPR0Emp] ASC, [OPR0Cod] ASC, [OPR1OPEmp] ASC, [OPR1OPCod] ASC, [OPR1CPbCod] ASC, [OPR3HisDtH] ASC);


GO
CREATE NONCLUSTERED INDEX [UOPROMITEMHISTORICOA]
    ON [dbo].[OPROMITEMHISTORICO]([OPR0Emp] ASC, [OPR0Cod] ASC, [OPR1OPEmp] ASC, [OPR1OPCod] ASC, [OPR1CPbCod] ASC, [OPR3HisSeq] DESC);

