CREATE TABLE [dbo].[OPROMITEM] (
    [OPR0Emp]     CHAR (2)      NOT NULL,
    [OPR0Cod]     INT           NOT NULL,
    [OPR1OPEmp]   CHAR (2)      NOT NULL,
    [OPR1OPCod]   INT           NOT NULL,
    [OPR1CPbCod]  CHAR (60)     NOT NULL,
    [OPR1Qtd]     DECIMAL (10)  NULL,
    [OPR1LPPed]   INT           NULL,
    [OPR1LpSeq]   SMALLINT      NULL,
    [OPR1Bai]     CHAR (1)      NULL,
    [OPR1BaiDat]  DATETIME      NULL,
    [OPR1BaiDtH]  DATETIME      NULL,
    [OPR1BaiUsu]  CHAR (20)     NULL,
    [OPR1LPEmp]   CHAR (2)      NULL,
    [OPR1BaiObs]  VARCHAR (500) NULL,
    [OPR1Obs]     VARCHAR (500) NULL,
    [OPR1BaiQtd]  DECIMAL (10)  NULL,
    [OPr1IniUsu]  CHAR (20)     NULL,
    [OPR1IniDtH]  DATETIME      NULL,
    [OPR1IniDat]  DATETIME      NULL,
    [OPR1Ini]     CHAR (1)      NULL,
    [OPR1PrCDias] SMALLINT      NULL,
    [OPR1PrCDat]  DATETIME      NULL,
    [OPr1Aca]     CHAR (10)     NULL,
    [OPR1DtHCri]  DATETIME      NULL,
    [OPR1UsuCri]  CHAR (20)     NULL,
    PRIMARY KEY CLUSTERED ([OPR0Emp] ASC, [OPR0Cod] ASC, [OPR1OPEmp] ASC, [OPR1OPCod] ASC, [OPR1CPbCod] ASC)
);

