CREATE TABLE [dbo].[ORDFABLAN1] (
    [OrdEmp]    CHAR (2) NOT NULL,
    [OrdCod]    INT      NOT NULL,
    [CTSERCO]   CHAR (7) NOT NULL,
    [OrdBenDtE] DATETIME NULL,
    PRIMARY KEY CLUSTERED ([OrdEmp] ASC, [OrdCod] ASC, [CTSERCO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IORDFABLAN11]
    ON [dbo].[ORDFABLAN1]([CTSERCO] ASC);

