CREATE TABLE [dbo].[REGEMP] (
    [RegCod]       INT             NOT NULL,
    [CEMPCOD]      CHAR (2)        NOT NULL,
    [RegDta]       DATETIME        NULL,
    [RegEmp]       CHAR (100)      NULL,
    [RegFilPAi]    CHAR (100)      NULL,
    [RegFliPaiNac] CHAR (40)       NULL,
    [RegFilMae]    CHAR (100)      NULL,
    [RegFilMaeNac] CHAR (40)       NULL,
    [RegDtaNas]    DATETIME        NULL,
    [RegIda]       CHAR (10)       NULL,
    [RegNac]       CHAR (20)       NULL,
    [RegEstCiv]    CHAR (20)       NULL,
    [RegEst]       CHAR (20)       NULL,
    [RegRg]        CHAR (30)       NULL,
    [RegCarPro]    CHAR (20)       NULL,
    [RegSer]       CHAR (10)       NULL,
    [RegCarRev]    CHAR (20)       NULL,
    [RegCat]       CHAR (20)       NULL,
    [RecCpf]       CHAR (20)       NULL,
    [RegTitEle]    CHAR (20)       NULL,
    [RegCarSau]    CHAR (20)       NULL,
    [RegQEst]      DATETIME        NULL,
    [RegCar19]     CHAR (20)       NULL,
    [RegCas]       CHAR (3)        NULL,
    [RegNat]       CHAR (3)        NULL,
    [RegFil]       CHAR (3)        NULL,
    [RegRegGer]    CHAR (20)       NULL,
    [RegConj]      CHAR (30)       NULL,
    [RegQua]       CHAR (3)        NULL,
    [RegEnd]       CHAR (200)      NULL,
    [RegCor]       CHAR (10)       NULL,
    [RegAltu]      CHAR (10)       NULL,
    [RegPes]       CHAR (10)       NULL,
    [RegCab]       CHAR (10)       NULL,
    [RegOlh]       CHAR (10)       NULL,
    [RegSin]       CHAR (10)       NULL,
    [RegBen1]      CHAR (40)       NULL,
    [RegPar1]      CHAR (20)       NULL,
    [RegNas1]      DATETIME        NULL,
    [RegBen2]      CHAR (40)       NULL,
    [RegPar2]      CHAR (20)       NULL,
    [RegNas2]      DATETIME        NULL,
    [RegBen3]      CHAR (40)       NULL,
    [RegPar3]      CHAR (20)       NULL,
    [RegNas3]      DATETIME        NULL,
    [RegBen4]      CHAR (40)       NULL,
    [RegPar4]      CHAR (20)       NULL,
    [RegNas4]      DATETIME        NULL,
    [RegBen5]      CHAR (40)       NULL,
    [RegPar5]      CHAR (20)       NULL,
    [RegNas5]      DATETIME        NULL,
    [RegCad]       CHAR (20)       NULL,
    [RegSonN]      CHAR (20)       NULL,
    [RegDptBco]    CHAR (20)       NULL,
    [RegEndInt]    CHAR (20)       NULL,
    [RegCodBco]    CHAR (10)       NULL,
    [RegAge]       CHAR (10)       NULL,
    [RegDatAdm]    DATETIME        NULL,
    [regdatReg]    DATETIME        NULL,
    [RegCar]       CHAR (20)       NULL,
    [RegSec]       CHAR (20)       NULL,
    [RegSal]       CHAR (20)       NULL,
    [RegCom]       CHAR (20)       NULL,
    [RegTar]       CHAR (20)       NULL,
    [RegFor]       CHAR (20)       NULL,
    [RegOp]        CHAR (3)        NULL,
    [RegDtaOp]     DATETIME        NULL,
    [RegDatRet]    DATETIME        NULL,
    [RegBco]       CHAR (10)       NULL,
    [RegHorEnt]    DATETIME        NULL,
    [RegHorRef]    CHAR (20)       NULL,
    [RegHorSai]    DATETIME        NULL,
    [RegDes]       CHAR (20)       NULL,
    [RegFoto]      VARBINARY (MAX) NULL,
    PRIMARY KEY CLUSTERED ([RegCod] ASC, [CEMPCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IREGEMP1]
    ON [dbo].[REGEMP]([CEMPCOD] ASC);

