CREATE TABLE [dbo].[RNC] (
    [RNCEMP]         CHAR (2)      NOT NULL,
    [RNCNUM]         INT           NOT NULL,
    [RNCDTACAD]      DATETIME      NULL,
    [RNCEMI]         CHAR (40)     NULL,
    [RNCTIP]         CHAR (1)      NULL,
    [RNCCLI]         CHAR (20)     NULL,
    [RNCDES]         CHAR (60)     NULL,
    [RNCINS]         CHAR (1)      NULL,
    [RNCINSOUT]      CHAR (20)     NULL,
    [RNCPEDCOM]      DECIMAL (10)  NULL,
    [RNCPEDVEN]      DECIMAL (10)  NULL,
    [RNCNUMOP]       DECIMAL (10)  NULL,
    [RNCNUMNF]       DECIMAL (10)  NULL,
    [RNCNUMCER]      DECIMAL (10)  NULL,
    [RNCDATNF]       DATETIME      NULL,
    [RNCSET]         CHAR (20)     NULL,
    [RNCQTDINS]      INT           NULL,
    [RNCQTDCON]      INT           NULL,
    [RNCLOT]         INT           NULL,
    [RNCOUT]         CHAR (20)     NULL,
    [RNCESP]         VARCHAR (500) NULL,
    [RNCENC]         VARCHAR (500) NULL,
    [RNCPES]         VARCHAR (500) NULL,
    [RNCPRO]         CHAR (1)      NULL,
    [RNCACEEST]      CHAR (1)      NULL,
    [RNCCORSUC]      CHAR (1)      NULL,
    [RNCCORSUCPC]    INT           NULL,
    [RNCCORRET]      CHAR (1)      NULL,
    [RNCCORRETPC]    INT           NULL,
    [RNCCORREC]      CHAR (1)      NULL,
    [RNCCORRECPC]    INT           NULL,
    [RNCCORCREP]     CHAR (1)      NULL,
    [RNCCORSREP]     CHAR (1)      NULL,
    [RNCCORREPFAB]   CHAR (1)      NULL,
    [RNCCORREPFABOP] INT           NULL,
    [RNCCOREST]      CHAR (1)      NULL,
    [RNCCORESTOP]    INT           NULL,
    [RNCCORAUT]      CHAR (50)     NULL,
    [RNCCORDAT]      DATETIME      NULL,
    [RNCRETDES]      VARCHAR (500) NULL,
    [RNCINSVIS]      CHAR (1)      NULL,
    [RNCVISAPR]      CHAR (1)      NULL,
    [RNCINSDIM]      CHAR (1)      NULL,
    [RNCDIMAPR]      CHAR (1)      NULL,
    [RNCRETRES]      CHAR (60)     NULL,
    [RNCRETDAT]      DATETIME      NULL,
    [RNCNOTVEN]      CHAR (50)     NULL,
    [RNCNOTCOM]      CHAR (50)     NULL,
    [RNCNOTPRO]      CHAR (50)     NULL,
    [RNCNOTQUA]      CHAR (50)     NULL,
    [RNCNOTRH]       CHAR (50)     NULL,
    [RNCNOTDIR]      CHAR (50)     NULL,
    [RNCNOTSAC]      CHAR (1)      NULL,
    [RNCNOTNSAC]     INT           NULL,
    PRIMARY KEY CLUSTERED ([RNCEMP] ASC, [RNCNUM] ASC)
);

