CREATE TABLE [dbo].[SAC] (
    [SACEMP]  CHAR (2)      NOT NULL,
    [SACCOD]  INT           NOT NULL,
    [SACDAT]  DATETIME      NULL,
    [SACSAC]  CHAR (1)      NULL,
    [SACRNC]  CHAR (1)      NULL,
    [SACOBS]  VARCHAR (500) NULL,
    [SACFRC]  CHAR (1)      NULL,
    [SACFRCN] INT           NULL,
    [SACFNC]  CHAR (1)      NULL,
    [SACFNCN] INT           NULL,
    [SACFPS]  CHAR (1)      NULL,
    [SACFPSN] INT           NULL,
    [SACFOU]  CHAR (1)      NULL,
    [SACFOUN] INT           NULL,
    [SACPQ1]  VARCHAR (500) NULL,
    [SACPQ2]  VARCHAR (500) NULL,
    [SACPQ3]  VARCHAR (500) NULL,
    [SACPQ4]  VARCHAR (500) NULL,
    [SACPQ5]  VARCHAR (500) NULL,
    [SACPOR]  CHAR (20)     NULL,
    [SACAPR]  CHAR (20)     NULL,
    [SACPCE]  DATETIME      NULL,
    [SACPRO]  DATETIME      NULL,
    [SACEFI]  CHAR (20)     NULL,
    [SACEFS]  CHAR (1)      NULL,
    [SACEFN]  CHAR (1)      NULL,
    [SACEFNU] INT           NULL,
    [SACCCO]  CHAR (1)      NULL,
    [SACCCOD] CHAR (20)     NULL,
    [SACCVE]  CHAR (1)      NULL,
    [SACCVED] CHAR (20)     NULL,
    [SACCPC]  CHAR (1)      NULL,
    [SACCPCD] CHAR (20)     NULL,
    [SACCDI]  CHAR (1)      NULL,
    [SACCDID] CHAR (20)     NULL,
    PRIMARY KEY CLUSTERED ([SACEMP] ASC, [SACCOD] ASC)
);

