CREATE TABLE [dbo].[SAC1] (
    [SACEMP]  CHAR (2)      NOT NULL,
    [SACCOD]  INT           NOT NULL,
    [SAC1COD] SMALLINT      NOT NULL,
    [SAC1WHA] VARCHAR (500) NULL,
    [SAC1HOW] VARCHAR (500) NULL,
    [SAC1WHY] VARCHAR (500) NULL,
    [SAC1WHE] VARCHAR (500) NULL,
    [SAC1WHO] VARCHAR (500) NULL,
    [SACEXE]  DATETIME      NULL,
    [SAC1REA] DATETIME      NULL,
    [SAC1POR] CHAR (20)     NULL,
    PRIMARY KEY CLUSTERED ([SACEMP] ASC, [SACCOD] ASC, [SAC1COD] ASC)
);

