CREATE TABLE [dbo].[SGEMPMOD1] (
    [CEMPCOD]    CHAR (2)   NOT NULL,
    [CEMPMODCOD] CHAR (3)   NOT NULL,
    [CEMPMODCRI] CHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([CEMPCOD] ASC, [CEMPMODCOD] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ISGEMPMODLEVEL12]
    ON [dbo].[SGEMPMOD1]([CEMPMODCOD] ASC);

