CREATE TABLE [dbo].[SGPER] (
    [SgPer0Cod] CHAR (20)      NOT NULL,
    [SgPer0Nom] CHAR (50)      NULL,
    [SgPer0Des] VARCHAR (1000) NULL,
    PRIMARY KEY CLUSTERED ([SgPer0Cod] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ISGPERB]
    ON [dbo].[SGPER]([SgPer0Nom] ASC);

