
CREATE procedure sp_AlteraEmpresa
--dados depois da execuçao (novos)
@cd_empresa          int ,
@nm_empresa          varchar (50),
@nm_fantasia_empresa varchar (30),
@nm_endereco_empresa varchar (50),
@nm_bairro_empresa   varchar(30),
@cd_cep_empresa      int,
@cd_telefone_empresa varchar (20),
@cd_fax_empresa varchar (20),
@nm_dominio_internet varchar (50),
@nm_email_internet varchar (50),
@cd_cgc_empresa char (14),
@cd_iest_empresa char (20),
@cd_usuario int,
@dt_usuario datetime,
@nm_caixa_postal char (20),
@dt_fundacao_empresa datetime,
@dt_cadastro_empresa datetime,
@ds_empresa varchar (50),
@cd_pais int,
@cd_estado int,
@cd_cidade int,
@cd_operadora int,
@cd_ramo_atividade int,
@nm_versao char(10),
@ic_default char(1),
@nm_caminho_logo_empresa varchar(100),
@ds_cartorio_empresa text,
@nm_inscricao_municipal varchar(18),
@ic_plano_multi_lingua char(1),
@ic_email_ativo char(1),
@ic_fax_ativo char(1),
@ic_imprimelogotipo char(1),
@ic_imprimezebrado char(1),
@ic_imprimeModelo char(1),
@ic_imprimemensagem char(1),
@ds_mensagemrel Text,
@ic_direcaomensagemrel char(1),
@qt_minutoOcioso int,
@vl_fat_minimo float,
@vl_lib_pedido_compra float,
@vl_tx_mensal_cust_fin float,
@qt_dias_uteis_env_ce int,
@qt_dias_nec_env_ce int,
@ic_gridzebrado char(1),
@nm_FCgridzebrado varchar(9),
@nm_BCgridzebrado varchar(9),
@cd_seguro_porta_empresa varchar(6),
@cd_seguro_empresa	 varchar(15),
@cd_ftp_porta_empresa	 varchar(6),
@cd_ftp_empresa	varchar(15),
@cd_http_porta_empresa	varchar(6),
@cd_http_empresa	varchar(15),
@ic_end_padrao_empresa	char(1),
@cd_ip_porta_empresa	varchar(6),
@cd_ip_empresa	varchar(15),
@cd_smtp_porta_empresa	varchar(6),
@cd_smtp_empresa	varchar(15),
@pc_juro_nota_debito_emp float,
@vl_nota_debito_empresa float,
@cd_nota_debito_empresa int,
@pc_juro_empresa float,
@qt_mes_consumo_empresa int,
@ic_repnet_empresa char(1),
@ic_wapnet_empresa char(1),
@ic_credito_sac_empresa char(1),
@ic_prevfat_empresa char(1),
@cd_cnae int,
@cd_natureza_juridica int,
@ic_gera_serie_empresa char(1),
@ic_gera_lote_empresa char(1),
@ic_rastreabilidade_empres char(1),
@ic_iso_empresa char(1),
@ic_dica_empresa char(1),
@ic_ordsep_barra_empresa char(1),
@ic_ordsep_local_empresa char(1),
@qt_item_nota_empresa int,
@qt_servico_nota_empresa int,
@qt_pagreg_saida_empresa int,
@qt_pagreg_entrada_empresa int,
@ic_controla_desconto char(1),
@cd_serie_notent_empresa int,
@cd_serie_notsaida_empresa int,
@qt_servico_notent_empresa int,
@qt_item_notent_empresa int,
@ic_contrato_serv_empresa char(1),
@cd_tipo_numeracao_nota int,
@nm_banco_empresa varchar(25),
@ic_digita_usuario_empresa char(1),
@pc_irrf_serv_empresa float,
@ds_visao_empresa text,
@ds_missao_empresa text,
@cd_moeda int,
@ic_lembrete_empresa char(1),
@ds_qualidade_empresa text,
@qt_time_verif_ocorrencia int,
@qt_time_mostra_ocorrencia int,
@ic_acesso_internet_empresa char(1),
@ic_pesq_credito_empresa char(1),
@ds_obs_empresa text = '',
@cd_reg_exercito_empresa varchar(15) = '',
@dt_reg_exercito_empresa datetime = Null,
@ic_ocorrencia_empresa char(1),
@cd_guia_trafego int,
@cd_idioma int,
@cd_porto int,
@sg_pais_imp_empresa char(10),
@sg_pedido_imp_empresa char(2),
@cd_cliente_sistema int = -1,
--dados antes da execuçao (antigos)
@cd_empresa_old int,
@cd_numero char(6),
@nm_complemento_endereco char(30),
@cd_ramal char(4),
@cd_registro_jucesp varchar(15),
@ic_loja_empresa char(1),
@pc_custo_capital_empresa float,
@ic_tipo_periodo_empresa char(1),
@ic_fap_modelo_empresa char(1) = '0',
@ic_video_empresa char(1) = 'N',
@ic_ativa_empresa char(1) = 'S',
@ic_multi_empresa char(1) = 'N',
@ic_restricao_usuario_empresa char(1) = 'N',
@ic_sintegra_empresa          char(1) = 'N',
@ic_implantacao_empresa			char(1) = 'N',
@cd_cep char(9),
@cd_identifica_cep int,
@cd_tipo_versao int = 0,
@ic_area_empresa           char(1) = 'N',
@ic_alfa_modulo_empresa	   char(1)     = 'N',
@ic_unico_login_usuario	   char(1)     = 'N',
@cd_senha_menu_empresa     varchar(10) = '',
@nm_banco_origem           varchar(25) = '',
@cd_iest_st_empresa        varchar(18) = '',
@cd_suframa_empresa        varchar(18) = '',
@ic_simples_empresa        char(1)     = '',
@cd_registro_m_agricultura varchar(30) = ''
 
AS

BEGIN

  --inicia a transaçao
  BEGIN TRANSACTION
  --gera código e executa travamento
  UPDATE Empresa SET
         cd_empresa              = @cd_empresa,
         nm_empresa              = @nm_empresa,
         nm_fantasia_empresa     = @nm_fantasia_empresa,
         nm_endereco_empresa     = @nm_endereco_empresa,
         nm_bairro_empresa       = @nm_bairro_empresa,
         cd_cep_empresa          = @cd_cep_empresa,
         cd_telefone_empresa     = @cd_telefone_empresa,
         cd_fax_empresa          = @cd_fax_empresa,
         nm_dominio_internet     = @nm_dominio_internet,
         nm_email_internet       = @nm_email_internet,
         cd_cgc_empresa          = @cd_cgc_empresa,
         cd_iest_empresa         = @cd_iest_empresa,
         cd_usuario              = @cd_usuario,
         dt_usuario              = @dt_usuario,
         nm_caixa_postal         = @nm_caixa_postal,
         dt_fundacao_empresa     = @dt_fundacao_empresa,
         dt_cadastro_empresa     = @dt_cadastro_empresa,
         ds_empresa              = @ds_empresa,
         cd_pais                 = @cd_pais,
         cd_estado               = @cd_estado,
         cd_cidade               = @cd_cidade,
         cd_operadora            = @cd_operadora,
         cd_ramo_atividade       = @cd_ramo_atividade,
         nm_versao               = @nm_versao,
         ic_default              = @ic_default,
         nm_caminho_logo_empresa = @nm_caminho_logo_empresa,
         ds_cartorio_empresa     = @ds_cartorio_empresa,
         nm_inscricao_municipal  = @nm_inscricao_municipal,
         ic_plano_multi_lingua   = @ic_plano_multi_lingua,
      	 ic_email_ativo          = @ic_email_ativo,
      	 ic_fax_ativo            = @ic_fax_ativo,
      	 ic_imprimelogotipo      = @ic_imprimelogotipo,
      	 ic_imprimezebrado       = @ic_imprimezebrado,
      	 ic_imprimeModelo        = @ic_imprimeModelo,
      	 ic_imprimemensagem      = @ic_imprimemensagem,
      	 ds_mensagemrel          = @ds_mensagemrel,
      	 ic_direcaomensagemrel   = @ic_direcaomensagemrel,
         qt_minutoOcioso         = @qt_minutoOcioso,
         vl_fat_minimo           = @vl_fat_minimo,
         vl_lib_pedido_compra    = @vl_lib_pedido_compra,
         vl_tx_mensal_cust_fin   = @vl_tx_mensal_cust_fin,
         qt_dias_uteis_env_ce    = @qt_dias_uteis_env_ce,
         qt_dias_nec_env_ce      = @qt_dias_nec_env_ce,
         ic_gridzebrado          = @ic_gridzebrado,
         nm_FCgridzebrado        = @nm_FCgridzebrado,
         nm_BCgridzebrado        = @nm_BCgridzebrado,
         cd_seguro_porta_empresa = @cd_seguro_porta_empresa,
         cd_seguro_empresa       = @cd_seguro_empresa,
         cd_ftp_porta_empresa    = @cd_ftp_porta_empresa,
         cd_ftp_empresa          = @cd_ftp_empresa,
         cd_http_porta_empresa   = @cd_http_porta_empresa,
         cd_http_empresa         = @cd_http_empresa,
         ic_end_padrao_empresa   = @ic_end_padrao_empresa,
         cd_ip_porta_empresa     = @cd_ip_porta_empresa,
         cd_ip_empresa           = @cd_ip_empresa,
         cd_smtp_porta_empresa   = @cd_smtp_porta_empresa,
         cd_smtp_empresa         = @cd_smtp_empresa,
         pc_juro_nota_debito_emp = @pc_juro_nota_debito_emp,
         vl_nota_debito_empresa  = @vl_nota_debito_empresa,
         cd_nota_debito_empresa  = @cd_nota_debito_empresa,
         pc_juro_empresa         = @pc_juro_empresa,
      	 qt_mes_consumo_empresa  = @qt_mes_consumo_empresa,
         ic_repnet_empresa       = @ic_repnet_empresa,
         ic_wapnet_empresa       = @ic_wapnet_empresa,
         ic_credito_sac_empresa  = @ic_credito_sac_empresa,
      	 ic_prevfat_empresa      = @ic_prevfat_empresa,
      	 cd_cnae                 = @cd_cnae,
         cd_natureza_juridica    = @cd_natureza_juridica,
         ic_gera_serie_empresa   = @ic_gera_serie_empresa,
         ic_gera_lote_empresa    = @ic_gera_lote_empresa,
         ic_rastreabilidade_empres = @ic_rastreabilidade_empres,
      	 ic_iso_empresa          = @ic_iso_empresa,
      	 ic_dica_empresa         = @ic_dica_empresa,
      	 ic_ordsep_barra_empresa = @ic_ordsep_barra_empresa,
      	 ic_ordsep_local_empresa = @ic_ordsep_local_empresa,
      	 qt_item_nota_empresa    = @qt_item_nota_empresa,
      	 qt_servico_nota_empresa = @qt_servico_nota_empresa,
      	 qt_pagreg_saida_empresa = @qt_pagreg_saida_empresa,
      	 qt_pagreg_entrada_empresa = @qt_pagreg_entrada_empresa,
      	 ic_controla_desconto    = @ic_controla_desconto,
      	 cd_serie_notent_empresa = @cd_serie_notent_empresa,
      	 cd_serie_notsaida_empresa = @cd_serie_notsaida_empresa,
      	 qt_servico_notent_empresa = @qt_servico_notent_empresa,
      	 qt_item_notent_empresa    = @qt_item_notent_empresa,
      	 ic_contrato_serv_empresa    = @ic_contrato_serv_empresa,
      	 cd_tipo_numeracao_nota      = @cd_tipo_numeracao_nota,
         nm_banco_empresa            = @nm_banco_empresa,
         ic_digita_usuario_empresa   = @ic_digita_usuario_empresa,
      	 pc_irrf_serv_empresa        = @pc_irrf_serv_empresa,
         ds_visao_empresa            = @ds_visao_empresa,
         ds_missao_empresa           = @ds_missao_empresa,
         cd_moeda                    = @cd_moeda,
         ic_lembrete_empresa         = @ic_lembrete_empresa,
         ds_qualidade_empresa        = @ds_qualidade_empresa,
         qt_time_verif_ocorrencia    = @qt_time_verif_ocorrencia,
         qt_time_mostra_ocorrencia   = @qt_time_mostra_ocorrencia,
      	 ic_acesso_internet_empresa  = @ic_acesso_internet_empresa ,
         ic_pesq_credito_empresa     = @ic_pesq_credito_empresa,
      	 ds_obs_empresa              = @ds_obs_empresa,
      	 cd_reg_exercito_empresa     = @cd_reg_exercito_empresa,
      	 dt_reg_exercito_empresa     = @dt_reg_exercito_empresa,
         ic_ocorrencia_empresa       = @ic_ocorrencia_empresa,
         cd_guia_trafego             = @cd_guia_trafego,
         cd_idioma                   = @cd_idioma ,
         cd_porto                    = @cd_porto,
         sg_pais_imp_empresa         = @sg_pais_imp_empresa,
         sg_pedido_imp_empresa       = @sg_pedido_imp_empresa,
         cd_cliente_sistema          = @cd_cliente_sistema,
         cd_numero                   = @cd_numero,
         nm_complemento_endereco     = @nm_complemento_endereco,
         cd_ramal                    = @cd_ramal,
         cd_registro_jucesp          = @cd_registro_jucesp, 
         ic_loja_empresa             = @ic_loja_empresa,
         pc_custo_capital_empresa    = @pc_custo_capital_empresa,
         ic_tipo_periodo_empresa     = @ic_tipo_periodo_empresa,
         ic_fap_modelo_empresa       = @ic_fap_modelo_empresa,
         ic_video_empresa            = @ic_video_empresa,
         ic_ativa_empresa            = @ic_ativa_empresa,
         ic_multi_empresa            = @ic_multi_empresa,
         ic_restricao_usuario_empresa=@ic_restricao_usuario_empresa,
         ic_sintegra_empresa         =@ic_sintegra_empresa,
         ic_implantacao_empresa      =@ic_implantacao_empresa,
         cd_cep 							 =@cd_cep,
         cd_identifica_cep 			 =@cd_identifica_cep,
         cd_tipo_versao              = @cd_tipo_versao,
         ic_area_empresa             = @ic_area_empresa,
			ic_alfa_modulo_empresa		 = @ic_alfa_modulo_empresa,
         ic_unico_login_usuario      = @ic_unico_login_usuario,
         cd_senha_menu_empresa       = @cd_senha_menu_empresa,
         nm_banco_origem             = @nm_banco_origem,
         cd_iest_st_empresa          = @cd_iest_st_empresa,
         cd_suframa_empresa          = @cd_suframa_empresa,
         ic_simples_empresa          = @ic_simples_empresa,
         cd_registro_m_agricultura   = @cd_registro_m_agricultura
 
    WHERE
         cd_empresa = @cd_empresa_old

  if @ic_default = 'S'
    Update Empresa set ic_default = 'N'
     where cd_empresa <> @cd_empresa_old 
  if @@ERROR = 0
    COMMIT TRAN
  else
  begin
  --RAISERROR @@ERROR
    ROLLBACK TRAN
  end
end

