ALTER TABLE [SMS].[Log]
    ADD CONSTRAINT [PK_SMS.Log] PRIMARY KEY CLUSTERED ([Guid] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

