CREATE LOGIN [interclick]
    WITH PASSWORD = N'mltMsfjlo&ylt~|#|l4Q8snLmsFT7_&#$!~<N,jktit=oIpv', SID = 0x6D96A6BE6815544EBFA381429F92ACD6, DEFAULT_DATABASE = [GPIMAC_Altamira], DEFAULT_LANGUAGE = [Português (Brasil)], CHECK_POLICY = OFF;

