using System;
using System.Collections.Generic;

namespace WBCCAD.Model.Models
{
    public partial class ORCCAB
    {
        public string numeroOrcamento { get; set; }
        public string BANDEIRA { get; set; }
        public Nullable<decimal> COMISSAO_FATOR { get; set; }
        public string GrupoImpostos { get; set; }
        public Nullable<decimal> orccab_Area { get; set; }
        public Nullable<bool> orccab_bloqueado { get; set; }
        public Nullable<bool> orccab_bloquear_icad { get; set; }
        public Nullable<System.DateTime> orccab_Cadastro { get; set; }
        public string orccab_caminho_dwg { get; set; }
        public string orccab_chave { get; set; }
        public string orccab_cliente_bmp { get; set; }
        public string orccab_cliente_CGC_cpf { get; set; }
        public Nullable<int> orccab_cliente_Codigo { get; set; }
        public string orccab_cliente_end_bairro { get; set; }
        public string orccab_cliente_end_cep { get; set; }
        public string orccab_cliente_end_complemento { get; set; }
        public string orccab_cliente_end_endereco { get; set; }
        public string orccab_cliente_end_especie { get; set; }
        public string orccab_cliente_end_numero { get; set; }
        public string orccab_cliente_Nome { get; set; }
        public string orccab_contato { get; set; }
        public string ORCCAB_CONTATO_EMAIL { get; set; }
        public Nullable<System.DateTime> OrcCab_data_email { get; set; }
        public Nullable<System.DateTime> orccab_Data_preco_Cor { get; set; }
        public Nullable<System.DateTime> orccab_Data_Status { get; set; }
        public Nullable<decimal> orccab_desconto_valor { get; set; }
        public Nullable<decimal> OrcCab_Diferenca { get; set; }
        public Nullable<decimal> orccab_diferenca_valor { get; set; }
        public Nullable<int> OrcCab_email { get; set; }
        public Nullable<System.DateTime> orccab_emissao { get; set; }
        public Nullable<decimal> orccab_encargos_perc { get; set; }
        public Nullable<decimal> orccab_encargos_valor { get; set; }
        public string orccab_fax { get; set; }
        public string orccab_fone { get; set; }
        public Nullable<decimal> orccab_frete_valor { get; set; }
        public Nullable<decimal> OrcCab_FRETE1 { get; set; }
        public string orccab_gerente { get; set; }
        public string orccab_ie_rg { get; set; }
        public Nullable<decimal> orccab_ipi_valor { get; set; }
        public string orccab_Lista { get; set; }
        public string orccab_loja { get; set; }
        public Nullable<decimal> OrcCab_Montagem { get; set; }
        public string orccab_motivo { get; set; }
        public string orccab_municipio { get; set; }
        public string orccab_nova_reforma { get; set; }
        public string orccab_nr_orc_vnd { get; set; }
        public string orccab_opcao_comissao { get; set; }
        public string orccab_opcao_resumo { get; set; }
        public string orccab_orcamentista { get; set; }
        public string orccab_pedido { get; set; }
        public Nullable<System.DateTime> orccab_Pedido_Data { get; set; }
        public string orccab_Pedido_Usuario { get; set; }
        public Nullable<decimal> OrcCab_Preco_lista_Sem { get; set; }
        public string orccab_projetista { get; set; }
        public string orccab_ramo { get; set; }
        public string ORCCAB_REFERENCIA { get; set; }
        public string orccab_revisao { get; set; }
        public string orccab_revisao_orc { get; set; }
        public Nullable<int> orccab_Status { get; set; }
        public string orccab_suframa { get; set; }
        public Nullable<int> orccab_Temperatura { get; set; }
        public Nullable<decimal> orccab_total { get; set; }
        public Nullable<decimal> orccab_total_geral { get; set; }
        public Nullable<decimal> ORCCAB_TOTAL1 { get; set; }
        public Nullable<decimal> ORCCAB_TOTAL2 { get; set; }
        public string orccab_UF { get; set; }
        public string orccab_vendedor { get; set; }
        public string orccab_versao_dat { get; set; }
        public Nullable<int> ORCCAB_VINCULAR { get; set; }
        public Nullable<System.DateTime> ORCCABDATAENTREGA { get; set; }
        public Nullable<System.DateTime> ORCCABDATAFATURAMENTO { get; set; }
        public Nullable<System.DateTime> ORCCABDATAULTATUALIZACAO { get; set; }
        public Nullable<bool> OrccabFlagImpostos { get; set; }
        public Nullable<decimal> OrcCabPrecoLista { get; set; }
        public string OrccabTextoProposta { get; set; }
        public Nullable<decimal> ORCCABVALORFINAL1 { get; set; }
        public Nullable<decimal> ORCCABVALORFINAL2 { get; set; }
        public Nullable<decimal> ORCCABVALORFINAL3 { get; set; }
        public Nullable<decimal> ORCCABVALORFINAL4 { get; set; }
        public Nullable<decimal> ORCCABVALORFINAL5 { get; set; }
        public Nullable<decimal> ORCCABVALORFINAL6 { get; set; }
        public Nullable<bool> ORCCABTROCARFINAL1 { get; set; }
        public Nullable<bool> ORCCABTROCARFINAL2 { get; set; }
        public Nullable<bool> ORCCABTROCARFINAL3 { get; set; }
        public Nullable<bool> ORCCABTROCARFINAL4 { get; set; }
        public Nullable<bool> ORCCABTROCARFINAL5 { get; set; }
        public Nullable<bool> ORCCABTROCARFINAL6 { get; set; }
        public Nullable<decimal> ORCCABVALORBASE1 { get; set; }
        public Nullable<decimal> ORCCABVALORBASE2 { get; set; }
        public Nullable<decimal> ORCCABVALORBASE3 { get; set; }
        public Nullable<decimal> ORCCABVALORBASE4 { get; set; }
        public Nullable<decimal> ORCCABVALORBASE5 { get; set; }
        public Nullable<decimal> ORCCABVALORBASE6 { get; set; }
        public string PAISCODIGO { get; set; }
        public string PgtCabCodigo { get; set; }
        public Nullable<int> QtdeAlteradas { get; set; }
        public string TipoVenda { get; set; }
        public string condicaoPagamento { get; set; }
        public string condicaoPagamentoDescricao { get; set; }
        public string orccab_pedido_cliente { get; set; }
        public string orccab_cliente_et_especie { get; set; }
        public string orccab_cliente_et_endereco { get; set; }
        public string orccab_cliente_et_numero { get; set; }
        public string orccab_cliente_et_complemento { get; set; }
        public string orccab_cliente_et_bairro { get; set; }
        public string orccab_cliente_et_municipio { get; set; }
        public string orccab_cliente_et_uf { get; set; }
        public string orccab_cliente_et_cep { get; set; }
        public string orccab_cliente_et_pais { get; set; }
        public string orccab_cliente_cb_especie { get; set; }
        public string orccab_cliente_cb_endereco { get; set; }
        public string orccab_cliente_cb_numero { get; set; }
        public string orccab_cliente_cb_complemento { get; set; }
        public string orccab_cliente_cb_bairro { get; set; }
        public string orccab_cliente_cb_municipio { get; set; }
        public string orccab_cliente_cb_uf { get; set; }
        public string orccab_cliente_cb_cep { get; set; }
        public string orccab_cliente_cb_pais { get; set; }
        public string ObservacoesEntrega { get; set; }
        public Nullable<bool> orccab_cliente_et_utilizar { get; set; }
        public Nullable<bool> orccab_cliente_cb_utilizar { get; set; }
        public Nullable<double> condicaoPagamentoFator { get; set; }
        public string concorrentes { get; set; }
        public string orccab_cliente_codinome { get; set; }
        public string ORCCAB_AGENTE { get; set; }
    }
}
