CREATE TABLE [dbo].[Atributo_Padrao] (
    [cd_atributo]               INT          NOT NULL,
    [nm_atributo]               VARCHAR (40) NULL,
    [cd_dominio]                INT          NULL,
    [ds_atributo]               VARCHAR (40) NULL,
    [cd_natureza_atributo]      INT          NOT NULL,
    [qt_tamanho_atributo]       INT          NULL,
    [qt_decimal_atributo]       INT          NULL,
    [nm_mascara_atributo]       VARCHAR (20) NULL,
    [nm_atributo_relatorio]     VARCHAR (40) NULL,
    [nm_atributo_consulta]      VARCHAR (40) NULL,
    [ic_numeracao_automatica]   CHAR (1)     NULL,
    [ic_atributo_chave]         CHAR (1)     NULL,
    [nm_atributo_tabela_dbf]    CHAR (10)    NULL,
    [cd_help]                   INT          NULL,
    [ic_atributo_obrigatorio]   CHAR (1)     NOT NULL,
    [ic_mostra_grid]            CHAR (1)     NULL,
    [ic_edita_cadastro]         CHAR (1)     NULL,
    [ic_mostra_relatorio]       CHAR (1)     NULL,
    [ic_mostra_cadastro]        CHAR (1)     NULL,
    [vl_default]                CHAR (20)    NULL,
    [nu_ordem]                  INT          NULL,
    [ic_chave_estrangeira]      CHAR (1)     NULL,
    [ic_combo_box]              CHAR (1)     NULL,
    [nm_campo_mostra_combo_box] VARCHAR (50) NULL,
    [nm_tabela_combo_box]       VARCHAR (50) NULL,
    [nm_campo_chave_combo_box]  VARCHAR (50) NULL,
    [ic_lista_valor]            CHAR (1)     NULL,
    [nm_alias]                  VARCHAR (20) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_formata_string]         CHAR (1)     NULL,
    CONSTRAINT [PK_Atributo_Padrao] PRIMARY KEY CLUSTERED ([cd_atributo] ASC) WITH (FILLFACTOR = 90)
);

