CREATE TABLE [dbo].[Empresa] (
    [cd_empresa]                   INT           NOT NULL,
    [nm_empresa]                   VARCHAR (50)  NULL,
    [nm_fantasia_empresa]          VARCHAR (30)  NULL,
    [nm_endereco_empresa]          VARCHAR (50)  NULL,
    [cd_cep_empresa]               INT           NULL,
    [cd_telefone_empresa]          VARCHAR (20)  NULL,
    [cd_fax_empresa]               VARCHAR (20)  NULL,
    [nm_dominio_internet]          VARCHAR (50)  NULL,
    [nm_email_internet]            VARCHAR (50)  NULL,
    [cd_cgc_empresa]               CHAR (14)     NULL,
    [cd_iest_empresa]              CHAR (20)     NULL,
    [cd_usuario]                   INT           NULL,
    [dt_usuario]                   DATETIME      NULL,
    [nm_caixa_postal]              CHAR (20)     NULL,
    [dt_fundacao_empresa]          DATETIME      NULL,
    [dt_cadastro_empresa]          DATETIME      NULL,
    [ds_empresa]                   VARCHAR (50)  NULL,
    [cd_pais]                      INT           NULL,
    [cd_estado]                    INT           NULL,
    [cd_cidade]                    INT           NULL,
    [cd_operadora]                 INT           NULL,
    [cd_ramo_atividade]            INT           NULL,
    [nm_versao]                    CHAR (10)     NULL,
    [nm_bairro_empresa]            VARCHAR (30)  NULL,
    [ic_default]                   CHAR (1)      NULL,
    [nm_caminho_logo_empresa]      VARCHAR (100) NULL,
    [ic_fax_ativo]                 CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [ic_email_ativo]               CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [ic_plano_multi_lingua]        CHAR (1)      NULL,
    [ds_cartorio_empresa]          TEXT          NULL,
    [nm_inscricao_municipal]       VARCHAR (18)  NULL,
    [ic_imprime_traco]             CHAR (1)      NULL,
    [ic_imprime_logo]              CHAR (1)      NULL,
    [ic_imprimelogotipo]           CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [ic_imprimezebrado]            CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [ic_imprimeModelo]             CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [ic_imprimemensagem]           CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [ds_mensagemrel]               TEXT          COLLATE Latin1_General_CI_AS NULL,
    [ic_direcaomensagemrel]        CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [qt_minutoOcioso]              INT           NULL,
    [vl_fat_minimo]                FLOAT (53)    NULL,
    [vl_lib_pedido_compra]         FLOAT (53)    NULL,
    [vl_tx_mensal_cust_fin]        FLOAT (53)    NULL,
    [qt_dias_uteis_env_ce]         INT           NULL,
    [qt_dias_nec_env_ce]           INT           NULL,
    [ic_gridzebrado]               CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [nm_FCgridzebrado]             VARCHAR (9)   COLLATE Latin1_General_CI_AS NULL,
    [nm_BCgridzebrado]             VARCHAR (9)   COLLATE Latin1_General_CI_AS NULL,
    [cd_ip_empresa]                VARCHAR (15)  COLLATE Latin1_General_CI_AS NULL,
    [cd_ip_porta_empresa]          VARCHAR (6)   COLLATE Latin1_General_CI_AS NULL,
    [ic_end_padrao_empresa]        CHAR (1)      COLLATE Latin1_General_CI_AS NULL,
    [cd_http_empresa]              VARCHAR (15)  COLLATE Latin1_General_CI_AS NULL,
    [cd_http_porta_empresa]        VARCHAR (6)   COLLATE Latin1_General_CI_AS NULL,
    [cd_ftp_empresa]               VARCHAR (15)  COLLATE Latin1_General_CI_AS NULL,
    [cd_ftp_porta_empresa]         VARCHAR (6)   COLLATE Latin1_General_CI_AS NULL,
    [cd_seguro_empresa]            VARCHAR (15)  NULL,
    [cd_seguro_porta_empresa]      VARCHAR (6)   COLLATE Latin1_General_CI_AS NULL,
    [cd_smtp_empresa]              VARCHAR (15)  COLLATE Latin1_General_CI_AS NULL,
    [pc_juro_empresa]              FLOAT (53)    NULL,
    [cd_nota_debito_empresa]       INT           NULL,
    [vl_nota_debito_empresa]       FLOAT (53)    NULL,
    [pc_juro_nota_debito_emp]      FLOAT (53)    NULL,
    [cd_smtp_porta_empresa]        VARCHAR (6)   COLLATE Latin1_General_CI_AS NULL,
    [ic_repnet_empresa]            CHAR (1)      NULL,
    [ic_wapnet_empresa]            CHAR (1)      NULL,
    [cd_cnae]                      INT           NULL,
    [cd_natureza_juridica]         INT           NULL,
    [qt_mes_consumo_empresa]       INT           NULL,
    [ic_credito_sac_empresa]       CHAR (1)      NULL,
    [ic_prevfat_empresa]           CHAR (1)      NULL,
    [ic_grid_zebrado]              CHAR (1)      NULL,
    [ic_rastreabilidade_empres]    CHAR (1)      NULL,
    [ic_gera_lote_empresa]         CHAR (1)      NULL,
    [ic_gera_serie_empresa]        CHAR (1)      NULL,
    [ic_ordsep_local_empresa]      CHAR (1)      NULL,
    [ic_ordsep_bana_empresa]       CHAR (1)      NULL,
    [ic_consulta_executa_usu]      CHAR (1)      NULL,
    [ic_gera_serie_produto]        CHAR (1)      NULL,
    [ic_iso_empresa]               CHAR (1)      NULL,
    [qt_item_nota_empresa]         INT           NULL,
    [ic_dica_empresa]              CHAR (1)      NULL,
    [qt_servico_nota_empresa]      INT           NULL,
    [ic_ordsep_barra_empresa]      CHAR (1)      NULL,
    [qt_pagreg_saida_empresa]      INT           NULL,
    [qt_pagreg_entrada_empresa]    INT           NULL,
    [cd_serie_notsaida_empresa]    INT           NULL,
    [cd_serie_notent_empresa]      INT           NULL,
    [qt_item_notent_empresa]       INT           NULL,
    [ic_contrato_serv_empresa]     CHAR (1)      NULL,
    [qt_servico_notent_empresa]    INT           NULL,
    [nm_banco_empresa]             VARCHAR (25)  NULL,
    [ic_controla_desconto]         CHAR (1)      NULL,
    [cd_tipo_numeracao_nota]       INT           NULL,
    [ic_digita_usuario_empresa]    CHAR (1)      NULL,
    [pc_irrf_serv_empresa]         FLOAT (53)    NULL,
    [ds_visao_empresa]             TEXT          NULL,
    [ds_missao_empresa]            TEXT          NULL,
    [cd_moeda]                     INT           NULL,
    [ic_lembrete_empresa]          CHAR (1)      NULL,
    [ds_qualidade_empresa]         TEXT          NULL,
    [qt_time_verif_ocorrencia]     FLOAT (53)    NULL,
    [qt_time_mostra_ocorrencia]    FLOAT (53)    NULL,
    [ic_acesso_internet_empresa]   CHAR (1)      NULL,
    [ic_pesq_credito_empresa]      CHAR (1)      NULL,
    [ds_obs_empresa]               TEXT          NULL,
    [cd_clf_empresa]               VARCHAR (15)  NULL,
    [cd_guia_trafego]              INT           NULL,
    [cd_grupo_mapa_policia]        INT           NULL,
    [cd_reg_exercito_empresa]      VARCHAR (15)  NULL,
    [dt_reg_exercito_empresa]      DATETIME      NULL,
    [ic_ocorrencia_empresa]        CHAR (1)      NULL,
    [cd_idioma]                    INT           NULL,
    [sg_pedido_imp_empresa]        CHAR (2)      NULL,
    [sg_pais_imp_empresa]          CHAR (10)     NULL,
    [cd_porto]                     INT           NULL,
    [ic_sintegra_empresa]          CHAR (1)      NULL,
    [cd_cliente_sistema]           INT           NULL,
    [nm_complemento_endereco]      VARCHAR (60)  NULL,
    [cd_numero]                    CHAR (6)      NULL,
    [cd_ramal]                     CHAR (4)      NULL,
    [cd_registro_jucesp]           VARCHAR (15)  NULL,
    [ic_loja_empresa]              CHAR (1)      NULL,
    [pc_custo_capital_empresa]     FLOAT (53)    NULL,
    [ic_tipo_periodo_empresa]      CHAR (1)      NULL,
    [ic_fap_modelo_empresa]        CHAR (1)      NULL,
    [ic_video_empresa]             CHAR (1)      NULL,
    [ic_ativa_empresa]             CHAR (1)      NULL,
    [ic_multi_empresa]             CHAR (1)      NULL,
    [ic_restricao_usuario_empresa] CHAR (1)      NULL,
    [ic_implantacao_empresa]       CHAR (1)      NULL,
    [ic_alfa_modulo_empresa]       CHAR (1)      NULL,
    [cd_cep]                       CHAR (9)      NULL,
    [cd_identifica_cep]            INT           NULL,
    [cd_tipo_versao]               INT           NULL,
    [ic_area_empresa]              CHAR (1)      NULL,
    [ic_unico_login_usuario]       CHAR (1)      NULL,
    [cd_senha_menu_empresa]        VARCHAR (15)  NULL,
    [nm_banco_origem]              VARCHAR (25)  NULL,
    [cd_iest_st_empresa]           VARCHAR (18)  NULL,
    [cd_suframa_empresa]           VARCHAR (18)  NULL,
    [ic_simples_empresa]           CHAR (1)      NULL,
    [cd_registro_m_agricultura]    VARCHAR (30)  NULL,
    CONSTRAINT [PK_Empresa] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90)
);

