CREATE TABLE [dbo].[Menu_Historico] (
    [cd_menu_historico]         INT           NOT NULL,
    [nm_os]                     VARCHAR (25)  NULL,
    [dt_usuario]                DATETIME      NULL,
    [ds_menu_historico]         TEXT          NOT NULL,
    [cd_usuario]                INT           NULL,
    [dt_homologacao]            DATETIME      NULL,
    [dt_compilacao]             DATETIME      NULL,
    [ic_status_menu]            CHAR (1)      NULL,
    [nm_analista]               VARCHAR (20)  NULL,
    [nm_empresa]                VARCHAR (50)  NULL,
    [vl_pontuacao_menu]         FLOAT (53)    NULL,
    [ic_retrabalho]             CHAR (1)      NULL,
    [dt_fim_desenvolvimento]    DATETIME      NULL,
    [dt_inicio_desenvolvimento] DATETIME      NULL,
    [nm_solicitante]            VARCHAR (20)  NULL,
    [nm_unit_menu]              VARCHAR (40)  NULL,
    [cd_menu]                   INT           NULL,
    [vl_pontuacao_conhecimento] INT           NULL,
    [vl_pontuacao_tempo]        INT           NULL,
    [vl_pontuacao_dificuldade]  INT           NULL,
    [nm_atividade_processo]     VARCHAR (100) NULL,
    [cd_modulo]                 INT           NULL,
    [dt_prevista_os]            DATETIME      NULL,
    [qt_dia_os]                 FLOAT (53)    NULL,
    [qt_hora_os]                FLOAT (53)    NULL,
    [ic_customizacao_os]        CHAR (1)      NULL,
    [ds_problema_os]            TEXT          NULL,
    [nm_documento_os]           VARCHAR (100) NULL,
    [cd_prioridade]             INT           NULL,
    [nm_obs_menu_historico]     VARCHAR (40)  NULL,
    [ic_compilar_modulo]        CHAR (1)      NULL,
    [cd_classe]                 INT           NULL,
    [cd_solicitante]            INT           NULL,
    [cd_analista]               INT           NULL,
    [cd_empresa]                INT           NULL,
    [dt_previsao_desenv]        DATETIME      NULL,
    [cd_cliente_sistema]        INT           NULL,
    [ds_roteiro_implantacao]    TEXT          NULL,
    [dt_teste_os_consultor]     DATETIME      NULL,
    [cd_consultor]              INT           NULL,
    [ic_treinamento]            CHAR (1)      NULL,
    [dt_treinamento]            DATETIME      NULL,
    [ic_emitida_os]             CHAR (1)      NULL,
    [cd_tipo_manut_sistema]     INT           NULL,
    [cd_processo]               INT           NULL,
    [cd_registro_atividade]     INT           NULL,
    [cd_funcao]                 INT           NULL,
    [cd_registro_suporte]       INT           NULL,
    CONSTRAINT [PK_Menu_Historico] PRIMARY KEY CLUSTERED ([cd_menu_historico] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Menu_Historico_Cliente_Sistema] FOREIGN KEY ([cd_cliente_sistema]) REFERENCES [dbo].[Cliente_Sistema] ([cd_cliente_sistema]),
    CONSTRAINT [FK_Menu_Historico_Consultor_Implantacao] FOREIGN KEY ([cd_consultor]) REFERENCES [dbo].[Consultor_Implantacao] ([cd_consultor]),
    CONSTRAINT [FK_Menu_Historico_Usuario] FOREIGN KEY ([cd_usuario]) REFERENCES [dbo].[Usuario] ([cd_usuario])
);

