CREATE TABLE [dbo].[Modulo] (
    [cd_modulo]                     INT           NOT NULL,
    [nm_modulo]                     VARCHAR (40)  NULL,
    [sg_modulo]                     CHAR (10)     NULL,
    [ic_liberado]                   CHAR (1)      NULL,
    [nm_imagem_apresentacao_modulo] VARCHAR (40)  NULL,
    [ds_modulo]                     TEXT          NULL,
    [cd_imagem]                     INT           NULL,
    [cd_help]                       INT           NULL,
    [nm_executavel]                 VARCHAR (100) NULL,
    [cd_ordem_modulo]               INT           NULL,
    [nm_local_origem_modulo]        VARCHAR (100) NULL,
    [cd_cadeia_valor]               INT           NULL,
    [ic_vincular_cadeia_valor]      CHAR (1)      NULL,
    [cd_usuario]                    INT           NULL,
    [dt_usuario]                    DATETIME      NULL,
    [nm_servidor]                   VARCHAR (50)  NULL,
    [ic_alteracao]                  CHAR (1)      NULL,
    [nm_help_modulo]                VARCHAR (100) NULL,
    [nm_imagem_apresentacao]        VARCHAR (40)  NULL,
    [dt_ult_versao_modulo]          DATETIME      NULL,
    [dt_ultima_versao_modulo]       DATETIME      NULL,
    [qt_acesso_modulo]              INT           NULL,
    [qt_ativo_modulo]               INT           NULL,
    [nm_pacote]                     VARCHAR (50)  NULL,
    [cd_nota_saida]                 INT           NULL,
    [cd_item_nota_saida]            INT           NULL,
    [dt_dev_item_nota_saida]        DATETIME      NULL,
    [nm_mot_rest_item_nt_saida]     VARCHAR (40)  NULL,
    [qt_dev_item_nota_saida]        FLOAT (53)    NULL,
    [cd_num_formulario_nota]        INT           NULL,
    [cd_versao_cliente_modulo]      VARCHAR (15)  NULL,
    [cd_versao_modulo]              VARCHAR (15)  NULL,
    [ic_web_modulo]                 CHAR (1)      NULL,
    [qt_hora_implantacao_modulo]    INT           NULL,
    [nm_fluxo_modulo]               VARCHAR (100) NULL,
    [ic_fluxo_modulo]               CHAR (1)      NULL,
    [nm_modelagem_modulo]           VARCHAR (100) NULL,
    [nm_manual_modulo]              VARCHAR (100) NULL,
    [nm_logo_web_modulo]            VARCHAR (100) NULL,
    [nm_video_modulo]               VARCHAR (100) NULL,
    [ic_moeda_modulo]               CHAR (1)      NULL,
    [ic_venfat_modulo]              CHAR (1)      NULL,
    [cd_tipo_versao]                INT           NULL,
    CONSTRAINT [PK_Modulo] PRIMARY KEY CLUSTERED ([cd_modulo] ASC) WITH (FILLFACTOR = 90)
);

