CREATE TABLE [dbo].[Tabela] (
    [cd_tabela]                INT           NOT NULL,
    [nm_tabela]                VARCHAR (100) NOT NULL,
    [ds_tabela]                VARCHAR (50)  NULL,
    [ic_tipo_tabela]           CHAR (1)      NULL,
    [dt_criacao_tabela]        DATETIME      NULL,
    [dt_alteracao_tabela]      DATETIME      NULL,
    [ic_controle_numeracao]    CHAR (1)      NULL,
    [cd_tabela_dbf]            INT           NULL,
    [ic_repnet]                CHAR (1)      NULL,
    [ic_clinet]                CHAR (1)      NULL,
    [ic_fornet]                CHAR (1)      NULL,
    [ic_sap_dbf]               CHAR (1)      NULL,
    [ic_migracao_concluida]    CHAR (1)      NULL,
    [ds_obs_tabela]            TEXT          NULL,
    [cd_usuario]               INT           NULL,
    [dt_usuario]               DATETIME      NULL,
    [ic_sap_admin]             CHAR (1)      NULL,
    [ic_filtra_periodo]        CHAR (1)      NULL,
    [ic_filtra_empresa]        CHAR (1)      NULL,
    [ic_supervisor_altera]     CHAR (1)      NULL,
    [ic_alteracao]             CHAR (1)      NULL,
    [ic_vincular_cadeia_valor] CHAR (1)      NULL,
    [ic_fixa_tabela]           CHAR (1)      NULL,
    [ic_implantacao_tabela]    CHAR (1)      NULL,
    [cd_prioridade_tabela]     INT           NULL,
    [ic_parametro_tabela]      CHAR (1)      NULL,
    [ic_inativa_tabela]        CHAR (1)      NULL,
    [ic_nucleo_tabela]         CHAR (1)      NULL,
    [ic_publica_tabela]        CHAR (1)      NULL,
    [cd_banco_dados]           INT           NULL,
    [ic_codigo_barra_tabela]   CHAR (1)      NULL,
    [cd_tipo_codigo_barra]     INT           NULL,
    [ic_selecao_tabela]        CHAR (1)      NULL,
    [ic_versao_tabela]         CHAR (1)      NULL,
    [cd_ordem_tabela]          INT           NULL,
    CONSTRAINT [PK_Tabela] PRIMARY KEY CLUSTERED ([cd_tabela] ASC) WITH (FILLFACTOR = 90)
);

