CREATE TABLE [dbo].[Usuario] (
    [cd_usuario]                  INT           NOT NULL,
    [nm_usuario]                  VARCHAR (40)  NOT NULL,
    [nm_fantasia_usuario]         CHAR (15)     NOT NULL,
    [cd_senha_usuario]            CHAR (10)     NOT NULL,
    [ic_tipo_usuario]             CHAR (1)      NULL,
    [dt_validade_senha_usuario]   DATETIME      NULL,
    [qt_tentativa_acesso_usuario] INT           NULL,
    [dt_nascimento_usuario]       DATETIME      NULL,
    [ic_controle_aniversario]     CHAR (1)      NULL,
    [nm_email_usuario]            CHAR (50)     NULL,
    [nm_ramal_usuario]            CHAR (10)     NULL,
    [cd_telefone_usuario]         CHAR (8)      NULL,
    [cd_celular_usuario]          CHAR (8)      NULL,
    [nm_arquivo_foto_usuario]     VARCHAR (50)  NULL,
    [dt_cadastro_usuario]         DATETIME      NULL,
    [nm_local_arquivo_usuario]    VARCHAR (70)  NULL,
    [dt_aniversariantes_usuario]  DATETIME      NULL,
    [qt_dias_troca]               INT           NULL,
    [ic_consulta_executiva]       CHAR (1)      NULL,
    [ic_consulta_comissao_total]  CHAR (1)      NULL,
    [cd_vendedor]                 INT           NULL,
    [ic_alterar_primeiro_log]     CHAR (1)      NULL,
    [ic_ativo]                    CHAR (1)      NULL,
    [cd_departamento]             INT           NULL,
    [ic_moeda_usuario]            CHAR (1)      NULL,
    [cd_usuario_atualiza]         INT           NULL,
    [dt_usuario_atualiza]         DATETIME      NULL,
    [ic_lista_aniversariantes]    CHAR (1)      NULL,
    [ic_wapnet_usuario]           CHAR (4)      NULL,
    [cd_senha_wapnet_usuario]     CHAR (3)      NULL,
    [ic_repnet_usuario]           CHAR (1)      NULL,
    [cd_senha_repnet_usuario]     VARCHAR (10)  NULL,
    [cd_senha_email]              VARCHAR (10)  NULL,
    [nm_usuario_email]            VARCHAR (30)  NULL,
    [nm_assinatura_usuario]       VARCHAR (100) NULL,
    [ic_dica_usuario]             CHAR (1)      NULL,
    [cd_cargo_empresa]            INT           NULL,
    [ic_lembrete_usuario]         CHAR (1)      NULL,
    [qt_tenta_acesso_usuario]     INT           NULL,
    [ic_consul_comissao_total]    CHAR (1)      NULL,
    [ic_ass_eletronica_usuario]   CHAR (1)      NULL,
    [ic_operador_tmkt_usuario]    CHAR (1)      NULL,
    [ic_acesso_internet_usuario]  CHAR (1)      NULL,
    [cd_tipo_usuario]             INT           NULL,
    [cd_centro_custo]             INT           NULL,
    [cd_tipo_aprovacao]           INT           NULL,
    [ic_bx_req_interna_usuario]   CHAR (1)      NULL,
    [ic_bx_req_interna]           CHAR (1)      NULL,
    [cd_comprador]                INT           NULL,
    [dt_ultimo_acesso_usuario]    DATETIME      NULL,
    [ic_ocorrencia_usuario]       CHAR (1)      NULL,
    [ic_multi_idioma_usuario]     CHAR (1)      NULL,
    [cd_idioma]                   INT           NULL,
    [ic_autoriza_pagamento]       CHAR (1)      NULL,
    [cd_acesso_usuario]           CHAR (10)     NULL,
    [cd_loja]                     INT           NULL,
    [ic_instrucao_usuario]        CHAR (1)      NULL,
    [cd_operador_caixa]           INT           NULL,
    [cd_projetista]               INT           NULL,
    [ic_exportacao_usuario]       CHAR (1)      NULL,
    [ic_email_usuario]            CHAR (1)      NULL,
    [cd_vendedor_interno]         INT           NULL,
    [ic_acesso_padrao_usuario]    CHAR (1)      NULL,
    [ic_bx_req_fab_usuario]       CHAR (1)      NULL,
    [ic_consultor_usario]         CHAR (1)      NULL,
    [ic_fixo_usuario]             CHAR (1)      NULL,
    [cd_funcionario]              INT           NULL,
    [ic_moeda_nacional]           CHAR (1)      NULL,
    [ic_moeda_estrangeira]        CHAR (1)      NULL,
    [ic_bloqueio_vendedor]        CHAR (1)      NULL,
    CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED ([cd_usuario] ASC) WITH (FILLFACTOR = 90)
);

