//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestaoApp.Assets.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ActionOpen {
            get {
                return ResourceManager.GetString("ActionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare.
        /// </summary>
        public static string ActionPrepare {
            get {
                return ResourceManager.GetString("ActionPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altamira Management System.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Foward.
        /// </summary>
        public static string AttendanceFoward {
            get {
                return ResourceManager.GetString("AttendanceFoward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for attendance client.
        /// </summary>
        public static string AttendanceFowardClient {
            get {
                return ResourceManager.GetString("AttendanceFowardClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance History.
        /// </summary>
        public static string AttendanceHistory {
            get {
                return ResourceManager.GetString("AttendanceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string AttendanceHistoryComments {
            get {
                return ResourceManager.GetString("AttendanceHistoryComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string AttendanceHistoryDeadline {
            get {
                return ResourceManager.GetString("AttendanceHistoryDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Date Time.
        /// </summary>
        public static string AttendanceHistoryOriginalDateTime {
            get {
                return ResourceManager.GetString("AttendanceHistoryOriginalDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AttendanceHistoryStatus {
            get {
                return ResourceManager.GetString("AttendanceHistoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AttendanceHistoryType {
            get {
                return ResourceManager.GetString("AttendanceHistoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Register.
        /// </summary>
        public static string AttendanceRegister {
            get {
                return ResourceManager.GetString("AttendanceRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string AttendanceRegisterClient {
            get {
                return ResourceManager.GetString("AttendanceRegisterClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string AttendanceRegisterCode {
            get {
                return ResourceManager.GetString("AttendanceRegisterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string AttendanceRegisterComments {
            get {
                return ResourceManager.GetString("AttendanceRegisterComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AttendanceRegisterDate {
            get {
                return ResourceManager.GetString("AttendanceRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AttendanceRegisterDateField {
            get {
                return ResourceManager.GetString("AttendanceRegisterDateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string AttendanceRegisterDeadline {
            get {
                return ResourceManager.GetString("AttendanceRegisterDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string AttendanceRegisterProtocol {
            get {
                return ResourceManager.GetString("AttendanceRegisterProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicity.
        /// </summary>
        public static string AttendanceRegisterPublicity {
            get {
                return ResourceManager.GetString("AttendanceRegisterPublicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Vendor.
        /// </summary>
        public static string AttendanceRegisterSalesVendor {
            get {
                return ResourceManager.GetString("AttendanceRegisterSalesVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AttendanceRegisterStatus {
            get {
                return ResourceManager.GetString("AttendanceRegisterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AttendanceRegisterStatusField {
            get {
                return ResourceManager.GetString("AttendanceRegisterStatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Register.
        /// </summary>
        public static string AttendanceRegisterTop {
            get {
                return ResourceManager.GetString("AttendanceRegisterTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AttendanceRegisterType {
            get {
                return ResourceManager.GetString("AttendanceRegisterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AttendanceRegisterTypeField {
            get {
                return ResourceManager.GetString("AttendanceRegisterTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Attendance Status.
        /// </summary>
        public static string AttendanceStatusTop {
            get {
                return ResourceManager.GetString("AttendanceStatusTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Attendance Type.
        /// </summary>
        public static string AttendanceTypeTop {
            get {
                return ResourceManager.GetString("AttendanceTypeTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string BusyMessage {
            get {
                return ResourceManager.GetString("BusyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string CitySelectTop {
            get {
                return ResourceManager.GetString("CitySelectTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ClientAddress {
            get {
                return ResourceManager.GetString("ClientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string ClientAddresses {
            get {
                return ResourceManager.GetString("ClientAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ClientAlias {
            get {
                return ResourceManager.GetString("ClientAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Address.
        /// </summary>
        public static string ClientAttendanceAddress {
            get {
                return ResourceManager.GetString("ClientAttendanceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances.
        /// </summary>
        public static string ClientAttendances {
            get {
                return ResourceManager.GetString("ClientAttendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string ClientContacEmailAddress {
            get {
                return ResourceManager.GetString("ClientContacEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Register.
        /// </summary>
        public static string ClientContactEmailTop {
            get {
                return ResourceManager.GetString("ClientContactEmailTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Code.
        /// </summary>
        public static string ClientContactFoneAccessCode {
            get {
                return ResourceManager.GetString("ClientContactFoneAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        public static string ClientContactFoneAreaCode {
            get {
                return ResourceManager.GetString("ClientContactFoneAreaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string ClientContactFoneNumber {
            get {
                return ResourceManager.GetString("ClientContactFoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string ClientContactFonePrefix {
            get {
                return ResourceManager.GetString("ClientContactFonePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Register.
        /// </summary>
        public static string ClientContactFoneTop {
            get {
                return ResourceManager.GetString("ClientContactFoneTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ClientContactFoneType {
            get {
                return ResourceManager.GetString("ClientContactFoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Persons.
        /// </summary>
        public static string ClientContactPerson {
            get {
                return ResourceManager.GetString("ClientContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string ClientContactPersonDepartment {
            get {
                return ResourceManager.GetString("ClientContactPersonDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Emails.
        /// </summary>
        public static string ClientContactPersonEmails {
            get {
                return ResourceManager.GetString("ClientContactPersonEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Phones.
        /// </summary>
        public static string ClientContactPersonFones {
            get {
                return ResourceManager.GetString("ClientContactPersonFones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClientContactPersonName {
            get {
                return ResourceManager.GetString("ClientContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ClientContactPersons {
            get {
                return ResourceManager.GetString("ClientContactPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Register.
        /// </summary>
        public static string ClientContactPersonTop {
            get {
                return ResourceManager.GetString("ClientContactPersonTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string ClientContactPhoneNumber {
            get {
                return ResourceManager.GetString("ClientContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Data.
        /// </summary>
        public static string ClientData {
            get {
                return ResourceManager.GetString("ClientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string ClientEmail {
            get {
                return ResourceManager.GetString("ClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string ClientEntity {
            get {
                return ResourceManager.GetString("ClientEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string ClientInfo {
            get {
                return ResourceManager.GetString("ClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ClientLocationAddress {
            get {
                return ResourceManager.GetString("ClientLocationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Address.
        /// </summary>
        public static string ClientLocationAddressTop {
            get {
                return ResourceManager.GetString("ClientLocationAddressTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ClientLocationCity {
            get {
                return ResourceManager.GetString("ClientLocationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        public static string ClientLocationComplement {
            get {
                return ResourceManager.GetString("ClientLocationComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ClientLocationCountry {
            get {
                return ResourceManager.GetString("ClientLocationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string ClientLocationDistrict {
            get {
                return ResourceManager.GetString("ClientLocationDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string ClientLocationNumber {
            get {
                return ResourceManager.GetString("ClientLocationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string ClientLocationPostalCode {
            get {
                return ResourceManager.GetString("ClientLocationPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ClientLocationState {
            get {
                return ResourceManager.GetString("ClientLocationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string ClientPerson {
            get {
                return ResourceManager.GetString("ClientPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string ClientPhone {
            get {
                return ResourceManager.GetString("ClientPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Register.
        /// </summary>
        public static string ClientRegisterTop {
            get {
                return ResourceManager.GetString("ClientRegisterTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type.
        /// </summary>
        public static string ClientType {
            get {
                return ResourceManager.GetString("ClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string CountrySelectTop {
            get {
                return ResourceManager.GetString("CountrySelectTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Phone Type.
        /// </summary>
        public static string FoneTypeSelectTop {
            get {
                return ResourceManager.GetString("FoneTypeSelectTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add new item.
        /// </summary>
        public static string GridViewAlwaysVisibleNewRow {
            get {
                return ResourceManager.GetString("GridViewAlwaysVisibleNewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string GridViewClearFilter {
            get {
                return ResourceManager.GetString("GridViewClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string GridViewFilter {
            get {
                return ResourceManager.GetString("GridViewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string GridViewFilterAnd {
            get {
                return ResourceManager.GetString("GridViewFilterAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string GridViewFilterContains {
            get {
                return ResourceManager.GetString("GridViewFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string GridViewFilterEndsWith {
            get {
                return ResourceManager.GetString("GridViewFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is contained in.
        /// </summary>
        public static string GridViewFilterIsContainedIn {
            get {
                return ResourceManager.GetString("GridViewFilterIsContainedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string GridViewFilterIsEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        public static string GridViewFilterIsGreaterThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        public static string GridViewFilterIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        public static string GridViewFilterIsLessThan {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        public static string GridViewFilterIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not equal to.
        /// </summary>
        public static string GridViewFilterIsNotEqualTo {
            get {
                return ResourceManager.GetString("GridViewFilterIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string GridViewFilterMatchCase {
            get {
                return ResourceManager.GetString("GridViewFilterMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string GridViewFilterOr {
            get {
                return ResourceManager.GetString("GridViewFilterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string GridViewFilterSelectAll {
            get {
                return ResourceManager.GetString("GridViewFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rows with value that.
        /// </summary>
        public static string GridViewFilterShowRowsWithValueThat {
            get {
                return ResourceManager.GetString("GridViewFilterShowRowsWithValueThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string GridViewFilterStartsWith {
            get {
                return ResourceManager.GetString("GridViewFilterStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        /// </summary>
        public static string GridViewGroupPanelText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Header.
        /// </summary>
        public static string GridViewGroupPanelTopText {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped by:.
        /// </summary>
        public static string GridViewGroupPanelTopTextGrouped {
            get {
                return ResourceManager.GetString("GridViewGroupPanelTopTextGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string LoginViewName {
            get {
                return ResourceManager.GetString("LoginViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginViewPassword {
            get {
                return ResourceManager.GetString("LoginViewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginViewSubmitButton {
            get {
                return ResourceManager.GetString("LoginViewSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Control.
        /// </summary>
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainPageRibbonGroupButtonOptions {
            get {
                return ResourceManager.GetString("MainPageRibbonGroupButtonOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainPageRibbonGroupButtonOptionsNew {
            get {
                return ResourceManager.GetString("MainPageRibbonGroupButtonOptionsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new item.
        /// </summary>
        public static string MainPageRibbonGroupButtonOptionsNewDesc {
            get {
                return ResourceManager.GetString("MainPageRibbonGroupButtonOptionsNewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New(Ctrl+N).
        /// </summary>
        public static string MainPageRibbonGroupButtonOptionsNewTip {
            get {
                return ResourceManager.GetString("MainPageRibbonGroupButtonOptionsNewTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainPageRibbonMenuExit {
            get {
                return ResourceManager.GetString("MainPageRibbonMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainPageRibbonMenuOptions {
            get {
                return ResourceManager.GetString("MainPageRibbonMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Itens.
        /// </summary>
        public static string MainPageRibbonMenuRecentItens {
            get {
                return ResourceManager.GetString("MainPageRibbonMenuRecentItens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainPageRibbonTabHome {
            get {
                return ResourceManager.GetString("MainPageRibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicity.
        /// </summary>
        public static string Publicity {
            get {
                return ResourceManager.GetString("Publicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string SalesClient {
            get {
                return ResourceManager.GetString("SalesClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string SalesVendor {
            get {
                return ResourceManager.GetString("SalesVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string SalesVendorClientAliasField {
            get {
                return ResourceManager.GetString("SalesVendorClientAliasField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SalesVendorClientNameField {
            get {
                return ResourceManager.GetString("SalesVendorClientNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string SaveButtonAs {
            get {
                return ResourceManager.GetString("SaveButtonAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product.
        /// </summary>
        public static string SelectProductTop {
            get {
                return ResourceManager.GetString("SelectProductTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Publicity.
        /// </summary>
        public static string SelectPublicityTop {
            get {
                return ResourceManager.GetString("SelectPublicityTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sales Vendor.
        /// </summary>
        public static string SelectSalesVendorTop {
            get {
                return ResourceManager.GetString("SelectSalesVendorTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version A.
        /// </summary>
        public static string VersionA {
            get {
                return ResourceManager.GetString("VersionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version B.
        /// </summary>
        public static string VersionB {
            get {
                return ResourceManager.GetString("VersionB", resourceCulture);
            }
        }
    }
}
