CREATE TABLE [dbo].[A2] (
    [cd_nota_saida]             INT             NOT NULL,
    [cd_num_formulario_nota]    INT             NULL,
    [dt_nota_saida]             DATETIME        NULL,
    [cd_requisicao_faturamento] INT             NULL,
    [cd_operacao_fiscal]        INT             NULL,
    [nm_fantasia_nota_saida]    CHAR (15)       NULL,
    [cd_transportadora]         INT             NULL,
    [cd_destinacao_produto]     INT             NULL,
    [cd_obs_padrao_nf]          INT             NULL,
    [cd_tipo_pagamento_frete]   INT             NULL,
    [qt_peso_liq_nota_saida]    FLOAT (53)      NULL,
    [qt_peso_bruto_nota_saida]  FLOAT (53)      NULL,
    [qt_volume_nota_saida]      FLOAT (53)      NULL,
    [cd_especie_embalagem]      INT             NULL,
    [nm_especie_nota_saida]     VARCHAR (25)    NULL,
    [nm_marca_nota_saida]       VARCHAR (20)    NULL,
    [cd_placa_nota_saida]       VARCHAR (8)     NULL,
    [nm_numero_emb_nota_saida]  VARCHAR (10)    NULL,
    [ic_emitida_nota_saida]     CHAR (1)        NULL,
    [nm_mot_cancel_nota_saida]  VARCHAR (50)    NULL,
    [dt_cancel_nota_saida]      DATETIME        NULL,
    [dt_saida_nota_saida]       DATETIME        NULL,
    [cd_usuario]                INT             NULL,
    [dt_usuario]                DATETIME        NULL,
    [vl_bc_icms]                DECIMAL (25, 2) NULL,
    [vl_icms]                   DECIMAL (25, 2) NULL,
    [vl_bc_subst_icms]          DECIMAL (25, 2) NULL,
    [vl_produto]                DECIMAL (25, 2) NULL,
    [vl_frete]                  DECIMAL (25, 2) NULL,
    [vl_seguro]                 DECIMAL (25, 2) NULL,
    [vl_desp_acess]             DECIMAL (25, 2) NULL,
    [vl_total]                  DECIMAL (25, 2) NULL,
    [vl_icms_subst]             DECIMAL (25, 2) NULL,
    [vl_ipi]                    DECIMAL (25, 2) NULL,
    [cd_vendedor]               INT             NULL,
    [cd_fornecedor]             INT             NULL,
    [cd_cliente]                INT             NULL,
    [cd_itinerario]             INT             NULL,
    [nm_obs_entrega_nota_saida] VARCHAR (40)    NULL,
    [nm_entregador_nota_saida]  VARCHAR (40)    NULL,
    [cd_observacao_entrega]     INT             NULL,
    [cd_entregador]             INT             NULL,
    [ic_entrega_nota_saida]     CHAR (1)        NULL,
    [sg_estado_placa]           CHAR (2)        NULL,
    [cd_pedido_cliente]         VARCHAR (30)    NULL,
    [cd_status_nota]            INT             NULL,
    [cd_tipo_calculo]           CHAR (1)        NULL,
    [cd_num_formulario]         INT             NULL,
    [cd_cnpj_nota_saida]        VARCHAR (20)    NULL,
    [cd_inscest_nota_saida]     VARCHAR (20)    NULL,
    [cd_inscmunicipal_nota]     VARCHAR (18)    NULL,
    [cd_cep_entrega]            CHAR (9)        NULL,
    [nm_endereco_entrega]       VARCHAR (60)    NULL,
    [cd_numero_endereco_ent]    CHAR (10)       NULL,
    [nm_complemento_end_ent]    VARCHAR (30)    NULL,
    [nm_bairro_entrega]         VARCHAR (25)    NULL,
    [cd_ddd_nota_saida]         CHAR (4)        NULL,
    [cd_telefone_nota_saida]    VARCHAR (15)    NULL,
    [cd_fax_nota_saida]         VARCHAR (15)    NULL,
    [nm_pais_nota_saida]        VARCHAR (30)    NULL,
    [sg_estado_entrega]         CHAR (2)        NULL,
    [nm_cidade_entrega]         VARCHAR (50)    NULL,
    [hr_saida_nota_saida]       CHAR (5)        NULL,
    [nm_endereco_cobranca]      VARCHAR (60)    NULL,
    [nm_bairro_cobranca]        VARCHAR (25)    NULL,
    [cd_cep_cobranca]           CHAR (9)        NULL,
    [nm_cidade_cobranca]        VARCHAR (30)    NULL,
    [sg_estado_cobranca]        CHAR (2)        NULL,
    [cd_numero_endereco_cob]    CHAR (10)       NULL,
    [nm_complemento_end_cob]    VARCHAR (30)    NULL,
    [qt_item_nota_saida]        INT             NULL,
    [ic_outras_operacoes]       CHAR (1)        NULL,
    [cd_pedido_venda]           INT             NULL,
    [ic_status_nota_saida]      CHAR (1)        NULL,
    [vl_iss]                    DECIMAL (25, 2) NULL,
    [vl_servico]                DECIMAL (25, 2) NULL,
    [ic_minuta_nota_saida]      CHAR (1)        NULL,
    [dt_entrega_nota_saida]     DATETIME        NULL,
    [sg_estado_nota_saida]      CHAR (2)        NULL,
    [nm_cidade_nota_saida]      VARCHAR (50)    NULL,
    [nm_bairro_nota_saida]      VARCHAR (25)    NULL,
    [nm_endereco_nota_saida]    VARCHAR (60)    NULL,
    [cd_numero_end_nota_saida]  CHAR (10)       NULL,
    [cd_cep_nota_saida]         CHAR (9)        NULL,
    [nm_razao_social_nota]      VARCHAR (40)    NULL,
    [nm_razao_social_c]         VARCHAR (40)    NULL,
    [cd_mascara_operacao]       CHAR (6)        NULL,
    [nm_operacao_fiscal]        VARCHAR (35)    NULL,
    [cd_tipo_destinatario]      INT             NULL,
    [cd_contrato_servico]       INT             NULL,
    [cd_condicao_pagamento]     INT             NULL,
    [vl_irrf_nota_saida]        DECIMAL (25, 2) NULL,
    [pc_irrf_serv_empresa]      FLOAT (53)      NULL,
    [nm_fantasia_destinatario]  VARCHAR (30)    NULL,
    [nm_compl_endereco_nota]    VARCHAR (10)    NULL,
    [ic_sedex_nota_saida]       CHAR (1)        NULL,
    [ic_coleta_nota_saida]      CHAR (1)        NULL,
    [dt_coleta_nota_saida]      DATETIME        NULL,
    [nm_coleta_nota_saida]      VARCHAR (30)    NULL,
    [cd_tipo_local_entrega]     INT             NULL,
    [ic_dev_nota_saida]         CHAR (1)        NULL,
    [cd_nota_dev_nota_saida]    INT             NULL,
    [dt_nota_dev_nota_saida]    DATETIME        NULL,
    [nm_razao_social_cliente]   VARCHAR (40)    NULL,
    [nm_razao_socila_cliente_c] VARCHAR (40)    NULL,
    [cd_tipo_operacao_fiscal]   INT             NULL,
    [vl_bc_ipi]                 DECIMAL (25, 2) NULL,
    [cd_operacao_fiscal2]       INT             NULL,
    [cd_operacao_fiscal3]       INT             NULL,
    [cd_mascara_operacao2]      CHAR (6)        NULL,
    [cd_mascara_operacao3]      CHAR (6)        NULL,
    [nm_operacao_fiscal2]       VARCHAR (35)    NULL,
    [nm_operacao_fiscal3]       VARCHAR (35)    NULL,
    [cd_tipo_operacao_fiscal2]  INT             NULL,
    [cd_tipo_operacao_fiscal3]  INT             NULL,
    [cd_tipo_operacao2]         INT             NULL,
    [cd_tipo_operacao3]         INT             NULL,
    [ic_zona_franca]            VARCHAR (1)     NULL,
    [vl_cofins]                 FLOAT (53)      NULL,
    [vl_pis]                    FLOAT (53)      NULL,
    [vl_desp_aduaneira]         FLOAT (53)      NULL,
    [vl_ii]                     FLOAT (53)      NULL,
    [nm_destinacao_produto]     VARCHAR (30)    NULL,
    [ic_forma_nota_saida]       CHAR (1)        NULL,
    [ic_editada_slf]            CHAR (1)        NOT NULL
);

