CREATE TABLE [dbo].[Aluno] (
    [cd_aluno]            INT           NOT NULL,
    [nm_aluno]            VARCHAR (40)  NULL,
    [nm_fantasia_aluno]   VARCHAR (15)  NULL,
    [cd_funcionario]      INT           NULL,
    [cd_usuario]          INT           NULL,
    [dt_usuario]          DATETIME      NULL,
    [cd_cep]              CHAR (8)      NULL,
    [cd_identifica_cep]   INT           NULL,
    [nm_endereco_aluno]   VARCHAR (40)  NULL,
    [cd_numero_endereco]  VARCHAR (40)  NULL,
    [nm_compl_endereco]   VARCHAR (40)  NULL,
    [nm_bairro_aluno]     VARCHAR (25)  NULL,
    [cd_pais]             INT           NULL,
    [cd_estado]           INT           NULL,
    [cd_cidade]           INT           NULL,
    [cd_ddd_aluno]        VARCHAR (3)   NULL,
    [cd_fone_aluno]       VARCHAR (15)  NULL,
    [cd_ddd_celular]      INT           NULL,
    [cd_celular_aluno]    VARCHAR (15)  NULL,
    [ds_perfil_aluno]     TEXT          NULL,
    [nm_email_aluno]      VARCHAR (100) NULL,
    [nm_foto_aluno]       VARCHAR (100) NULL,
    [cd_cliente]          INT           NULL,
    [dt_nascimento_aluno] DATETIME      NULL,
    [cd_rg_aluno]         VARCHAR (18)  NULL,
    [cd_cpf_aluno]        VARCHAR (18)  NULL,
    [cd_sexo]             INT           NULL,
    [cd_status_aluno]     INT           NULL,
    CONSTRAINT [PK_Aluno] PRIMARY KEY CLUSTERED ([cd_aluno] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Aluno_Funcionario] FOREIGN KEY ([cd_funcionario]) REFERENCES [dbo].[Funcionario] ([cd_funcionario]),
    CONSTRAINT [FK_Aluno_Sexo] FOREIGN KEY ([cd_sexo]) REFERENCES [dbo].[Sexo] ([cd_sexo]),
    CONSTRAINT [FK_Aluno_Status_Aluno] FOREIGN KEY ([cd_status_aluno]) REFERENCES [dbo].[Status_Aluno] ([cd_status_aluno])
);

