CREATE TABLE [dbo].[Arquivo_Texto_Invoice_Item] (
    [ic_produto_diferente]          CHAR (1)     NULL,
    [ic_produto_cadastrado]         CHAR (1)     NULL,
    [ic_quantidade_diferente]       CHAR (1)     NULL,
    [ic_preco_diferente]            CHAR (1)     NULL,
    [cd_pedido_importacao]          INT          NOT NULL,
    [nm_produto_pedido]             VARCHAR (30) NULL,
    [qt_item_pedido]                FLOAT (53)   NULL,
    [vl_unitario_item_ped]          FLOAT (53)   NULL,
    [cd_identificacao_pedido]       VARCHAR (20) NULL,
    [cd_item_ped_imp]               INT          NOT NULL,
    [cd_origem_importacao]          INT          NULL,
    [qt_peso]                       FLOAT (53)   NULL,
    [nm_produto_arquivo]            VARCHAR (30) NULL,
    [qt_item_arquivo_texto]         FLOAT (53)   NULL,
    [vl_item_arquivo_texto]         FLOAT (53)   NULL,
    [ds_produto_arquivo]            VARCHAR (30) NULL,
    [sg_origem_importacao]          CHAR (1)     NULL,
    [cd_moeda]                      INT          NULL,
    [cd_condicao_pagamento]         INT          NULL,
    [nm_fantasia_importador]        VARCHAR (15) NULL,
    [nm_fantasia_fornecedor]        VARCHAR (30) NULL,
    [cd_produto]                    INT          NULL,
    [cd_importador]                 INT          NULL,
    [cd_fornecedor]                 INT          NULL,
    [qt_peso_arquivo]               FLOAT (53)   NULL,
    [ic_pedido_nao_encontrado]      CHAR (1)     NULL,
    [sg_tipo_embalagem]             CHAR (2)     NULL,
    [cd_embalagem]                  CHAR (4)     NULL,
    [cd_arquivo_texto_invoice_item] INT          NULL
);

