CREATE TABLE [dbo].[Autorizacao_Pagamento_Contabil] (
    [cd_contab_ap]           INT          NOT NULL,
    [dt_contab_ap]           DATETIME     NULL,
    [cd_ap]                  INT          NULL,
    [cd_lancamento_padrao]   INT          NULL,
    [cd_conta_debito]        INT          NULL,
    [cd_conta_credito]       INT          NULL,
    [cd_historico_contabil]  INT          NULL,
    [nm_historico_contabil]  VARCHAR (40) NULL,
    [ic_sct_ap]              CHAR (1)     NULL,
    [dt_sct_ap]              DATETIME     NULL,
    [vl_contab_ap]           FLOAT (53)   NULL,
    [cd_lote_contabil]       INT          NULL,
    [ic_manutencao_contabil] CHAR (1)     NULL,
    [cd_usuario]             INT          NULL,
    [dt_usuario]             DATETIME     NULL,
    [cd_centro_custo]        INT          NULL,
    [cd_projeto_viagem]      INT          NULL,
    [nm_projeto_viagem]      VARCHAR (40) NULL,
    [ic_contabilizado]       CHAR (1)     NULL,
    [ic_cartao_credito]      CHAR (1)     NULL,
    [cd_prestacao]           INT          NULL,
    [cd_lancamento_contabil] INT          NULL,
    CONSTRAINT [PK_Autorizacao_Pagamento_Contabil] PRIMARY KEY CLUSTERED ([cd_contab_ap] ASC) WITH (FILLFACTOR = 90)
);

