CREATE TABLE [dbo].[Avaliacao_Ambiental] (
    [cd_avaliacao]            INT          NOT NULL,
    [dt_avaliacao]            DATETIME     NULL,
    [cd_status_avaliacao]     INT          NULL,
    [cd_atividade]            INT          NULL,
    [cd_aspecto_ambiental]    INT          NULL,
    [ic_tipo_requisito_legal] CHAR (1)     NULL,
    [cd_situacao_impacto]     INT          NULL,
    [cd_temporalidade]        INT          NULL,
    [cd_incidencia_ambiental] INT          NULL,
    [cd_tipo_aspecto]         INT          NULL,
    [cd_escala_ambiental]     INT          NULL,
    [cd_severidade_ambiental] INT          NULL,
    [cd_imabem_ambiental]     INT          NULL,
    [ic_signif_avaliacao]     CHAR (1)     NULL,
    [cd_significancia]        INT          NULL,
    [nm_signif_avaliacao]     VARCHAR (40) NULL,
    [ic_ajuste_avaliacao]     CHAR (1)     NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    [nm_obs_avaliacao]        VARCHAR (40) NULL,
    [nm_controle_avaliacao]   VARCHAR (60) NULL,
    [nm_objetivo_avaliacao]   VARCHAR (60) NULL,
    [dt_aprovacao_avaliacao]  DATETIME     NULL,
    [cd_usuario_aprovacao]    INT          NULL,
    [cd_risco_ambiental]      INT          NULL,
    [cd_gravidade]            INT          NULL,
    [c]                       INT          NULL,
    [cd_impacto_ambiental]    INT          NULL,
    CONSTRAINT [PK_Avaliacao_Ambiental] PRIMARY KEY CLUSTERED ([cd_avaliacao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Avaliacao_Ambiental_Gravidade_Ambiental] FOREIGN KEY ([cd_gravidade]) REFERENCES [dbo].[Gravidade_Ambiental] ([cd_gravidade]),
    CONSTRAINT [FK_Avaliacao_Ambiental_Impacto_Ambiental] FOREIGN KEY ([cd_impacto_ambiental]) REFERENCES [dbo].[Impacto_Ambiental] ([cd_impacto_ambiental]),
    CONSTRAINT [FK_Avaliacao_Ambiental_Probabiliade_Ambiental] FOREIGN KEY ([c]) REFERENCES [dbo].[Probabiliade_Ambiental] ([cd_probabilidade]),
    CONSTRAINT [FK_Avaliacao_Ambiental_Risco_Ambiental] FOREIGN KEY ([cd_risco_ambiental]) REFERENCES [dbo].[Risco_Ambiental] ([cd_risco_ambiental]),
    CONSTRAINT [FK_Avaliacao_Ambiental_Usuario] FOREIGN KEY ([cd_usuario_aprovacao]) REFERENCES [dbo].[Usuario] ([cd_usuario])
);

