CREATE TABLE [dbo].[backup_parametro_faturamento] (
    [cd_empresa]                     INT           NOT NULL,
    [ic_irrf_empresa]                CHAR (1)      NULL,
    [cd_usuario]                     INT           NULL,
    [dt_usuario]                     DATETIME      NULL,
    [ic_fat_minimo_empresa]          CHAR (1)      NULL,
    [vl_fat_minimo_empresa]          FLOAT (53)    NULL,
    [ic_rateio_frete_empresa]        CHAR (1)      NULL,
    [vl_irrf_minimo]                 FLOAT (53)    NULL,
    [cd_dispositivo_legal_irrf]      INT           NULL,
    [ic_grava_data_hora_saida]       CHAR (1)      NULL,
    [cd_dispositivo_legal_mp66]      INT           NULL,
    [ic_agrupa_pedido_empresa]       CHAR (1)      NULL,
    [nm_porta_impressao_nota]        VARCHAR (100) NULL,
    [ic_prog_restricao_estoque]      CHAR (1)      NULL,
    [cd_classificacao_fiscal]        INT           NULL,
    [cd_icms_dispositivo]            INT           NULL,
    [ic_filtro_prog_fat]             CHAR (1)      NULL,
    [ic_filtro_ativo_prog_fat]       CHAR (1)      NULL,
    [qt_diaria_cilindro_empres]      MONEY         NULL,
    [ic_modifica_tributacao]         CHAR (1)      NULL,
    [ic_solicitante_requis_fat]      CHAR (1)      NULL,
    [ic_class_fiscal_req_fat]        CHAR (1)      NULL,
    [ic_montagem_base_icms]          CHAR (1)      NULL,
    [ic_destaque_montagem]           CHAR (1)      NULL,
    [ic_data_nota_saida_hoje]        CHAR (1)      NULL,
    [ic_importar_parcela_pv]         CHAR (1)      NULL,
    [cd_obs_padrao_nf]               INT           NULL,
    [nm_cilindros]                   VARCHAR (60)  NULL,
    [pc_desc_icms_zona_franca]       FLOAT (53)    NULL,
    [cd_fiscal_tipo_produto_zf]      VARCHAR (5)   NULL,
    [ic_validar_sequencia_nota]      CHAR (1)      NULL,
    [ic_qtd_pedido_nota_exced]       CHAR (1)      NULL,
    [cd_dispositivo_iss_ret_fonte]   INT           NULL,
    [cd_dispositivo_ret_imp]         INT           NULL,
    [cd_fiscal_consignacao]          VARCHAR (5)   NULL,
    [ds_mensagem_nota_saida_fin]     TEXT          NULL,
    [ic_filtrar_req_fat_usuario]     CHAR (1)      NULL,
    [ic_observacao_nf_vendedor]      CHAR (1)      NULL,
    [ic_observacao_nf_pedido_client] CHAR (1)      NULL,
    [ic_observacao_nf_nosso_pedido]  CHAR (1)      NULL,
    [ic_observacao_nf_produto]       CHAR (1)      NULL,
    [ic_informa_lote_nota_saida]     CHAR (1)      NULL,
    [ic_observacao_nf_dest_prod]     CHAR (1)      NULL,
    [ic_multiplic_comp_dev_cancel]   CHAR (1)      NULL,
    [ic_cupom_fiscal]                CHAR (1)      NULL,
    [vl_teto_imposto_retido]         MONEY         NULL,
    [ic_observacao_nf_cambio]        CHAR (1)      NULL,
    [ic_bloquear_devolucao_pagto]    CHAR (1)      NULL,
    [ic_desconto_cliente_nf]         CHAR (1)      NULL,
    [ic_altera_parcela_pedido]       CHAR (1)      NULL,
    [ic_valor_simbolico_nota_fiscal] CHAR (1)      NULL,
    [ic_prog_restricao_producao]     CHAR (1)      NULL,
    [ic_prog_restricao_importacao]   CHAR (1)      NULL,
    [cd_dispositivo_cupom]           INT           NULL,
    [ic_data_geracao_parcela]        CHAR (1)      NULL,
    [ic_previa_gera_prog]            CHAR (1)      NULL,
    [ic_confirmar_recalculo_nf]      CHAR (1)      NULL,
    [ic_bloquear_cancelamento_pagto] CHAR (1)      NULL,
    [ic_lib_credito_programacao]     CHAR (1)      NULL,
    [cd_dispositivo_inss]            INT           NULL,
    [ic_cancela_saldo_pedido]        CHAR (1)      NULL,
    [ic_plano_financeiro]            CHAR (1)      NULL,
    [cd_dispositivo_inss_disp]       INT           NULL,
    [ic_centro_custo]                CHAR (1)      NULL,
    [ic_analise_faturamento]         CHAR (1)      NULL,
    [ic_baixa_ri_faturamento]        CHAR (1)      NULL,
    [ic_deduz_pis_cofins_total]      CHAR (1)      NULL,
    [ic_restricao_canc_dev]          CHAR (1)      NULL,
    [cd_tipo_restricao_pedido]       INT           NULL,
    [ic_calculo_volume]              CHAR (1)      NULL,
    [ic_dado_adicional_produto]      CHAR (1)      NULL,
    [ic_minuta_saida_nota]           CHAR (1)      NULL,
    [ic_bloq_prog_fat_compra]        CHAR (1)      NULL,
    [ic_multi_formulario]            CHAR (1)      NULL,
    [ic_perfil_cliente]              CHAR (1)      NULL,
    [ic_bloqueia_item_sem_lote]      CHAR (1)      NULL,
    [ic_demo_base_icms]              CHAR (1)      NULL,
    [ic_gera_classif_fiscal_corpo]   CHAR (1)      NULL,
    [ic_nao_contribuinte_icms]       CHAR (1)      NULL,
    [pc_cofins]                      FLOAT (53)    NULL,
    [pc_pis]                         FLOAT (53)    NULL,
    [ic_nf_servico_eletronica]       CHAR (1)      NULL
);

