CREATE TABLE [dbo].[Bem] (
    [dt_aquisicao_bem]     DATETIME      NULL,
    [cd_bem]               INT           NOT NULL,
    [nm_bem]               VARCHAR (60)  NULL,
    [ds_bem]               TEXT          NULL,
    [nm_mascara_bem]       VARCHAR (20)  NULL,
    [cd_grupo_bem]         INT           NOT NULL,
    [cd_plano_conta]       INT           NULL,
    [cd_centro_custo]      INT           NULL,
    [cd_status_bem]        INT           NULL,
    [cd_localizacao_bem]   INT           NULL,
    [cd_tipo_reavaliacao]  INT           NULL,
    [cd_apolice_seguro]    INT           NULL,
    [dt_inicio_uso_bem]    DATETIME      NULL,
    [dt_garantia_bem]      DATETIME      NULL,
    [nm_marca_bem]         VARCHAR (30)  NULL,
    [nm_modelo_bem]        VARCHAR (30)  NULL,
    [nm_serie_bem]         VARCHAR (30)  NULL,
    [cd_patrimonio_bem]    VARCHAR (25)  NULL,
    [cd_area_risco]        INT           NULL,
    [cd_empresa]           INT           NULL,
    [cd_item_bem]          INT           NULL,
    [cd_subitem_bem]       INT           NULL,
    [cd_usuario]           INT           NULL,
    [dt_usuario]           DATETIME      NULL,
    [cd_nota_entrada]      INT           NULL,
    [cd_fornecedor]        INT           NULL,
    [cd_serie_nota_fiscal] INT           NULL,
    [cd_item_nota_entrada] INT           NULL,
    [nm_obs_item]          VARCHAR (100) NULL,
    [cd_departamento]      INT           NULL,
    [cd_turno]             INT           NULL,
    [cd_tipo_baixa_bem]    INT           NULL,
    [dt_baixa_bem]         DATETIME      NULL,
    [cd_operacao_fiscal]   INT           NULL,
    [qt_item_nota_entrada] FLOAT (53)    NULL,
    [qt_bem]               FLOAT (53)    NULL,
    [cd_planta]            INT           NULL,
    [cd_barra_bem]         VARCHAR (25)  NULL,
    [cd_seguradora]        INT           NULL,
    [cd_tipo_bem]          INT           NULL,
    [cd_nota_saida]        INT           NULL,
    [cd_item_nota_saida]   INT           NULL,
    [qt_item_nota_saida]   FLOAT (53)    NULL,
    [cd_cliente]           INT           NULL,
    [nm_foto_bem]          VARCHAR (120) NULL,
    [cd_origem_bem]        INT           NULL,
    [ic_inventario_bem]    CHAR (1)      NULL,
    [cd_conta]             INT           NULL,
    [ic_usado_bem]         CHAR (1)      NULL,
    [ic_bem_ciap]          CHAR (1)      NULL,
    [nm_medida_bem]        VARCHAR (40)  NULL,
    CONSTRAINT [PK_Bem] PRIMARY KEY CLUSTERED ([cd_bem] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Bem_Area_Risco] FOREIGN KEY ([cd_area_risco]) REFERENCES [dbo].[Area_Risco] ([cd_area_risco]),
    CONSTRAINT [FK_Bem_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Bem_Departamento] FOREIGN KEY ([cd_departamento]) REFERENCES [dbo].[Departamento] ([cd_departamento]),
    CONSTRAINT [FK_Bem_Grupo_Bem] FOREIGN KEY ([cd_grupo_bem]) REFERENCES [dbo].[Grupo_Bem] ([cd_grupo_bem]),
    CONSTRAINT [FK_Bem_Localizacao_Bem] FOREIGN KEY ([cd_localizacao_bem]) REFERENCES [dbo].[Localizacao_Bem] ([cd_localizacao_bem]),
    CONSTRAINT [FK_Bem_Planta] FOREIGN KEY ([cd_planta]) REFERENCES [dbo].[Planta] ([cd_planta]),
    CONSTRAINT [FK_Bem_Seguradora] FOREIGN KEY ([cd_seguradora]) REFERENCES [dbo].[Seguradora] ([cd_seguradora]),
    CONSTRAINT [FK_Bem_Status_Bem] FOREIGN KEY ([cd_status_bem]) REFERENCES [dbo].[Status_Bem] ([cd_status_bem]),
    CONSTRAINT [FK_Bem_Tipo_Baixa_Bem] FOREIGN KEY ([cd_tipo_baixa_bem]) REFERENCES [dbo].[Tipo_Baixa_Bem] ([cd_tipo_baixa_bem]),
    CONSTRAINT [FK_Bem_Tipo_Bem] FOREIGN KEY ([cd_tipo_bem]) REFERENCES [dbo].[Tipo_Bem] ([cd_tipo_bem]),
    CONSTRAINT [FK_Bem_Tipo_Reavaliacao] FOREIGN KEY ([cd_tipo_reavaliacao]) REFERENCES [dbo].[Tipo_Reavaliacao] ([cd_tipo_reavaliacao]),
    CONSTRAINT [FK_Bem_Turno] FOREIGN KEY ([cd_turno]) REFERENCES [dbo].[Turno] ([cd_turno])
);

