CREATE TABLE [dbo].[Calculo_Folha] (
    [cd_calculo_folha]        INT          NOT NULL,
    [cd_funcionario]          INT          NULL,
    [dt_base_calculo_folha]   DATETIME     NULL,
    [cd_evento]               INT          NULL,
    [vl_referencia_calculo]   FLOAT (53)   NULL,
    [vl_provento_calculo]     FLOAT (53)   NULL,
    [vl_desconto_calculo]     FLOAT (53)   NULL,
    [pc_calculo]              FLOAT (53)   NULL,
    [vl_calculo_folha]        FLOAT (53)   NULL,
    [cd_departamento]         INT          NULL,
    [cd_seccao]               INT          NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    [cd_vinculo_empregaticio] INT          NULL,
    [mm_calculo_folha]        INT          NULL,
    [aa_calculo_folha]        INT          NULL,
    [cd_centro_custo]         INT          NULL,
    [dt_pagto_calculo_folha]  DATETIME     NULL,
    [ic_forma_calculo_folha]  CHAR (1)     NULL,
    [cd_tipo_calculo_folha]   INT          NULL,
    [cd_controle]             INT          NULL,
    [cd_controle_folha]       INT          NULL,
    [cd_ap]                   INT          NULL,
    [vl_base_calculo_evento]  FLOAT (53)   NULL,
    [cd_evento_desconto]      INT          NULL,
    [vl_ref_provento_calculo] FLOAT (53)   NULL,
    [vl_ref_desconto_calculo] FLOAT (53)   NULL,
    [nm_evento_provento]      VARCHAR (40) NULL,
    [nm_evento_desconto]      VARCHAR (40) NULL,
    CONSTRAINT [PK_Calculo_Folha] PRIMARY KEY CLUSTERED ([cd_calculo_folha] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Calculo_Folha_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Calculo_Folha_Seccao] FOREIGN KEY ([cd_seccao]) REFERENCES [dbo].[Seccao] ([cd_seccao]),
    CONSTRAINT [FK_Calculo_Folha_Tipo_Calculo_Folha] FOREIGN KEY ([cd_tipo_calculo_folha]) REFERENCES [dbo].[Tipo_Calculo_Folha] ([cd_tipo_calculo_folha]),
    CONSTRAINT [FK_Calculo_Folha_Vinculo_Empregaticio] FOREIGN KEY ([cd_vinculo_empregaticio]) REFERENCES [dbo].[Vinculo_Empregaticio] ([cd_vinculo_empregaticio])
);

