CREATE TABLE [dbo].[Cartorio] (
    [cd_cartorio]             INT           NOT NULL,
    [nm_cartorio]             VARCHAR (40)  NULL,
    [nm_endereco_cartorio]    VARCHAR (50)  NULL,
    [nm_bairro_cartorio]      VARCHAR (25)  NULL,
    [cd_pais]                 INT           NULL,
    [cd_estado]               INT           NULL,
    [cd_cidade]               INT           NULL,
    [cd_identifica_cep]       INT           NULL,
    [cd_cep]                  CHAR (9)      NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [sg_cartorio]             CHAR (10)     NULL,
    [nm_fantasia_cartorio]    VARCHAR (15)  NULL,
    [cd_fone_cartorio]        VARCHAR (10)  NULL,
    [cd_ddd_cartorio]         CHAR (4)      NULL,
    [cd_cnpj_cartorio]        VARCHAR (18)  NULL,
    [nm_contato_cartorio]     VARCHAR (40)  NULL,
    [nm_email_cartorio]       VARCHAR (100) NULL,
    [dt_cadastro]             DATETIME      NULL,
    [cd_insmunicipal]         VARCHAR (18)  NULL,
    [nm_complemento_endereco] VARCHAR (10)  NULL,
    [cd_numero_endereco]      INT           NULL,
    [ds_cartorio]             TEXT          NULL,
    [cd_fax_cartorio]         VARCHAR (10)  NULL,
    [nm_ponto_ref_cartorio]   VARCHAR (100) NULL,
    [cd_insestadual_cartorio] VARCHAR (18)  NULL,
    CONSTRAINT [PK_Cartorio] PRIMARY KEY CLUSTERED ([cd_cartorio] ASC) WITH (FILLFACTOR = 90)
);

