CREATE TABLE [dbo].[Ciap] (
    [cd_ciap]                  INT          NOT NULL,
    [dt_ciap]                  DATETIME     NULL,
    [qt_mes_ciap]              FLOAT (53)   NULL,
    [vl_icms_ciap]             FLOAT (53)   NULL,
    [cd_fornecedor]            INT          NULL,
    [cd_operacao_fiscal]       INT          NULL,
    [cd_nota_entrada]          INT          NULL,
    [cd_serie_nota_fiscal]     INT          NULL,
    [cd_nota_entrada_manual]   INT          NULL,
    [cd_serie_entrada_manual]  INT          NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [dt_baixa_ciap]            DATETIME     NULL,
    [cd_bem]                   INT          NULL,
    [pc_fator_bem_ciap]        FLOAT (53)   NULL,
    [nm_obs_ciap]              VARCHAR (60) NULL,
    [cd_livro_entrada]         INT          NULL,
    [cd_livro_saida]           INT          NULL,
    [dt_entrada_nota_ciap]     DATETIME     NULL,
    [qt_folha_livro_entrada]   INT          NULL,
    [qt_folha_livro_saida]     INT          NULL,
    [vl_estorno_ciap]          FLOAT (53)   NULL,
    [qt_saldo_mes_ciap]        FLOAT (53)   NULL,
    [vl_saldo_ciap]            FLOAT (53)   NULL,
    [vl_baixa_ciap]            FLOAT (53)   NULL,
    [dt_saldo_ciap]            DATETIME     NULL,
    [cd_livro_ciap]            INT          NULL,
    [cd_tipo_baixa_bem]        INT          NULL,
    [nm_motivo_baixa_ciap]     VARCHAR (40) NULL,
    [ic_credito_ciap]          CHAR (1)     NULL,
    [cd_tipo_ciap]             INT          NULL,
    [cd_local_bem]             INT          NULL,
    [qt_ordem_livro_ciap]      INT          NULL,
    [dt_calculo_ciap]          DATETIME     NULL,
    [ic_tipo_uso_perc_cred]    CHAR (1)     NULL,
    [pc_creditamento_bem_ciap] FLOAT (53)   NULL,
    [dt_base_fixo_saldo_ciap]  DATETIME     NULL,
    [vl_fixo_saldo_ciap]       FLOAT (53)   NULL,
    [cd_tipo_movimento]        INT          NULL,
    [cd_chave_acesso_nfe]      VARCHAR (50) NULL,
    CONSTRAINT [PK_Ciap] PRIMARY KEY CLUSTERED ([cd_ciap] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Ciap_Bem] FOREIGN KEY ([cd_bem]) REFERENCES [dbo].[Bem] ([cd_bem]),
    CONSTRAINT [FK_Ciap_Local_Bem_Ciap] FOREIGN KEY ([cd_local_bem]) REFERENCES [dbo].[Local_Bem_Ciap] ([cd_local_bem]),
    CONSTRAINT [FK_Ciap_Serie_Nota_Fiscal] FOREIGN KEY ([cd_serie_nota_fiscal]) REFERENCES [dbo].[Serie_Nota_Fiscal] ([cd_serie_nota_fiscal])
);

