CREATE TABLE [dbo].[Cliente_Informacao_Credito] (
    [cd_cliente]                INT          NOT NULL,
    [vl_limite_credito_cliente] FLOAT (53)   NULL,
    [ic_cobranca_eletronica]    CHAR (1)     NULL,
    [ic_informacao_credito]     CHAR (1)     NULL,
    [qt_dia_atraso_cliente]     INT          NULL,
    [qt_media_atraso_cliente]   INT          NULL,
    [qt_pagamento_atraso]       INT          NULL,
    [vl_maior_fatura_cliente]   FLOAT (53)   NULL,
    [dt_maior_fatura_cliente]   DATETIME     NULL,
    [vl_ultimo_faturamento]     FLOAT (53)   NULL,
    [dt_ultimo_faturamento]     DATETIME     NULL,
    [qt_titulo_aberto_cliente]  INT          NULL,
    [qt_titulo_protesto]        INT          NULL,
    [qt_titulo_cartorio]        INT          NULL,
    [ds_observacao_credito]     TEXT         NULL,
    [ic_credito_suspenso]       CHAR (1)     NULL,
    [dt_situacao_credito]       DATETIME     NULL,
    [qt_titulo_pago]            INT          NULL,
    [qt_maior_atraso]           INT          NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [dt_ultimo_pagamento_atras] DATETIME     NULL,
    [vl_total_faturamento]      FLOAT (53)   NULL,
    [vl_saldo_atual_aberto]     FLOAT (53)   NULL,
    [nm_credito_suspenso]       VARCHAR (30) NULL,
    [qt_total_documentos]       INT          NULL,
    [dt_orgao_credito]          DATETIME     NULL,
    [cd_orgao_credito]          INT          NULL,
    [vl_maior_acumulo]          FLOAT (53)   NULL,
    [dt_maior_acumulo]          DATETIME     NULL,
    [qt_nota_debito]            INT          NULL,
    [vl_nota_debito]            FLOAT (53)   NULL,
    [dt_suspensao_credito]      DATETIME     NULL,
    [cd_usuario_cred_susp]      INT          NULL,
    [vl_total_credito_pendente] FLOAT (53)   NULL,
    [cd_suspensao_credito]      INT          NULL,
    [nm_fantasia_usuario]       VARCHAR (15) NULL,
    [vl_saldo_credito_cliente]  FLOAT (53)   NULL,
    [cd_tipo_cobranca]          INT          NULL,
    [vl_operacao_cambio]        FLOAT (53)   NULL,
    [vl_embarque_cliente]       FLOAT (53)   NULL,
    [vl_total_documento_pago]   FLOAT (53)   NULL,
    [cd_motivo_liberacao]       INT          NULL,
    [ic_alerta_credito_cliente] CHAR (1)     NULL,
    [cd_condicao_pagamento]     INT          NULL,
    [cd_conceito_credito]       INT          NULL,
    [cd_portador]               INT          NULL,
    [dt_validade_orgao_credito] DATETIME     NULL,
    [ic_bloqueio_total_cliente] CHAR (1)     NULL,
    [ic_deposito_cliente]       CHAR (1)     NULL,
    [cd_conta_banco]            INT          NULL,
    [cd_forma_pagamento]        INT          NULL,
    [vl_fat_minimo_cliente]     FLOAT (53)   NULL,
    [ds_msg_boleto]             TEXT         NULL,
    [pc_desconto_boleto]        FLOAT (53)   NULL,
    CONSTRAINT [PK_Cliente_Informacao_Credito] PRIMARY KEY CLUSTERED ([cd_cliente] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Cliente_Informacao_Credito_Tipo_Cobranca] FOREIGN KEY ([cd_tipo_cobranca]) REFERENCES [dbo].[Tipo_Cobranca] ([cd_tipo_cobranca])
);

