CREATE TABLE [dbo].[Cliente_Lista_Ams] (
    [Nome Fantasia]       NVARCHAR (255) NULL,
    [CNPJ]                NVARCHAR (255) NULL,
    [DDD]                 NVARCHAR (255) NULL,
    [Telefone]            NVARCHAR (255) NULL,
    [Pais]                NVARCHAR (255) NULL,
    [Cidade]              NVARCHAR (255) NULL,
    [Estado]              NVARCHAR (255) NULL,
    [CEP]                 NVARCHAR (255) NULL,
    [Razão Social]        NVARCHAR (255) NULL,
    [Ramo de Atividade]   NVARCHAR (255) NULL,
    [Vendedor]            NVARCHAR (255) NULL,
    [Vendedor Interno]    NVARCHAR (255) NULL,
    [Fonte de Informação] NVARCHAR (255) NULL,
    [Status]              NVARCHAR (255) NULL,
    [Dt# Cadastro]        NVARCHAR (255) NULL,
    [Grupo]               NVARCHAR (255) NULL,
    [Tipo Mercado]        NVARCHAR (255) NULL,
    [Destinação]          NVARCHAR (255) NULL,
    [Transportadora]      NVARCHAR (255) NULL,
    [Condição Pagamento]  NVARCHAR (255) NULL,
    [Idioma]              NVARCHAR (255) NULL,
    [Critério Visita]     NVARCHAR (255) NULL,
    [Centro Custo]        NVARCHAR (255) NULL,
    [Tipo Pessoa]         NVARCHAR (255) NULL,
    [Conceito Cliente]    NVARCHAR (255) NULL,
    [Tipo Tabela Preço]   NVARCHAR (255) NULL,
    [ICMS]                NVARCHAR (255) NULL,
    [Lib# Pesq# Cred]     NVARCHAR (255) NULL,
    [Usuário]             NVARCHAR (255) NULL,
    [Dt# Usuário]         NVARCHAR (255) NULL
);

