CREATE TABLE [dbo].[CLIENTES] (
    [CODCLIENTE] NUMERIC (8)   NOT NULL,
    [NOME]       VARCHAR (30)  NULL,
    [SOBRENOME]  VARCHAR (30)  NULL,
    [ENDERECO]   VARCHAR (30)  NULL,
    [BAIRRO]     VARCHAR (20)  NULL,
    [CEP]        NUMERIC (8)   NULL,
    [CIDADE]     VARCHAR (20)  NULL,
    [UF]         CHAR (2)      NULL,
    [FONERES]    VARCHAR (12)  NULL,
    [FONECOM]    VARCHAR (12)  NULL,
    [DTCADASTRO] SMALLDATETIME NULL,
    CONSTRAINT [CODCLIENTE_PK] PRIMARY KEY CLUSTERED ([CODCLIENTE] ASC) WITH (FILLFACTOR = 90)
);

