CREATE TABLE [dbo].[Cliente_Vendedor] (
    [cd_cliente]                INT           NOT NULL,
    [cd_vendedor]               INT           NOT NULL,
    [cd_cliente_vendedor]       INT           NOT NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_celular]                VARCHAR (15)  NULL,
    [vl_meta]                   FLOAT (53)    NULL,
    [ic_ativo]                  CHAR (1)      NULL,
    [cd_tipo_vendedor]          INT           NULL,
    [cd_tipo_pessoa]            INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_estado]                 INT           NULL,
    [cd_pais]                   INT           NULL,
    [cd_banco]                  INT           NULL,
    [cd_cep]                    CHAR (9)      NULL,
    [cd_conta_corrente]         VARCHAR (20)  NULL,
    [cd_agencia_banco_vendedor] VARCHAR (15)  NULL,
    [qt_visita_diaria_vendedor] INT           NULL,
    [nm_contato_vendedor]       VARCHAR (40)  NULL,
    [pc_comissao_vendedor]      FLOAT (53)    NULL,
    [pc_aliquota_irpj]          FLOAT (53)    NULL,
    [nm_email_particular]       VARCHAR (100) NULL,
    [nm_email_vendedor]         VARCHAR (100) NULL,
    [nm_dominio_vendedor]       VARCHAR (100) NULL,
    [cd_insmunicipal_vendedor]  VARCHAR (18)  NULL,
    [cd_inscestadual_vendedor]  VARCHAR (18)  NULL,
    [cd_cnpj_vendedor]          VARCHAR (18)  NULL,
    [cd_fax_vendedor]           VARCHAR (15)  NULL,
    [cd_telefone_vendedor]      VARCHAR (15)  NULL,
    [cd_ddd_vendedor]           CHAR (4)      NULL,
    [nm_bairro_vendedor]        VARCHAR (25)  NULL,
    [nm_complemento_endereco]   VARCHAR (30)  NULL,
    [cd_numero_endereco]        VARCHAR (10)  NULL,
    [nm_endereco_vendedor]      VARCHAR (60)  NULL,
    [sg_vendedor]               CHAR (10)     NULL,
    [nm_fantasia_vendedor]      VARCHAR (15)  NULL,
    [nm_vendedor]               VARCHAR (40)  NULL,
    [cd_inscmunicipal_vendedor] VARCHAR (18)  NULL
);

