CREATE TABLE [dbo].[Cliente_Prospeccao] (
    [cd_cliente_prospeccao]  INT           NOT NULL,
    [dt_cadastro_cliente]    DATETIME      NULL,
    [nm_cliente]             VARCHAR (40)  NULL,
    [nm_fantasia_cliente]    VARCHAR (15)  NULL,
    [cd_tipo_cliente]        INT           NULL,
    [cd_vendedor]            INT           NULL,
    [cd_fonte_informacao]    INT           NULL,
    [cd_regiao_venda]        INT           NULL,
    [cd_cidade]              INT           NULL,
    [cd_estado]              INT           NULL,
    [cd_pais]                INT           NULL,
    [ds_perfil_cliente]      TEXT          NULL,
    [cd_fax_cliente]         VARCHAR (15)  NULL,
    [cd_fone_cliente]        CHAR (15)     NULL,
    [cd_ddd_cliente]         CHAR (4)      NULL,
    [cd_cep_cliente]         CHAR (9)      NULL,
    [nm_bairro_cliente]      VARCHAR (25)  NULL,
    [nm_compl_end_cliente]   VARCHAR (30)  NULL,
    [nm_endereco_cliente]    VARCHAR (60)  NULL,
    [cd_identifica_cep]      INT           NULL,
    [dt_usuario]             DATETIME      NULL,
    [cd_usuario]             INT           NULL,
    [cd_ramo_atividade]      INT           NULL,
    [cd_status_prospeccao]   INT           NULL,
    [qt_filial_cliente]      INT           NULL,
    [qt_faturamento_cliente] FLOAT (53)    NULL,
    [qt_funcionario_cliente] INT           NULL,
    [nm_email_contato]       VARCHAR (40)  NULL,
    [nm_contato_cliente]     VARCHAR (40)  NULL,
    [nm_email_cliente]       VARCHAR (40)  NULL,
    [nm_site_cliente]        VARCHAR (100) NULL,
    [ds_referencia_cliente]  TEXT          NULL,
    [cd_cliente]             INT           NULL,
    CONSTRAINT [PK_Cliente_Prospeccao] PRIMARY KEY CLUSTERED ([cd_cliente_prospeccao] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Cliente_Prospeccao_Fonte_Informacao] FOREIGN KEY ([cd_fonte_informacao]) REFERENCES [dbo].[Fonte_Informacao] ([cd_fonte_informacao]),
    CONSTRAINT [FK_Cliente_Prospeccao_Regiao_Venda] FOREIGN KEY ([cd_regiao_venda]) REFERENCES [dbo].[Regiao_Venda] ([cd_regiao_venda]),
    CONSTRAINT [FK_Cliente_Prospeccao_Vendedor] FOREIGN KEY ([cd_vendedor]) REFERENCES [dbo].[Vendedor] ([cd_vendedor])
);

