CREATE TABLE [dbo].[Cliente_Endereco] (
    [cd_cliente]                INT           NOT NULL,
    [cd_tipo_endereco]          INT           NOT NULL,
    [cd_identifica_cep]         INT           NULL,
    [dt_cadastro_endereco]      DATETIME      NULL,
    [cd_cnpj_cliente]           VARCHAR (18)  NULL,
    [cd_inscestadual]           VARCHAR (18)  NULL,
    [cd_inscmunicipal_cliente]  VARCHAR (18)  NULL,
    [cd_cep_cliente]            CHAR (9)      NULL,
    [nm_endereco_cliente]       VARCHAR (60)  NULL,
    [cd_numero_endereco]        CHAR (10)     NULL,
    [nm_complemento_endereco]   VARCHAR (30)  NULL,
    [nm_bairro_cliente]         VARCHAR (25)  NULL,
    [cd_ddd_cliente]            CHAR (4)      NULL,
    [cd_telefone_cliente]       VARCHAR (15)  NULL,
    [cd_fax_cliente]            VARCHAR (15)  NULL,
    [cd_pais]                   INT           NULL,
    [cd_estado]                 INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_suframa]                VARCHAR (15)  NULL,
    [cd_reparticao_origem]      VARCHAR (15)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_regiao]                 INT           NULL,
    [cd_local_entrega]          CHAR (10)     NULL,
    [nm_ponto_ref_cli_endereco] VARCHAR (100) NULL,
    [ic_isento_insc_cliente]    CHAR (1)      NULL,
    [ds_cliente_endereco]       TEXT          NULL,
    CONSTRAINT [PK_Cliente_Endereco] PRIMARY KEY CLUSTERED ([cd_cliente] ASC, [cd_tipo_endereco] ASC) WITH (FILLFACTOR = 90)
);

