CREATE TABLE [dbo].[Cobrador] (
    [cd_cobrador]               INT           NOT NULL,
    [nm_cobrador]               VARCHAR (40)  NULL,
    [ic_ativo_cobrador]         CHAR (1)      NULL,
    [nm_fantasia_cobrador]      VARCHAR (15)  NULL,
    [sg_cobrador]               CHAR (10)     NULL,
    [cd_tipo_pessoa]            INT           NULL,
    [nm_endereco_cobrador]      VARCHAR (50)  NULL,
    [nm_bairro_cobrador]        VARCHAR (25)  NULL,
    [cd_ddd_cobrador]           CHAR (4)      NULL,
    [cd_celular_cobrador]       VARCHAR (15)  NULL,
    [cd_telefone_cobrador]      VARCHAR (15)  NULL,
    [cd_fax_cobrador]           VARCHAR (15)  NULL,
    [cd_cnpj_cobrador]          VARCHAR (18)  NULL,
    [cd_inscestadual_cobrador]  VARCHAR (18)  NULL,
    [nm_email_cobrador]         VARCHAR (100) NULL,
    [nm_contato_cobrador]       VARCHAR (10)  NULL,
    [cd_cep]                    CHAR (9)      NULL,
    [cd_banco]                  INT           NULL,
    [cd_pais]                   INT           NULL,
    [cd_estado]                 INT           NULL,
    [cd_cidade]                 INT           NULL,
    [cd_agencia_banco_cobrador] VARCHAR (15)  NULL,
    [cd_conta_corrente]         VARCHAR (20)  NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [nm_email_particular]       VARCHAR (100) NULL,
    [pc_aliquota_irpj]          FLOAT (53)    NULL,
    [pc_comissao_cobrador]      FLOAT (53)    NULL,
    [vl_salario_cobrador]       FLOAT (53)    NULL,
    [ic_recibo_comis_cobrador]  CHAR (1)      NULL,
    [dt_base_pagto_comissao]    DATETIME      NULL,
    [dt_base_final_comissao]    DATETIME      NULL,
    [cd_tipo_comissao]          INT           NULL,
    [vl_piso_comissao_cobrador] FLOAT (53)    NULL,
    [vl_teto_comissao_cobrador] FLOAT (53)    NULL,
    [vl_salario_comis_cobrador] FLOAT (53)    NULL,
    [cd_insmunicipal_vendedor]  VARCHAR (18)  NULL,
    [cd_numero_endereco]        INT           NULL,
    [nm_complemento_endereco]   VARCHAR (40)  NULL,
    [qt_visita_diaria_cobrador] INT           NULL,
    [vl_meta]                   FLOAT (53)    NULL,
    [nm_ponto_ref_cobrador]     VARCHAR (100) NULL,
    CONSTRAINT [PK_Cobrador] PRIMARY KEY CLUSTERED ([cd_cobrador] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Cobrador_Banco] FOREIGN KEY ([cd_banco]) REFERENCES [dbo].[Banco] ([cd_banco]),
    CONSTRAINT [FK_Cobrador_Tipo_Pessoa] FOREIGN KEY ([cd_tipo_pessoa]) REFERENCES [dbo].[Tipo_Pessoa] ([cd_tipo_pessoa])
);

