CREATE TABLE [dbo].[Composicao_Standard_Material] (
    [cd_composicao_standard]  INT           NOT NULL,
    [cd_composicao_material]  INT           NOT NULL,
    [nm_composicao_material]  VARCHAR (50)  NULL,
    [cd_produto]              INT           NULL,
    [qt_composicao_material]  FLOAT (53)    NULL,
    [cd_fornecedor]           INT           NULL,
    [cd_materia_prima]        INT           NULL,
    [nm_marca]                VARCHAR (30)  NULL,
    [cd_unidade_medida]       INT           NULL,
    [cd_tipo_produto_projeto] INT           NULL,
    [cd_processo]             INT           NULL,
    [nm_desenho_material]     VARCHAR (50)  NULL,
    [nm_caminho_desenho]      VARCHAR (200) NULL,
    [cd_projetista]           INT           NULL,
    [ds_material]             TEXT          NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [ic_compra_prod_material] CHAR (1)      NULL,
    [ic_desgaste_material]    CHAR (1)      NULL,
    [ic_reposicao_material]   CHAR (1)      NULL,
    [ic_ativo_material]       CHAR (1)      NULL,
    CONSTRAINT [PK_Composicao_Standard_Material] PRIMARY KEY CLUSTERED ([cd_composicao_standard] ASC, [cd_composicao_material] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Composicao_Standard_Material_Materia_Prima] FOREIGN KEY ([cd_materia_prima]) REFERENCES [dbo].[Materia_Prima] ([cd_mat_prima]),
    CONSTRAINT [FK_Composicao_Standard_Material_Produto] FOREIGN KEY ([cd_produto]) REFERENCES [dbo].[Produto] ([cd_produto]),
    CONSTRAINT [FK_Composicao_Standard_Material_Projetista] FOREIGN KEY ([cd_projetista]) REFERENCES [dbo].[Projetista] ([cd_projetista]),
    CONSTRAINT [FK_Composicao_Standard_Material_Tipo_Produto_Projeto] FOREIGN KEY ([cd_tipo_produto_projeto]) REFERENCES [dbo].[Tipo_Produto_Projeto] ([cd_tipo_produto_projeto]),
    CONSTRAINT [FK_Composicao_Standard_Material_Unidade_Medida] FOREIGN KEY ([cd_unidade_medida]) REFERENCES [dbo].[Unidade_Medida] ([cd_unidade_medida])
);

