CREATE TABLE [dbo].[Concessionario_Beneficiario] (
    [cd_concessionario]        INT           NOT NULL,
    [cd_beneficiario]          INT           NOT NULL,
    [nm_beneficiario]          VARCHAR (50)  NULL,
    [nm_contato_beneficiario]  VARCHAR (50)  NULL,
    [cd_identifica_cep]        INT           NULL,
    [cd_cep]                   VARCHAR (9)   NULL,
    [nm_endereco_beneficiario] VARCHAR (50)  NULL,
    [nm_bairro_beneficiario]   VARCHAR (25)  NULL,
    [cd_pais]                  INT           NULL,
    [cd_estado]                INT           NULL,
    [cd_cidade]                INT           NULL,
    [cd_cpf_beneficiario]      VARCHAR (14)  NULL,
    [cd_rg_beneficiario]       VARCHAR (14)  NULL,
    [ds_beneficiario]          TEXT          NULL,
    [cd_usuario]               INT           NULL,
    [dt_usuario]               DATETIME      NULL,
    [cd_ddd_beneficiario]      VARCHAR (4)   NULL,
    [cd_telefone_beneficiario] VARCHAR (15)  NULL,
    [cd_fax_beneficiario]      VARCHAR (15)  NULL,
    [cd_celular_beneficiario]  VARCHAR (15)  NULL,
    [nm_email_beneficiario]    VARCHAR (40)  NULL,
    [dt_nasc_beneficiario]     DATETIME      NULL,
    [cd_numero_endereco]       VARCHAR (10)  NULL,
    [nm_complemento_endereco]  VARCHAR (30)  NULL,
    [nm_ponto_ref_conc_ender]  VARCHAR (100) NULL,
    CONSTRAINT [PK_Concessionario_Beneficiario] PRIMARY KEY CLUSTERED ([cd_concessionario] ASC, [cd_beneficiario] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Concessionario_Beneficiario_Cep] FOREIGN KEY ([cd_identifica_cep]) REFERENCES [dbo].[Cep] ([cd_identifica_cep])
);

