CREATE TABLE [dbo].[Concessionario] (
    [cd_conc]                INT          NOT NULL,
    [nm_conc]                VARCHAR (40) NOT NULL,
    [cd_sexo]                INT          NOT NULL,
    [cd_cep]                 VARCHAR (9)  NOT NULL,
    [nm_endereco_conc]       VARCHAR (40) NOT NULL,
    [nm_compl_end_conc]      VARCHAR (30) NULL,
    [cd_num_end_conc]        VARCHAR (10) NULL,
    [nm_bairro_conc]         VARCHAR (20) NULL,
    [nm_site_conc]           VARCHAR (40) NULL,
    [nm_email_conc]          VARCHAR (40) NULL,
    [cd_ddd_conc]            CHAR (4)     NULL,
    [nm_telefone_conc]       VARCHAR (30) NULL,
    [nm_compl_fone_conc]     VARCHAR (40) NULL,
    [nm_celular_conc]        VARCHAR (30) NULL,
    [cd_profissao]           INT          NOT NULL,
    [dt_nascto_conc]         DATETIME     NULL,
    [cd_cpf_conc]            CHAR (11)    NOT NULL,
    [cd_rg_conc]             VARCHAR (16) NULL,
    [cd_inscestadual_conc]   VARCHAR (18) NULL,
    [cd_nacional]            INT          NULL,
    [cd_estado_civil]        INT          NULL,
    [nm_corresp_conc]        VARCHAR (40) NULL,
    [cd_cep_corresp_conc]    VARCHAR (9)  NOT NULL,
    [nm_end_corresp_conc]    VARCHAR (40) NULL,
    [nm_bairro_corresp_conc] VARCHAR (20) NULL,
    [cd_ddd_corresp_conc]    VARCHAR (4)  NULL,
    [nm_tel_corresp_conc]    VARCHAR (30) NULL,
    [nm_rec_corresp_conc]    VARCHAR (40) NULL,
    [nm_cel_corresp_conc]    VARCHAR (30) NULL,
    [dt_cadastro_conc]       DATETIME     NULL,
    [ds_conc]                TEXT         NULL,
    [cd_usuario]             INT          NULL,
    [dt_usuario]             DATETIME     NULL,
    [nm_compl_corresp_conc]  VARCHAR (30) NULL,
    [cd_num_corresp_conc]    VARCHAR (10) NULL,
    [cd_cidade]              INT          NULL,
    [cd_estado]              INT          NULL,
    [cd_pais]                INT          NULL,
    [cd_nacionalidade]       INT          NULL,
    [cd_status_cliente]      INT          NULL,
    [nm_ponto_ref_conc]      VARCHAR (40) NULL,
    CONSTRAINT [PK_Concessionario] PRIMARY KEY CLUSTERED ([cd_conc] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Concessionario_Estado_Civil] FOREIGN KEY ([cd_estado_civil]) REFERENCES [dbo].[Estado_Civil] ([cd_estado_civil])
);

