CREATE TABLE [dbo].[condicao_pagamento_parcela_bkp] (
    [cd_condicao_parcela_pgto]  INT        NOT NULL,
    [cd_condicao_pagamento]     INT        NOT NULL,
    [pc_condicao_parcela_pgto]  FLOAT (53) NULL,
    [qt_dia_cond_parcela_pgto]  FLOAT (53) NULL,
    [ic_ipi_cond_parcela_pgto]  CHAR (1)   NULL,
    [cd_usuario]                INT        NULL,
    [dt_usuario]                DATETIME   NULL,
    [ic_custofin_cond_pagament] CHAR (1)   NULL,
    [qt_mes_parcela_pagto]      INT        NULL,
    [qt_dia_util_mes_parcela_p] INT        NULL,
    [cd_semana]                 INT        NULL,
    [ic_vctodia_parcela_pgto]   CHAR (1)   NULL,
    [ic_fora_semana_parcela_pg] CHAR (1)   NULL,
    [ic_liquido_parcela_pagto]  CHAR (1)   NULL,
    [dt_parcela_pgto]           DATETIME   NULL,
    [ic_vctoespecif_pagto_parc] CHAR (1)   NULL,
    [pc_parcela_condicao_pgto]  FLOAT (53) NULL,
    [qt_dia_parcela_cond_pgto]  FLOAT (53) NULL,
    [ic_ipi_parcela_cond_pgto]  CHAR (1)   NULL,
    [ic_custofin_cond_pgto]     CHAR (1)   NULL,
    [ic_dtvctoespecif_pgto_par] CHAR (1)   NULL,
    [ic_solicitadata_parc_pgto] CHAR (1)   NULL,
    [ic_liquido_parcela_pgto]   CHAR (1)   NULL,
    [qt_diautil_mes_parcela_pg] INT        NULL,
    [qt_mes_parcela_pgto]       INT        NULL,
    [ic_fora_parcela]           CHAR (1)   NULL,
    [qt_dia_fora_parcela]       INT        NULL
);

