CREATE TABLE [dbo].[Condicao_Pagamento] (
    [cd_condicao_pagamento]     INT           NOT NULL,
    [nm_condicao_pagamento]     VARCHAR (50)  NULL,
    [sg_condicao_pagamento]     CHAR (40)     NULL,
    [qt_parcela_condicao_pgto]  FLOAT (53)    NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [ic_ativo]                  CHAR (1)      NULL,
    [ic_limitcredit_cond_pagto] CHAR (1)      NULL,
    [cd_siscomex]               INT           NULL,
    [ic_importacao_cond_pagto]  CHAR (1)      NULL,
    [ic_tipo_cond_pagamento]    CHAR (1)      NULL,
    [ic_padrao_cond_pagamento]  CHAR (1)      NULL,
    [ic_importacao_cond_pgto]   CHAR (1)      NULL,
    [ic_limitcred_cond_pgto]    CHAR (1)      NULL,
    [ic_vctoespecif_pag_parce]  CHAR (1)      NULL,
    [ic_imprimir_sigla]         CHAR (1)      NULL,
    [ic_iss_cond_parcela_pagto] CHAR (1)      NULL,
    [ic_icm_cond_parcela_pagto] CHAR (1)      NULL,
    [ic_exige_financeira]       CHAR (1)      NULL,
    [sg_imp_condicao_pagamento] CHAR (2)      NULL,
    [sg_imp_cond_pagamento]     CHAR (2)      NULL,
    [ds_condicao_pagamento]     TEXT          NULL,
    [cd_tipo_mercado]           INT           NULL,
    [ic_antecipado]             CHAR (1)      NULL,
    [vl_minimo_cond_pagto]      FLOAT (53)    NULL,
    [vl_minimo_parcela]         FLOAT (53)    NULL,
    [cd_interface]              VARCHAR (15)  NULL,
    [cd_forma_condicao]         INT           NULL,
    [ic_exporta_cond_pagamento] CHAR (1)      NULL,
    [cd_plano_financeiro]       INT           NULL,
    [pc_acrescimo_parcela]      FLOAT (53)    NULL,
    [nm_descritivo_pagamento]   VARCHAR (500) NULL,
    CONSTRAINT [PK_Condicao_Pagamento] PRIMARY KEY CLUSTERED ([cd_condicao_pagamento] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Condicao_Pagamento_Tipo_Mercado] FOREIGN KEY ([cd_tipo_mercado]) REFERENCES [dbo].[Tipo_Mercado] ([cd_tipo_mercado])
);

