CREATE TABLE [dbo].[Config_Terminal_Venda] (
    [cd_empresa]                 INT          NOT NULL,
    [ic_registro_venda]          CHAR (1)     NULL,
    [ic_layout_terminal]         CHAR (1)     NULL,
    [ic_mostra_dados]            CHAR (1)     NULL,
    [nm_obs_terminal_venda]      VARCHAR (40) NULL,
    [cd_usuario]                 INT          NULL,
    [dt_usuario]                 DATETIME     NULL,
    [ic_altera_operador]         CHAR (1)     NULL,
    [ic_credito_caixa]           CHAR (1)     NULL,
    [ic_debito_caixa]            CHAR (1)     NULL,
    [ic_cheque_eletronico_caixa] CHAR (1)     NULL,
    [ic_devolucao_caixa]         CHAR (1)     NULL,
    [ic_desconto_caixa]          CHAR (1)     NULL,
    [ic_descricao]               CHAR (1)     NULL,
    [ic_item]                    CHAR (1)     NULL,
    [ic_unidade]                 CHAR (1)     NULL,
    [ic_entrega]                 CHAR (1)     NULL,
    [ic_cupom_fiscal]            CHAR (1)     NULL,
    [cd_senha_gaveta_caixa]      VARCHAR (10) NULL,
    [ic_gaveta_caixa]            CHAR (1)     NULL,
    [ic_estoque_caixa]           CHAR (1)     NULL,
    [ic_contrato]                CHAR (1)     NULL,
    [qt_casa_decimal_terminal]   INT          NULL,
    [ic_cancela_venda_terminal]  CHAR (1)     NULL,
    [ic_marca_produto]           CHAR (1)     NULL,
    [ic_valida_estoque_caixa]    CHAR (1)     NULL,
    [cd_impressora_ecf]          INT          NULL,
    [ic_saldo_produto]           CHAR (1)     NULL,
    [cd_fase_produto]            INT          NULL,
    CONSTRAINT [PK_Config_Terminal_Venda] PRIMARY KEY CLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Config_Terminal_Venda_Fase_Produto] FOREIGN KEY ([cd_fase_produto]) REFERENCES [dbo].[Fase_Produto] ([cd_fase_produto]),
    CONSTRAINT [FK_Config_Terminal_Venda_Impressora_ECF] FOREIGN KEY ([cd_impressora_ecf]) REFERENCES [dbo].[Impressora_ECF] ([cd_impressora_ecf])
);

