CREATE TABLE [dbo].[Consulta_Item_Orcamento_Alojamento] (
    [cd_consulta]               INT           NOT NULL,
    [cd_item_consulta]          INT           NOT NULL,
    [cd_item_orcamento]         INT           NOT NULL,
    [cd_item_alojamento]        INT           NOT NULL,
    [qt_alojamento]             INT           NULL,
    [ic_tipo_face_alojamento]   CHAR (1)      NULL,
    [ic_tipo_furo_alojamento]   CHAR (1)      NULL,
    [ic_raio_fundo_alojamento]  CHAR (1)      NULL,
    [ic_cabeca_alojamento]      CHAR (1)      NULL,
    [nm_alojamento]             VARCHAR (100) NULL,
    [qt_tempo_alojamento]       FLOAT (53)    NULL,
    [vl_alojamento]             FLOAT (53)    NULL,
    [nm_obs_alojamento]         VARCHAR (40)  NULL,
    [qt_tempo_acab_alojamento]  FLOAT (53)    NULL,
    [qt_tempo_desb_alojamento]  FLOAT (53)    NULL,
    [vl_acab_alojamento]        FLOAT (53)    NULL,
    [vl_desb_alojamento]        FLOAT (53)    NULL,
    [cd_tipo_mao_obra]          INT           NULL,
    [ic_tipo_mao_obra]          CHAR (1)      NULL,
    [qt_profundidade_aloj]      FLOAT (53)    NULL,
    [nm_medida_alojamento]      VARCHAR (50)  NULL,
    [qt_diametro_alojamento]    FLOAT (53)    NULL,
    [qt_largura_alojamento]     FLOAT (53)    NULL,
    [qt_comprimento_alojamento] FLOAT (53)    NULL,
    [qt_profundidade_cabeca]    FLOAT (53)    NULL,
    [nm_medida_cabeca]          VARCHAR (50)  NULL,
    [qt_diametro_cabeca]        FLOAT (53)    NULL,
    [qt_largura_cabeca]         FLOAT (53)    NULL,
    [qt_comprimento_cabeca]     FLOAT (53)    NULL,
    [ic_tipo_acab_alojamento]   CHAR (1)      NULL,
    [vl_custo_mandrilhadora]    FLOAT (53)    NULL,
    [qt_hora_mandrilhadora]     FLOAT (53)    NULL,
    [ic_alivio_alojamento]      CHAR (1)      NULL,
    [qt_altura_alivio_aloj]     FLOAT (53)    NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    CONSTRAINT [PK_Consulta_Item_Orcamento_Alojamento] PRIMARY KEY CLUSTERED ([cd_consulta] ASC, [cd_item_consulta] ASC, [cd_item_orcamento] ASC, [cd_item_alojamento] ASC) WITH (FILLFACTOR = 90)
);

