CREATE TABLE [dbo].[Consulta] (
    [cd_consulta]               INT          NOT NULL,
    [dt_consulta]               DATETIME     NULL,
    [cd_cliente]                INT          NULL,
    [cd_vendedor_interno]       INT          NULL,
    [cd_vendedor]               INT          NULL,
    [cd_contato]                INT          NULL,
    [cd_tipo_local_entrega]     INT          NULL,
    [vl_total_consulta]         FLOAT (53)   NULL,
    [ic_operacao_triangular]    CHAR (1)     NULL,
    [dt_alteracao_consulta]     DATETIME     NULL,
    [cd_tipo_endereco]          INT          NULL,
    [cd_pedido_compra_consulta] VARCHAR (40) NULL,
    [ic_fax_consulta]           CHAR (1)     NULL,
    [ic_email_consulta]         CHAR (1)     NULL,
    [cd_transportadora]         INT          NULL,
    [cd_destinacao_produto]     INT          NULL,
    [ds_observacao_consulta]    TEXT         NULL,
    [ic_fatsmo_consulta]        CHAR (1)     NULL,
    [hr_inicial_consulta]       DATETIME     NULL,
    [hr_final_consulta]         DATETIME     NULL,
    [ds_obs_fat_consulta]       TEXT         NULL,
    [cd_consulta_assinatura]    INT          NULL,
    [cd_consulta_representante] INT          NULL,
    [cd_moeda]                  INT          NULL,
    [dt_cambio_consulta]        DATETIME     NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_tipo_pagamento_frete]   INT          NULL,
    [vl_custo_financeiro]       FLOAT (53)   NULL,
    [ic_custo_financeiro]       CHAR (1)     NULL,
    [cd_cliente_fatura]         INT          NULL,
    [cd_cliente_entrega]        INT          NULL,
    [cd_condicao_pagamento]     INT          NULL,
    [cd_usuario_atendente]      INT          NULL,
    [ic_vendedor_interno]       CHAR (1)     NULL,
    [vl_tx_mensal_cust_fin]     FLOAT (53)   NULL,
    [ic_fechada_consulta]       CHAR (1)     NULL,
    [ic_fechamento_total]       CHAR (1)     NULL,
    [ic_outro_cliente]          CHAR (1)     NULL,
    [ic_pedido_venda]           CHAR (1)     NULL,
    [ic_digitacao]              CHAR (1)     NULL,
    [ic_transf_matriz]          CHAR (1)     NULL,
    [cd_representante]          INT          NULL,
    [cd_status_proposta]        INT          NULL,
    [nm_assina_consulta]        VARCHAR (40) NULL,
    [vl_total_ipi]              FLOAT (53)   NULL,
    [ic_obs_corpo_nf]           CHAR (1)     NULL,
    [dt_fechamento_consulta]    DATETIME     NULL,
    [cd_tipo_entrega_produto]   INT          NULL,
    [nm_referencia_consulta]    VARCHAR (40) NULL,
    [cd_tipo_atendimento]       INT          NULL,
    [cd_tipo_proposta]          INT          NULL,
    [cd_tipo_restricao_pedido]  INT          NULL,
    [ic_permite_agrupar_pedido] CHAR (1)     NULL,
    [vl_sedex_consulta]         FLOAT (53)   NULL,
    [pc_desconto_consulta]      FLOAT (53)   NULL,
    [ic_consignacao_consulta]   CHAR (1)     NULL,
    [ic_amostra_consulta]       CHAR (1)     NULL,
    [nm_contato_op_triang_con]  VARCHAR (30) NULL,
    [ic_credito_icms_consulta]  CHAR (1)     NULL,
    [dt_validade_consulta]      DATETIME     NULL,
    [vl_cambio_consulta]        FLOAT (53)   NULL,
    [cd_exportador]             INT          NULL,
    [nm_titulo_consulta]        VARCHAR (45) NULL,
    [cd_loja]                   INT          NULL,
    [cd_idioma]                 INT          NULL,
    [cd_aplicacao_produto]      INT          NULL,
    [ic_bloqueio_credito]       CHAR (1)     NULL,
    [ic_entrega_futura]         CHAR (1)     NULL,
    [dt_entrada_consulta]       DATETIME     NULL,
    [ic_bloqueio_licenca]       CHAR (1)     NULL,
    [cd_licenca_bloqueada]      INT          NULL,
    [cd_cliente_origem]         INT          NULL,
    [cd_projeto_mercado]        INT          NULL,
    [cd_fase_proposta]          INT          NULL,
    [ic_bonificacao_consulta]   CHAR (1)     NULL,
    [pc_comissao_consulta]      FLOAT (53)   NULL,
    [vl_icms_st]                FLOAT (53)   NULL,
    [vl_frete_consulta]         FLOAT (53)   NULL,
    [cd_identificacao_consulta] INT          NULL,
    CONSTRAINT [PK_Consulta] PRIMARY KEY CLUSTERED ([cd_consulta] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Consulta_Exportador] FOREIGN KEY ([cd_exportador]) REFERENCES [dbo].[Exportador] ([cd_exportador]),
    CONSTRAINT [FK_Consulta_Loja] FOREIGN KEY ([cd_loja]) REFERENCES [dbo].[Loja] ([cd_loja])
);


GO
CREATE NONCLUSTERED INDEX [ix_dt_consulta]
    ON [dbo].[Consulta]([dt_consulta] ASC) WITH (FILLFACTOR = 90);

