CREATE TABLE [dbo].[Consulta_Caract_Tecnica_Cq] (
    [cd_consulta]                 INT           NOT NULL,
    [cd_item_consulta]            INT           NOT NULL,
    [nm_produto_cliente]          VARCHAR (40)  NULL,
    [qt_peso_produto_consulta]    FLOAT (53)    NULL,
    [qt_espessura_parede]         FLOAT (53)    NULL,
    [qt_espessura_ponto_injecao]  FLOAT (53)    NULL,
    [qt_distancia_centros_x]      FLOAT (53)    NULL,
    [qt_distancia_centros_y]      FLOAT (53)    NULL,
    [ds_ponto_injecao_consulta]   TEXT          NULL,
    [ic_carga_consulta]           CHAR (1)      NULL,
    [pc_talco_consulta]           FLOAT (53)    NULL,
    [pc_fibra_vidro_consulta]     FLOAT (53)    NULL,
    [ic_troca_cor_consulta]       CHAR (1)      NULL,
    [ic_tipo_molde_consulta]      CHAR (1)      NULL,
    [qt_cavidade_consulta]        INT           NULL,
    [qt_bucha_consulta]           INT           NULL,
    [qt_diametro_anel_consulta]   FLOAT (53)    NULL,
    [qt_raio_bucha_consulta]      FLOAT (53)    NULL,
    [ic_elimina_galho_consulta]   CHAR (1)      NULL,
    [qt_angulo_acopla_consulta]   FLOAT (53)    NULL,
    [ds_observacao_produto]       TEXT          NULL,
    [ds_aplicacao_produto]        TEXT          NULL,
    [ic_porta_molde_cq]           CHAR (1)      NULL,
    [nm_comp_material_plastico]   VARCHAR (20)  NULL,
    [qt_tempo_projeto]            INT           NULL,
    [ic_desenho_produto]          CHAR (1)      NULL,
    [ic_desenho_molde_consulta]   CHAR (1)      NULL,
    [cd_material_plastico]        INT           NULL,
    [qt_espessura_p1]             FLOAT (53)    NULL,
    [qt_largura_molde_cq]         FLOAT (53)    NULL,
    [qt_comprimento_molde_cq]     FLOAT (53)    NULL,
    [ic_cota_controlador]         CHAR (1)      NULL,
    [qt_zonas_controlador]        INT           NULL,
    [qt_comprimento_bico]         INT           NULL,
    [ic_amostra_produto]          CHAR (1)      NULL,
    [nm_caminho_desenho]          VARCHAR (100) NULL,
    [qt_bicos_cavidade]           INT           NULL,
    [ic_cota_placas_hot_runner]   CHAR (1)      NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [qt_espes_ponto_injecao]      FLOAT (53)    NULL,
    [cd_tipo_sistema]             INT           NULL,
    [cd_numero_desenho_molde]     INT           NULL,
    [cd_ordem_servico_cliente]    VARCHAR (20)  NULL,
    [cd_tipo_manifold]            INT           NULL,
    [ic_padrao_conector]          CHAR (1)      NULL,
    [qt_voltagem_controlador]     FLOAT (53)    NULL,
    [qt_tampao_manifold]          INT           NULL,
    [qt_prep_usinagem_lateral]    INT           NULL,
    [qt_via_manifold]             INT           NULL,
    [qt_perimetro_perfil_externo] FLOAT (53)    NULL,
    [cd_produto_padrao_orcam]     INT           NULL,
    [ds_observacao_orcamento]     TEXT          NULL,
    [qt_peso_produto_string]      VARCHAR (20)  NULL,
    [qt_cavidade_string]          VARCHAR (10)  NULL,
    [cd_dias_uteis_entrega]       INT           NULL,
    [ds_observacao_entrega]       TEXT          NULL
);

