CREATE TABLE [dbo].[Consulta_Item_Componente] (
    [cd_consulta]               INT          NOT NULL,
    [cd_item_consulta]          INT          NOT NULL,
    [cd_item_comp_orcamento]    INT          NOT NULL,
    [cd_produto]                INT          NULL,
    [qt_item_comp_orcamento]    FLOAT (53)   NOT NULL,
    [ic_esp_comp_orcamento]     CHAR (1)     NULL,
    [nm_medacab_comp_orcam]     VARCHAR (30) NULL,
    [vl_custo_produto]          FLOAT (53)   NULL,
    [dt_custo_produto]          DATETIME     NULL,
    [vl_produto]                FLOAT (53)   NULL,
    [dt_produto]                DATETIME     NULL,
    [cd_categoria_produto]      INT          NULL,
    [nm_obs_comp_orcamento]     VARCHAR (40) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_orcamento_status]       CHAR (1)     NULL,
    [cd_base_concorrente]       INT          NULL,
    [cd_base_polimold]          INT          NULL,
    [qt_A1_item_orcamento]      FLOAT (53)   NULL,
    [qt_A2_item_orcamento]      FLOAT (53)   NULL,
    [qt_B1_item_orcamento]      FLOAT (53)   NULL,
    [qt_B2_item_orcamento]      INT          NULL,
    [qt_R_item_orcamento]       FLOAT (53)   NULL,
    [qt_F_item_orcamento]       FLOAT (53)   NULL,
    [qt_E1_item_orcamento]      INT          NULL,
    [qt_E2_item_orcamento]      INT          NULL,
    [qt_D1_item_orcamento]      INT          NULL,
    [qt_D2_item_orcamento]      INT          NULL,
    [qt_L_item_orcamento]       INT          NULL,
    [qt_classe_folga_item_orc]  FLOAT (53)   NULL,
    [cd_montagem]               INT          NULL,
    [nm_medacab_comp_orcamento] VARCHAR (30) NULL,
    [ic_componente_substituto]  CHAR (1)     NULL,
    [ds_produto_orcamento]      TEXT         NULL,
    [nm_produto_orcamento]      VARCHAR (50) NULL,
    [ic_acessorio_orcamento]    CHAR (1)     NULL,
    [nm_fantasia_componente]    VARCHAR (30) NULL,
    [ic_componente_agregado]    CHAR (1)     NULL,
    [nm_obs_componente]         VARCHAR (40) NULL,
    [cd_fornecedor]             INT          NULL,
    [cd_grupo_orcamento]        INT          NULL,
    [cd_categoria_orcamento]    INT          NULL,
    [ic_gera_cotacao]           CHAR (1)     NULL,
    [cd_requisicao_compra]      INT          NULL,
    [cd_item_requisicao_compra] INT          NULL,
    [cd_processo]               INT          NULL,
    [cd_unidade_medida]         INT          NULL,
    [cd_aplicacao_markup]       INT          NULL,
    [cd_tipo_lucro]             INT          NULL,
    [pc_icms_item_componente]   FLOAT (53)   NULL,
    [pc_ipi_item_componente]    FLOAT (53)   NULL,
    [pc_item_componente]        FLOAT (53)   NULL,
    [qt_dia_item_componente]    INT          NULL,
    [nm_obs_entrega_item]       VARCHAR (40) NULL,
    [nm_fornecedor_referencia]  VARCHAR (15) NULL,
    [pc_desconto_item]          FLOAT (53)   NULL,
    [pc_importacao_item]        FLOAT (53)   NULL,
    [vl_custo_item_componente]  FLOAT (53)   NULL,
    CONSTRAINT [PK_CdConsulta] PRIMARY KEY CLUSTERED ([cd_consulta] ASC, [cd_item_consulta] ASC, [cd_item_comp_orcamento] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Consulta_Item_Componente_Unidade_Medida] FOREIGN KEY ([cd_unidade_medida]) REFERENCES [dbo].[Unidade_Medida] ([cd_unidade_medida])
);

