CREATE TABLE [dbo].[Contador] (
    [cd_contador]             INT           NOT NULL,
    [nm_contador]             VARCHAR (60)  NULL,
    [nm_fantasia_contador]    VARCHAR (15)  NULL,
    [cd_crc_contador]         VARCHAR (25)  NOT NULL,
    [dt_crc_contador]         DATETIME      NULL,
    [cd_usuario]              INT           NOT NULL,
    [dt_usuario]              DATETIME      NOT NULL,
    [nm_email_contador]       VARCHAR (150) NULL,
    [cd_cpf_contador]         VARCHAR (14)  NULL,
    [cd_cnpj_contador]        VARCHAR (18)  NULL,
    [cd_identifica_cep]       INT           NULL,
    [cd_cep_contador]         INT           NULL,
    [nm_endereco_contador]    VARCHAR (60)  NULL,
    [cd_numero_endereco]      VARCHAR (10)  NULL,
    [nm_bairro_contador]      VARCHAR (25)  NULL,
    [nm_complemento_endereco] VARCHAR (40)  NULL,
    [cd_fone_contador]        VARCHAR (15)  NULL,
    [cd_fax_contador]         VARCHAR (15)  NULL,
    [cd_celular_contador]     VARCHAR (15)  NULL,
    [cd_pais]                 INT           NULL,
    [cd_estado]               INT           NULL,
    [cd_cidade]               INT           NULL,
    [nm_empresa_contador]     VARCHAR (60)  NULL,
    [cd_qualificacao]         INT           NULL,
    CONSTRAINT [PK_Contador] PRIMARY KEY NONCLUSTERED ([cd_contador] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Contador_Estado] FOREIGN KEY ([cd_estado]) REFERENCES [dbo].[Estado] ([cd_estado]),
    CONSTRAINT [FK_Contador_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Contador_SPED_Qualificacao_Assinante] FOREIGN KEY ([cd_qualificacao]) REFERENCES [dbo].[SPED_Qualificacao_Assinante] ([cd_qualificacao])
);

