CREATE TABLE [dbo].[Contrato_Compra] (
    [cd_contrato_compra]       INT          NOT NULL,
    [dt_contrato_compra]       DATETIME     NULL,
    [dt_vencimento_contrato]   DATETIME     NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [cd_identicacao_contrato]  VARCHAR (25) NULL,
    [ds_contrato_compra]       TEXT         NULL,
    [cd_fornecedor]            INT          NULL,
    [cd_contato_fornecedor]    INT          NULL,
    [dt_inicio_validade]       DATETIME     NULL,
    [dt_fim_validade]          DATETIME     NULL,
    [cd_comprador]             INT          NULL,
    [cd_condicao_pagamento]    INT          NULL,
    [cd_plano_compra]          INT          NULL,
    [cd_status_contrato]       INT          NULL,
    [cd_destinacao_produto]    INT          NULL,
    [cd_moeda]                 INT          NULL,
    [cd_transportadora]        INT          NULL,
    [cd_aplicacao_produto]     INT          NULL,
    [cd_tipo_pedido]           INT          NULL,
    [cd_centro_custo]          INT          NULL,
    [vl_total_contrato_compra] FLOAT (53)   NULL,
    [cd_tipo_local_entrega]    INT          NULL,
    [cd_plano_financeiro]      INT          NULL,
    [cd_local_entrega_empresa] INT          NULL,
    [cd_destinacao_compra]     INT          NULL,
    [cd_opcao_compra]          INT          NULL,
    [cd_tipo_pagamento_frete]  INT          NULL,
    CONSTRAINT [PK_Contrato_Compra] PRIMARY KEY CLUSTERED ([cd_contrato_compra] ASC) WITH (FILLFACTOR = 90)
);

