CREATE TABLE [dbo].[Conta_Agencia_Banco] (
    [cd_conta_banco]            INT          NOT NULL,
    [cd_empresa]                INT          NOT NULL,
    [cd_banco]                  INT          NOT NULL,
    [cd_agencia_banco]          INT          NOT NULL,
    [nm_conta_banco]            VARCHAR (30) NULL,
    [cd_contrato_conta_banco]   VARCHAR (30) NULL,
    [ic_cobranca_eletronica]    CHAR (1)     NULL,
    [cd_tipo_conta]             INT          NULL,
    [nm_contato_agencia_banco]  VARCHAR (30) NULL,
    [nm_obs_conta_agencia_banc] VARCHAR (50) NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [vl_limite_conta_banco]     FLOAT (53)   NULL,
    [cd_plano_financeiro]       INT          NULL,
    [ic_aplicacao_conta]        CHAR (1)     NULL,
    [ic_libera_documento]       CHAR (1)     NULL,
    [cd_moeda]                  INT          NULL,
    [cd_conta]                  INT          NULL,
    [cd_dac_conta_banco]        CHAR (1)     NULL,
    [ic_fluxo_caixa_conta]      CHAR (1)     NULL,
    [ic_limite_fluxo_caixa]     CHAR (1)     NULL,
    [ic_ativo_conta]            CHAR (1)     NULL,
    [nm_convenio_cobranca]      VARCHAR (30) NULL,
    [qt_posicao_convenio]       INT          NULL,
    [vl_taxa_desconto]          FLOAT (53)   NULL,
    [vl_taxa_custo_desconto]    FLOAT (53)   NULL,
    [vl_taxa_bordero_desconto]  FLOAT (53)   NULL,
    [vl_taxa_iof_desconto]      FLOAT (53)   NULL,
    CONSTRAINT [PK_Conta_Agencia_Banco] PRIMARY KEY CLUSTERED ([cd_conta_banco] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Conta_Agencia_Banco_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda])
);

