CREATE TABLE [dbo].[Contrato_Concessao] (
    [cd_categoria_contrato]    INT          NULL,
    [cd_tipo_contrato]         INT          NULL,
    [cd_status_contrato]       INT          NULL,
    [nm_nome_responsavel]      VARCHAR (50) NULL,
    [cd_cemiterio_quadra]      INT          NULL,
    [cd_bloco_ossario]         INT          NULL,
    [cd_contrato]              INT          NOT NULL,
    [nm_contrato_carac]        VARCHAR (10) NULL,
    [cd_cliente]               INT          NULL,
    [cd_cemiterio]             INT          NULL,
    [dt_cancelamento]          DATETIME     NULL,
    [ic_sepultado_contrato]    CHAR (1)     NULL,
    [ds_obs_contrato]          TEXT         NULL,
    [dt_lim_isenc_contrato]    DATETIME     NULL,
    [dt_negativ_contrato]      DATETIME     NULL,
    [dt_reabil_contrato]       DATETIME     NULL,
    [vl_divida_contrato]       FLOAT (53)   NULL,
    [ic_manut_aberto_conc]     CHAR (1)     NULL,
    [ic_parc_aberto_conc]      CHAR (1)     NULL,
    [qt_parc_atraso_contrato]  INT          NULL,
    [vl_parc_atraso_contr]     FLOAT (53)   NULL,
    [qt_manut_atraso_contr]    INT          NULL,
    [vl_manut_atraso_contr]    FLOAT (53)   NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [dt_contrato]              DATETIME     NULL,
    [cd_forma_pagamento]       INT          NULL,
    [cd_condicao_pagamento]    INT          NULL,
    [ic_ativo]                 CHAR (1)     NULL,
    [ic_manut_contr]           CHAR (1)     NULL,
    [cd_cemiterio_jazigo]      INT          NULL,
    [cd_cemiterio_rua_alameda] INT          NULL,
    [cd_tipo_contrato_manut]   INT          NULL,
    [ic_cliente_responsavel]   CHAR (1)     NULL,
    [cd_numero_ossario]        INT          NULL,
    [ic_isento]                CHAR (1)     NULL,
    [dt_carencia_contrato]     DATETIME     NULL,
    [dt_limite_isencao_contr]  DATETIME     NULL,
    CONSTRAINT [PK_Contrato_Concessao] PRIMARY KEY CLUSTERED ([cd_contrato] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Contrato_Concessao_Numero_Ossario] FOREIGN KEY ([cd_numero_ossario]) REFERENCES [dbo].[Numero_Ossario] ([cd_numero_ossario])
);

