CREATE TABLE [dbo].[Conta_Banco_Lancamento] (
    [cd_lancamento]            INT          NOT NULL,
    [dt_lancamento]            DATETIME     NULL,
    [vl_lancamento]            FLOAT (53)   NULL,
    [nm_historico_lancamento]  VARCHAR (45) NULL,
    [cd_conta_banco]           INT          NULL,
    [cd_plano_financeiro]      INT          NULL,
    [cd_tipo_operacao]         INT          NULL,
    [cd_historico_financeiro]  INT          NULL,
    [cd_moeda]                 INT          NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [cd_tipo_lancamento_fluxo] INT          NULL,
    [ic_lancamento_conciliado] CHAR (1)     NULL,
    [ic_transferencia_conta]   CHAR (1)     NULL,
    [cd_empresa]               INT          NULL,
    [cd_documento]             INT          NULL,
    [cd_documento_baixa]       INT          NULL,
    [cd_lancamento_padrao]     INT          NULL,
    [cd_documento_receber]     INT          NULL,
    [dt_contabilizacao]        DATETIME     NULL,
    [cd_lancamento_contabil]   INT          NULL,
    [cd_lote]                  INT          NULL,
    [cd_conta_credito]         INT          NULL,
    [cd_conta_debito]          INT          NULL,
    [cd_dac_conta_banco]       CHAR (1)     NULL,
    [ic_fluxo_caixa]           CHAR (1)     NULL,
    [ic_manual_lancamento]     CHAR (1)     NULL,
    [nm_compl_lancamento]      VARCHAR (45) NULL,
    CONSTRAINT [PK_Conta_Banco_Lancamento] PRIMARY KEY CLUSTERED ([cd_lancamento] ASC) WITH (FILLFACTOR = 90)
);

