CREATE TABLE [dbo].[Cotacao_Item] (
    [cd_cotacao]                INT          NOT NULL,
    [cd_item_cotacao]           INT          NOT NULL,
    [qt_item_cotacao]           FLOAT (53)   NULL,
    [nm_produto_item_cotacao]   VARCHAR (40) NULL,
    [cd_produto]                INT          NULL,
    [nm_marca_item_cotacao]     VARCHAR (20) NULL,
    [nm_ref_item_cotacao]       VARCHAR (20) NULL,
    [vl_item_cotacao]           FLOAT (53)   NULL,
    [pc_desconto_item_cotacao]  FLOAT (53)   NULL,
    [pc_ipi_item_cotacao]       FLOAT (53)   NULL,
    [pc_icms_item_cotacao]      FLOAT (53)   NULL,
    [cd_requisicao_compra]      INT          NULL,
    [cd_item_requisicao_compra] INT          NULL,
    [ic_retorno_item_cotacao]   CHAR (1)     NULL,
    [ic_ficha_item_cotacao]     CHAR (1)     NULL,
    [qt_fechada_item_cotacao]   FLOAT (53)   NULL,
    [qt_dia_item_cotacao]       FLOAT (53)   NULL,
    [dt_entrega_item_cotacao]   DATETIME     NULL,
    [cd_moeda]                  INT          NULL,
    [dt_cambio_item_cotacao]    DATETIME     NULL,
    [ds_item_cotacao]           TEXT         NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [ic_tipo_item]              VARCHAR (1)  NULL,
    [cd_unidade_medida]         INT          NULL,
    [ic_pedido_compra_cotacao]  CHAR (1)     NULL,
    [cd_maquina]                INT          NULL,
    [qt_bruto_item_cotacao]     FLOAT (53)   NULL,
    [qt_liquido_item_cotacao]   FLOAT (53)   NULL,
    [vl_indice_cotacao_compra]  FLOAT (53)   NULL,
    [ds_obs_item_cotacao]       TEXT         NULL,
    [cd_mascara_classificacao]  CHAR (10)    NULL,
    [ic_fechar_negocio]         CHAR (1)     NULL,
    [cd_servico]                INT          NULL,
    [vl_desconto_item_cotacao]  FLOAT (53)   NULL,
    [vl_fornecedor_moeda]       FLOAT (53)   NULL,
    [vl_convertido_moeda]       FLOAT (53)   NULL,
    [cd_opcao_compra]           INT          NULL,
    [cd_desenho_item_cotacao]   VARCHAR (30) NULL,
    [cd_rev_des_item_cotacao]   VARCHAR (5)  NULL,
    [cd_requisicao_viagem]      INT          NULL,
    [cd_item_requisicao_viagem] INT          NULL,
    CONSTRAINT [PK_Cotacao_Item] PRIMARY KEY CLUSTERED ([cd_cotacao] ASC, [cd_item_cotacao] ASC) WITH (FILLFACTOR = 90)
);

