CREATE TABLE [dbo].[Credenciado] (
    [nm_complemento_endereco] VARCHAR (30)  NULL,
    [sg_credenciado]          CHAR (10)     NULL,
    [cd_conta_corrente]       VARCHAR (20)  NULL,
    [cd_credenciado]          INT           NOT NULL,
    [nm_credenciado]          VARCHAR (50)  NULL,
    [nm_fantasia_credenciado] VARCHAR (15)  NULL,
    [cd_identifica_cep]       INT           NULL,
    [cd_cep]                  CHAR (9)      NULL,
    [nm_endereco_credenciado] VARCHAR (50)  NULL,
    [nm_bairro_credenciado]   VARCHAR (25)  NULL,
    [cd_pais]                 INT           NULL,
    [cd_estado]               INT           NULL,
    [cd_cidade]               INT           NULL,
    [cd_ddd_credenciado]      CHAR (4)      NULL,
    [cd_fone_credenciado]     VARCHAR (15)  NULL,
    [cd_fax_credenciado]      VARCHAR (15)  NULL,
    [cd_cnpj_credenciado]     VARCHAR (18)  NULL,
    [cd_inscEstadual]         VARCHAR (18)  NULL,
    [cd_inscMunicipal]        VARCHAR (18)  NULL,
    [nm_contato_credenciado]  VARCHAR (40)  NULL,
    [cd_regiao]               INT           NULL,
    [cd_numero_endereco]      INT           NULL,
    [dt_cadastro]             DATETIME      NULL,
    [nm_email_credenciado]    VARCHAR (100) NULL,
    [nm_logotipo_credenciado] VARCHAR (100) NULL,
    [cd_tipo_pessoa]          INT           NULL,
    [cd_banco]                INT           NULL,
    [cd_celular]              VARCHAR (15)  NULL,
    [cd_tipo_credenciado]     INT           NULL,
    [cd_agencia_banco]        VARCHAR (15)  NULL,
    [ds_perfil_credenciado]   TEXT          NULL,
    [ds_credenciado]          TEXT          NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    CONSTRAINT [PK_Credenciado] PRIMARY KEY CLUSTERED ([cd_credenciado] ASC) WITH (FILLFACTOR = 90)
);

