CREATE TABLE [dbo].[Di] (
    [cd_di]                   INT          NOT NULL,
    [cd_pedido_importacao]    INT          NULL,
    [nm_di]                   VARCHAR (20) NULL,
    [nm_bl_awb]               VARCHAR (20) NULL,
    [nm_h_bl_awb]             VARCHAR (20) NULL,
    [nm_refbancaria]          VARCHAR (30) NULL,
    [cd_consignatario]        INT          NULL,
    [dt_prev_desembaraco]     DATETIME     NULL,
    [dt_desembaraco]          DATETIME     NULL,
    [dt_validade_di]          DATETIME     NULL,
    [cd_notify]               INT          NULL,
    [cd_usuario]              INT          NULL,
    [dt_usuario]              DATETIME     NULL,
    [cd_despesa_padrao_comex] INT          NULL,
    [nm_fatcomercial]         VARCHAR (20) NULL,
    [dt_fatura_comercial]     DATETIME     NULL,
    [cd_transportadora]       INT          NULL,
    [cd_transitario]          INT          NULL,
    [cd_despachante]          INT          NULL,
    [cd_tipo_importacao]      INT          NULL,
    [nm_local_embarque]       VARCHAR (30) NULL,
    [dt_remessa_di]           DATETIME     NULL,
    [cd_porto]                INT          NULL,
    [cd_receita_federal]      INT          NULL,
    [nm_agencia_di]           VARCHAR (20) NULL,
    [nm_ref_despachante_di]   VARCHAR (20) NULL,
    [nm_navio_di]             VARCHAR (20) NULL,
    [cd_banco]                INT          NULL,
    [nm_agencia_cambio_di]    VARCHAR (20) NULL,
    [cd_tipo_risco_comex]     INT          NULL,
    [nm_cobertura_di]         VARCHAR (30) NULL,
    [cd_corretora_cambio]     INT          NULL,
    [dt_previsao_chegada_di]  DATETIME     NULL,
    [dt_chegada]              DATETIME     NULL,
    [dt_prev_chegada_fabrica] DATETIME     NULL,
    [dt_chegada_fabrica]      DATETIME     NULL,
    [dt_cancelamento_di]      DATETIME     NULL,
    [nm_cancelamento_di]      VARCHAR (40) NULL,
    [ds_observacao_di]        TEXT         NULL,
    [cd_tipo_embalagem]       INT          NULL,
    [qt_peso_bruto_di]        FLOAT (53)   NULL,
    [qt_peso_liquido_di]      FLOAT (53)   NULL,
    [vl_mercadoria_di]        FLOAT (53)   NULL,
    [pc_desconto_di]          FLOAT (53)   NULL,
    [vl_despesa_frete_di]     FLOAT (53)   NULL,
    [cd_tipo_seguro]          INT          NULL,
    [vl_seguro_internacional] FLOAT (53)   NULL,
    [vl_outras_despesas]      FLOAT (53)   NULL,
    [cd_tipo_frete]           INT          NULL,
    [cd_moeda_frete]          INT          NULL,
    [vl_frete_internacional]  FLOAT (53)   NULL,
    [vl_frete_nacional]       FLOAT (53)   NULL,
    [cd_moeda_seguro]         INT          NULL,
    [cd_seguradora]           INT          NULL,
    [nm_seguro_definitivo]    VARCHAR (20) NULL,
    [cd_fornecedor]           INT          NULL,
    [cd_embarque]             INT          NULL,
    [dt_bl_awb]               DATETIME     NULL,
    [vl_despesa_acessoria]    FLOAT (53)   NULL,
    [cd_status_di]            INT          NULL,
    [cd_termo_comercial]      INT          NULL,
    [cd_importador]           INT          NULL,
    [cd_moeda_di]             INT          NULL,
    [dt_moeda_di]             DATETIME     NULL,
    [vl_moeda_di]             FLOAT (53)   NULL,
    [vl_mercadoria_di_moeda]  FLOAT (53)   NULL,
    [dt_moeda_seguro]         DATETIME     NULL,
    [dt_embarque]             DATETIME     NULL,
    [cd_porto_destino]        INT          NULL,
    [dt_moeda_frete]          DATETIME     NULL,
    [vl_moeda_frete]          FLOAT (53)   NULL,
    [vl_embalagem_di]         FLOAT (53)   NULL,
    [qt_total_volume]         FLOAT (53)   NULL,
    [cd_condicao_pagamento]   INT          NULL,
    [dt_prev_embarque]        DATETIME     NULL,
    [vl_moeda_seguro]         FLOAT (53)   NULL,
    [vl_desp_aduaneira]       FLOAT (53)   NULL,
    [vl_seguro_nacional]      FLOAT (53)   NULL,
    [vl_paridade_moeda_di]    FLOAT (53)   NULL,
    [vl_aduaneiro_di]         FLOAT (53)   NULL,
    [vl_ii_di]                FLOAT (53)   NULL,
    [vl_ipi_di]               FLOAT (53)   NULL,
    [vl_despesa_di]           FLOAT (53)   NULL,
    [vl_pis_di]               FLOAT (53)   NULL,
    [vl_cofins_di]            FLOAT (53)   NULL,
    [dt_moeda_invoice]        DATETIME     NULL,
    [vl_moeda_invoice]        FLOAT (53)   NULL,
    [cd_moeda_invoice]        INT          NULL,
    [vl_capatazia_di]         FLOAT (53)   NULL,
    [vl_icms_di]              FLOAT (53)   NULL,
    [vl_siscomex_di]          FLOAT (53)   NULL,
    [dt_emissao_di]           DATETIME     NULL,
    [cd_tipo_canal_di]        INT          NULL,
    CONSTRAINT [PK_Di] PRIMARY KEY CLUSTERED ([cd_di] ASC) WITH (FILLFACTOR = 90)
);

