CREATE TABLE [dbo].[Diario_Veiculo] (
    [cd_diario_veiculo]         INT          NOT NULL,
    [nm_diario_veiculo]         VARCHAR (40) NULL,
    [dt_diario_veiculo]         DATETIME     NULL,
    [cd_veiculo]                INT          NOT NULL,
    [cd_motorista]              INT          NULL,
    [cd_area_entrega]           INT          NULL,
    [dt_entrega]                DATETIME     NULL,
    [dt_faturamento]            DATETIME     NULL,
    [dt_venda]                  DATETIME     NULL,
    [hr_saida_veiculo]          VARCHAR (8)  NULL,
    [hr_retorno_veiculo]        VARCHAR (8)  NULL,
    [hr_primeiro_cliente]       VARCHAR (8)  NULL,
    [hr_ultimo_cliente]         VARCHAR (8)  NULL,
    [dt_saida_veiculo]          DATETIME     NULL,
    [dt_entrada_veiculo]        DATETIME     NULL,
    [qt_hora_cliente]           FLOAT (53)   NULL,
    [qt_km_saida_veiculo]       FLOAT (53)   NULL,
    [qt_km_primeiro_cliente]    FLOAT (53)   NULL,
    [qt_km_ultimo_cliente]      FLOAT (53)   NULL,
    [qt_km_chegada_veiculo]     FLOAT (53)   NULL,
    [qt_km_total_diario]        FLOAT (53)   NULL,
    [qt_km_total_cliente]       FLOAT (53)   NULL,
    [qt_nota_diario]            FLOAT (53)   NULL,
    [qt_nota_devolucao_diario]  FLOAT (53)   NULL,
    [qt_caixa_diario]           FLOAT (53)   NULL,
    [qt_produto_diario]         FLOAT (53)   NULL,
    [qt_repasse_diario]         FLOAT (53)   NULL,
    [vl_total_diario]           FLOAT (53)   NULL,
    [vl_total_devolucao]        FLOAT (53)   NULL,
    [vl_frete_diario]           FLOAT (53)   NULL,
    [vl_credito_diario]         FLOAT (53)   NULL,
    [vl_debito_diario]          FLOAT (53)   NULL,
    [qt_tempo_perdido_diario]   FLOAT (53)   NULL,
    [nm_obs_diario]             VARCHAR (60) NULL,
    [ds_obs_diario]             TEXT         NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [qt_hora_diario]            FLOAT (53)   NULL,
    [cd_vendedor]               INT          NULL,
    [cd_mot_ocorrencia_veiculo] INT          NULL,
    CONSTRAINT [PK_Diario_Veiculo] PRIMARY KEY CLUSTERED ([cd_diario_veiculo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Diario_Veiculo_Vendedor] FOREIGN KEY ([cd_vendedor]) REFERENCES [dbo].[Vendedor] ([cd_vendedor])
);

