CREATE TABLE [dbo].[Distribuidor] (
    [cd_distribuidor]           INT          NOT NULL,
    [nm_distribuidor]           VARCHAR (40) NULL,
    [nm_fantasia_distribuidor]  VARCHAR (30) NULL,
    [pc_comissao_distribuidor]  FLOAT (53)   NULL,
    [pc_particip_distribuidor]  FLOAT (53)   NULL,
    [ds_area_atua_distribuidor] TEXT         NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_fax]                    VARCHAR (15) NULL,
    [cd_telefone]               VARCHAR (15) NULL,
    [cd_ddd]                    CHAR (4)     NULL,
    [cd_Pais]                   INT          NULL,
    [cd_estado]                 INT          NULL,
    [cd_cidade]                 INT          NULL,
    [nm_bairro]                 VARCHAR (25) NULL,
    [nm_complemento_endereco]   VARCHAR (30) NULL,
    [cd_numero_endereco]        CHAR (10)    NULL,
    [nm_endereco_distribuidor]  VARCHAR (60) NULL,
    [cd_cep]                    CHAR (9)     NULL,
    [cd_inscMunicipal]          VARCHAR (18) NULL,
    [cd_inscEstadual]           VARCHAR (18) NULL,
    [cd_cnpj_distribuidora]     VARCHAR (18) NULL,
    [cd_identifica_cep]         INT          NULL,
    [cd_tipo_pessoa]            INT          NULL,
    [nm_endereco_cliente]       VARCHAR (60) NULL,
    [ic_analise_distribuidor]   CHAR (1)     NULL,
    CONSTRAINT [pk_cd_distribuidor] PRIMARY KEY CLUSTERED ([cd_distribuidor] ASC) WITH (FILLFACTOR = 90)
);

