CREATE TABLE [dbo].[Documento_Qualidade] (
    [cd_documento_qualidade]     INT           NOT NULL,
    [cd_identificacao_documento] VARCHAR (20)  NOT NULL,
    [dt_documento_qualidade]     DATETIME      NULL,
    [nm_documento_qualidade]     VARCHAR (60)  NULL,
    [ds_documento_qualidade]     TEXT          NULL,
    [nm_caminho_documento]       VARCHAR (180) NULL,
    [cd_tipo_documento]          INT           NULL,
    [cd_usuario]                 INT           NULL,
    [dt_usuario]                 DATETIME      NULL,
    [cd_fase_documentacao]       INT           NULL,
    [cd_autor_documento]         INT           NULL,
    [cd_tipo_copia_documento]    INT           NULL,
    [cd_departamento]            INT           NULL,
    [cd_grupo_qualidade]         INT           NULL,
    [cd_categoria_qualidade]     INT           NULL,
    [cd_item_categoria]          INT           NULL,
    [cd_fase_documento]          INT           NULL,
    [cd_tipo_descarte]           INT           NULL,
    [cd_cliente]                 INT           NULL,
    [cd_planta]                  INT           NULL,
    [cd_origem_documento]        INT           NULL,
    [dt_revisao_documento]       DATETIME      NULL,
    [nm_ref_revisao_documento]   VARCHAR (15)  NULL,
    [cd_desenho_cliente]         VARCHAR (30)  NULL,
    [cd_produto]                 INT           NULL,
    [dt_validade_documento]      DATETIME      NULL,
    CONSTRAINT [PK_Documento_Qualidade] PRIMARY KEY CLUSTERED ([cd_documento_qualidade] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Documento_Qualidade_Cliente] FOREIGN KEY ([cd_cliente]) REFERENCES [dbo].[Cliente] ([cd_cliente]),
    CONSTRAINT [FK_Documento_Qualidade_Fase_Documento] FOREIGN KEY ([cd_fase_documento]) REFERENCES [dbo].[Fase_Documento] ([cd_fase_documento]),
    CONSTRAINT [FK_Documento_Qualidade_Produto] FOREIGN KEY ([cd_produto]) REFERENCES [dbo].[Produto] ([cd_produto]),
    CONSTRAINT [FK_Documento_Qualidade_Tipo_Descarte_Documento] FOREIGN KEY ([cd_tipo_descarte]) REFERENCES [dbo].[Tipo_Descarte_Documento] ([cd_tipo_descarte]),
    CONSTRAINT [FK_Documento_Qualidade_Tipo_Documento_Qualidade] FOREIGN KEY ([cd_tipo_documento]) REFERENCES [dbo].[Tipo_Documento_Qualidade] ([cd_tipo_documento])
);

