CREATE TABLE [dbo].[Embarque] (
    [cd_embarque]                 INT           NOT NULL,
    [cd_pedido_venda]             INT           NOT NULL,
    [nm_bl_awb]                   VARCHAR (20)  NULL,
    [nm_h_bl_awb]                 VARCHAR (20)  NULL,
    [nm_ref_bancaria]             VARCHAR (30)  NULL,
    [cd_consignatario]            INT           NULL,
    [cd_notify_1]                 INT           NULL,
    [cd_notify_2]                 INT           NULL,
    [cd_transportadora]           INT           NULL,
    [cd_despachante]              INT           NULL,
    [cd_porto_saida]              INT           NULL,
    [cd_receita_federal_despacho] INT           NULL,
    [cd_receita_federal_embarque] INT           NULL,
    [cd_receita_federal_entrega]  INT           NULL,
    [cd_banco_negociacao]         INT           NULL,
    [cd_conta_banco_negociacao]   INT           NULL,
    [cd_banco_cobranca]           INT           NULL,
    [cd_conta_banco_cobranca]     INT           NULL,
    [nm_cia_transporte]           VARCHAR (50)  NULL,
    [nm_navio_aviao]              VARCHAR (20)  NULL,
    [cd_tipo_risco_comex]         INT           NULL,
    [nm_cobertura]                VARCHAR (30)  NULL,
    [cd_corretora_cambio]         INT           NULL,
    [dt_previsao_embarque]        DATETIME      NULL,
    [dt_embarque]                 DATETIME      NULL,
    [dt_cancelamento_embarque]    DATETIME      NULL,
    [nm_cancelamento_embarque]    VARCHAR (40)  NULL,
    [cd_tipo_transporte]          INT           NULL,
    [nm_conhecimento_currier]     VARCHAR (20)  NULL,
    [nm_sacado_embarque]          VARCHAR (200) NULL,
    [cd_terminal_carga_retirada]  INT           NULL,
    [cd_terminal_carga_entrega]   INT           NULL,
    [nm_marca_numero_container]   VARCHAR (50)  NULL,
    [cd_tipo_embalagem]           INT           NULL,
    [qt_peso_bruto_embarque]      FLOAT (53)    NULL,
    [qt_peso_liquido_embarque]    FLOAT (53)    NULL,
    [qt_peso_net_embarque]        FLOAT (53)    NULL,
    [vl_mercadoria_embarque]      FLOAT (53)    NULL,
    [vl_desconto_embarque]        FLOAT (53)    NULL,
    [vl_frete_embarque]           FLOAT (53)    NULL,
    [vl_outra_despesa_embarque]   FLOAT (53)    NULL,
    [cd_seguradora]               INT           NULL,
    [vl_total_embarque]           FLOAT (53)    NULL,
    [cd_porto_destino]            INT           NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [cd_termo_comercial]          INT           NULL,
    [cd_moeda]                    INT           NULL,
    [cd_idioma]                   INT           NULL,
    [cd_condicao_pagamento]       INT           NULL,
    [cd_embarque_chave]           INT           NULL,
    [dt_previsao_chegada]         DATETIME      NULL,
    [dt_bl_awb]                   DATETIME      NULL,
    [vl_cobertura_seguro]         FLOAT (53)    NULL,
    [cd_moeda_seguro]             INT           NULL,
    [nm_seguro_provisorio]        VARCHAR (30)  NULL,
    [cd_moeda_frete]              INT           NULL,
    [cd_beneficiario]             INT           NULL,
    [nm_compl_01_container]       VARCHAR (50)  NULL,
    [nm_compl_02_container]       VARCHAR (50)  NULL,
    [nm_compl_03_container]       VARCHAR (50)  NULL,
    [ds_cond_pagto_embarque]      TEXT          NULL,
    [nm_obs_prazo_embarque]       VARCHAR (100) NULL,
    [cd_tipo_container]           INT           NULL,
    [ds_produto_item_embarque]    TEXT          NULL,
    [ds_obs_bancario]             TEXT          NULL,
    [ds_mensagem_packing_list]    TEXT          NULL,
    [nm_extenso]                  VARCHAR (255) NULL,
    [ds_informacao_adicional]     TEXT          NULL,
    [cd_governing_law]            INT           NULL,
    [cd_arbitration_clause]       INT           NULL,
    [cd_aux_termo_comercial]      INT           NULL,
    [nm_capacidade_embarque]      VARCHAR (40)  NULL,
    [qt_container_embarque]       INT           NULL,
    CONSTRAINT [PK_Embarque] PRIMARY KEY CLUSTERED ([cd_embarque] ASC, [cd_pedido_venda] ASC) WITH (FILLFACTOR = 90)
);

