CREATE TABLE [dbo].[Embarque_Importacao_Despesa] (
    [cd_pedido_importacao]     INT          NOT NULL,
    [cd_embarque]              INT          NOT NULL,
    [cd_item_despesa_embarque] INT          NOT NULL,
    [cd_tipo_despesa_comex]    INT          NULL,
    [dt_despesa_embarque]      DATETIME     NULL,
    [vl_despesa_embarque]      FLOAT (53)   NULL,
    [nm_obs_despesa_embarque]  VARCHAR (40) NULL,
    [cd_plano_financeiro]      INT          NULL,
    [cd_historico_financeiro]  INT          NULL,
    [nm_compl_historico]       VARCHAR (40) NULL,
    [ic_conversao_moeda]       CHAR (1)     NULL,
    [cd_moeda]                 INT          NULL,
    [dt_conversao_moeda]       DATETIME     NULL,
    [cd_movimento_financeiro]  INT          NULL,
    [ic_scp_despesa_embarque]  CHAR (1)     NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [cd_documento_pagar]       INT          NULL,
    [cd_empresa_diversa]       INT          NULL,
    [cd_favorecido_empresa]    INT          NULL,
    [dt_vencimento_despesa]    DATETIME     NULL,
    [cd_tipo_conta_pagar]      INT          NULL,
    [cd_centro_custo]          INT          NULL,
    [vl_tipo_despesa_comex]    FLOAT (53)   NULL,
    [vl_cotacao_moeda]         FLOAT (53)   NULL,
    CONSTRAINT [PK_Embarque_Importacao_Despesa] PRIMARY KEY CLUSTERED ([cd_pedido_importacao] ASC, [cd_embarque] ASC, [cd_item_despesa_embarque] ASC) WITH (FILLFACTOR = 90)
);

