CREATE TABLE [dbo].[Empresa_Diversa] (
    [cd_empresa_diversa]          INT           NOT NULL,
    [nm_empresa_diversa]          VARCHAR (50)  NOT NULL,
    [sg_empresa_diversa]          CHAR (10)     NOT NULL,
    [cd_usuario]                  INT           NULL,
    [dt_usuario]                  DATETIME      NULL,
    [cd_banco]                    INT           NULL,
    [cd_agencia_banco]            VARCHAR (15)  NULL,
    [cd_conta_corrente]           VARCHAR (20)  NULL,
    [ds_empresa_diversa]          TEXT          NULL,
    [cd_plano_financeiro]         INT           NULL,
    [nm_razao_social_empresa]     VARCHAR (60)  NULL,
    [cd_cnpj_empresa_diversa]     VARCHAR (14)  NULL,
    [cd_cidade_empresa_diversa]   INT           NULL,
    [cd_estado_empresa_diversa]   INT           NULL,
    [cd_pais_empresa_diversa]     INT           NULL,
    [nm_bairro_empresa_diversa]   VARCHAR (25)  NULL,
    [cd_numero_endereco]          INT           NULL,
    [nm_endereco_empresa_diversa] VARCHAR (50)  NULL,
    [cd_cep_empresa_diversa]      CHAR (9)      NULL,
    [cd_tipo_pessoa]              INT           NULL,
    [cd_conta]                    INT           NULL,
    [cd_ie_empresa_diversa]       VARCHAR (18)  NULL,
    [cd_ddd_empresa_diversa]      INT           NULL,
    [cd_fone_empresa_divesa]      VARCHAR (15)  NULL,
    [cd_fax_empresa_diversa]      VARCHAR (15)  NULL,
    [nm_contato_empresa_diversa]  VARCHAR (40)  NULL,
    [nm_site_empresa_diversa]     VARCHAR (100) NULL,
    [cd_pais]                     INT           NULL,
    [cd_estado]                   INT           NULL,
    [cd_cidade]                   INT           NULL,
    [cd_tipo_conta_pagar]         INT           NULL,
    [cd_tipo_documento]           INT           NULL,
    [cd_centro_custo]             INT           NULL,
    CONSTRAINT [PK_Empresa_Diversa] PRIMARY KEY CLUSTERED ([cd_empresa_diversa] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Empresa_Diversa_Centro_Custo] FOREIGN KEY ([cd_centro_custo]) REFERENCES [dbo].[Centro_Custo] ([cd_centro_custo]),
    CONSTRAINT [FK_Empresa_Diversa_Estado] FOREIGN KEY ([cd_estado]) REFERENCES [dbo].[Estado] ([cd_estado]),
    CONSTRAINT [FK_Empresa_Diversa_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Empresa_Diversa_Tipo_Conta_Pagar] FOREIGN KEY ([cd_tipo_conta_pagar]) REFERENCES [dbo].[Tipo_Conta_Pagar] ([cd_tipo_conta_pagar]),
    CONSTRAINT [FK_Empresa_Diversa_Tipo_Documento] FOREIGN KEY ([cd_tipo_documento]) REFERENCES [dbo].[Tipo_Documento] ([cd_tipo_documento])
);

