CREATE TABLE [dbo].[Empresa] (
    [cd_empresa]              INT           NOT NULL,
    [nm_empresa]              VARCHAR (50)  NULL,
    [nm_fantasia_empresa]     VARCHAR (30)  NULL,
    [nm_endereco_empresa]     VARCHAR (50)  NULL,
    [cd_cep_empresa]          INT           NULL,
    [cd_telefone_empresa]     VARCHAR (20)  NULL,
    [cd_fax_empresa]          VARCHAR (20)  NULL,
    [nm_dominio_internet]     VARCHAR (50)  NULL,
    [nm_email_internet]       VARCHAR (50)  NULL,
    [cd_cgc_empresa]          CHAR (14)     NULL,
    [cd_iest_empresa]         CHAR (20)     NULL,
    [cd_usuario]              INT           NULL,
    [dt_usuario]              DATETIME      NULL,
    [nm_caixa_postal]         CHAR (20)     NULL,
    [dt_fundacao_empresa]     DATETIME      NULL,
    [dt_cadastro_empresa]     DATETIME      NULL,
    [ds_empresa]              VARCHAR (50)  NULL,
    [cd_pais]                 INT           NOT NULL,
    [cd_estado]               INT           NOT NULL,
    [cd_cidade]               INT           NOT NULL,
    [cd_operadora]            INT           NULL,
    [cd_ramo_atividade]       INT           NULL,
    [nm_versao]               CHAR (10)     NULL,
    [nm_bairro_empresa]       VARCHAR (30)  NULL,
    [ic_default]              CHAR (1)      NULL,
    [nm_caminho_logo_empresa] VARCHAR (100) NULL,
    [ic_obs_proposta]         CHAR (1)      NULL,
    [ic_Carac_ISO9000]        CHAR (1)      NULL,
    [ic_msg_frete_proposta]   CHAR (1)      NULL,
    [ic_pessoa_proposta]      CHAR (10)     NULL,
    [cd_tipo_proposta]        INT           NULL,
    [cd_tipo_pessoa_proposta] INT           NULL,
    [ic_fax_ativo]            CHAR (1)      NULL,
    [ic_email_ativo]          CHAR (1)      NULL,
    [ic_plano_multi_lingua]   CHAR (1)      NULL,
    [ds_cartorio_empresa]     TEXT          NULL,
    [nm_inscricao_municipal]  VARCHAR (18)  NULL,
    [ic_imprimelogotipo]      CHAR (1)      NULL,
    [ic_imprimezebrado]       CHAR (1)      NULL,
    [ic_imprimeModelo]        CHAR (1)      NULL,
    [ic_imprimemensagem]      CHAR (1)      NULL,
    [ds_mensagemrel]          TEXT          NULL,
    [ic_grid_zebrado]         CHAR (1)      NULL,
    [ic_direcaomensagemrel]   CHAR (1)      NULL,
    [qt_minutoocioso]         INT           NULL,
    [vl_fat_minimo]           FLOAT (53)    NULL,
    [vl_lib_pedido_compra]    FLOAT (53)    NULL,
    [vl_tx_mensal_cust_fin]   FLOAT (53)    NULL,
    [qt_dias_uteis_env_ce]    FLOAT (53)    NULL,
    [qt_dias_nec_env_ce]      FLOAT (53)    NULL,
    [nm_FCgridzebrado]        VARCHAR (9)   NULL,
    [nm_BCgridzebrado]        VARCHAR (9)   NULL,
    [cd_ip_empresa]           VARCHAR (15)  NULL,
    [cd_ip_porta_empresa]     VARCHAR (6)   NULL,
    [ic_end_padrao_empresa]   CHAR (1)      NULL,
    [cd_http_empresa]         VARCHAR (15)  NULL,
    [cd_http_porta_empresa]   VARCHAR (6)   NULL,
    [cd_ftp_empresa]          VARCHAR (15)  NULL,
    [cd_ftp_porta_empresa]    VARCHAR (6)   NULL,
    [cd_seguro_empresa]       INT           NULL,
    [cd_seguro_porta_empresa] VARCHAR (6)   NULL,
    [cd_smtp_empresa]         VARCHAR (15)  NULL,
    [pc_juro_empresa]         FLOAT (53)    NULL,
    [cd_nota_debito_empresa]  INT           NULL,
    [vl_nota_debito_empresa]  FLOAT (53)    NULL,
    [pc_juro_nota_debito_emp] FLOAT (53)    NULL,
    [cd_smtp_porta_empresa]   VARCHAR (6)   NULL,
    [cd_end_padrao_empresa]   CHAR (1)      NULL,
    [ds_visao_empresa]        TEXT          NULL,
    [ds_missao_empresa]       TEXT          NULL,
    [cd_clf_empresa]          VARCHAR (15)  NULL,
    [cd_grupo_mapa_policial]  INT           NULL,
    [cd_reg_exercito_empresa] VARCHAR (15)  NULL,
    [dt_reg_exercito_empresa] DATETIME      NULL,
    CONSTRAINT [PK_Empresa] PRIMARY KEY NONCLUSTERED ([cd_empresa] ASC) WITH (FILLFACTOR = 90)
);

