CREATE TABLE [dbo].[Evento_Folha] (
    [cd_evento]                    INT          NOT NULL,
    [nm_evento]                    VARCHAR (40) NULL,
    [sg_evento]                    CHAR (10)    NULL,
    [vl_fator_evento]              FLOAT (53)   NULL,
    [nm_obs_evento]                VARCHAR (40) NULL,
    [ds_evento]                    TEXT         NULL,
    [cd_tipo_evento]               INT          NULL,
    [cd_natureza_evento]           INT          NULL,
    [cd_tipo_calculo_evento]       INT          NULL,
    [cd_usuario]                   INT          NULL,
    [dt_usuario]                   DATETIME     NULL,
    [cd_lancamento_padrao]         INT          NULL,
    [ic_demo_pag_evento]           CHAR (1)     NULL,
    [cd_plano_financeiro]          INT          NULL,
    [ic_movimento_evento]          CHAR (1)     NULL,
    [ic_automatico_evento]         CHAR (1)     NULL,
    [ic_salario_evento]            CHAR (1)     NULL,
    [ic_reajuste_evento]           CHAR (1)     NULL,
    [ic_gera_scp]                  CHAR (1)     NULL,
    [cd_conta]                     INT          NULL,
    [cd_tipo_documento]            INT          NULL,
    [cd_tipo_conta_pagar]          INT          NULL,
    [ic_gera_desconto]             CHAR (1)     NULL,
    [cd_evento_desconto]           INT          NULL,
    [cd_tipo_calculo_folha]        INT          NULL,
    [qt_prioridade_evento]         INT          NULL,
    [cd_roteiro_calculo]           INT          NULL,
    [ic_dirf_evento]               CHAR (1)     NULL,
    [ic_rais_evento]               CHAR (1)     NULL,
    [ic_fixo_evento]               CHAR (1)     NULL,
    [ic_calculo_lancamento_evento] CHAR (1)     NULL,
    CONSTRAINT [PK_Evento_Folha] PRIMARY KEY CLUSTERED ([cd_evento] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Evento_Folha_Evento_Folha] FOREIGN KEY ([cd_evento_desconto]) REFERENCES [dbo].[Evento_Folha] ([cd_evento]),
    CONSTRAINT [FK_Evento_Folha_Lancamento_Padrao] FOREIGN KEY ([cd_lancamento_padrao]) REFERENCES [dbo].[Lancamento_Padrao] ([cd_lancamento_padrao]),
    CONSTRAINT [FK_Evento_Folha_Roteiro_Calculo_Folha] FOREIGN KEY ([cd_roteiro_calculo]) REFERENCES [dbo].[Roteiro_Calculo_Folha] ([cd_roteiro_calculo]),
    CONSTRAINT [FK_Evento_Folha_Tipo_Calculo_Evento] FOREIGN KEY ([cd_tipo_calculo_evento]) REFERENCES [dbo].[Tipo_Calculo_Evento] ([cd_tipo_calculo_evento]),
    CONSTRAINT [FK_Evento_Folha_Tipo_Calculo_Folha] FOREIGN KEY ([cd_tipo_calculo_folha]) REFERENCES [dbo].[Tipo_Calculo_Folha] ([cd_tipo_calculo_folha]),
    CONSTRAINT [FK_Evento_Folha_Tipo_Conta_Pagar] FOREIGN KEY ([cd_tipo_conta_pagar]) REFERENCES [dbo].[Tipo_Conta_Pagar] ([cd_tipo_conta_pagar]),
    CONSTRAINT [FK_Evento_Folha_Tipo_Documento] FOREIGN KEY ([cd_tipo_documento]) REFERENCES [dbo].[Tipo_Documento] ([cd_tipo_documento])
);

