CREATE TABLE [dbo].[Evento] (
    [nm_endereco_evento]       VARCHAR (40) NULL,
    [nm_naturalidade]          VARCHAR (40) NULL,
    [cd_cemiterio_quadra]      INT          NULL,
    [cd_evento]                INT          NOT NULL,
    [cd_contrato]              INT          NOT NULL,
    [nm_falecido_evento]       VARCHAR (40) NULL,
    [dt_falecimento_evento]    DATETIME     NULL,
    [dt_sepultamento_evento]   DATETIME     NULL,
    [dt_nascimento_evento]     DATETIME     NULL,
    [dt_exumacao_evento]       DATETIME     NULL,
    [qt_idade_evento]          INT          NULL,
    [cd_profissao]             INT          NULL,
    [cd_sexo]                  INT          NULL,
    [cd_cor_pele]              INT          NULL,
    [cd_estado_civil]          INT          NULL,
    [cd_nacionalidade]         INT          NULL,
    [nm_pai_evento]            VARCHAR (40) NULL,
    [nm_mae_evento]            VARCHAR (40) NULL,
    [cd_causa_morte]           INT          NULL,
    [cd_livro_evento]          VARCHAR (10) NULL,
    [cd_folha_evento]          VARCHAR (10) NULL,
    [cd_numero_evento]         VARCHAR (10) NULL,
    [cd_cartorio]              INT          NULL,
    [nm_declarante_evento]     VARCHAR (40) NULL,
    [cd_parentesco]            INT          NULL,
    [cd_cep]                   VARCHAR (10) NULL,
    [nm_bairro_evento]         VARCHAR (30) NULL,
    [nm_fone_evento]           VARCHAR (30) NULL,
    [nm_local_obito_evento]    VARCHAR (30) NULL,
    [cd_funcionario]           INT          NULL,
    [cd_situacao_evento]       INT          NULL,
    [nm_transl_de_evento]      VARCHAR (40) NULL,
    [nm_transl_para_evento]    VARCHAR (40) NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [cd_medico]                INT          NULL,
    [cd_cidade]                INT          NULL,
    [cd_estado]                INT          NULL,
    [cd_pais]                  INT          NULL,
    [cd_numero_endereco]       INT          NULL,
    [cd_cemiterio]             INT          NULL,
    [cd_cemiterio_rua_alameda] INT          NULL,
    [cd_cemiterio_jazigo]      INT          NULL,
    [cd_cemiterio_gaveta]      INT          NULL,
    [ic_situacao_evento]       CHAR (1)     NULL,
    CONSTRAINT [PK_Evento] PRIMARY KEY CLUSTERED ([cd_evento] ASC, [cd_contrato] ASC) WITH (FILLFACTOR = 90)
);

