CREATE TABLE [dbo].[EVOLUCAO_CONSUMO] (
    [Sel]                       INT            NULL,
    [cd_produto]                INT            NOT NULL,
    [cd_mascara_produto]        VARCHAR (20)   NULL,
    [Comprar]                   VARCHAR (1)    NOT NULL,
    [EstNeg]                    VARCHAR (1)    NOT NULL,
    [ReservaMReal]              VARCHAR (1)    NOT NULL,
    [nm_fantasia_produto]       VARCHAR (30)   NULL,
    [nm_produto]                VARCHAR (50)   NULL,
    [cd_unidade_medida]         INT            NULL,
    [nm_unidade_medida]         VARCHAR (30)   NULL,
    [cd_categoria_produto]      INT            NULL,
    [qt_peso_liquido]           FLOAT (53)     NULL,
    [qt_peso_bruto]             FLOAT (53)     NULL,
    [nm_grupo_produto]          VARCHAR (40)   NULL,
    [Kogo]                      CHAR (1)       NOT NULL,
    [qt_evolucao_produto]       FLOAT (53)     NOT NULL,
    [nm_marca_produto]          VARCHAR (30)   NULL,
    [ic_producao_produto]       CHAR (1)       NOT NULL,
    [ic_compra_produto]         CHAR (1)       NOT NULL,
    [Qtd_Minimo]                FLOAT (53)     NULL,
    [qt_saldo_entreposto]       FLOAT (53)     NOT NULL,
    [Dt_Prev_Entrada1]          DATETIME       NULL,
    [Qtd_Prev_Entrada1]         FLOAT (53)     NULL,
    [Dt_Prev_Entrada2]          DATETIME       NULL,
    [Qtd_Prev_Entrada2]         FLOAT (53)     NULL,
    [Dt_Prev_Entrada3]          DATETIME       NULL,
    [Qtd_Prev_Entrada3]         FLOAT (53)     NULL,
    [Saldo_Disponivel]          FLOAT (53)     NULL,
    [Saldo_Atual]               FLOAT (53)     NOT NULL,
    [Qtd_Requisitada]           FLOAT (53)     NULL,
    [Qtd_Comprada]              FLOAT (53)     NULL,
    [Qtd_Producao]              FLOAT (53)     NOT NULL,
    [Qtd_Maximo]                FLOAT (53)     NULL,
    [Qtd_Prevista_PC]           FLOAT (53)     NULL,
    [Qtd_Lote_Compra]           FLOAT (53)     NULL,
    [Qtd_Padrao_Compra]         FLOAT (53)     NULL,
    [vl_custo_contabil_produto] FLOAT (53)     NULL,
    [vl_fob_produto]            FLOAT (53)     NULL,
    [vl_fob_convertido]         FLOAT (53)     NULL,
    [JANEIRO]                   FLOAT (53)     NULL,
    [FEVEREIRO]                 FLOAT (53)     NULL,
    [MARCO]                     FLOAT (53)     NULL,
    [ABRIL]                     FLOAT (53)     NULL,
    [MAIO]                      FLOAT (53)     NULL,
    [JUNHO]                     FLOAT (53)     NULL,
    [JULHO]                     FLOAT (53)     NULL,
    [AGOSTO]                    FLOAT (53)     NULL,
    [SETEMBRO]                  FLOAT (53)     NULL,
    [OUTUBRO]                   FLOAT (53)     NULL,
    [NOVEMBRO]                  FLOAT (53)     NULL,
    [DEZEMBRO]                  FLOAT (53)     NULL,
    [vlr_custo_unit]            NUMERIC (8, 2) NULL,
    [Vlr_Custo_Total]           FLOAT (53)     NULL,
    [MesesComConsumo]           INT            NULL,
    [Frequencia]                VARCHAR (5)    NULL,
    [X_Trim]                    FLOAT (53)     NULL,
    [X_Anual]                   FLOAT (53)     NULL,
    [qtd_est_compra]            FLOAT (53)     NULL,
    [qtd_est_producao]          FLOAT (53)     NULL,
    [cd_pais_origem]            INT            NULL,
    [Origem]                    VARCHAR (40)   NULL,
    [Ultima_Venda]              DATETIME       NULL,
    [Fornecedor]                CHAR (30)      NULL,
    [Carteira]                  FLOAT (53)     NULL,
    [PrevCompra]                FLOAT (53)     NULL,
    [PrevImportacao]            FLOAT (53)     NULL,
    [TotalCompra]               FLOAT (53)     NULL,
    [Qtd_Pedido_Imp]            FLOAT (53)     NOT NULL,
    [Qtd_Req_Total]             FLOAT (53)     NULL,
    [Qtd_Contrato]              INT            NULL,
    [Ultima_Entrada]            DATETIME       NULL,
    [Qtd_Perda]                 FLOAT (53)     NULL,
    [Qtd_Ultima_Entrada]        FLOAT (53)     NULL,
    [MEDIA_CONSUMO]             FLOAT (53)     NULL,
    [Duracao]                   FLOAT (53)     NULL,
    [Alocado]                   FLOAT (53)     NULL,
    [cd_part_number_produto]    VARCHAR (30)   NULL,
    [vl_produto_importacao]     FLOAT (53)     NOT NULL,
    [qt_previsao_venda]         FLOAT (53)     NULL,
    [qt_proposta]               FLOAT (53)     NULL,
    [qt_faturada]               FLOAT (53)     NULL,
    [nm_categoria_produto]      VARCHAR (40)   NOT NULL,
    [qtd_reservado_estoque]     FLOAT (53)     NOT NULL,
    [nm_fase_produto]           VARCHAR (30)   NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_Evolucao_Consumo]
    ON [dbo].[EVOLUCAO_CONSUMO]([cd_produto] ASC);

