CREATE TABLE [dbo].[Exportador] (
    [cd_exportador]             INT           NOT NULL,
    [nm_fantasia]               VARCHAR (15)  NOT NULL,
    [nm_razao_social]           VARCHAR (60)  NULL,
    [nm_dominio]                VARCHAR (50)  NULL,
    [dt_cadastro]               DATETIME      NULL,
    [ds_prestador_servico]      TEXT          NULL,
    [cd_banco]                  INT           NULL,
    [cd_agencia_banco]          VARCHAR (15)  NULL,
    [cd_conta_banco]            VARCHAR (20)  NULL,
    [cd_tipo_pessoa]            INT           NULL,
    [cd_fax]                    VARCHAR (15)  NULL,
    [cd_telefone]               VARCHAR (15)  NULL,
    [cd_ddd]                    CHAR (4)      NULL,
    [cd_pais]                   INT           NULL,
    [nm_bairro]                 VARCHAR (25)  NULL,
    [nm_complemento_endereco]   VARCHAR (100) NULL,
    [cd_numero_endereco]        CHAR (10)     NULL,
    [nm_endereco]               VARCHAR (100) NULL,
    [cd_cep]                    CHAR (9)      NULL,
    [cd_inscmunicipal]          VARCHAR (18)  NULL,
    [cd_inscestadual]           VARCHAR (18)  NULL,
    [cd_cnpj]                   VARCHAR (18)  NULL,
    [cd_identifica_cep]         INT           NULL,
    [cd_siscomex]               INT           NULL,
    [cd_usuario]                INT           NULL,
    [dt_usuario]                DATETIME      NULL,
    [cd_cidade]                 INT           NULL,
    [cd_estado]                 INT           NULL,
    [nm_contato]                VARCHAR (50)  NULL,
    [nm_logotipo]               VARCHAR (100) NULL,
    [ds_perfil]                 TEXT          NULL,
    [ds_exportador]             TEXT          NULL,
    [ic_pad_exportador]         CHAR (1)      NULL,
    [cd_porto]                  INT           NULL,
    [cd_moeda]                  INT           NULL,
    [cd_tipo_mercado]           INT           NULL,
    [ds_exportador_endereco]    TEXT          NULL,
    [nm_cidade_mercado_externo] VARCHAR (60)  NULL,
    [sg_estado_mercado_externo] VARCHAR (10)  NULL,
    [nm_pais_mercado_externo]   VARCHAR (60)  NULL,
    CONSTRAINT [PK_Exportador] PRIMARY KEY CLUSTERED ([cd_exportador] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Exportador_Banco] FOREIGN KEY ([cd_banco]) REFERENCES [dbo].[Banco] ([cd_banco]),
    CONSTRAINT [FK_Exportador_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda]),
    CONSTRAINT [FK_Exportador_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Exportador_Porto] FOREIGN KEY ([cd_porto]) REFERENCES [dbo].[Porto] ([cd_porto]),
    CONSTRAINT [FK_Exportador_Tipo_Pessoa] FOREIGN KEY ([cd_tipo_pessoa]) REFERENCES [dbo].[Tipo_Pessoa] ([cd_tipo_pessoa])
);

