CREATE TABLE [dbo].[Ferramenta] (
    [cd_ferramenta]                   INT           NOT NULL,
    [cd_grupo_ferramenta]             INT           NOT NULL,
    [nm_ferramenta]                   VARCHAR (60)  NOT NULL,
    [nm_fantasia_ferramenta]          VARCHAR (30)  NULL,
    [qt_diametro_ferramenta]          FLOAT (53)    NULL,
    [cd_num_ferramenta]               INT           NULL,
    [sg_ferramenta]                   VARCHAR (15)  NULL,
    [cd_usuario]                      INT           NULL,
    [dt_usuario]                      DATETIME      NULL,
    [qt_faca_ferramenta]              INT           NULL,
    [vl_comprimento_util_ferramenta]  FLOAT (53)    NULL,
    [vl_comprimento_total_ferramenta] FLOAT (53)    NULL,
    [vl_profundidade_corte]           FLOAT (53)    NULL,
    [vl_largura_corte_ferramenta]     FLOAT (53)    NULL,
    [vl_raio_ferramenta]              FLOAT (53)    NULL,
    [vl_angulo_ponta_ferramenta]      FLOAT (53)    NULL,
    [im_ferramenta]                   VARCHAR (100) NULL,
    [ds_ferramenta]                   TEXT          NULL,
    [cd_tipo_ferramenta]              INT           NULL,
    [cd_forma_ferramenta]             INT           NULL,
    [cd_refrig_ferramenta]            INT           NULL,
    [cd_grupo_produto]                INT           NULL,
    [cd_produto]                      INT           NULL,
    [cd_oleo_refrigerante]            INT           NULL,
    [cd_mat_prima]                    INT           NULL,
    [cd_tipo_iso_maquina]             INT           NULL,
    [nm_caminho_ferramenta]           VARCHAR (100) NULL,
    [vl_diametro]                     FLOAT (53)    NULL,
    [qt_facas]                        FLOAT (53)    NULL,
    [vl_comp_corte]                   FLOAT (53)    NULL,
    [vl_prof_corte]                   FLOAT (53)    NULL,
    [vl_larg_corte]                   FLOAT (53)    NULL,
    [cd_fornecedor]                   INT           NULL,
    [vl_raio_canto]                   FLOAT (53)    NULL,
    [vl_angulo_ponta]                 FLOAT (53)    NULL,
    [vl_passo_macho]                  FLOAT (53)    NULL,
    [vl_avanco_retracao]              FLOAT (53)    NULL,
    [vl_diametro_piloto]              FLOAT (53)    NULL,
    [vl_diametro_mandril]             FLOAT (53)    NULL,
    [vl_comp_mandril]                 FLOAT (53)    NULL,
    [vl_diametro_haste]               FLOAT (53)    NULL,
    [vl_comp_total]                   FLOAT (53)    NULL,
    [vl_avanco_faca]                  FLOAT (53)    NULL,
    [vl_rotacao]                      FLOAT (53)    NULL,
    [vl_avanco_trabalho]              FLOAT (53)    NULL,
    [vl_vida_util]                    FLOAT (53)    NULL,
    [vl_avanco_mergulho]              FLOAT (53)    NULL,
    [vl_comprimento_total_ferrament]  FLOAT (53)    NULL,
    [cd_identificacao_ferramenta]     VARCHAR (30)  NULL,
    [cd_desenho_ferramenta]           VARCHAR (30)  NULL,
    [cd_rev_desenho_ferramenta]       VARCHAR (5)   NULL,
    [cd_local_ferramenta]             INT           NULL,
    [nm_obs_ferramenta]               VARCHAR (40)  NULL,
    CONSTRAINT [PK_Ferramenta] PRIMARY KEY CLUSTERED ([cd_ferramenta] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK__Ferrament__cd_gr__3AA1AEB8] FOREIGN KEY ([cd_grupo_ferramenta]) REFERENCES [dbo].[Grupo_Ferramenta] ([cd_grupo_ferramenta]),
    CONSTRAINT [FK_Ferramenta_Local_Ferramenta] FOREIGN KEY ([cd_local_ferramenta]) REFERENCES [dbo].[Local_Ferramenta] ([cd_local_ferramenta])
);


GO
CREATE NONCLUSTERED INDEX [_WA_Sys_cd_ferramenta_2B947552]
    ON [dbo].[Ferramenta]([cd_ferramenta] ASC) WITH (FILLFACTOR = 90);

