CREATE TABLE [dbo].[Ficha_Medida_Composicao] (
    [cd_ficha_medida]           INT          NOT NULL,
    [cd_item_ficha_medida]      INT          NOT NULL,
    [cd_item_requisicao_compra] INT          NULL,
    [cd_mat_prima]              INT          NULL,
    [qt_item_ficha_medida]      FLOAT (53)   NULL,
    [ic_redondo_ficha_medida]   CHAR (1)     NULL,
    [nm_medacab_ficha_medida]   VARCHAR (30) NULL,
    [qt_espesacab_ficha_medida] FLOAT (53)   NULL,
    [qt_largacab_ficha_medida]  FLOAT (53)   NULL,
    [qt_compacab_ficha_medida]  FLOAT (53)   NULL,
    [nm_medbruta_ficha_medida]  VARCHAR (30) NULL,
    [qt_espesbruta_ficha_med]   FLOAT (53)   NULL,
    [qt_largbruta_ficha_medida] FLOAT (53)   NULL,
    [qt_compbruto_ficha_medida] FLOAT (53)   NULL,
    [nm_medret_ficha_medida]    VARCHAR (30) NULL,
    [qt_espesret_ficha_medida]  FLOAT (53)   NULL,
    [qt_largret_ficha_medida]   FLOAT (53)   NULL,
    [qt_compret_ficha_medida]   FLOAT (53)   NULL,
    [qt_tolespesacab_ficha_med] FLOAT (53)   NULL,
    [qt_tollargacab_ficha_med]  FLOAT (53)   NULL,
    [qt_tolcompacab_ficha_med]  FLOAT (53)   NULL,
    [qt_tolespesret_ficha_med]  FLOAT (53)   NULL,
    [qt_tollargret_ficha_med]   FLOAT (53)   NULL,
    [qt_tolcompret_ficha_med]   FLOAT (53)   NULL,
    [cd_usuario]                INT          NULL,
    [dt_usuario]                DATETIME     NULL,
    [cd_produto]                INT          NULL,
    [qt_liquido_ficha_medida]   FLOAT (53)   NULL,
    [qt_bruto_ficha_medida]     FLOAT (53)   NULL,
    [nm_obs_ficha_medida]       VARCHAR (50) NULL,
    [nm_fantasia_produto_esp]   VARCHAR (30) NULL,
    [qt_espesret_ficha_med]     FLOAT (53)   NULL,
    [cd_tipo_placa]             INT          NULL,
    [cd_tipo_produto_espessura] INT          NULL,
    [qt_tolespesmais_ret_ficha] FLOAT (53)   NULL,
    [qt_compfinal_ficha_medida] FLOAT (53)   NULL,
    [qt_largfinal_ficha_medida] FLOAT (53)   NULL,
    [qt_espfinal_ficha_medida]  FLOAT (53)   NULL,
    [nm_medfinal_ficha_medida]  VARCHAR (30) NULL,
    CONSTRAINT [PK_Ficha_Medida_Composicao] PRIMARY KEY CLUSTERED ([cd_ficha_medida] ASC, [cd_item_ficha_medida] ASC) WITH (FILLFACTOR = 90)
);

