CREATE TABLE [dbo].[Fornecedor_Informacao_Compra] (
    [cd_fornecedor]            INT          NOT NULL,
    [dt_ultima_compra_forn]    DATETIME     NULL,
    [dt_maior_compra_forn]     DATETIME     NULL,
    [dt_primeira_compra_forn]  DATETIME     NULL,
    [qt_grau_risco_fornecedor] INT          NULL,
    [qt_dia_entrega_atraso]    INT          NULL,
    [qt_media_atraso]          INT          NULL,
    [vl_maior_compra]          FLOAT (53)   NULL,
    [vl_limite_compra]         FLOAT (53)   NULL,
    [ds_obs_fornecedor]        TEXT         NULL,
    [ic_pagto_eletronico]      CHAR (1)     NULL,
    [cd_suspensao_fornecedor]  INT          NULL,
    [ic_suspenso_compra]       CHAR (1)     NULL,
    [nm_usu_suspenso_compra]   VARCHAR (15) NULL,
    [cd_usuario]               INT          NULL,
    [dt_usuario]               DATETIME     NULL,
    [qt_titulo_atraso]         INT          NULL,
    [qt_saldo_aberto_atraso]   INT          NULL,
    [vl_aberto_atraso]         FLOAT (53)   NULL,
    [vl_total_compra]          FLOAT (53)   NULL,
    [qt_total_compra]          INT          NULL,
    [qt_titulo_aberto]         INT          NULL,
    [qt_saldo_aberto]          INT          NULL,
    [dt_suspensao_compra]      DATETIME     NULL,
    [cd_forma_pagamento]       INT          NULL,
    CONSTRAINT [PK_Fornecedor_Informacao_Compra] PRIMARY KEY CLUSTERED ([cd_fornecedor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Fornecedor_Informacao_Compra_Suspensao_Fornecedor] FOREIGN KEY ([cd_suspensao_fornecedor]) REFERENCES [dbo].[Suspensao_Fornecedor] ([cd_suspensao_fornecedor])
);

