CREATE TABLE [dbo].[Fornecedor] (
    [cd_fornecedor]                 INT           NOT NULL,
    [nm_fantasia_fornecedor]        CHAR (15)     NOT NULL,
    [nm_razao_social]               VARCHAR (60)  NULL,
    [nm_razao_social_comple]        VARCHAR (40)  NULL,
    [nm_dominio_fornecedor]         VARCHAR (100) NULL,
    [ic_destinacao_fornecedor]      CHAR (1)      NULL,
    [cd_suframa_fornecedor]         VARCHAR (15)  NULL,
    [cd_reparticao_origem]          VARCHAR (15)  NULL,
    [dt_cadastro_fornecedor]        DATETIME      NULL,
    [ds_fornecedor]                 TEXT          NULL,
    [ic_equiparado_industrial]      CHAR (1)      NULL,
    [ic_simples_fornecedor]         CHAR (1)      NULL,
    [cd_banco]                      INT           NULL,
    [cd_agencia_banco]              VARCHAR (15)  NULL,
    [cd_conta_banco]                VARCHAR (20)  NULL,
    [cd_tipo_pessoa]                INT           NULL,
    [cd_ramo_atividade]             INT           NULL,
    [cd_comprador]                  INT           NULL,
    [cd_usuario]                    INT           NULL,
    [dt_usuario]                    DATETIME      NULL,
    [cd_fax]                        VARCHAR (15)  NULL,
    [cd_telefone]                   VARCHAR (15)  NULL,
    [cd_ddd]                        CHAR (4)      NULL,
    [cd_pais]                       INT           NULL,
    [cd_estado]                     INT           NULL,
    [cd_cidade]                     INT           NULL,
    [nm_bairro]                     VARCHAR (25)  NULL,
    [nm_complemento_endereco]       VARCHAR (60)  NULL,
    [cd_numero_endereco]            CHAR (10)     NULL,
    [nm_endereco_fornecedor]        VARCHAR (60)  NULL,
    [cd_cep]                        CHAR (9)      NULL,
    [cd_cnpj_fornecedor]            VARCHAR (18)  NULL,
    [cd_identifica_cep]             INT           NULL,
    [sg_fornecedor]                 CHAR (10)     NULL,
    [cd_ip_fornecedor]              VARCHAR (15)  NULL,
    [ic_wapnet_fornecedor]          CHAR (1)      NULL,
    [cd_abablz_fornecedor]          VARCHAR (30)  NULL,
    [cd_swift_fornecedor]           VARCHAR (30)  NULL,
    [ic_iso_fornecedor]             CHAR (1)      NULL,
    [dt_valid_iso_fornecedor]       DATETIME      NULL,
    [cd_tipo_envio]                 INT           NULL,
    [cd_condicao_pagamento]         INT           NULL,
    [cd_destinacao_produto]         INT           NULL,
    [cd_tipo_mercado]               INT           NULL,
    [cd_transportadora]             INT           NULL,
    [nm_email_fornecedor]           VARCHAR (100) NULL,
    [cd_aplicacao_produto]          INT           NULL,
    [ic_iss_fornecedor]             CHAR (1)      NULL,
    [ic_inss_fornecedor]            CHAR (1)      NULL,
    [nm_ponto_ref_fornecedor]       VARCHAR (100) NULL,
    [ds_perfil_fornecedor]          TEXT          NULL,
    [cd_plano_financeiro]           INT           NULL,
    [cd_grupo_fornecedor]           INT           NULL,
    [cd_conta]                      INT           NULL,
    [ds_endereco_fornecedor]        TEXT          NULL,
    [cd_fabricante]                 INT           NULL,
    [ic_isento_insc_fornecedor]     CHAR (1)      NULL,
    [cd_pag_guia_fornecedor]        VARCHAR (10)  NULL,
    [ic_inscestadual_valida]        CHAR (1)      NULL,
    [cd_inscEstadual]               VARCHAR (18)  NULL,
    [cd_inscMunicipal]              VARCHAR (18)  NULL,
    [pc_inss_fornecedor]            FLOAT (53)    NULL,
    [cd_senha_comnet_fornec]        VARCHAR (15)  NULL,
    [ic_comnet_fornecedor]          CHAR (1)      NULL,
    [dt_exportacao_registro]        DATETIME      NULL,
    [cd_moeda]                      INT           NULL,
    [cd_porto]                      INT           NULL,
    [cd_idioma]                     INT           NULL,
    [cd_porto_origem_padrao]        INT           NULL,
    [cd_barra_fornecedor]           VARCHAR (20)  NULL,
    [ic_fmea_fornecedor]            CHAR (1)      NULL,
    [ic_plano_fornecedor]           CHAR (1)      NULL,
    [qt_dia_vcto_av_fornecedor]     INT           NULL,
    [dt_vcto_avaliacao_fornec]      DATETIME      NULL,
    [cd_classif_fornecedor]         INT           NULL,
    [dt_iso_fornecedor]             DATETIME      NULL,
    [ic_residuo_fornecedor]         CHAR (1)      NULL,
    [ic_sucata_fornecedor]          CHAR (1)      NULL,
    [cd_idioma_produto]             INT           NULL,
    [ic_status_fornecedor]          CHAR (1)      NULL,
    [ic_analise_fornecedor]         CHAR (1)      NULL,
    [dt_exportacao_fornecedor]      DATETIME      NULL,
    [cd_identificacao_fornecedor]   VARCHAR (15)  NULL,
    [ic_gera_cliente]               CHAR (1)      NULL,
    [ic_gera_transportadora]        CHAR (1)      NULL,
    [ic_valida_ie_fornecedor]       CHAR (1)      NULL,
    [cd_certificado_avaliacao]      INT           NULL,
    [cd_certificado_iso_fornecedor] VARCHAR (30)  NULL,
    [cd_certificadora_qualidade]    INT           NULL,
    [cd_tipo_avaliacao]             INT           NULL,
    [ic_multi_form_fornecedor]      CHAR (1)      NULL,
    [cd_interface]                  VARCHAR (15)  NULL,
    [ic_sub_tributaria_fornecedor]  CHAR (1)      NULL,
    [ic_ipi_base_st_fornecedor]     CHAR (1)      NULL,
    CONSTRAINT [PK_Fornecedor] PRIMARY KEY CLUSTERED ([cd_fornecedor] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Fornecedor_Classificacao_Fornecedor] FOREIGN KEY ([cd_classif_fornecedor]) REFERENCES [dbo].[Classificacao_Fornecedor] ([cd_classif_fornecedor]),
    CONSTRAINT [FK_Fornecedor_Idioma] FOREIGN KEY ([cd_idioma_produto]) REFERENCES [dbo].[Idioma] ([cd_idioma]),
    CONSTRAINT [FK_Fornecedor_Moeda] FOREIGN KEY ([cd_moeda]) REFERENCES [dbo].[Moeda] ([cd_moeda]),
    CONSTRAINT [FK_Fornecedor_Porto] FOREIGN KEY ([cd_porto]) REFERENCES [dbo].[Porto] ([cd_porto])
);


GO
CREATE NONCLUSTERED INDEX [ix_nm_fantasia_fornecedor]
    ON [dbo].[Fornecedor]([nm_fantasia_fornecedor] ASC) WITH (FILLFACTOR = 90);

