CREATE TABLE [dbo].[Funcionario_Calculo] (
    [cd_funcionario_calculo]     INT          NOT NULL,
    [cd_funcionario]             INT          NOT NULL,
    [dt_base_calculo]            DATETIME     NULL,
    [dt_base_pagamento]          DATETIME     NULL,
    [vl_total_provento]          FLOAT (53)   NULL,
    [vl_total_desconto]          FLOAT (53)   NULL,
    [vl_total_liquido]           FLOAT (53)   NULL,
    [vl_salario_base]            FLOAT (53)   NULL,
    [vl_adiantamento]            FLOAT (53)   NULL,
    [vl_salario_inss]            FLOAT (53)   NULL,
    [vl_base_fgts]               FLOAT (53)   NULL,
    [vl_fgts]                    FLOAT (53)   NULL,
    [vl_base_irrf]               FLOAT (53)   NULL,
    [vl_faixa_irrf]              FLOAT (53)   NULL,
    [nm_obs_funcionario_calculo] VARCHAR (60) NULL,
    [cd_usuario]                 INT          NULL,
    [dt_usuario]                 DATETIME     NULL,
    [cd_ap]                      INT          NULL,
    [cd_solicitacao]             INT          NULL,
    [cd_documento_pagar]         INT          NULL,
    [cd_controle_folha]          INT          NULL,
    [cd_controle]                INT          NULL,
    [ic_banco_calculo]           CHAR (1)     NULL,
    [ic_emitido_demo_calculo]    CHAR (1)     NULL,
    [vl_irrf_adiantamento]       FLOAT (53)   NULL,
    [vl_inss_funcionario]        FLOAT (53)   NULL,
    CONSTRAINT [PK_Funcionario_Calculo] PRIMARY KEY CLUSTERED ([cd_funcionario_calculo] ASC) WITH (FILLFACTOR = 90)
);

