CREATE TABLE [dbo].[Funcionario] (
    [cd_funcionario]               INT           NOT NULL,
    [cd_empresa]                   INT           NULL,
    [nm_funcionario]               VARCHAR (50)  NULL,
    [cd_chapa_funcionario]         INT           NULL,
    [cd_agencia_funcionario]       VARCHAR (20)  NULL,
    [cd_conta_funcionario]         VARCHAR (20)  NULL,
    [cd_banco]                     INT           NULL,
    [cd_usuario]                   INT           NULL,
    [dt_usuario]                   DATETIME      NULL,
    [cd_seguradora]                INT           NULL,
    [cd_cartao_cred_func]          INT           NULL,
    [nm_cartao_cred_func]          VARCHAR (16)  NULL,
    [cd_rg_funcionario]            VARCHAR (20)  NULL,
    [cd_cpf_funcionario]           VARCHAR (14)  NULL,
    [dt_admissao_funcionario]      DATETIME      NULL,
    [cd_centro_custo]              INT           NULL,
    [cd_departamento]              INT           NULL,
    [cd_cartao_credito]            INT           NULL,
    [ds_perfil]                    TEXT          NULL,
    [cd_estrutura_empresa]         INT           NULL,
    [dt_ultima_avaliacao]          DATETIME      NULL,
    [dt_ultimo_reajuste]           DATETIME      NULL,
    [cd_nacionalidade]             INT           NULL,
    [cd_sexo]                      INT           NULL,
    [cd_grau_instrucao]            INT           NULL,
    [dt_nascimento_funcionario]    DATETIME      NULL,
    [cd_tipo_salario]              INT           NULL,
    [cd_categoria_salario]         INT           NULL,
    [cd_cargo_funcionario]         INT           NULL,
    [cd_turno]                     INT           NULL,
    [ic_ponto_funcionario]         CHAR (1)      NULL,
    [ic_sindicato_funcionario]     CHAR (1)      NULL,
    [cd_nivel_funcionario]         INT           NULL,
    [cd_ddd_funcionario]           CHAR (4)      NULL,
    [cd_telefone_funcionario]      VARCHAR (15)  NULL,
    [nm_foto_funcionario]          VARCHAR (255) NULL,
    [ic_deficiente_funcionario]    CHAR (1)      NULL,
    [qt_ano_chegada_funcionario]   FLOAT (53)    NULL,
    [dt_cadastro_funcionario]      DATETIME      NULL,
    [cd_registro_funcionario]      INT           NULL,
    [cd_situacao_funcionario]      INT           NULL,
    [cd_estado_civil]              INT           NULL,
    [cd_cel_funcionario]           VARCHAR (15)  NULL,
    [cd_ddd_cel_funcionario]       CHAR (4)      NULL,
    [nm_fantasia_funcionario]      VARCHAR (15)  NULL,
    [cd_vinculo_empregaticio]      INT           NULL,
    [cd_identificacao_funcionario] VARCHAR (15)  NULL,
    [cd_pais]                      INT           NULL,
    [cd_estado]                    INT           NULL,
    [cd_cidade]                    INT           NULL,
    [cd_localizacao_bem]           INT           NULL,
    [cd_fornecedor]                INT           NULL,
    [qt_limite_req_viagem]         INT           NULL,
    [nm_email_funcionario]         VARCHAR (150) NULL,
    [nm_setor_funcionario]         VARCHAR (15)  NULL,
    [cd_tipo_aprovacao]            INT           NULL,
    [cd_assunto_viagem]            INT           NULL,
    [cd_local_viagem]              INT           NULL,
    [cd_setor_funcionario]         INT           NULL,
    [nm_endereco_funcionario]      VARCHAR (60)  NULL,
    [nm_bairro_funcionario]        VARCHAR (25)  NULL,
    [nm_compl_end_funcionario]     VARCHAR (40)  NULL,
    [cd_cep]                       VARCHAR (8)   NULL,
    [cd_identifica_cep]            INT           NULL,
    [cd_numero_endereco]           VARCHAR (10)  NULL,
    [cd_conta]                     INT           NULL,
    [cd_planta]                    INT           NULL,
    [nm_local_funcionario]         VARCHAR (10)  NULL,
    [cd_seccao]                    INT           NULL,
    [nm_recado_funcionario]        VARCHAR (40)  NULL,
    [nm_site_funcionario]          VARCHAR (150) NULL,
    [cd_funcionario_liberacao]     INT           NULL,
    [cd_grupo_funcionario]         INT           NULL,
    [ic_beneficio_funcionario]     CHAR (1)      NULL,
    [ic_ir_resumo_funcionario]     CHAR (1)      NULL,
    [cd_interface]                 VARCHAR (15)  NULL,
    [cd_fone_recado1]              VARCHAR (15)  NULL,
    [cd_fone_recado2]              VARCHAR (15)  NULL,
    [cd_ramal_funcionario]         VARCHAR (15)  NULL,
    [cd_tipo_admissao]             INT           NULL,
    [cd_cor_pele]                  INT           NULL,
    CONSTRAINT [PK_Funcionario] PRIMARY KEY CLUSTERED ([cd_funcionario] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Funcionario_Assunto_Viagem] FOREIGN KEY ([cd_assunto_viagem]) REFERENCES [dbo].[Assunto_Viagem] ([cd_assunto_viagem]),
    CONSTRAINT [FK_Funcionario_Estado] FOREIGN KEY ([cd_estado]) REFERENCES [dbo].[Estado] ([cd_estado]),
    CONSTRAINT [FK_Funcionario_Funcionario] FOREIGN KEY ([cd_funcionario_liberacao]) REFERENCES [dbo].[Funcionario] ([cd_funcionario]),
    CONSTRAINT [FK_Funcionario_Grupo_Funcionario] FOREIGN KEY ([cd_grupo_funcionario]) REFERENCES [dbo].[Grupo_Funcionario] ([cd_grupo_funcionario]),
    CONSTRAINT [FK_Funcionario_Localizacao_Bem] FOREIGN KEY ([cd_localizacao_bem]) REFERENCES [dbo].[Localizacao_Bem] ([cd_localizacao_bem]),
    CONSTRAINT [FK_Funcionario_Pais] FOREIGN KEY ([cd_pais]) REFERENCES [dbo].[Pais] ([cd_pais]),
    CONSTRAINT [FK_Funcionario_Planta] FOREIGN KEY ([cd_planta]) REFERENCES [dbo].[Planta] ([cd_planta]),
    CONSTRAINT [FK_Funcionario_Seccao] FOREIGN KEY ([cd_seccao]) REFERENCES [dbo].[Seccao] ([cd_seccao]),
    CONSTRAINT [FK_Funcionario_Setor_Funcionario] FOREIGN KEY ([cd_setor_funcionario]) REFERENCES [dbo].[Setor_Funcionario] ([cd_setor_funcionario]),
    CONSTRAINT [FK_Funcionario_Tipo_Aprovacao] FOREIGN KEY ([cd_tipo_aprovacao]) REFERENCES [dbo].[Tipo_Aprovacao] ([cd_tipo_aprovacao])
);

