CREATE TABLE [dbo].[Funcionario_Dependente] (
    [cd_funcionario]               INT           NOT NULL,
    [cd_dependente]                INT           NOT NULL,
    [dt_cadastro_dependente]       DATETIME      NULL,
    [cd_parentesco]                INT           NULL,
    [nm_dependente]                VARCHAR (40)  NULL,
    [dt_nascimento_dependente]     DATETIME      NULL,
    [cd_grau_instrucao]            INT           NULL,
    [ic_plano_medico]              CHAR (1)      NULL,
    [nm_obs_dependente]            VARCHAR (40)  NULL,
    [nm_foto_dependente]           VARCHAR (100) NULL,
    [cd_usuario]                   INT           NULL,
    [dt_usuario]                   DATETIME      NULL,
    [ic_pensao_dependente]         CHAR (1)      NULL,
    [ic_salario_famila_dependente] CHAR (1)      NULL,
    [ic_ir_depedente]              CHAR (1)      NULL,
    [ic_mesmo_endereco]            CHAR (1)      NULL,
    [ds_obs_dependente]            TEXT          NULL,
    [nm_fantasia_dependente]       VARCHAR (20)  NULL,
    [nm_email_dependente]          VARCHAR (150) NULL,
    [cd_ddi]                       VARCHAR (4)   NULL,
    [cd_ddd]                       VARCHAR (4)   NULL,
    [cd_telefone]                  VARCHAR (15)  NULL,
    [cd_celular]                   VARCHAR (15)  NULL,
    [ic_deficiente]                CHAR (1)      NULL,
    CONSTRAINT [PK_Funcionario_Dependente] PRIMARY KEY CLUSTERED ([cd_funcionario] ASC, [cd_dependente] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Funcionario_Dependente_Grau_Instrucao] FOREIGN KEY ([cd_grau_instrucao]) REFERENCES [dbo].[Grau_Instrucao] ([cd_grau_instrucao])
);

