CREATE TABLE [dbo].[CEP_LOG] (
    [CHAVE_LOG]    NVARCHAR (6)  NOT NULL,
    [NOME_LOG]     NVARCHAR (60) NULL,
    [CHVLOCAL_LOG] NVARCHAR (6)  NULL,
    [CHVBAI1_LOG]  NVARCHAR (5)  NULL,
    [CHVBAI2_LOG]  NVARCHAR (5)  NULL,
    [CEP8_LOG]     NVARCHAR (8)  NULL,
    [UF_LOG]       NVARCHAR (2)  NULL,
    [CHVTIPO_LOG]  NVARCHAR (3)  NULL,
    [COMPLE_LOG]   NVARCHAR (65) NULL,
    [REOP_LOG]     NVARCHAR (2)  NULL,
    [OPER_LOG]     NVARCHAR (1)  NULL,
    [DATA_LOG]     NVARCHAR (6)  NULL
);

