CREATE TABLE [dbo].[CP_NotaFiscalDetalheBKP] (
    [cpnd_Fornecedor]            CHAR (14)     NOT NULL,
    [cpnd_NotaFiscal]            CHAR (6)      NOT NULL,
    [cpnd_TipoNota]              CHAR (1)      NOT NULL,
    [cpnd_Parcela]               SMALLINT      NOT NULL,
    [cpnd_Pedido]                INT           NOT NULL,
    [cpnd_DataVencimento]        SMALLDATETIME NOT NULL,
    [cpnd_DataProrrogacao]       SMALLDATETIME NULL,
    [cpnd_Valor]                 MONEY         NOT NULL,
    [cpnd_ValorMulta]            MONEY         NOT NULL,
    [cpnd_ValorDesconto]         MONEY         NOT NULL,
    [cpnd_ValorTotal]            MONEY         NOT NULL,
    [cpnd_NumeroCheque]          CHAR (15)     NULL,
    [cpnd_BancoCheque]           CHAR (3)      NOT NULL,
    [cpnd_CopiaCheque]           INT           NULL,
    [cpnd_DataPagamento]         SMALLDATETIME NULL,
    [cpnd_BancoPagamento]        CHAR (3)      NOT NULL,
    [cpnd_DataPreDatado]         SMALLDATETIME NULL,
    [cpnd_Grupo]                 TINYINT       NOT NULL,
    [cpnd_Destinacao]            TINYINT       NOT NULL,
    [cpnd_Duplicata]             CHAR (7)      NOT NULL,
    [cpnd_Observacao]            VARCHAR (200) NULL,
    [cpnd_NumeroOP]              INT           NULL,
    [cpnd_DataOP]                SMALLDATETIME NULL,
    [cpnd_ObservaçãoProrrogação] TEXT          NULL,
    [cpnd_ObservacãoAbatimento]  TEXT          NULL,
    [cpnd_Lock]                  BINARY (8)    NULL
);

