CREATE TABLE [dbo].[CP_NotaFiscalDetalhe] (
    [cpnd_Fornecedor]            NVARCHAR (14)  NOT NULL,
    [cpnd_NotaFiscal]            NVARCHAR (6)   NOT NULL,
    [cpnd_TipoNota]              NVARCHAR (1)   NOT NULL,
    [cpnd_Parcela]               SMALLINT       NOT NULL,
    [cpnd_Pedido]                INT            NOT NULL,
    [cpnd_DataVencimento]        SMALLDATETIME  NOT NULL,
    [cpnd_DataProrrogacao]       SMALLDATETIME  NULL,
    [cpnd_Valor]                 MONEY          NOT NULL,
    [cpnd_ValorMulta]            MONEY          NOT NULL,
    [cpnd_ValorDesconto]         MONEY          NOT NULL,
    [cpnd_ValorTotal]            MONEY          NOT NULL,
    [cpnd_NumeroCheque]          NVARCHAR (15)  NULL,
    [cpnd_BancoCheque]           NVARCHAR (3)   NOT NULL,
    [cpnd_CopiaCheque]           INT            NULL,
    [cpnd_DataPagamento]         SMALLDATETIME  NULL,
    [cpnd_BancoPagamento]        NVARCHAR (3)   NOT NULL,
    [cpnd_DataPreDatado]         SMALLDATETIME  NULL,
    [cpnd_Grupo]                 TINYINT        NOT NULL,
    [cpnd_Destinacao]            TINYINT        NOT NULL,
    [cpnd_Duplicata]             NVARCHAR (7)   NOT NULL,
    [cpnd_Observacao]            NVARCHAR (200) NULL,
    [cpnd_NumeroOP]              INT            NULL,
    [cpnd_DataOP]                SMALLDATETIME  NULL,
    [cpnd_ObservaçãoProrrogação] TEXT           NULL,
    [cpnd_ObservacãoAbatimento]  TEXT           NULL,
    [cpnd_Valida]                SMALLINT       NULL,
    [cpnd_Lock]                  VARBINARY (8)  NULL,
    CONSTRAINT [PK_CP_NotaFiscalDetalhe] PRIMARY KEY NONCLUSTERED ([cpnd_Fornecedor] ASC, [cpnd_NotaFiscal] ASC, [cpnd_TipoNota] ASC, [cpnd_Parcela] ASC, [cpnd_Pedido] ASC) WITH (FILLFACTOR = 90)
);

