CREATE TABLE [dbo].[FA_NotaFiscal] (
    [fanf_NotaFiscal]        INT           NOT NULL,
    [fanf_TipoNota]          CHAR (1)      NOT NULL,
    [fanf_DataNota]          SMALLDATETIME NOT NULL,
    [fanf_Pedido]            INT           NULL,
    [fanf_CNPJ]              CHAR (14)     NOT NULL,
    [fanf_Inscricao]         CHAR (14)     NULL,
    [fanf_ClienteFornecedor] CHAR (1)      NOT NULL,
    [fanf_Estado]            CHAR (2)      NOT NULL,
    [fanf_CFOP]              CHAR (6)      NOT NULL,
    [fanf_ICMS]              SMALLINT      NULL,
    [fanf_ValorTotal]        MONEY         NULL,
    [fanf_BaseCalculoICMS]   MONEY         NULL,
    [fanf_ValorIPI]          MONEY         NULL,
    [fanf_ValorIPIOutros]    MONEY         NULL,
    [fanf_ValorICMS]         MONEY         NULL,
    [fanf_ValorICMSOutros]   MONEY         NULL,
    [fanf_Situacao1]         INT           NOT NULL,
    [fanf_Situacao2]         INT           NOT NULL,
    [fanf_Representante]     CHAR (3)      NULL,
    [fanf_Comissao]          REAL          NULL,
    [fanf_QtdePagto]         TINYINT       NULL,
    [fanf_Vencimento1]       SMALLDATETIME NULL,
    [fanf_Vencimento2]       SMALLDATETIME NULL,
    [fanf_Vencimento3]       SMALLDATETIME NULL,
    [fanf_Vencimento4]       SMALLDATETIME NULL,
    [fanf_Vencimento5]       SMALLDATETIME NULL,
    [fanf_Vencimento6]       SMALLDATETIME NULL,
    [fanf_Vencimento7]       SMALLDATETIME NULL,
    [fanf_Vencimento8]       SMALLDATETIME NULL,
    [fanf_Pagamento1]        MONEY         NULL,
    [fanf_Pagamento2]        MONEY         NULL,
    [fanf_Pagamento3]        MONEY         NULL,
    [fanf_Pagamento4]        MONEY         NULL,
    [fanf_Pagamento5]        MONEY         NULL,
    [fanf_Pagamento6]        MONEY         NULL,
    [fanf_Pagamento7]        MONEY         NULL,
    [fanf_Pagamento8]        MONEY         NULL,
    [fanf_Cancelada]         CHAR (1)      NOT NULL,
    [fanf_JaIncluso]         CHAR (1)      NOT NULL,
    [fanf_JaImpresso]        CHAR (1)      NULL,
    [fanf_DescricaoCFOP]     CHAR (40)     NULL,
    [fanf_NfVinculada]       INT           NULL,
    [fanf_Lock]              BINARY (8)    NULL
);

