CREATE TABLE [dbo].[FA_REGISTRO752009OLD] (
    [TIPO]       VARCHAR (2)  NULL,
    [DTINICIAL]  VARCHAR (8)  NULL,
    [DTFINAL]    VARCHAR (8)  NULL,
    [CODPRODUTO] VARCHAR (14) NULL,
    [CODNCM]     VARCHAR (8)  NULL,
    [DESRICAO]   VARCHAR (53) NULL,
    [UNIDADE]    VARCHAR (6)  NULL,
    [ALIQIPI]    VARCHAR (5)  NULL,
    [ALIQICMS]   VARCHAR (4)  NULL,
    [REDICMS]    VARCHAR (5)  NULL,
    [BASEICMS]   VARCHAR (13) NULL
);

