CREATE TABLE [dbo].[FN_VENCIMENTOS] (
    [NFISCAL]        DECIMAL (10) NOT NULL,
    [EMISSAO]        DATETIME     NULL,
    [VECTOORIGINAL]  DATETIME     NULL,
    [VECTODUPLICATA] DATETIME     NULL,
    [VALORORIGINAL]  MONEY        NULL,
    [VALORDUPLICATA] MONEY        NULL,
    [BAIXA]          DATETIME     NULL
);

