CREATE TABLE [dbo].[PRE_Formacao] (
    [PRFO_CODIGOPAI]   VARCHAR (20)  NOT NULL,
    [PRFO_SEQUENCIAL]  INT           NOT NULL,
    [PRFO_CODIGOFILHO] VARCHAR (20)  NOT NULL,
    [PRFO_CONDICAO]    VARCHAR (50)  NULL,
    [PRFO_FORMULA]     TEXT          NULL,
    [PRFO_DEPARA]      TEXT          NULL,
    [FORMULAPRECO]     VARCHAR (50)  NULL,
    [COMPRIMENTO]      VARCHAR (50)  NULL,
    [ALTURA]           VARCHAR (50)  NULL,
    [PROFUNDIDADE]     VARCHAR (50)  NULL,
    [FANTASMA]         INT           NULL,
    [ATUALIZADOEM]     SMALLDATETIME NULL,
    [IMPORTADOEM]      SMALLDATETIME NULL,
    CONSTRAINT [PK_PRE_Formacao] PRIMARY KEY NONCLUSTERED ([PRFO_CODIGOPAI] ASC, [PRFO_SEQUENCIAL] ASC, [PRFO_CODIGOFILHO] ASC) WITH (FILLFACTOR = 90)
);

