CREATE TABLE [dbo].[PRE_ORCAMENTOS] (
    [pror_Numero]           INT           NOT NULL,
    [pror_Projeto]          VARCHAR (10)  NULL,
    [pror_DataDigitação]    SMALLDATETIME NULL,
    [pror_DataOrcamento]    SMALLDATETIME NULL,
    [pror_Previsão]         SMALLDATETIME NULL,
    [pror_CodSituacao]      SMALLINT      NULL,
    [pror_Situacao]         VARCHAR (30)  NULL,
    [pror_TipoPessoa]       VARCHAR (10)  NULL,
    [pror_TipoDestinação]   VARCHAR (30)  NULL,
    [pror_Contribuinte]     VARCHAR (30)  NULL,
    [pror_Representante]    VARCHAR (3)   NULL,
    [pror_ComissaoRep]      MONEY         NULL,
    [pror_CNPJ]             VARCHAR (14)  NULL,
    [pror_NomeCliente]      VARCHAR (50)  NULL,
    [pror_Endereço]         VARCHAR (50)  NULL,
    [pror_Bairro]           VARCHAR (50)  NULL,
    [pror_Cidade]           VARCHAR (30)  NULL,
    [pror_Estado]           VARCHAR (2)   NULL,
    [pror_CEP]              VARCHAR (10)  NULL,
    [pror_DDD1]             VARCHAR (10)  NULL,
    [pror_Telefone1]        VARCHAR (50)  NULL,
    [pror_DDD2]             VARCHAR (10)  NULL,
    [pror_Telefone2]        VARCHAR (30)  NULL,
    [pror_DDDFax]           VARCHAR (10)  NULL,
    [pror_Fax]              VARCHAR (30)  NULL,
    [pror_Contato]          VARCHAR (30)  NULL,
    [pror_Departamento]     VARCHAR (30)  NULL,
    [pror_Email1]           VARCHAR (50)  NULL,
    [pror_Email2]           VARCHAR (50)  NULL,
    [pror_Observacao]       TEXT          NULL,
    [pror_DestinoCidade]    VARCHAR (30)  NULL,
    [pror_DestinoEstado]    VARCHAR (10)  NULL,
    [pror_NumOS]            VARCHAR (10)  NULL,
    [pror_NumPedido]        VARCHAR (10)  NULL,
    [pror_Negociacao]       REAL          NULL,
    [pror_Usuario]          VARCHAR (50)  NULL,
    [pror_DataSaida]        SMALLDATETIME NULL,
    [pror_Tabela]           VARCHAR (50)  NULL,
    [pror_ProdBasico]       INT           NULL,
    [pror_ValEstante]       MONEY         NULL,
    [pror_ValPallet]        MONEY         NULL,
    [pror_ValMezanino]      MONEY         NULL,
    [pror_ValPainel]        MONEY         NULL,
    [pror_ValMoveis]        MONEY         NULL,
    [pror_ValDrive]         MONEY         NULL,
    [pror_ValOutros]        MONEY         NULL,
    [pror_Espaco]           VARCHAR (50)  NULL,
    [pror_Projetista]       VARCHAR (50)  NULL,
    [pror_WBCCad]           VARCHAR (1)   NULL,
    [pror_OrçamentoLink]    INT           NULL,
    [pror_NumeroRecado]     VARCHAR (11)  NULL,
    [pror_Financeiro]       VARCHAR (1)   NULL,
    [pror_NegociaçãoOLD]    REAL          NULL,
    [pror_CondiçãoPagto]    VARCHAR (50)  NULL,
    [pror_PrazoEntrega]     VARCHAR (50)  NULL,
    [pror_TipoTransporte]   INT           NULL,
    [pror_PorcTipoTransp]   MONEY         NULL,
    [pror_Montagem]         INT           NULL,
    [pror_PorcMontagem]     MONEY         NULL,
    [pror_LocalMontagem]    VARCHAR (20)  NULL,
    [pror_Embalagem]        VARCHAR (50)  NULL,
    [pror_TipoEmbalagem]    VARCHAR (10)  NULL,
    [pror_Acabamento]       INT           NULL,
    [pror_PorcAcabamento]   MONEY         NULL,
    [pror_Premio]           REAL          NULL,
    [pror_entEndereco]      VARCHAR (50)  NULL,
    [pror_entBairro]        VARCHAR (50)  NULL,
    [pror_entCidade]        VARCHAR (50)  NULL,
    [pror_entEstado]        VARCHAR (50)  NULL,
    [pror_entCEP]           VARCHAR (10)  NULL,
    [pror_entDDD]           VARCHAR (10)  NULL,
    [pror_entTelefone]      VARCHAR (20)  NULL,
    [pror_entCNPJ]          VARCHAR (14)  NULL,
    [pror_entInscricao]     VARCHAR (14)  NULL,
    [pror_Serasa]           INT           NULL,
    [pror_Sintegra]         VARCHAR (10)  NULL,
    [pror_EntregaDiferente] SMALLINT      NULL,
    CONSTRAINT [PK_PRE_ORCAMENTOS_1] PRIMARY KEY NONCLUSTERED ([pror_Numero] ASC) WITH (FILLFACTOR = 90)
);

