CREATE TABLE [dbo].[PRE_ORCAMENTO_TEMP] (
    [NUMERO]                  INT           NOT NULL,
    [PROJETO]                 VARCHAR (10)  NULL,
    [DATA_DIGITACAO]          SMALLDATETIME NULL,
    [DATA_ORCAMENTO]          SMALLDATETIME NULL,
    [DATA_PREVISAO]           SMALLDATETIME NULL,
    [CODIGO_SITUACAO]         SMALLINT      NULL,
    [SITUACAO]                VARCHAR (30)  NULL,
    [TIPO_PESSOA]             VARCHAR (10)  NULL,
    [TIPO_DESTINACAO]         VARCHAR (30)  NULL,
    [CONTRIBUINTE]            VARCHAR (30)  NULL,
    [REPRESENTANTE]           VARCHAR (3)   NULL,
    [COMISSAO]                MONEY         NULL,
    [CNPJ]                    VARCHAR (14)  NULL,
    [CLIENTE]                 VARCHAR (50)  NULL,
    [ENDERECO]                VARCHAR (50)  NULL,
    [BAIRRO]                  VARCHAR (50)  NULL,
    [CIDADE]                  VARCHAR (30)  NULL,
    [ESTADO]                  VARCHAR (2)   NULL,
    [CEP]                     VARCHAR (10)  NULL,
    [DDD1]                    VARCHAR (10)  NULL,
    [TELEFONE1]               VARCHAR (50)  NULL,
    [DDD2]                    VARCHAR (10)  NULL,
    [TELEFONE2]               VARCHAR (30)  NULL,
    [DDD_FAX]                 VARCHAR (10)  NULL,
    [FAX]                     VARCHAR (30)  NULL,
    [CONTATO]                 VARCHAR (30)  NULL,
    [DEPARTAMENTO]            VARCHAR (30)  NULL,
    [EMAIL1]                  VARCHAR (50)  NULL,
    [EMAIL2]                  VARCHAR (50)  NULL,
    [OBSERVACAO]              TEXT          NULL,
    [DESTINO_CIDADE]          VARCHAR (30)  NULL,
    [DESTINO_ESTADO]          VARCHAR (10)  NULL,
    [OS]                      VARCHAR (10)  NULL,
    [PEDIDO]                  VARCHAR (10)  NULL,
    [NEGOCIACAO]              REAL          NULL,
    [USUARIO]                 VARCHAR (50)  NULL,
    [DATA_SAIDA]              SMALLDATETIME NULL,
    [TABELA]                  VARCHAR (50)  NULL,
    [PRODUTOS]                INT           NULL,
    [VALOR_ESTANTES]          MONEY         NULL,
    [VALOR_PALETE]            MONEY         NULL,
    [VALOR_MEZANINO]          MONEY         NULL,
    [VALOR_PAINEL]            MONEY         NULL,
    [VALOR_MOVEIS]            MONEY         NULL,
    [VALOR_DRIVE]             MONEY         NULL,
    [VALOR_OUTROS]            MONEY         NULL,
    [ESPACO]                  VARCHAR (50)  NULL,
    [PROJETISTA]              VARCHAR (50)  NULL,
    [WBCCAD]                  VARCHAR (1)   NULL,
    [ORCAMENTO_LINK]          INT           NULL,
    [NUMERO_RECADO]           VARCHAR (11)  NULL,
    [FINANCEIRO]              VARCHAR (1)   NULL,
    [NEGOCIACAO_ANTERIOR]     REAL          NULL,
    [COND_PAGAMENTO]          VARCHAR (50)  NULL,
    [PRAZO_ENTREGA]           VARCHAR (50)  NULL,
    [TIPO_TRANSPORTADORA]     INT           NULL,
    [PORCTIPO_TRANSPORTADORA] MONEY         NULL,
    [MONTAGEM]                INT           NULL,
    [PORC_MONTAGEM]           MONEY         NULL,
    [LOCALMONTAGEM]           VARCHAR (20)  NULL,
    [EMBALAGEM]               VARCHAR (50)  NULL,
    [TIPO_EMBALAGEM]          VARCHAR (10)  NULL,
    [ACABAMENTO]              INT           NULL,
    [PORC_ACABAMENTO]         MONEY         NULL,
    [PREMIO]                  REAL          NULL,
    [ENTREGA_ENDERECO]        VARCHAR (50)  NULL,
    [ENTREGA_BAIRRO]          VARCHAR (50)  NULL,
    [ENTREGA_CIDADE]          VARCHAR (50)  NULL,
    [ENTREGA_ESTADO]          VARCHAR (50)  NULL,
    [ENTREGA_CEP]             VARCHAR (10)  NULL,
    [ENTREGA_DDD]             VARCHAR (10)  NULL,
    [ENTREGA_TELEFONE]        VARCHAR (20)  NULL,
    [ENTREGA_CNPJ]            VARCHAR (14)  NULL,
    [ENTREGA_INSCRICAO]       VARCHAR (14)  NULL,
    [SERASA]                  INT           NULL,
    [SINTEGRA]                VARCHAR (10)  NULL,
    [ENTREGA_DIFERENTE]       SMALLINT      NULL
);

