CREATE TABLE [dbo].[PRE_Textos] (
    [prte_Numero]         INT          NOT NULL,
    [prte_Item]           INT          NOT NULL,
    [prte_Opcao]          INT          NOT NULL,
    [prte_Area]           INT          NOT NULL,
    [prte_Texto]          TEXT         NULL,
    [prte_NumIntegracao]  INT          NULL,
    [prte_MesOrca]        INT          NULL,
    [prte_AnoOrca]        INT          NULL,
    [prte_Quantidade]     INT          NULL,
    [prte_QtdePagamentos] INT          NULL,
    [prte_ValorOrcamento] MONEY        NULL,
    [prte_IPI]            VARCHAR (50) NULL,
    [prte_Negociação]     REAL         NULL,
    [prte_CondPagto]      VARCHAR (60) NULL,
    [prte_PrazoEntrega]   VARCHAR (60) NULL,
    [prte_TipoTransporte] TINYINT      NULL,
    [prte_PorcTransporte] REAL         NULL,
    [prte_TipoProduto]    VARCHAR (50) NULL,
    [prte_Montagem]       INT          NULL,
    [prte_PorcMontagem]   REAL         NULL,
    [prte_LocalMontagem]  VARCHAR (50) NULL,
    [prte_Embalagem]      INT          NULL,
    [prte_TipoEmbalagem]  CHAR (50)    NULL,
    [prte_Acabamento]     INT          NULL,
    [prte_PorcAcabamento] REAL         NULL,
    [prte_Premio]         REAL         NULL,
    [prte_Usuario]        VARCHAR (50) NULL,
    CONSTRAINT [PK_PRE_Textos] PRIMARY KEY NONCLUSTERED ([prte_Numero] ASC, [prte_Item] ASC, [prte_Opcao] ASC, [prte_Area] ASC) WITH (FILLFACTOR = 90)
);

