CREATE TABLE [dbo].[RH_Configura] (
    [cf_Data]                  SMALLDATETIME NOT NULL,
    [cf_ISS]                   FLOAT (53)    NULL,
    [cf_PIS]                   FLOAT (53)    NULL,
    [cf_Cofins]                FLOAT (53)    NULL,
    [cf_IRPJ]                  FLOAT (53)    NULL,
    [cf_CSLL]                  FLOAT (53)    NULL,
    [cf_OutrosImpostos]        FLOAT (53)    NULL,
    [cf_Aluguel]               MONEY         NULL,
    [cf_Contabilidade]         MONEY         NULL,
    [cf_AguaLuzTelefone]       MONEY         NULL,
    [cf_Nextel]                MONEY         NULL,
    [cf_13Contabilidade]       MONEY         NULL,
    [cf_DespesasGerais]        FLOAT (53)    NULL,
    [cf_ProLabore]             MONEY         NULL,
    [cf_OutrasDespesas]        FLOAT (53)    NULL,
    [cf_INSS]                  FLOAT (53)    NULL,
    [cf_FGTS]                  FLOAT (53)    NULL,
    [cf_MultaRecisao]          FLOAT (53)    NULL,
    [cf_ValeRefeicao]          MONEY         NULL,
    [cf_13Salario]             FLOAT (53)    NULL,
    [cf_DiasFerias]            INT           NULL,
    [cf_OutrosEncargos]        MONEY         NULL,
    [cf_Empresa]               INT           NULL,
    [cf_ValeTransporte]        MONEY         NULL,
    [cf_ServicoVT]             MONEY         NULL,
    [cf_TaxaVT]                MONEY         NULL,
    [cf_SeguroVT]              MONEY         NULL,
    [cf_ServicoVR]             MONEY         NULL,
    [cf_TaxaVR]                MONEY         NULL,
    [cf_SeguroVR]              MONEY         NULL,
    [cf_Bonificacao]           MONEY         NULL,
    [cf_CustosFuncionais]      MONEY         NULL,
    [cf_CustosAdministrativos] MONEY         NULL,
    [cf_PercBonificacao]       MONEY         NULL,
    [cf_Uniforme]              MONEY         NULL,
    [cf_ManutEscritorio]       MONEY         NULL,
    [cf_PaesCafe]              MONEY         NULL,
    [cf_Homologacao]           MONEY         NULL,
    CONSTRAINT [PK_RH_Configura] PRIMARY KEY NONCLUSTERED ([cf_Data] ASC) WITH (FILLFACTOR = 90)
);

