CREATE TABLE [dbo].[SI_MIGRACLIENTE] (
    [CNPJ]        CHAR (14)    NOT NULL,
    [RAZAOSOCIAL] VARCHAR (50) NULL,
    [INSCRICAO]   CHAR (14)    NULL,
    [ENDERECO]    VARCHAR (50) NULL,
    [CIDADE]      CHAR (25)    NULL,
    [UF]          CHAR (2)     NULL,
    [CEP]         CHAR (9)     NULL,
    CONSTRAINT [PK_SI_MIGRACLIENTE] PRIMARY KEY NONCLUSTERED ([CNPJ] ASC) WITH (FILLFACTOR = 90)
);

