CREATE TABLE [dbo].[SI_TabelaNBM] (
    [COD_NBM]  NVARCHAR (12) NOT NULL,
    [NOME_NBM] NVARCHAR (55) NULL,
    [COD_NCM]  NVARCHAR (10) NOT NULL,
    [NOME_NCM] NVARCHAR (55) NULL,
    CONSTRAINT [PK_SI_TabelaNBM] PRIMARY KEY NONCLUSTERED ([COD_NBM] ASC, [COD_NCM] ASC) WITH (FILLFACTOR = 90)
);

