CREATE TABLE [dbo].[VE_CLIATIVOS09] (
    [CNPJ]          NVARCHAR (255) NULL,
    [RAZAOSOCIAL]   NVARCHAR (255) NULL,
    [ENDERECO]      NVARCHAR (255) NULL,
    [CIDADE]        NVARCHAR (255) NULL,
    [UF]            NVARCHAR (255) NULL,
    [CEP]           NVARCHAR (255) NULL,
    [verp_Codigo]   NVARCHAR (255) NULL,
    [REPRESENTANTE] NVARCHAR (255) NULL
);

