CREATE TABLE [Representante].[Visita] (
    [Número]                         INT            IDENTITY (1, 1) NOT NULL,
    [Data do Cadastro]               DATETIME       CONSTRAINT [DF_Agenda_Data do Cadastro] DEFAULT (getdate()) NOT NULL,
    [Data e Hora da Visita]          DATETIME       NOT NULL,
    [Identificador da Sessão]        INT            CONSTRAINT [DF_Visita_Identificador da Sessão] DEFAULT ((0)) NOT NULL,
    [Identificador do Representante] INT            CONSTRAINT [DF_Visita_Identificador do Representante] DEFAULT ((0)) NOT NULL,
    [Código do Representante]        CHAR (3)       NOT NULL,
    [Identificador do Recado]        INT            CONSTRAINT [DF_Agenda_Identificador do Recado] DEFAULT ((0)) NOT NULL,
    [Número do Orçamento]            INT            CONSTRAINT [DF_Agenda_Número do Orçamento] DEFAULT ((0)) NOT NULL,
    [Nome Fantasia]                  NVARCHAR (20)  NULL,
    [Razão Social]                   NVARCHAR (50)  NULL,
    [Endereço]                       NVARCHAR (50)  NULL,
    [Numero do Endereço]             NVARCHAR (5)   NULL,
    [Complemento do Endereço]        NVARCHAR (10)  NULL,
    [Bairro]                         NVARCHAR (50)  NULL,
    [Cidade]                         NVARCHAR (50)  NULL,
    [Estado]                         NCHAR (2)      NULL,
    [Nome do Contato]                NVARCHAR (40)  NULL,
    [Departamento]                   NVARCHAR (35)  NULL,
    [DDD do Telefone]                NCHAR (3)      NULL,
    [Telefone]                       NVARCHAR (15)  NULL,
    [Ramal do Telefone]              NCHAR (5)      NULL,
    [DDD do Celular]                 NCHAR (3)      NULL,
    [Celular]                        NVARCHAR (15)  NULL,
    [Email]                          NVARCHAR (100) NULL,
    [Observações]                    NTEXT          NULL,
    CONSTRAINT [PK_Agenda] PRIMARY KEY CLUSTERED ([Número] ASC),
    CONSTRAINT [FK_Visita_Representante] FOREIGN KEY ([Identificador do Representante]) REFERENCES [Representante].[Representante] ([Identificador]),
    CONSTRAINT [FK_Visita_Sessão de Representante] FOREIGN KEY ([Identificador da Sessão]) REFERENCES [Representante].[Sessão de Representante] ([Identificador])
);

