


/*

	1.PEDIDO
	2.ENTREGA
	3.D.D.L.
	4.MONTAGEM
	5.D.D.P.

*/


CREATE VIEW [dbo].[View_PVCPgDBALTAMIRA] AS


	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(1 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias1] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem1] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha1] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha1] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo1] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor1] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem1] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(2 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias2] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem2] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha2] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha2] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo2] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor2] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem2] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(3 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias3] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem3] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha3] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha3] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo3] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor3] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem3] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(4 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias4] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem4] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha4] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha4] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo4] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor4] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem4] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(5 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias5] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem5] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha5] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha5] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo5] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor5] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem5] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(6 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias6] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem6] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha6] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha6] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo6] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor6] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem6] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(7 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias7] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem7] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha7] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha7] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo7] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor7] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem7] > 0
	UNION
	SELECT CAST([vepe_Pedido] AS INT) AS VwPVGes0Num, CAST(8 AS SMALLINT) as VwPVGes2ParSeq, CAST([vepe_Dias8] AS INT) AS VwPVGes2ParDias, CAST([vepe_Porcentagem8] AS SMALLMONEY) AS VwPVGes2ParPor, CAST([vepe_Escolha8] AS SMALLINT) AS VwPVGes2ParTip, CAST(CASE CAST([vepe_Escolha8] AS SMALLINT) WHEN 1 THEN 'PEDIDO' WHEN 2 THEN 'ENTREGA' WHEN 3 THEN 'D.D.L.' WHEN 4 THEN 'MONTAGEM' WHEN 5 THEN 'D.D.P.' ELSE '' END AS CHAR(10) ) AS VwPVGes2ParTipDes, CAST([vepe_Tipo8] AS CHAR(1)) AS VwPVGes2ParPouN, CAST([vepe_Valor8] AS MONEY) AS VwPVGes2ParVal FROM [DBALTAMIRA].[dbo].[VE_Pedidos] WHERE [vepe_Porcentagem8] > 0



GO
GRANT SELECT
    ON OBJECT::[dbo].[View_PVCPgDBALTAMIRA] TO [interclick]
    AS [dbo];

