
CREATE VIEW [dbo].[View_INT_WBCCAD_ORCITM]
AS
SELECT     WBCCAD.dbo.INTEGRACAO_ORCITM.idIntegracao_OrcItm AS INT_ORCITM_ID, WBCCAD.dbo.INTEGRACAO_ORCITM.ORCNUM AS INT_ORCITM_OrcNum, 
                      WBCCAD.dbo.INTEGRACAO_ORCITM.GRPCOD AS INT_ORCITM_GrpCod, WBCCAD.dbo.INTEGRACAO_ORCITM.SUBGRPCOD AS INT_ORCITM_SGrCod, 
                      WBCCAD.dbo.INTEGRACAO_ORCITM.ORCITM AS INT_ORCITM_Itm, WBCCAD.dbo.INTEGRACAO_ORCITM.ORCPRDCOD AS INT_ORCITM_PrdCod, 
                      WBCCAD.dbo.INTEGRACAO_ORCITM.ORCPRDQTD AS INT_ORCITM_PrdQtd, WBCCAD.dbo.INTEGRACAO_ORCITM.ORCTXT AS INT_ORCITM_OrcTxt, 
                      WBCCAD.dbo.INTEGRACAO_ORCITM.ORCVAL AS INT_ORCITM_OrcVal, WBCCAD.dbo.INTEGRACAO_ORCITM.ORCIPI AS INT_ORCITM_IpiAli, 
                      WBCCAD.dbo.INTEGRACAO_ORCITM.ORCICM AS INT_ORCITM_IcmAli, CASE WHEN ISNULL(dbo.LPV1.LPPED, 0) > 0 THEN 'S' ELSE 'N' END AS INT_ORCITM_LPGer, ISNULL(dbo.LPV1.LPEMP, '') 
                      AS INT_ORCITM_LPEmp, ISNULL(dbo.LPV1.LPPED, 0) AS INT_ORCITM_LpPed, ISNULL(dbo.LPV1.LPSEQ, 0) AS INT_ORCITM_LpSeq
FROM         dbo.LPV1 LEFT OUTER JOIN
                      dbo.LPV ON dbo.LPV1.LPEMP = dbo.LPV.LPEMP AND dbo.LPV1.LPPED = dbo.LPV.LPPED RIGHT OUTER JOIN
                      WBCCAD.dbo.INTEGRACAO_ORCITM ON dbo.LPV1.LPWBCCADORCITM = WBCCAD.dbo.INTEGRACAO_ORCITM.ORCITM AND 
                      dbo.LPV.LPWBCCADORCNUM = WBCCAD.dbo.INTEGRACAO_ORCITM.ORCNUM AND dbo.LPV.LPEtSitRed <> 'CANCELADO'


GO
GRANT SELECT
    ON OBJECT::[dbo].[View_INT_WBCCAD_ORCITM] TO [interclick]
    AS [dbo];

