CREATE LOGIN [interclick]
    WITH PASSWORD = N'|edueujibnmitLv!B{eaxbgxmsFT7_&#$!~<%yFi|aeHuOxi', SID = 0x6D96A6BE6815544EBFA381429F92ACD6, DEFAULT_DATABASE = [GPIMAC_Altamira], DEFAULT_LANGUAGE = [Português (Brasil)], CHECK_POLICY = OFF;

