CREATE TABLE [dbo].[CP_NotaFiscalDetalhe] (
    [cpnd_Fornecedor]            CHAR (14)     NOT NULL,
    [cpnd_NotaFiscal]            CHAR (6)      NOT NULL,
    [cpnd_TipoNota]              CHAR (1)      NOT NULL,
    [cpnd_Parcela]               SMALLINT      NOT NULL,
    [cpnd_Pedido]                INT           NOT NULL,
    [cpnd_DataVencimento]        SMALLDATETIME CONSTRAINT [DF_CP_NotaFiscalDetalhe_cpnd_DataVencimento] DEFAULT (NULL) NULL,
    [cpnd_DataProrrogacao]       SMALLDATETIME CONSTRAINT [DF_CP_NotaFiscalDetalhe_cpnd_DataProrrogacao] DEFAULT (NULL) NULL,
    [cpnd_Valor]                 MONEY         NOT NULL,
    [cpnd_ValorMulta]            MONEY         NOT NULL,
    [cpnd_ValorDesconto]         MONEY         NOT NULL,
    [cpnd_ValorTotal]            MONEY         NOT NULL,
    [cpnd_NumeroCheque]          CHAR (15)     NULL,
    [cpnd_BancoCheque]           CHAR (3)      NOT NULL,
    [cpnd_CopiaCheque]           CHAR (20)     NULL,
    [cpnd_DataPagamento]         SMALLDATETIME CONSTRAINT [DF_CP_NotaFiscalDetalhe_cpnd_DataPagamento] DEFAULT (NULL) NULL,
    [cpnd_BancoPagamento]        CHAR (3)      NOT NULL,
    [cpnd_DataPreDatado]         SMALLDATETIME CONSTRAINT [DF_CP_NotaFiscalDetalhe_cpnd_DataPreDatado] DEFAULT (NULL) NULL,
    [cpnd_Grupo]                 TINYINT       NOT NULL,
    [cpnd_Destinacao]            TINYINT       NOT NULL,
    [cpnd_Duplicata]             CHAR (7)      NULL,
    [cpnd_Observacao]            VARCHAR (50)  NULL,
    [cpnd_NumeroOP]              INT           NULL,
    [cpnd_DataOP]                SMALLDATETIME CONSTRAINT [DF_CP_NotaFiscalDetalhe_cpnd_DataOP] DEFAULT (NULL) NULL,
    [cpnd_ObservaçãoProrrogação] TEXT          NULL,
    [cpnd_ObservacãoAbatimento]  TEXT          NULL,
    [cpnd_Valida]                SMALLINT      NULL,
    [cpnd_Lock]                  ROWVERSION    NOT NULL,
    CONSTRAINT [PK_CP_NotaFiscalDetalhe] PRIMARY KEY NONCLUSTERED ([cpnd_Fornecedor] ASC, [cpnd_NotaFiscal] ASC, [cpnd_TipoNota] ASC, [cpnd_Parcela] ASC, [cpnd_Pedido] ASC) WITH (FILLFACTOR = 90)
);

